### ISSUE TITLE
Traefik panics when using ForwardAuth with HTTP/3

### ISSUE THREAD

**Issue by timoschwarzer** [traefik/traefik#8377] opened 2021-08-19 19:10 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Traefik and Authelia running in Kubernetes. The Traefik dashboard is exposed to `traefik.example.com`, which also has the Authelia middleware (ForwardAuth) applied. Experimental HTTP/3 is enabled for the entrypoint.

**Without HTTP/3 enabled, everything forks fine.**

### What did you see instead?

Internal Server Error from Traefik, see below for logs.

### What version of Traefik are you using?

2.5.0

### What is your environment & configuration?

Authelia is exposed at `auth.example.com`. Authelia's internal IP and port is `10.42.0.144:9091` (authelia.authelia.svc.cluster.local). Traefik Dashboard is exposed at `traefik.example.com`.

Spec of the `ForwardAuth` middleware:

```
spec:
  forwardAuth:
    address: >-
      http://authelia.authelia.svc.cluster.local/api/verify?rd=https://auth.example.com/
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Email
      - Remote-Groups
    trustForwardHeader: true
```

### If applicable, please paste the log output in DEBUG level

```
time="2021-08-19T18:58:10Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://10.42.0.144:9091" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/firstfactor\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/3\",\"ProtoMajor\":3,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, text/plain, */*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-CA,en;q=0.9\"],\"Content-Type\":[\"application/json;charset=UTF-8\"],\"Dnt\":[\"1\"],\"Origin\":[\"https://auth.example.com\"],\"Referer\":[\"https://auth.example.com/?rd=https%3A%2F%2Ftraefik.example.com%2F\\u0026rm=GET\"],\"Sec-Ch-Ua\":[\"\\\"Chromium\\\";v=\\\"92\\\", \\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Google Chrome\\\";v=\\\"92\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Fetch-Dest\":[\"empty\"],\"Sec-Fetch-Mode\":[\"cors\"],\"Sec-Fetch-Site\":[\"same-origin\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36\"],\"X-Forwarded-Host\":[\"auth.example.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik-6c568874d8-w7qtf\"],\"X-Real-Ip\":[\"12.34.56.78\"]},\"ContentLength\":141,\"TransferEncoding\":null,\"Host\":\"auth.example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"12.34.56.78:52626\",\"RequestURI\":\"/api/firstfactor\",\"TLS\":null}"
time="2021-08-19T18:58:10Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/firstfactor\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/3\",\"ProtoMajor\":3,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, text/plain, */*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-CA,en;q=0.9\"],\"Content-Type\":[\"application/json;charset=UTF-8\"],\"Dnt\":[\"1\"],\"Origin\":[\"https://auth.example.com\"],\"Referer\":[\"https://auth.example.com/?rd=https%3A%2F%2Ftraefik.example.com%2F\\u0026rm=GET\"],\"Sec-Ch-Ua\":[\"\\\"Chromium\\\";v=\\\"92\\\", \\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Google Chrome\\\";v=\\\"92\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Fetch-Dest\":[\"empty\"],\"Sec-Fetch-Mode\":[\"cors\"],\"Sec-Fetch-Site\":[\"same-origin\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36\"],\"X-Forwarded-Host\":[\"auth.example.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik-6c568874d8-w7qtf\"],\"X-Real-Ip\":[\"12.34.56.78\"]},\"ContentLength\":141,\"TransferEncoding\":null,\"Host\":\"auth.example.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"12.34.56.78:52626\",\"RequestURI\":\"/api/firstfactor\",\"TLS\":null}"
time="2021-08-19T18:58:10Z" level=error msg="Recovered from panic in HTTP handler [12.34.56.78:52626 - /api/firstfactor]: interface conversion: *gzhttp.GzipResponseWriter is not http.CloseNotifier: missing method CloseNotify" middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2021-08-19T18:58:10Z" level=error msg="Stack: goroutine 542 [running]:
github.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x7f82ee157590, 0xc000962f20}, 0xc0001ffc00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:46 +0x225
panic({0x2db1ba0, 0xc000d11c20})
  /usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x215
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*responseModifier).CloseNotify(0xc000d11a40)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/responsewriter.go:98 +0x2d
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*responseModifier).CloseNotify(0x38e6d40)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/responsewriter.go:98 +0x38
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc001b24730, {0x38b7c28, 0xc001860910}, 0xc000f54000)
  /usr/local/golang/1.10.8/go/src/net/http/httputil/reverseproxy.go:224 +0x14f
github.com/traefik/traefik/v2/pkg/middlewares/pipelining.(*pipelining).ServeHTTP(0xc001b3be40, {0x38b7c28, 0xc001860910}, 0xc000f54000)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/pipelining/pipelining.go:34 +0x6b
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddServiceFields({0x38b7c28, 0xc001860910}, 0xc000f54000, {0x38854a0, 0xc001b3be40}, 0xc000e14900)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:47 +0x110
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc001b393c0, {0x38b7c28, 0xc001860910}, 0xa)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:36 +0xd8
github.com/vulcand/oxy/roundrobin.(*RoundRobin).ServeHTTP(0xc001b4a5b0, {0x38b7c28, 0xc001860910}, 0xc0001fff00)
  /home/semaphore/go/pkg/mod/github.com/vulcand/oxy@v1.3.0/roundrobin/rr.go:147 +0x52c
github.com/traefik/traefik/v2/pkg/middlewares/emptybackendhandler.(*emptyBackend).ServeHTTP(0xc001b4c010, {0x38b7c28, 0xc001860910}, 0xc001860910)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/emptybackendhandler/empty_backend_handler.go:25 +0xfd
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*forwarderMiddleware).ServeHTTP(0xc001b45620, {0x38b7c28, 0xc001860910}, 0xc0001fff00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/forwarder.go:38 +0x47d
github.com/traefik/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP.func1({0x38b7c28, 0xc0018608c0}, 0xc0001fff00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/secure.go:53 +0x11d
github.com/unrolled/secure.(*Secure).HandlerFuncWithNextForRequestOnly(0xc00170d4a0, {0x38b7c28, 0xc0018608c0}, 0x503e05, 0xc000c18b00)
  /home/semaphore/go/pkg/mod/github.com/unrolled/secure@v1.0.9/secure.go:233 +0x2b1
github.com/traefik/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP({{0x3885620, 0xc001b45620}, 0xc00170d4a0, {0x0, 0xc001914510, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...}}, ...)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/secure.go:52 +0x5b
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*Header).ServeHTTP(0xc001b39680, {0x38b74a8, 0xc0003d02a0}, 0xc0001ffe00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/header.go:64 +0x146
github.com/traefik/traefik/v2/pkg/middlewares/connectionheader.Remover.func1({0x38b74a8, 0xc0003d02a0}, 0xc0001ffe00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/connectionheader/connectionheader.go:34 +0x2a4
net/http.HandlerFunc.ServeHTTP(0x27c3727, {0x38b74a8, 0xc0003d02a0}, 0x347d118)
  /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x2f
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*headers).ServeHTTP(0x38e6d40, {0x38b74a8, 0xc0003d02a0}, 0xc000c19000)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/headers.go:91 +0x2c
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc001b45b30, {0x38b74a8, 0xc0003d02a0}, 0xc0001ffe00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/wrapper.go:57 +0x106
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x7f82ee157590, 0xc000962f20}, 0xc000c190f0)
  /home/semaphore/go/pkg/mod/github.com/klauspost/compress@v1.13.0/gzhttp/gzip.go:380 +0x2fc
net/http.HandlerFunc.ServeHTTP(0xc001b39700, {0x7f82ee157590, 0xc000962f20}, 0xc00184c940)
  /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x2f
github.com/traefik/traefik/v2/pkg/middlewares/compress.(*compress).ServeHTTP(0xc001b39700, {0x7f82ee157590, 0xc000962f20}, 0xc0001ffe00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/compress/compress.go:55 +0x1b4
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc001b45cb0, {0x7f82ee157590, 0xc000962f20}, 0xc0001ffe00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/wrapper.go:57 +0x106
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc001b39740, {0x7f82ee157590, 0xc000962f20}, 0x3258440)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:38 +0xf6
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001447e60, {0x7f82ee157590, 0xc000962f20}, 0xc0001ffc00)
  /home/semaphore/go/pkg/mod/github.com/containous/mux@v0.0.0-20181024131434-c33f32e26898/mux.go:133 +0x270
github.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0x40fa94, {0x7f82ee157590, 0xc000962f20}, 0xc00123f4a0)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:32 +0x82
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddOriginFields({0x7f82ee157590, 0xc000962f00}, 0x333194a, {0x38854e0, 0xc0016fd330}, 0xc000e14900)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:55 +0x1a2
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0013f8440, {0x7f82ee157590, 0xc000962f00}, 0x383f501)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:36 +0xd8
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc00011fd08, {0x7f82ee157590, 0xc000962f00}, 0xc0001ffb00, 0xc00123f678)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x57b
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x7f82ee157590, 0xc000962f00}, 0xc000962f00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x68
net/http.HandlerFunc.ServeHTTP(0xc000d11620, {0x7f82ee157590, 0xc000962f00}, 0xa)
  /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x2f
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*Handler).ServeHTTP(0xc0006b5140, {0x38b7628, 0xc000e14840}, 0xc0001ffa00, {0x388bb80, 0xc001a3b4c0})
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/logger.go:227 +0xfa3
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.WrapHandler.func1.1({0x38b7628, 0xc000e14840}, 0xc00176de00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/logger.go:71 +0x3b
net/http.HandlerFunc.ServeHTTP(0xc0010c23a8, {0x38b7628, 0xc000e14840}, 0x40fa94)
  /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x2f
github.com/traefik/traefik/v2/pkg/server/router/tcp.(*Manager).buildEntryPointHandler.func1({0x38b7628, 0xc000e14840}, 0xc0001ffa00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/tcp/router.go:194 +0x199
net/http.HandlerFunc.ServeHTTP(0xc000da1000, {0x38b7628, 0xc000e14840}, 0xc000341cd0)
  /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x2f
github.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0xc000129630, {0x38b7628, 0xc000e14840}, 0x9)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/handler_switcher.go:23 +0x62
github.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc000129630, {0x38b7628, 0xc000e14840}, 0xc0001ffa00)
  /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/forwardedheaders/forwarded_header.go:183 +0xca
github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest.func2(0x38e6d40, 0x7f82ee1574a0, {0x38853a0, 0xc000129630}, 0x2ff6fc0, 0xc000d116e0)
  /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:396 +0x7d
github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest(0xc000129680, {0x3950fc0, 0xc000420000}, {0x7f82ee1574a0, 0xc000f3a000}, 0x0, 0xc001662990)
  /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:397 +0x9da
github.com/lucas-clemente/quic-go/http3.(*Server).handleConn.func1()
  /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:253 +0xfb
created by github.com/lucas-clemente/quic-go/http3.(*Server).handleConn
  /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:252 +0x1f4
" middlewareName=traefik-internal-recovery middlewareType=Recovery
12.34.56.78 - - [19/Aug/2021:18:58:10 +0000] "POST /api/firstfactor HTTP/3" 500 22 "-" "-" 34 "authelia-authelia-971e05b4eb220ba557b1@kubernetescrd" "http://10.42.0.144:9091" 1ms
```

**Comment by ldez** [comment] 2021-08-19 19:16
Duplicate of #8373

**Closed by ldez** 2021-08-19 19:16 UTC
Labels: status/0-needs-triage
