### ISSUE TITLE
LE certificates not renewing

### ISSUE THREAD

**Issue by RBetting77** [traefik/traefik#9901] opened 2023-05-21 11:42 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

ACME issued LE certificates failed to renew and expired.

Investigation led me to traefik creating dual entries in the acme-dns file.
- The "expected entry" using the domain named used.
- And an "extra entry" using [GUID].acme-dns-domain, the GUID here doesn't match the GUID used for the CNAME DNS entry.

To the ACME-REST-API an update is posted using the "extra entry" while LE checks the "expected entry", resulting in a non-match.

### What did you see instead?

Downgrade to 2.8.8 make my certificate renewed immediately.
Haven't tried intermediate versions.

### What version of Traefik are you using?

Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

      - --certificatesresolvers.le.acme.email=my@email
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.keytype=EC384
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=acme-dns
      - --certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.le.acme.dnschallenge.delayBeforeCheck=20
      - --log.level=INFO

### If applicable, please paste the log output in DEBUG level

The domain is changed to: the-domain.ext
The ACME-DNS is changed to: my-acme-dns.ext

```
level=error msg="Error renewing certificate from LE: {the-domain.ext [*.the-domain.ext]}" ACME CA="https://acme-v02.api.letsencrypt.org/directory" error="error: one or more domains had a problem:\n[*.the-domain.ext] time limit exceeded: last error: NS ns1.my-acme-dns.ext. did not return the expected TXT record [fqdn: 4c4495a6-251c-4dab-9912-f36feef12e33.my-acme-dns.ext., value: tcNgp9jvjhPMm4OYp2AS_jnRx-4A93BIYD0pgqjY0ac]: lGJWtWDN44jZe_rcWMx1If5w2K43d2S-o9xap96QQ14 ,_MunTCPqhrZFeokO8u4jekZZdGThqkkOdgQWQIffyGI\n[the-domain.ext] time limit exceeded: last error: NS ns1.my-acme-dns.ext. did not return the expected TXT record [fqdn: 4c4495a6-251c-4dab-9912-f36feef12e33.my-acme-dns.ext., value: QNZ-EdhYxzooA0wYJl8OYQVjr3ChG-hJcrPut7vbkUA]: lGJWtWDN44jZe_rcWMx1If5w2K43d2S-o9xap96QQ14 ,_MunTCPqhrZFeokO8u4jekZZdGThqkkOdgQWQIffyGI\n" providerName=le.acme
```

**Comment by ldez** [comment] 2023-05-21 12:04
Hello,

this problem has been fixed in lego v4.11.0 (https://github.com/go-acme/lego/pull/1863).

lego has been updated in #9883.

This will be a part of the next bug fix release (traefik v2.10.2)

Duplicate of #9879

**Closed by ldez** 2023-05-21 12:04 UTC
Labels: resolution/duplicate
