### ISSUE TITLE
Enable dynamic configuration for proxyProtocol.trustedIPs

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9378] opened 2022-09-27 07:16 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be great to have `trustedIPs` as dynamic config, so when we add a load balancer we don't need to restart Traefik, but we can just update a dynamic configuration file for "zero downtime deployments".

From the [Traefik EntryPoints docs](https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol):

```
## Static configuration
entryPoints:
  web:
    address: ":80"
    proxyProtocol:
      trustedIPs:
        - "127.0.0.1/32"
        - "192.168.1.7" 
```

**Comment by rtribotte** [comment] 2022-09-28 11:53
Hello @bluepuma77,

Thanks for your interest in Traefik!

Your proposal seems to fit with dynamic entrypoints proposal: https://github.com/traefik/traefik/issues/6551.
Accordingly, we are closing this one as a duplicate.

Duplicate of https://github.com/traefik/traefik/issues/6551

**Closed by rtribotte** 2022-09-28 11:54 UTC
Labels: status/0-needs-triage
