### ISSUE TITLE
[2.6.3] Can´t pull traefik docker image for amd64

### ISSUE THREAD

**Issue by Y0ngg4n** [traefik/traefik#8902] opened 2022-03-29 21:04 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

```bash
docker pull traefik:2.6.3
2.6.3: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries
```

### What did you see instead?

I could not pull the image but it seems that there is an image in the release tag for amd64.

### What version of Traefik are you using?

2.6.3

### What is your environment & configuration?

nothing

**Comment by ldez** [comment] 2022-03-29 21:17
Hello,

The official Docker images are built by Docker itself, it's the process for official images: https://github.com/docker-library/official-images

The official Docker images of Traefik are currently under construction in the Docker build system.

The process takes time, you have to wait for a bit (a few hours).

- The related PR in the Official Image repository: https://github.com/docker-library/official-images/pull/12145
- The Traefik page in the Jenkins of the Official Images: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/


duplicate of #8213n #7023, #7265, #5992, #5512, #4265,  #2467, #5348, and many other issues like every time we create a new version.

**Closed by ldez** 2022-03-29 21:17 UTC
Labels: status/0-needs-triage

**Comment by timothystewart6** [comment] 2022-03-31 00:29
Hi!  It's been over 24 hours and I am still not seeing it

```
➜  traefik docker pull traefik:2.6.3
2.6.3: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by timothystewart6** [comment] 2022-03-31 00:31
![image](https://user-images.githubusercontent.com/1322205/160952722-2710af3f-0685-4553-9737-31869278e106.png)
https://hub.docker.com/layers/traefik/library/traefik/v2.6.3/images/sha256-2a6e91644420e884a47301e5719349eb6a1c6c36d044c7fcfac6789aeb4b0475?context=explore

**Comment by Y0ngg4n** [comment] 2022-03-31 16:33
@timothystewart6 same here :(
PS: Loving your videos. They often helped me out :+1:

**Comment by timothystewart6** [comment] 2022-03-31 23:32
it works now
```
docker pull traefik:v2.6.3
v2.6.3: Pulling from library/traefik
cfab2db72209: Already exists
491249faa733: Already exists
0e7660e64df1: Pull complete
080a3ffe94e5: Pull complete
Digest: sha256:4ff6ffde832702965c3602dfd3023b164f10f75b5d748889b190ca72bfff8f2a
Status: Downloaded newer image for traefik:v2.6.3
docker.io/library/traefik:v2.6.3
```

**Comment by ldez** [comment] 2022-03-31 23:45
FYI I provided an explanation here: https://github.com/traefik/traefik/issues/8885#issuecomment-1083458134

**Comment by timothystewart6** [comment] 2022-04-01 00:37
Thank you!
