### ISSUE TITLE
Endpoint-level ACME directives in static configuration ignored

### ISSUE THREAD

**Issue by Legogris** [traefik/traefik#8908] opened 2022-04-02 06:14 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Expecting to be able to configure (and ideally generate) wildcard certificates on endpoint-level in static configuration through `[[entryPoints.EntryPoint0.http.tls.domains]]`. The intention is to be able to get the behavior from 1.x where it's possible to specify it on provider level:
```
[[acme.domains]]
  main = "example.com"
  sans = ["*.example.com"]
```

According to the [static configuration reference](https://doc.traefik.io/traefik/reference/static-configuration/file/), this should be possible:
```
        [[entryPoints.EntryPoint0.http.tls.domains]]
          main = "foobar"
          sans = ["foobar", "foobar"]
```

I understand that a proposed workaround until this bug is fixed would probably be to add it to the dynamic configuration on each service/router:

```
tags += [
  "traefik.http.routers.foo.tls.domains[0].main=example.com",
  "traefik.http.routers.foo.tls.domains[0].sans=*.example.com"
]
```

This is not a solution; it significantly increases the risk of misconfiguration when maintaining large amounts of services across domains. We need to be able to configure domains in the static conf, either on the level of endpoint (as in 2.6 reference docs) or on the level of acme provider (as in 1.x). 

Plus, we would expect that certs issues this way would mean that individual routers can share certs when wildcards make them overlap when configures this way - this is a large point of why one would make use of wildcard certs (though the docs don't specify expected behavior on this, so while surprising the last point may be considered a feature request rather than a bug and therefore a separate issue; that is not clear to me).

Related issue: https://github.com/traefik/traefik/issues/5678

### What did you see instead?

Instead, the `Rule` directive from the dynamic configuration on the routers overrides it, yielding unique individual issuance requests, certificates, and names/sans for each service/router.

### What version of Traefik are you using?

`traefik:2.6.3`

### static:

```yaml
[providers.consulCatalog]

[entrypoints.http]
address="$IP:80"
[entryPoints.http.http.redirections]
  [entryPoints.http.http.redirections.entrypoint]
    to = "https"
    scheme = "https"

[entrypoints.https]
address="$IP:443"
[entryPoints.https.http.tls]
  certResolver = "providername"
  [[entryPoints.https.http.tls.domains]]
    main = "example.com"
    sans = ["*.example.com"]


[certificatesResolvers.providername.acme]
  email = "certs@example.com"
  storage = "/certs/acme.json"
[certificatesResolvers.providername.acme.dnsChallenge]
  provider = "$PROVIDERNAME"
  resolvers = ["$RESOLVER:53"]
[[acme.domains]]
  main = "example.com"
  sans = ["*.example.com"]
```

### dynamic:
```
tags = [
  "traefik.http.routers.foo-http.entrypoints=http",
  "traefik.http.routers.foo-http.rule=Host(`foo.example.com`)",
  "traefik.http.routers.foo.tls=true",
  "traefik.http.routers.foo.tls.certResolver=providername",
  "traefik.http.routers.foo.entrypoints=https",
  "traefik.http.routers.foo.rule=Host(`foo.example.com`)
]
```

**Comment by rtribotte** [comment] 2022-04-04 07:54
Hello @Legogris,

Thanks for your interest in Traefik!

This behavior is not a bug and is documented in [EntryPoints documentation page](https://doc.traefik.io/traefik/routing/entrypoints/#tls).
The TLS configuration on the `EntryPoints` only applies if no configuration has been defined on a router.

In your case, removing the TLS configuration on the router `foo` should allow the `EntryPoints` TLS configuration to be applied to the router.

As this issue seems to be a configuration issue, we will close it as a question.
Thus, feel free to reopen it if you think we missed something.

**Closed by rtribotte** 2022-04-04 07:54 UTC
Labels: status/0-needs-triage
