### ISSUE TITLE
Service locator middleware

### ISSUE THREAD

**Issue by neongreen** [traefik/traefik#8967] opened 2022-04-25 17:05 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'd like to route requests to either service A or service B based on non-trivial logic that involves querying the database. E.g. "if the user is authorized to _edit_ a certain page, forward them to the editor app frontend, otherwise — to the page preview backend".

Of course, other and more complicated cases are possible.

My understanding is that this is usually solved with the "service locator pattern". There's a separate microservice that has access to the database and can return results like "which service should handle this request". Then Traefik can act based on that information.

Is there anything like this implemented in Traefik? I went through the list of middlewares but haven't found anything.

**Comment by neongreen** [comment] 2022-04-25 17:27
I looked through GitHub some more and found https://github.com/traefik/traefik/issues/5154. Not sure if it's the same or not but seems to be similar.

The `ForwardAuth` middleware is also a more specialized case of this general idea.

And there's also https://community.traefik.io/t/dynamic-routing-of-ingress-based-on-urls-from-database-service/10854.

**Comment by rtribotte** [comment] 2022-04-26 12:35
Hello @neongreen,

Thanks for your interest in Traefik!

We think that your feature request is a duplicate of https://github.com/traefik/traefik/issues/5098.
With prerouting one should be able to leverage the `ForwardAuth` middleware to add some headers to the request, which could then be re-routed to the right service.

We are closing this issue accordingly.

**Closed by rtribotte** 2022-04-26 12:35 UTC
Labels: status/0-needs-triage
