### ISSUE TITLE
Traefik v2 - Adding a unique Trace ID to the header

### ISSUE THREAD

**Issue by kjanshair** [traefik/traefik#8303] opened 2021-07-24 10:17 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Can we add a unique UUID\X-Request-ID\Trace-ID to a header using a middleware? For example, below is the section of a `docker-compose.yml` file:

```
.................
  headers:
    image: akalipetis/headers:latest # This image prints all the HTTP Headers
    container_name: headers
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headers.middlewares=testHeader"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.X-Trace-Id=12345"
.................
```

Can we assign the value of the UUID\X-Request-ID\Trace-ID to this above X-Trace-ID? Adding a Trace-ID would be the best option. :)

**Comment by ldez** [comment] 2021-07-24 13:33
duplicate of  #4640

**Closed by ldez** 2021-07-24 13:33 UTC
Labels: resolution/duplicate

**Comment by kjanshair** [comment] 2021-07-24 14:26
I have seen issue but I don't know how to apply it in my case.
