### ISSUE TITLE
Use forwarded AuthResponseHeaders as customResponseHeaders

### ISSUE THREAD

**Issue by DanielCarrami** [traefik/traefik#9951] opened 2023-06-12 23:08 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello!

I'm trying to add a cookie to the browser. So I'm using and auth service that creates a header (Set-Cookie) and sends it to the services inside the application, like this:
```
        jwtAuthentication:
            forwardAuth:
                address: "some/url/that/works"
                trustForwardHeader: true
                authResponseHeaders:
                    - "Set-Cookie"
```
The cookie is created inside my Auth service. I checked and the Set-Cookie header is sent to the service correctly. 
The thing is that I want to add the same header as it is to the service response without having to go inside the service and add the request header to the response headers, but I haven't found a clear answer to that:
```
        serviceAudience:
            headers:
                customRequestHeaders:
                    X-Audience: "some-x-audience"
                customResponseHeaders:
                    Set-Cookie: 'I don't know what to put here'
```
I know that if I add the Set-Cookie to the customResponseHeaders it will set a cookie on the browser with whichever value I provide, but I want the value from the forwarded auth service headers.

**Comment by nmengin** [comment] 2023-06-15 12:25
Duplicate of https://github.com/traefik/traefik/issues/3660

**Closed by nmengin** 2023-06-15 12:25 UTC
Labels: status/0-needs-triage

**Comment by DanielCarrami** [comment] 2023-06-18 19:59
I see why it's a duplicate, but how is this achieved? The 'Set Cookie' headers reaches all my services with this configuration:

```
authResponseHeaders:
    - "Set-Cookie"
```

But I have to add the cookie to all my services manually so it reaches the end client. How do you automatically forward the auth headers?

**Comment by nmengin** [comment] 2023-06-19 14:59
Hello @DanielCarrami,

Unfortunately, there is currently no way to automate such behavior.
But it's the purpose of the PR #8924 that solves the issue #3660.
