### ISSUE TITLE
v3.x prometheus metrics returns wrong service name exclusively for the 'traefik_service_server_up' metric.

### ISSUE THREAD

**Issue by BoSen29** [traefik/traefik#10895] opened 2024-07-11 12:30 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgraded our test-environment to v3.1.0, and got inconsistent labeling in the prometheus metrics. 
Replicated the issue in v3.0.4. 

Expected to see the 'service' tag to be '%service%@%provider%' for the metric.

### What did you see instead?

Exposed metric show a 'service' with a unique 16 character identifier.  

### What version of Traefik are you using?

```
Version:      3.0.4
Codename:     beaufort
Go version:   go1.22.4
Built:        2024-07-02T13:46:37Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Related configuration
```
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:9001"
      - "--providers.swarm=true"
```
The service in question:
```
        - "traefik.http.services.%name%.loadbalancer.healthcheck.path=%path%"
        - "traefik.http.services.%name%.loadbalancer.healthcheck.hostname=%hostname"
```

Attempted disabling plugins aswell. 
Works as expectd in Traefik v2.6

'service' tag for other metrics under traefik_service_* seems to be correct. 
ie: traefik_service_response_bytes_total

Correct tag:
`traefik_service_responses_bytes_total{code="200",method="GET",protocol="http",service="%servicename%@%provider%"} 100`
Wrong tag:
`traefik_service_server_up{service="%16characteridentifier%",url="%url%"} 1`

**Comment by kevinpollet** [comment] 2024-07-11 13:12
Hello @BoSen29 and thanks for opening this issue,

This issue is a duplicate of https://github.com/traefik/traefik/issues/10734, therefore I am closing it accordingly.

Duplicate of https://github.com/traefik/traefik/issues/10734

**Closed by kevinpollet** 2024-07-11 13:12 UTC
Labels: status/0-needs-triage
