### ISSUE TITLE
Can not pull latest 1.7 (1.7.31) images from docker hub

### ISSUE THREAD

**Issue by tgerakitis** [traefik/traefik#8492] opened 2021-10-05 09:44 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

`docker pull traefik:1.7.31`

### What did you see instead?

```
docker pull traefik:1.7.31
> v1.7.31: Pulling from library/traefik
> no matching manifest for linux/amd64 in the manifest list entries
```

### What version of Traefik are you using?

I want to use 1.7 with the latest update

### What is your environment & configuration?

tried several machines, got the problem everywhere.

I can pull `1.7.30` and `2.5.3` without issues

**Comment by ldez** [comment] 2021-10-05 09:48
Duplicate of #8490

**Closed by ldez** 2021-10-05 09:48 UTC
Labels: status/0-needs-triage
