### ISSUE TITLE
[Traefik V2] Allow TLS -> [Traefik] -> TLS (backend service)

### ISSUE THREAD

**Issue by github-sys-admin** [traefik/traefik#8985] opened 2022-05-04 09:47 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

```yaml
    - "--api.insecure=false"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=100.64.59.2:80"
      - "--entrypoints.websecure.address=100.64.59.2:443"
      - "--entrypoints.ircs.address=100.64.59.2:6697"
      - "--entrypoints.ircsdmz.address=100.64.59.2:6698"
      - "--entrypoints.ircslink.address=100.64.59.2:7000"
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=no-reply@clandestine.network"
      - "--log.level=DEBUG"
```

```yaml
# this all works as intended albeit, just barely
      - "traefik.enable=true"
      - "traefik.docker.network=in_traefik_backend"
      - "traefik.tcp.routers.ircdgeneral.entrypoints=ircs"
      - "traefik.tcp.routers.ircdgeneral.rule=HostSNI(`irc.ma.sv.eu.clandestine.network`) || HostSNI(`irc.clandestine.network`)"
      - "traefik.tcp.routers.ircdgeneral.tls=true"
      - "traefik.tcp.routers.ircdgeneral.tls.passthrough=false"
      - "traefik.tcp.routers.ircdgeneral.tls.certresolver=le"
      - "traefik.tcp.routers.ircdgeneral.tls.domains[0].main=irc.ma.sv.eu.clandestine.network"
      - "traefik.tcp.routers.ircdgeneral.tls.domains[0].sans=irc.clandestine.network"
      - "traefik.tcp.services.ircdgeneral.loadbalancer.server.port=6667"
      - "traefik.tcp.services.ircdgeneral.loadbalancer.proxyprotocol.version=2"
# also won't work with traefik.tcp.services.* but the idea here would basically just be
# openssl s_client -connect <backend:6697>:
#      - "traefik.http.services.ircdgeneral.loadbalancer.server.port=6697"
#      - "traefik.http.services.ircdgeneral.loadbalancer.server.scheme=https"
# this also sucks, would like to use a CA certificate to verify, the backend:
#      - "traefik.http.services.ircdgeneral.loadbalancer.tls.insecureskipverify=true"
# Notes:
# https://doc.traefik.io/traefik/routing/providers/docker/#tcp
# https://doc.traefik.io/traefik/routing/routers/#passthrough
# https://doc.traefik.io/traefik/routing/providers/docker/#services
```

### What did you see instead?

I saw that `traefik.http.services.ircdgeneral.loadbalancer.server.scheme=https"` and `traefik.tcp.services.ircdgeneral.loadbalancer.server.scheme=https"` didn't work

### What version of Traefik are you using?

yes

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
yes

### If applicable, please paste the log output in DEBUG level

doesn't say anything I just want it to do the simple thing that would be real useful because ircd requires ssl connection for various reasons the rest works just fine just need it to connect to the ircd with tls and its done

**Comment by kevinpollet** [comment] 2022-05-04 12:40
Duplicate of https://github.com/traefik/traefik/issues/7803

**Closed by kevinpollet** 2022-05-04 12:40 UTC
Labels: status/0-needs-triage

**Comment by rtribotte** [comment] 2022-05-05 07:23
Hello @github-sys-admin,

Thanks for your feedback, thus as this issue is closed in benefit of the #7803, please step in this one instead to discuss the feature, if something is not clear enough.

As we label #7803 as `P2`, as mentioned in [contributor guide](https://github.com/traefik/contributors-guide/blob/master/issue_triage.md#define-priority), it is something that we found interesting, but we don't have time right now to work on it. 

This being said, all contributions are welcome, and if you want to do so, feel free to open a PR following the Pull Request [Guidelines](https://github.com/traefik/contributors-guide/blob/master/pr_guidelines.md).
