### ISSUE TITLE
Can not escape character '\\.' in yaml config file

### ISSUE THREAD

**Issue by gitsang** [traefik/traefik#8873] opened 2022-03-24 03:49 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

[link issue 3409](https://github.com/traefik/traefik/issues/3409)

### What did you do?

my dynamic yaml config file

```
http:
  routers:
    to-server:
      rule: "Path(`/{?:.*\\.+.*}`)"
      service: server
```

my server linsten `0.0.0.0:2321` and route `/` root path and will always return 403

`curl http://localhost:2321/api/v2/../v1/` can not match. It will return 404.

```
http:
  routers:
    to-server:
      rule: "Path(`/{?:.*\.+.*}`)"
      service: server
```

if use `\.` will log `found unknown escape character` 

I have try `\.` `\\.` `\\\.` `\\\\.` , all can not work

If `.` replace with char won't escape like `z`
```
http:
  routers:
    to-server:
      rule: "Path(`/{?:.*z+.*}`)"
      service: server
```

`http://www.example.com/api/v2/zzz/v1/` can match.

### What did you see instead?

It return 404

### What version of Traefik are you using?

Version:      2.5.3
Codename:     livarot
Go version:   go1.17.1
Built:        2021-09-20T15:43:56Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
http:
  routers:
    to-server:
      rule: "Path(`/{?:.*\\.+.*}`)"
      service: server
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-03-24T03:38:31Z" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\":{\"**********":{\"service\":\"server\",\"rule\":\"Path(`/{?:.*\\\\.+.*}`)\"}},\"**********},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=file

time="2022-03-24T03:38:31Z" level=debug msg="Added outgoing tracing middleware redis" entryPointName=websecure routerName=redis@docker middlewareType=TracingForwarder middlewareName=tracing
time="2022-03-24T03:38:31Z" level=debug msg="Creating middleware" routerName=to-server@file serviceName=server entryPointName=websecure middlewareName=pipelining middlewareType=Pipelining
time="2022-03-24T03:38:31Z" level=debug msg="Creating load-balancer" entryPointName=websecure routerName=to-server@file serviceName=server
time="2022-03-24T03:38:31Z" level=debug msg="Creating server 0 http://127.0.0.1:3212" serviceName=server serverName=0 entryPointName=websecure routerName=to-server@file
time="2022-03-24T03:38:31Z" level=debug msg="child http://127.0.0.1:3212 now UP"
```

**Comment by gitsang** [comment] 2022-03-24 03:58
And I have try to write a go test file, but it work.

```
package rules

import (
        "net/http"
        "net/http/httptest"
        "testing"

        "github.com/gorilla/mux"
        "github.com/stretchr/testify/assert"
        "github.com/stretchr/testify/require"
        "github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator"
        "github.com/traefik/traefik/v2/pkg/testhelpers"
)

func TestTemp(t *testing.T) {
        testCases := []struct {
                desc          string
                rule          string
                headers       map[string]string
                remoteAddr    string
                expected      map[string]int
                expectedError bool
        }{
                {
                        desc: "Path Regex",
                        rule: `Path("/{?:.*z+.*}")`,
                        expected: map[string]int{
                                "http://www.example.com/api/v1/zz/function": http.StatusOK,
                        },
                },
                {
                        desc: "Path Regex",
                        rule: `Path("/{?:.*\\.\\..*}")`,
                        expected: map[string]int{
                                "http://www.example.com/api/v1/../function": http.StatusOK,
                                "http://www.example.com/api/v1/function":    http.StatusNotFound,
                        },
                },
                {
                        desc: "Path Regex",
                        rule: `Path("/{?:.*\\.+.*}")`,
                        expected: map[string]int{
                                "http://www.example.com/api/v1/../function": http.StatusOK,
                                "http://www.example.com/api/v1/function":    http.StatusNotFound,
                        },
                },
                {
                        desc: "Path Regex",
                        rule: `!Path("/{?:.*\\.+.*}")`,
                        expected: map[string]int{
                                "http://www.example.com/api/v1/../function": http.StatusNotFound,
                                "http://www.example.com/api/v1/function":    http.StatusOK,
                        },
                },
                {
                        desc: "Path Regex",
                        rule: "Path(`/{?:.*\\.+.*}`)",
                        expected: map[string]int{
                                "http://www.example.com/api/v1/../function": http.StatusOK,
                                "http://www.example.com/api/v1/function":    http.StatusNotFound,
                        },
                },
                {
                        desc: "Path Regex",
                        rule: "!Path(`/{?:.*\\.+.*}`)",
                        expected: map[string]int{
                                "http://www.example.com/api/v1/../function": http.StatusNotFound,
                                "http://www.example.com/api/v1/function":    http.StatusOK,
                        },
                },
                {
                        desc: "Path Regex",
                        rule: "!Path(`/{?:.*\\.+.*}`)",
                        expected: map[string]int{
                                "http://www.example.com/api/v1/../function": http.StatusNotFound,
                                "http://www.example.com/api/v1/function":    http.StatusOK,
                        },
                },
        }

        for _, test := range testCases {
                test := test

                t.Run(test.desc, func(t *testing.T) {
                        t.Parallel()

                        handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})
                        router, err := NewRouter()
                        require.NoError(t, err)

                        err = router.AddRoute(test.rule, 0, handler)
                        if test.expectedError {
                                require.Error(t, err)
                        } else {
                                require.NoError(t, err)

                                // RequestDecorator is necessary for the host rule
                                reqHost := requestdecorator.New(nil)

                                results := make(map[string]int)
                                for calledURL := range test.expected {
                                        w := httptest.NewRecorder()

                                        req := testhelpers.MustNewRequest(http.MethodGet, calledURL, nil)

                                        // Useful for the ClientIP matcher
                                        req.RemoteAddr = test.remoteAddr

                                        for key, value := range test.headers {
                                                req.Header.Set(key, value)
                                        }
                                        reqHost.ServeHTTP(w, req, router.ServeHTTP)
                                        results[calledURL] = w.Code
                                }
                                assert.Equal(t, test.expected, results)
                        }
                })
        }
}
```


```
# go test -v ./pkg/rules/ -test.run TestTemp
=== RUN   TestTemp
=== RUN   TestTemp/Path_Regex
=== PAUSE TestTemp/Path_Regex
=== RUN   TestTemp/Path_Regex#01
=== PAUSE TestTemp/Path_Regex#01
=== RUN   TestTemp/Path_Regex#02
=== PAUSE TestTemp/Path_Regex#02
=== RUN   TestTemp/Path_Regex#03
=== PAUSE TestTemp/Path_Regex#03
=== RUN   TestTemp/Path_Regex#04
=== PAUSE TestTemp/Path_Regex#04
=== RUN   TestTemp/Path_Regex#05
=== PAUSE TestTemp/Path_Regex#05
=== RUN   TestTemp/Path_Regex#06
=== PAUSE TestTemp/Path_Regex#06
=== CONT  TestTemp/Path_Regex
=== CONT  TestTemp/Path_Regex#04
=== CONT  TestTemp/Path_Regex#06
=== CONT  TestTemp/Path_Regex#05
=== CONT  TestTemp/Path_Regex#01
=== CONT  TestTemp/Path_Regex#02
=== CONT  TestTemp/Path_Regex#03
--- PASS: TestTemp (0.00s)
    --- PASS: TestTemp/Path_Regex (0.00s)
    --- PASS: TestTemp/Path_Regex#06 (0.00s)
    --- PASS: TestTemp/Path_Regex#01 (0.00s)
    --- PASS: TestTemp/Path_Regex#04 (0.00s)
    --- PASS: TestTemp/Path_Regex#05 (0.00s)
    --- PASS: TestTemp/Path_Regex#03 (0.00s)
    --- PASS: TestTemp/Path_Regex#02 (0.00s)
PASS
ok      github.com/traefik/traefik/v2/pkg/rules 0.014s
```

**Comment by ldez** [comment] 2022-03-24 10:30
Hello,

These kinds of URLs `http://www.example.com/api/v1/../function` are resolved by the browser (or curl) to `http://www.example.com/api/function` so Traefik will never see the dots.

The escape `\\.` works.

**Closed by ldez** 2022-03-24 10:30 UTC
Labels: kind/question

**Comment by gitsang** [comment] 2022-03-24 11:23
I'm sure `..` can send to traefik.

## cond1

when my config file is

```
http:

  routers:
    to-test:
      rule: "PathPrefix(`/api/v1`)"
      service: test

  services:
    test:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:3212
```

127.0.0.1:3231 will always return 403.

When I use curl with `..`

```
#  curl -I localhost/api/v1/../xxx
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Date: Thu, 24 Mar 2022 11:19:11 GMT
Location: /api/xxx
```

traefik log is

```
time="2022-03-24T11:19:11Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"HEAD\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v1/../xxx\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"],\"X-Forwarded-Host\":[\"localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"chensx.novalocal\"],\"X-Real-Ip\":[\"::1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:59176\",\"RequestURI\":\"/api/v1/../xxx\",\"TLS\":null}"
time="2022-03-24T11:19:11Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"HEAD\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v1/../xxx\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"],\"X-Forwarded-Host\":[\"localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"chensx.novalocal\"],\"X-Real-Ip\":[\"::1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:59176\",\"RequestURI\":\"/api/v1/../xxx\",\"TLS\":null}" ForwardURL="http://127.0.0.1:3212"
time="2022-03-24T11:19:11Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"HEAD\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v1/../xxx\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"],\"X-Forwarded-Host\":[\"localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"chensx.novalocal\"],\"X-Real-Ip\":[\"::1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:59176\",\"RequestURI\":\"/api/v1/../xxx\",\"TLS\":null}"
```

## cond2

but if i change config to 

```
http:

  routers:
    to-test:
      rule: "Path(`/{?:.*\\.+.*}`)"
      service: test

  services:
    test:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:3212
```

curl will return 301 then 404, but not 403

```
# curl -I -L localhost/api/v1/../xxx
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Date: Thu, 24 Mar 2022 11:16:18 GMT
Location: /api/xxx

HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 24 Mar 2022 11:16:18 GMT
Content-Length: 19
```

traefik log is

```
time="2022-03-24T11:17:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"HEAD\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v1/../xxx\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"],\"X-Forwarded-Host\":[\"localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"chensx.novalocal\"],\"X-Real-Ip\":[\"::1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:59144\",\"RequestURI\":\"/api/v1/../xxx\",\"TLS\":null}"
time="2022-03-24T11:17:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"HEAD\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v1/../xxx\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"],\"X-Forwarded-Host\":[\"localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"chensx.novalocal\"],\"X-Real-Ip\":[\"::1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:59144\",\"RequestURI\":\"/api/v1/../xxx\",\"TLS\":null}" ForwardURL="http://127.0.0.1:3212"
time="2022-03-24T11:17:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"HEAD\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v1/../xxx\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"],\"X-Forwarded-Host\":[\"localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"chensx.novalocal\"],\"X-Real-Ip\":[\"::1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"[::1]:59144\",\"RequestURI\":\"/api/v1/../xxx\",\"TLS\":null}"
```

**Comment by ldez** [comment] 2022-03-24 11:56
Can you open another issue? Because the problem is not related to character escaping.

In your snippets, you can see the `HTTP/1.1 301 Moved Permanently`, so the path, via the redirection, is evaluated before the routing process (`HTTP/1.1 404 Not Found`).

**Comment by gitsang** [comment] 2022-03-24 12:44
> Can you open another issue? Because the problem is not related to character escaping.
> 
> In your snippets, you can see the `HTTP/1.1 301 Moved Permanently`, so the path, via the redirection, is evaluated before the routing process (`HTTP/1.1 404 Not Found`).

Ok, thanks for your reply. I have open another issue at https://github.com/traefik/traefik/issues/8875

**Comment by gitsang** [comment] 2022-03-24 13:02
It's my fault. I have found out that, 301 is the correct behavior. I misunderstand the phenomenon. Sorry for take your time.@ldez
