### ISSUE TITLE
Support dynamic configure for entrypoint

### ISSUE THREAD

**Issue by letian0805** [traefik/traefik#7862] opened 2021-02-05 13:51 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When i add an entrypoint for tcp, i must restart traefik. 
If it can be placed in the dynamic configuration, it will be easy to manage.

**Comment by ldez** [comment] 2021-02-05 15:06
duplicate of #6551

**Closed by ldez** 2021-02-05 15:06 UTC
Labels: resolution/duplicate
