### ISSUE TITLE
pilot.token should be able to be fetched from a secret

### ISSUE THREAD

**Issue by docwhat** [traefik/traefik#7916] opened 2021-02-18 19:39 UTC
Feature

### What did you expect to see?

The `pilot.token` value should be able to be stored in a secret in k8s. Not everyone is able to hide the entire contents of their helm configuration.

**Comment by ldez** [comment] 2021-02-19 15:47
Duplicate of #3853

**Closed by ldez** 2021-02-19 15:47 UTC
Labels: area/provider/k8s, kind/proposal
