### ISSUE TITLE
TLS environment variables for multi domain

### ISSUE THREAD

**Issue by Trogie** [traefik/traefik#10336] opened 2024-01-05 17:03 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I have 2 domains on Cloudflare (or could also be other provider) and want to 'host' them on a single Traefik instance.
So I have created 2 certResolvers but the corresponding api keys/tokens (environment variables) can not be linked to the respective certResolver...

What could be the best way to link the api keys/tokens to a specific CertResolver? A prefix, index,...?

**Comment by Trogie** [comment] 2024-01-08 08:34
I'll try to solve it temporary by using the httpChallenge for LetsEncrypt but would prefer to use dnsChallenge.

**Comment by kevinpollet** [comment] 2024-01-08 13:35
Duplicate of #5472

**Closed by kevinpollet** 2024-01-08 13:35 UTC
Labels: status/0-needs-triage
