### ISSUE TITLE
traefik tracing sdk not support for open telemetry

### ISSUE THREAD

**Issue by ztyandjw** [traefik/traefik#9447] opened 2022-10-17 11:01 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

we use the open telemetry for jaeger/zipkin, but the traefik is the beging of our system,
the traefik use the sdk opentracing may be Deprecated...
we can't use open telemetry sdk to extract the header for traefik, because the traceid not encode and decode for same format

**Comment by ldez** [comment] 2022-10-17 11:04
Duplicate of #6374

**Closed by ldez** 2022-10-17 11:04 UTC
Labels: resolution/duplicate
