### ISSUE TITLE
HTTP headers case gets modified

### ISSUE THREAD

**Issue by maguec** [traefik/traefik#466] opened 2016-06-17 22:02 UTC
When sending a custom header through traefik, it gets recased causing the application to fail.

Is there a way to disable any re-casing?

Repro step:
curl using a cusom header

```
curl -H "X-tEST-hEADER: true" -o /dev/null -v http://backend.example
```

TCPDUMP on the other side to see

```
X-Forwarded-For: <REDACTED>
X-Forwarded-Host: <READACTED>:31880
X-Forwarded-Proto: http
X-Forwarded-Server: qatcd-haproxy-1
X-Test-Header: true
X-Traefik-Reqid: 153670
Accept-Encoding: gzip
```

Note this happens on the way back as well if I set a header in all caps it comes back camel-cased

**Comment by emilevauge** [comment] 2016-06-17 22:16
Hi, 
From RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", Section 4.2, "Message Headers":

>Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

golang std library transforms them in a canonical way https://github.com/golang/go/issues/5022. 
I strongly recommend you to make your apps case insensitive too.

**Comment by maguec** [comment] 2016-06-17 22:29
Thank you for the amazingly quick response.
It is greatly appreciated.

Unfortunately this is not an option at this time for these legacy applications.  
Keep up the awesome product

**Comment by emilevauge** [comment] 2018-07-06 14:35
Reopening this old issue, as we might discuss a way to disable this behavior.

**Comment by dtomcej** [comment] 2018-07-06 16:01
There is the classic way to dodge this behavior, by setting headers via map, so the key case is preserved ;) its old, and may not work forever, but it _is_ doable 😝

**Comment by xx6412223** [comment] 2018-12-21 02:02
Field names are case-insensitive. So why change the first char to uppercase  ??? Business really wanna use the lowercase key

**Comment by cmullendore** [comment] 2019-09-26 14:39
1. It is not the responsibility of Go to unilaterally decide how other systems should behave, including whether or not the systems being interacted with follow the case-insensitivity statement of the RFC.
2. A system/platform should not modify the information it is handling unless modification is the direct purpose of the request. 
3. The code used to modify the casing of field names likely introduces unnecessary functionality that risks additional bugs (regardless of whether such bugs currently exist) and removing that (and in fact any) such code eliminates the risk that such code could introduce unintended behavior.
4. If the supposition that uses of the platform really are respecting the case-insensitivity nature of the current implementation and therefore the current behavior of case modification theoretically introduces no issues, then removing this behavior should also cause equally zero impact to users.

This is *literally no reason* for modification of this behavior to be resisted by this team.

**Comment by acejam** [comment] 2019-11-02 02:06
@emilevauge Are there any updates on this issue? I unfortunately can no longer use Traefik due to the header casing manipulation. (Regardless of what the RFC says)

**Comment by emericv** [comment] 2020-03-11 16:29
I have the same issue too with an app that cannot be modified!

**Comment by JohnRusk** [comment] 2020-03-13 00:13
We get lots of requests, from users of our Go app, to preserve the case of headers. Our app transfers data and, consistent with @cmullendore's first point above, our users are most displeased with our app changing their data as it moves it (even if those changes are only in capitalization).

I understand there are workarounds already for Go apps that _set_ headers (stuff it directly into the map); but what we also need is a workaround when we _read_ headers. We need to make a request to an external service, read the response headers, and preserve their case. (Or, it would even be enough, if we could just get a map of CannonicalizedName->originalName.  I.e. it would be OK if everything worked the way it does now... as long as we could ALSO get information about what the original names were before cannonicalization.  I don't particularly care how hard it would be to get that info, as long as we could get it.)

I'd be happy to contribute code to do this, but before investing time in that, I'd be keen to hear from the Go team in this thread - what's your current view on this?  Can we win you around to the idea that something could be added or changed in this area?

**Comment by ldez** [comment] 2020-03-13 00:24
Small reminder:

- [HTTP/2 RFC7540](https://tools.ietf.org/html/rfc7540#section-8.1.2)

> Just as in HTTP/1.x, header field names are strings of ASCII
   characters that are compared in a case-insensitive fashion.  However,
   header field names MUST be converted to lowercase prior to their
   encoding in HTTP/2.

- [HTTP/1.0 RFC2616](https://tools.ietf.org/html/rfc2616#section-4.2)

>  Each header field consists of a name followed by a colon (":") and the field value. Field names  are case-insensitive.

- Golang related issue: https://github.com/golang/go/issues/5022

**Comment by JohnRusk** [comment] 2020-03-13 00:28
>Field names are case-insensitive.

Yes, but unfortunately, this is one of those areas where "what the standard says" and "what many people have come to rely on" are not the same thing.

**Comment by acejam** [comment] 2020-04-15 14:57
Bump for updates. We can no longer use Traefik due to this issue.

**Comment by JohnRusk** [comment] 2020-04-15 23:57
Feel free to also comment here: https://github.com/golang/go/issues/37834  

It's a thread to ask the Go team to either offer a workaround, or accept one developed by the community. Hopefully, if there's enough activity on that thread, they'll say yes ;-)

FYI, I'm not aware of any other viable answer to the problem.

**Comment by Lincoln-dac** [comment] 2020-04-16 08:19
how fix this issue??

**Comment by ToasterKTN** [comment] 2020-05-09 13:27
Modify a strings case for no reason is a bad habit. it not only breaks other peoples stuff, it also wastes resources.

**Comment by gufertum** [comment] 2021-12-15 09:02
+1
Please do not modify headers that pass through a proxy - this is bad-by-design. It should be transparent.

**Comment by milankowww** [comment] 2022-04-27 07:12
one more use case for you for not doing unnecessary conversions: old Outlook clients can't talk to Exchange via Traefik; only newest ones work

**Comment by ddtmachado** [comment] 2022-04-28 19:50
Thanks for everyone that participated in the discussions so far.  As of now, we are not going to change the way we handle headers. We've put a lot of thought into it and here is why we think this is the right decision:

- We think the use-case for case-sensitive headers is going to become increasingly smaller as headers must be case-insensitive according to the HTTP RFC and HTTP/2 doesn't change that.  Therefore, trying to adapt to this will bring more code complexity. Even worse, we believe that changing has the potential to introduce unintended behavior that would affect most/all users.
- Traefik Proxy was never meant to be a transparent proxy, and we have no plans of becoming one, so that solution is not going to work for us as well.
- If Go chooses to provide a solution in the future, we should follow it, but we just don't think they will do so.
- Finally, an App that uses case-sensitive has always been broken and needs to be fixed sooner or later.

We are going to close this issue, should Go provide a solution, please feel free to open a new one.

**Closed by ddtmachado** 2022-04-28 19:50 UTC
Labels: kind/enhancement, area/oxy
