### ISSUE TITLE
ReverseProxy read error during body copy: use of closed network connection

### ISSUE THREAD

**Issue by Yelijah** [traefik/traefik#9228] opened 2022-08-04 03:57 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

when i do performance testing for my application which use traefik as gateway，I find some of my request happens error，result is :
<img width="725" alt="企业微信截图_58e2aa6d-0d2d-46af-9db2-f9d6c418c44a" src="https://user-images.githubusercontent.com/33784573/182758858-1ee86161-1391-489d-a801-142a47d8b5b5.png">

Then i find some error log of traefik at the same time:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/33784573/182758994-a4a2a6f9-ce97-477d-8320-1a1450195bd8.png">

### What did you see instead?

I want to fix this error by anyway

### What version of Traefik are you using?

<img width="468" alt="image" src="https://user-images.githubusercontent.com/33784573/182759717-ce82d8a1-a3a7-40f3-ae5e-4d99f055ecff.png">

### What is your environment & configuration?

```yaml
[http]
  [http.routers]
    [http.routers.fr]
      entryPoints = ["fr"]
      # 匹配任意的域名或者ip，如果需要指定域名ip则用：rule = "Host(`www.xxx.com`) || (Host(`192.168.xxx.xxx)"
      rule = "HostRegexp(`{host:^[a-zA-Z0-9.]+$}`)"
      service = "fr"

  [http.services]
    [http.services.fr]
      [http.services.fr.loadBalancer]
        [[http.services.fr.loadBalancer.servers]]
          url = "http://localhost:8075/"
        [http.services.fr.loadBalancer.healthCheck]
          path = "/webroot/decision/system/health"  # 主动检查路径,如果响应码不是200或者超时,就摘除该节点
          interval = "30s"  # 每隔30秒检查一次
          timeout = "20s" # 超时时间
```

Add more configuration information here.

**Comment by Yelijah** [comment] 2022-08-04 04:00
by the way, the problem occurred 3 times in 10 minutes of performance testing

**Comment by rtribotte** [comment] 2022-08-04 13:11
Hello @Yelijah,

Thanks for your interest Traefik!

It looks like the java backend closed some connections and there is no wrong behavior on the Traefik side to report that.

Unfortunately, without a minimal reproducible case that would allow us to reproduce the issue, we are going to close this issue as a question.

**Closed by rtribotte** 2022-08-04 13:11 UTC
Labels: status/0-needs-triage
