### ISSUE TITLE
Support multiple podman instance, each in different user zone

### ISSUE THREAD

**Issue by Froggy232** [traefik/traefik#11211] opened 2024-10-23 00:16 UTC
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,
First, sorry if it's not possible, in this case feel free to just dismiss this bug report.
I use a server that run every of it's services in rootless podman container, each in a different user zone.
Would it be possible to make an instance of Traefik (that would run in a privileged rootful container of course) that could connect to multiples podman services, each in his own user zone?
If no, does someone know if Traefik is still relevant in this case, or is it better to use a regular manual reverse proxy like NGINX?
Thanks you a lot!

**Comment by emilevauge** [comment] 2024-10-24 12:42
I think it's a duplicate of https://github.com/traefik/traefik/issues/9101, therefore we are closing it as we do not want to support multiple providers of the same type.

**Closed by emilevauge** 2024-10-24 12:42 UTC
Labels: status/0-needs-triage
