### ISSUE TITLE
Handling "=" at the end of the string in the query parameters

### ISSUE THREAD

**Issue by timrettop** [traefik/traefik#10218] opened 2023-11-07 16:11 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm writing a router rule to match an API key that includes two "=" signs at the end of the key.  it looks like this: 

```      ## API Key Bypass
      - "traefik.http.routers.test-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.test-rtr-bypass.rule=Host(`test.$DOMAINNAME`) && Headers(`X-Api-Key`, `$TEST_API_KEY`) || Query(`apikey`,`$TEST_API_KEY`)"
      - "traefik.http.routers.test-rtr-bypass.priority=100"
```

### What did you see instead?

I get an error in the traefik logs indicating that its counting more than 2 parameters. 
```traefik   | 2023-11-07T15:54:26.904533479Z time="2023-11-07T15:54:26Z" level=error msg="mux: number of parameters must be multiple of 2, got [apikey {redacted key without ==} =]" routerName=test-rtr-bypass@docker entryPointName=https```

I see in PR #9369 that this was addressed in 2.8, but I'm wondering if the test didn't cover a case where 2 equals signs were at the end of the value. 

### What version of Traefik are you using?

Version:      2.10.5
Codename:     saintmarcelin
Go version:   go1.21.3
Built:        2023-10-11T13:54:02Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```traefik   | 2023-11-07T16:05:00.993482333Z time="2023-11-07T16:05:00Z" level=error msg="mux: number of parameters must be multiple of 2, got [apikey {redacted API key without ==} =]" entryPointName=https routerName=test-rtr-bypass@docker```

**Comment by nmengin** [comment] 2023-11-09 14:03
Hey @timrettop,

Thanks for reaching out.

If any community member can help us fix the issue, we would love the help.

**Comment by timrettop** [comment] 2023-11-10 18:25
Just to follow up, appreciate any thoughts on this.   I've tried various escaping to no avail, the environment variable shows correctly.   This seems to be errored after or during the creation of the middleware for the router based on the previous debug logs. 
```traefik  | 2023-11-10T18:10:28.865622722Z time="2023-11-10T18:10:28Z" level=debug msg="Creating middleware" routerName=test-rtr-bypass@docker middlewareName=middlewares-rate-limit@file middlewareType=RateLimiterType entryPointName=https
traefik  | 2023-11-10T18:10:28.865626250Z time="2023-11-10T18:10:28Z" level=debug msg="Using IPStrategy" entryPointName=https routerName=test-rtr-bypass@docker middlewareName=middlewares-rate-limit@file middlewareType=RateLimiterType
traefik  | 2023-11-10T18:10:28.865629683Z time="2023-11-10T18:10:28Z" level=debug msg="Adding tracing to middleware" routerName=test-rtr-bypass@docker entryPointName=https middlewareName=middlewares-rate-limit@file
traefik  | 2023-11-10T18:10:28.865635795Z time="2023-11-10T18:10:28Z" level=error msg="mux: number of parameters must be multiple of 2, got [apikey {redacted key without equals} =]" entryPointName=https routerName=test-rtr-bypass@docker
```

**Comment by sssash18** [comment] 2023-11-16 07:37
@timrettop @nmengin I tried to reproduce the error by hitting the unit test for the function responsible for this with the below  config.
`{
	desc: "Query with multiple equals",
	rule: "Query(`foo=bar==`)",
	expected: map[string]int{
		"http://localhost/foo?foo=bar==": http.StatusOK,
		"http://localhost/foo?foo=bar":   http.StatusNotFound,
	},
},`
The error message that @timrettop  quoted above is produced by `pkg/muxer/http/mux.go/query` func and the unit test above calls that func.
However the test passed successfully with above key value with two `=` signs at end. @timrettop Can you confirm once that the above query pattern as same as used by you ?

**Comment by andsarr** [comment] 2023-12-27 20:10
@timrettop The problem with your example is that it contains a syntax error. The correct syntax for the rule is:

``- "traefik.http.routers.test-rtr-bypass.rule=Host(`test.$DOMAINNAME`) && Headers(`X-Api-Key`, `$TEST_API_KEY`) || Query(`apikey=$TEST_API_KEY`)" ``

Take a look at the documentation at [Routers](https://doc.traefik.io/traefik/routing/routers/#rule)

If you are curious of why you get the error, this is the explanation:

Let's say that the value of  `TEST_API_KEY` is `dGhpcyBpcyBhIHRlc3Q=`. The code that handle the queries is:

https://github.com/traefik/traefik/blob/0a7964300166d167f68d5502bc245b3b9c8842b4/pkg/muxer/http/mux.go#L237-L246

In your example, the function will receive the `query` parameter as:
![query_parms](https://github.com/traefik/traefik/assets/6067584/eb245288-43b2-43e5-860a-ca8c7bc09aae)

which means that the call to `route.Queries(queries...)` will fails since it will be `route.Queries("apikey", "dGhpcyBpcyBhIHRlc3Q", "")`( `len(queries)` is not even).

**Comment by andsarr** [comment] 2023-12-27 20:10
@nmengin I think this issue can be closed

**Comment by juliens** [comment] 2023-12-29 14:55
Since this issue seems link to a syntax error and not a bug, I close it,
Feel free to reopen if needed.

**Closed by juliens** 2023-12-29 14:55 UTC
Labels: kind/bug/possible, area/rules

**Comment by timrettop** [comment] 2023-12-29 15:10
Thank you @andsarr, yes fixing this syntax error seems to have resolved the issue.
