### ISSUE TITLE
Feature: Support for LXD / Incus as a Provider

### ISSUE THREAD

**Issue by rendyananta** [traefik/traefik#10251] opened 2023-11-19 19:00 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi team, does the Traefik team have a roadmap plan to support LXD / Incus as a Traefik Provider? Currently both of the system containers don't have the instance groups feature. As I read and use Traefik, it is possible use Traefik Proxy as a service registry for exposing the LXD instances. I've written a simple HTTP app to provide Traefik config [in my repository](https://github.com/rndeey/traefik-provider-http-lxd). I need some kind of advice or community to help and test my application if it is in the Traefik roadmap. The HTTP provider is currently still in an experimental stage, because it is only tested on a sandboxed environment. Thank you.

**Comment by nmengin** [comment] 2023-11-20 13:40
Hey @rndeey,

Thanks for your suggestion.

This feature is currently not on the Roadmap.
We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.
We will reevaluate as people respond.

**Comment by ldez** [comment] 2023-11-20 13:46
Duplicate of #2195

**Comment by nmengin** [comment] 2024-10-17 13:36
Hello @rendyananta,
This proposal has almost no traction.

We won't add it to the Roadmap yet and we prefer to close it.
We'll re-open it later if necessary.

**Closed by nmengin** 2024-10-17 13:36 UTC
Labels: kind/proposal, area/provider
