### ISSUE TITLE
Improve ForwardAuth documentation (method, body)

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9952] opened 2023-06-13 09:12 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

[Traefik ForwardAuth documentation](https://doc.traefik.io/traefik/middlewares/http/forwardauth/) is IMHO missing some information bits:

1. Will original request be forwarded with the same HTTP method or will they all be "converted" to GET?

2. If POSTs are forwarded as POSTs, how can the BODY be disabled? Nginx has `proxy_pass_request_body off;`

**Comment by bluepuma77** [comment] 2023-06-16 08:27
I would think that 1. is only a single sentence, but someone with knowledge of the code needs to tell us.

**Comment by dargmuesli** [comment] 2024-10-12 01:14
My experience is that
1. the method stays the same
2. body will not be forwarded (https://github.com/traefik/traefik/issues/11029)

**Comment by dargmuesli** [comment] 2024-10-12 01:14
Also see:
- https://github.com/traefik/traefik/issues/7106

**Comment by nmengin** [comment] 2024-10-14 12:39
Hello @bluepuma77,

As mentioned by @dargmuesli, this issue is a duplicate of #7106.
I close this issue accordingly.

**Closed by nmengin** 2024-10-14 12:39 UTC
Labels: kind/enhancement, area/documentation, priority/P3, contributor/wanted
