### ISSUE TITLE
compression error

### ISSUE THREAD

**Issue by tipruzs** [traefik/traefik#3981] opened 2018-10-04 16:24 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

i configured traefik to serve tomcat 8.5 webapp using http2

### What did you expect to see?

working as expected (v1.6.6 works)

### What did you see instead?

internal server error

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.1-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - "--loglevel=DEBUG"
      - "--checknewversion=false"
      - "--insecureskipverify=true"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Compress:false Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS TLS.MinVersion:VersionTLS12 Compress:false"
      - "--api"
      - "--api.statistics"
      - "--metrics"
      - "--metrics.prometheus"
      - "--ping"
      - "--docker"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--docker.swarmmode"

...

  app:
   ...
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "overlay"
        traefik.port: "8443"
        traefik.protocol: "https"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:api.example.com;PathPrefix:/path1,/path2"
```

Stripped out unimportant details.

I already tried do disable compression on the backend, but the issue still happens. Only workaround is to downgrade back to v1.6.6

Tomcat uses self signed certificate (EC, prime256v1)

For the sake of completeness, this is the tomcat connector config
```xml
<Connector port="8443" protocol="org.apache.coyote.http11.Http11AprProtocol" executor="tomcatThreadPool" SSLEnabled="true" acceptorThreadCount="2"
           compression="off" connectionTimeout="120000" sendReasonPhrase="true" >
    <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
    <SSLHostConfig>
        <Certificate certificateKeyFile="/path/to/localhost.key"
                     certificateFile="/path/to/localhost.pem"
                     type="EC" />
    </SSLHostConfig>
</Connector>
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
level=debug msg="'500 Internal Server Error' caused by: connection error: COMPRESSION_ERROR"
level=debug msg="vulcand/oxy/forward/http: Round trip: https://10.0.7.68:8443, code: 500, Length: 21, duration: 8.800802ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:api.example.com"
```

**Comment by Juliens** [comment] 2018-10-08 12:59
Thanks for you interest in the project.

First of all, the message about pipelining is not linked to your problem.
I think, the message about COMPRESSION_ERRROR has been sent by the backend.
Do you have some logs on your backend when this error occur?

**Comment by tipruzs** [comment] 2018-10-10 09:50
i created a sandbox for testing this issue without any custom applications. The issue is only tracked in the traefik logs.

I'm wondering what changed in traefik 1.7 at the compression handling. I currently have no idea how to debug this further.

Please find attached the required docker-compose and snippets in order to be able to reproduce this issue.

```yaml
version: "3.6"

networks:
  overlay:
    attachable: true

services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - "--loglevel=DEBUG"
      - "--checknewversion=false"
      - "--insecureskipverify=true"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Compress:false Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS TLS.MinVersion:VersionTLS12 Compress:false"
      - "--api"
      - "--api.statistics"
      - "--ping"
      - "--docker"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--docker.swarmmode"
    networks:
      - overlay
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
  tomcat:
    image: tomcat:8-jre8-alpine
    entrypoint: "/entrypoint.sh"
    command: "catalina.sh run"
    networks:
      - overlay
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - ./entrypoint_tomcat.sh:/entrypoint.sh
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "overlay"
        traefik.port: "8443"
        traefik.protocol: "https"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:tomcat.example.com"
```

[tomcat-server-xml-and-entrypoint.zip](https://github.com/containous/traefik/files/2464109/tomcat-server-xml-and-entrypoint.zip)

**Comment by istilbahc** [comment] 2019-03-25 08:38
I'm also getting this error using Payara 5.181 and Traefik's  stable helm chart with image - 1.7.9

```2019/03/21 15:07:54 frame.go:388: http2: Framer 0xc000a79340: wrote HEADERS flags=END_STREAM|END_HEADERS stream=25 len=239
2019/03/21 15:07:54 frame.go:514: http2: Framer 0xc000a79340: read GOAWAY len=8 LastStreamID=25 ErrCode=COMPRESSION_ERROR Debug=""
2019/03/21 15:07:54 transport.go:2179: http2: Transport received GOAWAY len=8 LastStreamID=25 ErrCode=COMPRESSION_ERROR Debug=""
2019/03/21 15:07:54 transport.go:2179: transport got GOAWAY with error code = COMPRESSION_ERROR
2019/03/21 15:07:54 transport.go:2179: http2: Transport readFrame error on conn 0xc000656c40: (*errors.errorString) EOF
2019/03/21 15:07:54 transport.go:2179: RoundTrip failure: http2: server sent GOAWAY and closed the connection; LastStreamID=25, ErrCode=COMPRESSION_ERROR, debug=""
time="2019-03-21T15:07:54Z" level=debug msg="'500 Internal Server Error' caused by: http2: server sent GOAWAY and closed the connection; LastStreamID=25, ErrCode=COMPRESSION_ERROR, debug=\"\""
time="2019-03-21T15:07:54Z" level=debug msg="vulcand/oxy/forward/http: Round trip: https://10.1.1.210:8181, code: 500, Length: 21, duration: 26.3842ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:local.test.com"

**Comment by EspA** [comment] 2019-10-22 13:21
I'm facing the same issue since I'm using HTTP2 with Tomcat 9.0.27. With HTTP1 everything is ok.

Traefik version = 1.7

**Comment by tfny** [comment] 2022-04-14 15:46
As we no longer support Traefik version 1, I am going to close this issue.

If this issue persists in version 2, feel free to open a new issue.   Thanks!

**Closed by tfny** 2022-04-14 15:46 UTC
Labels: priority/P1, kind/bug/possible, area/middleware
