### ISSUE TITLE
docker image for 2.5.0 only for linux/arm/v6

### ISSUE THREAD

**Issue by macno** [traefik/traefik#8365] opened 2021-08-18 07:06 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

`docker pull traefik:2.5.0` on linux/amd64

### What did you see instead?

```
╰─➤  docker pull traefik:2.5.0
2.5.0: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries
```

Checking on hub.docker.com confirms that only linux/arm/v6 is available https://hub.docker.com/layers/traefik/library/traefik/2.5.0/images/sha256-20e664ac09630f6ba4f32bc839f8e1efdb427ebe7cd75348613592cc4e71a93b?context=explore

### What version of Traefik are you using?

trying to install 2.5.0 from docker hub

### What is your environment & configuration?

on linux/amd64

**Comment by Heisenberg74** [comment] 2021-08-18 10:02
Hi, Same issue there !

**Comment by james-d-elliott** [comment] 2021-08-18 10:30
Also the v2.5 image is actually v2.5.0-rc6. ;)

**Comment by baalajimaestro** [comment] 2021-08-18 10:34
When I pulled, i too noticed the dockerhub description alone was updated, with the tags being still at 2.5.0-rc6 or 2.4.14 in the case of latest, but noticably the [docker builder](https://github.com/traefik/traefik-library-image/tree/master/alpine) was updated, so I did manage to just docker build it easily. It didn't take much time to build too, unlike building from master.

**Comment by macno** [comment] 2021-08-18 11:05
I see new images were pushed but `v2.5.0` and `2.5.0` still miss the image for `linux/amd64`

<img width="1276" alt="Screenshot 2021-08-18 at 13 01 24" src="https://user-images.githubusercontent.com/76600/129887379-5f07934e-90f7-4d40-ad04-08e3febe9a40.png">

**Comment by ldez** [comment] 2021-08-18 11:58
Hello,

It always happens because the images are built by Docker, we do not control the way they are published.

The image is currently under construction.

https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/

duplicate of #7265, #7023,  #6287,  #5992, #5512, #4265,  #2467, #5348

**Closed by ldez** 2021-08-18 11:58 UTC
Labels: status/0-needs-triage
