### ISSUE TITLE
session sticky based on cookie or header hash strategy 

### ISSUE THREAD

**Issue by Yelijah** [traefik/traefik#9236] opened 2022-08-09 08:13 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Can traefik support session sticky based on cookie or header hash strategy which just like nginx's "hash  $cookie_xxx" ? 

In other words，I want that all requests with same header value or cookie value can be forward to one same server.

I couldn't find anything like it in doc or plugins.

**Comment by ddtmachado** [comment] 2022-08-09 12:26
Duplicate of https://github.com/traefik/traefik/issues/1207

**Closed by ddtmachado** 2022-08-09 12:26 UTC
Labels: status/0-needs-triage
