### ISSUE TITLE
1.7.24: service weights: equal distribution across 3 backends

### ISSUE THREAD

**Issue by bitsofinfo** [traefik/traefik#7843] opened 2021-02-01 18:33 UTC
traefik:1.7.24

Does not seem possible to do a equal distribution of weights into 3rds

```
    traefik.ingress.kubernetes.io/service-weights: |
      myapp1-9000: 33.333%
      myapp2--9000: 33.333%
      myapp3--9000: 33.333%
```

```
{"level":"error","msg":"failed to create fractional weight allocator for ingress x/myapp-9000.all--mydomain.com: the sum of weights(99.999%) in the path mydomain must be 100% when no omitted fractional service left","time":"2021-02-01T18:23:55Z"}
```

**Comment by bitsofinfo** [comment] 2021-02-01 22:26
If I use 34,33,33, it is accepted however the resulting routing is not what I'd expect. The majority of the traffic goes to one service, and the other two get very little, when I'd expect them to all get roughly the same amount (1/3rd)

**Comment by SantoDE** [comment] 2021-02-02 15:58
Duplicate of #5595

**Closed by SantoDE** 2021-02-02 15:58 UTC
Labels: status/0-needs-triage

**Comment by bitsofinfo** [comment] 2021-02-02 16:27
im not sure its a duplicate, im not adding percentages w/ decimal places....
