### ISSUE TITLE
mTLS between traefik and kubernetes services

### ISSUE THREAD

**Issue by kumar-shantanu** [traefik/traefik#7632] opened 2020-12-07 11:45 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

I am not sure if this should be categorized as a bug or feature request to be honest. I would imagine I should be able to do mTLS between traefik and backend service. This is something I have been able to do with Nginx ingress and gloo so I would think probably there is some documentation missing around this. 

I am trying to achive this flow, 

client >>>>  traefilk(The client TLS terminates here) >>>>  mTLS starts here with a different cert/key >> >> kubernetes service 

I **don't** want to have mTLS between the client to the end service(hosted on Kubernetes). 

### What did you see instead?

I am not able to achieve this. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker tag 2.3.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (kuberenetes)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by kevinpollet** [comment] 2020-12-07 17:13
Duplicate of #4835

**Closed by kevinpollet** 2020-12-07 17:13 UTC
Labels: status/0-needs-triage
