### ISSUE TITLE
RedirectRegex Middleware with multiple entries

### ISSUE THREAD

**Issue by PhilipMay** [traefik/traefik#8644] opened 2021-12-20 07:15 UTC
Hi,
it seems like the RedirectRegex Middleware accepts only one entry. Like so:
```yaml
spec:
  redirectRegex:
    regex: ^http://localhost/(.*)
    replacement: http://mydomain/${1}
```

What about providing the possibility to provide multiple entries - like so:

```yaml
spec:
  redirectRegex:
    - regex: ^http://localhost/(.*)
      replacement: http://mydomain/${1}
    - regex: ^http://localhost/xy/(.*)
      replacement: http://abc.mydomain/${1}
    - regex: ^http://localhost/cw/(.*)
      replacement: http://efg.otherdomain/${1}
```

**Comment by ldez** [comment] 2021-12-20 08:35
duplicate of #723

**Closed by ldez** 2021-12-20 08:35 UTC
Labels: status/0-needs-triage
