### ISSUE TITLE
Traefik instances sharing TLS certificates between each other

### ISSUE THREAD

**Issue by couling** [traefik/traefik#8815] opened 2022-03-03 14:59 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Background
------------

We have many instances of Traefik which all act as a gateway for many separate domain names.  On more than one occasion we've run into problems with rate [Letsencrypt rate limits](https://letsencrypt.org/docs/rate-limits/).  Some of these issues have been caused by unfortunate timing between multiple instances all trying to renew certificates for the same domain at the same time.

We can get round this partially with wildcard certificates to colapse down the number of certificates required.  But we still keep bumping into limits and having to adjust.

Reading through the documentation, it's not clear if multiple instances of Traefik can share the same certificate store and  avoid having multiple concurrent certificates for the same domain name.  I've tried asking about this [on the community forum](https://community.traefik.io/t/can-traefik-instances-share-the-same-acme-certificate-store/11836) but with no response.

Therefore I'm not sure if I'm asking for better documentation or a new feature.

Suggested Feature
----------

Traefik should support multiple instances sharing the same certificate store.  This would allow the certificate store to be replicated between nodes (eg: shared over NFS) to avoid any need for multiple instances each having their own certificate for the same domain name:
1. Writing certificates to the certificate store should be atomic. Usually this means writing to a temporary file and then renaming the file to move it into place.  This would allow another instance sharing the same certificate store could safely read without fear of reading a partial file.
2. The certificate store should be protected against concurrent writing with a lock file or similar.
3. Before executing an ACME request Traefik should reload the certificate store from disk to check if another instance has already renewed the certificate.

**Comment by kevinpollet** [comment] 2022-03-04 14:03
Duplicate of https://github.com/traefik/traefik/issues/5426

**Closed by kevinpollet** 2022-03-04 14:03 UTC
Labels: status/0-needs-triage
