### ISSUE TITLE
[Bug] APM data is not ingested into DATADOG using OTLP

### ISSUE THREAD

**Issue by changhyuni** [traefik/traefik#10916] opened 2024-07-18 11:31 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

APM data is not ingested into DATADOG using OTLP

### What did you see instead?

No data received datadog log

### What version of Traefik are you using?

traefik 3.0.1
eks - kubernetes 1.27
helm chart 29.0.0

### What is your environment & configuration?

```yaml
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
      - '--tracing.otlp.http.endpoint=http://$(DD_AGENT_HOST):4318' (traefik args)
```
```yaml
  datadog:
    otlp:
      receiver:
        protocols:
          http:
            enabled: true
            endpoint: "0.0.0.0:4318"
            useHostPort: true
```

**Comment by nmengin** [comment] 2024-07-18 13:22
Hey @changhyuni,

Thanks for reaching out.

Could you provide a minimal reproducible case (for instance, full Kubernetes manifest to reproduce the issue)?

**Comment by changhyuni** [comment] 2024-07-19 03:02
@nmengin 
Thanks you for asking!
```yaml

**Comment by rtribotte** [comment] 2024-07-22 13:11
Hello @changhyuni,

This issue seems to be a configuration issue, that is not related to the Traefik's behavior.

Which version of the Datadog agent are you using? Also, the Datadog agent OTel ingestion endpoint needs to be enabled (please see https://docs.datadoghq.com/fr/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=docker#enabling-otlp-ingestion-on-the-datadog-agent).

> What logs are left after a successful trace ingested?

If the tracer doesn't succeed in sending the traces, you should see a log like this:
```
2024-07-22T15:02:48+02:00 DBG ... handler.go:30: traces export: Post "https://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused
```

The GitHub issue tracker is dedicated to bug and feature requests.
For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think we missed something.

**Closed by rtribotte** 2024-07-22 13:11 UTC
Labels: status/0-needs-triage, contributor/waiting-for-feedback
