### ISSUE TITLE
Filter query parameters from access logs

### ISSUE THREAD

**Issue by sebas2day** [traefik/traefik#8515] opened 2021-10-13 11:35 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Query parameters/string is embedded within `RequestPath` that is being extracted from the request URI. Query parameters can contain privacy sensitive information, just like headers. 

Currently there is no such thing as `RequestQueryString` or something. It would be great if I could `redact`/`drop` this information.

**Comment by rickygarg** [comment] 2024-08-26 04:01
Ideally allow custom regex to find and replace logs, similar to nginx. 

But meanwhile, simply the ability to drop `RequestQueryString` as proposed would be make it more justifiable to use on production environments.

**Comment by nmengin** [comment] 2024-08-26 13:04
Close a duplicate of #10735

**Closed by nmengin** 2024-08-26 13:04 UTC
Labels: kind/proposal
