### ISSUE TITLE
Mutual TLS (client auth): Blacklist/Revoke certificates

### ISSUE THREAD

**Issue by 0x6a61** [traefik/traefik#9817] opened 2023-03-30 18:38 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The possibility to revoke/blacklist certificates.

E.g. if the private key of 1 out of 100 client certificates was leaked, there should be a way to blacklist this specific certificate.

**Comment by rtribotte** [comment] 2023-03-31 12:24
Hello @0x6a61,

Thanks for your interest in Traefik!

It looks like this is a duplicate, we are closing it in benefit of #3433.

Duplicate of #3433.

**Closed by rtribotte** 2023-03-31 12:24 UTC
Labels: status/0-needs-triage
