### ISSUE TITLE
Adding "Priority" router information on the Traekik GUI

### ISSUE THREAD

**Issue by Yivan** [traefik/traefik#7503] opened 2020-11-03 15:46 UTC
Hello,

This is a suggestion to improve debug of routing more easily and friendly.
Purpose of this issue is adding on the Traefik GUI in the router section the priority of the route (the one automaticaly computed from the rule or the one forced by the `priority` setting):

![image](https://user-images.githubusercontent.com/9025839/98007488-bc662000-1df3-11eb-839f-756178d0846a.png)

This information could be added as well on the route list so it is more easy to compare priorities:

![image](https://user-images.githubusercontent.com/9025839/98007745-06e79c80-1df4-11eb-9976-a114bac32688.png)

Thanks.

**Comment by rtribotte** [comment] 2020-11-03 16:14
Hello @Yivan,

Thanks for your suggestion !
I think it's a duplicate of #5667 and i'll close it accordingly.
Feel free to interact in this issue for further discussions.

**Closed by rtribotte** 2020-11-03 16:14 UTC
Labels: status/0-needs-triage

**Comment by Yivan** [comment] 2020-11-03 17:41
You are right, sorry i didn't have seen this other issue !
Thanks a lot.
