### ISSUE TITLE
[Feature request] Route name in metrics

### ISSUE THREAD

**Issue by jorge07** [traefik/traefik#7504] opened 2020-11-03 19:57 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

From Traefik 1 to Traefik 2 the metrics differs and that's ok but there're some limitations with the current implementation that were possible in v1. One in particular it's very important for our use case:

- `backend` labels in `traefik_backend_requests_total` referred to the `rule` not to the `backend/service` name. Having it like this I can monitor each rule as I've multiple sites served by the same service. If one domain has an anomaly I can know it. Not in v2.
Example
```
Rule -> Service
---
members.YYY.com/graphql -> api-gateway
members.XXX.com/graphql -> api-gateway
www.YYY.com/graphql -> api-gateway
www.XXX.com/graphql -> api-gateway
www.YYY.com/img -> static-svc
www.YYYY.com/ -> tour
www.XXX.com/ -> tour
```
By having this rules defined in my different k8s ingress I can identify an anomaly in `api-gateway` coming from site `YYY`. 
That's not possible in v2 unless I define a new service for each site, which for my use case it's quite pointless.

#### Request

Add `router name` as label in `traefik_service_*` metrics. 
Or
Add router metrics 

Feel free to ask for more context if isn't clear.

**Comment by jorge07** [comment] 2020-11-03 20:02
I understand that some people can be worried about cardinality but IMO you shouldn't as rule names aren't dynamic like URI.

**Comment by rtribotte** [comment] 2020-11-04 16:17
Hello @jorge07,

Thanks for your suggestion !
I think it's a duplicate of #6495 and i'll close it accordingly.
Feel free to interact in this issue for further discussions.

**Closed by rtribotte** 2020-11-04 16:17 UTC
Labels: status/0-needs-triage

**Comment by jorge07** [comment] 2020-11-04 16:34
Sure, sorry that I missed that.
