### ISSUE TITLE
`redirectScheme` doesn't work when applied to entrypoints

### ISSUE THREAD

**Issue by RealOrangeOne** [traefik/traefik#8035] opened 2021-04-06 10:55 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Create an entrypoint with an attached middleware:

```yml
web-secure:
    address: :443
    http:
      middlewares:
        - tls-redirect@file
```

```yml
http:
  middlewares:
    tls-redirect:
      redirectScheme:
        scheme: https
```

### What did you expect to see?

When connecting using `curl -I http://example.com:443`, I should be redirected to `https`

### What did you see instead?

404 response

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker, using configuration above.

Note that the above also didn't work with the middleware applied to a `:80` entrypoint, but the middleware does work as needed when applied to a a router.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A

**Comment by jakubhajek** [comment] 2021-04-08 11:37
Hello @RealOrangeOne 

Thanks for your interest in Traefik. 

In order to have redirection from HTTP to HTTPS,  you need to assign the middleware on the router that is responsible for managing HTTP connections.  The recommended way is to create two routers, the first for HTTP (with the `redirectscheme` middleware assigned to) and the second for HTTPS. Then you will get the 301 HTTP response.

You can also enable the permanent redirection of all incoming requests on an entry point to another entry point as you already configured in your PR.

**Comment by RealOrangeOne** [comment] 2021-04-08 16:04
My example may not be the best, but I did also try that.

```yml
web:
    address: :80
    http:
      middlewares:
        - tls-redirect@file
```

Which also didn't work.

I do have 2 _entrypoints_ handling HTTP and HTTPS connections, but it was only when moving the middleware from a catch-all router to the entrypoint that I spotted this issue.

**Comment by jakubhajek** [comment] 2021-04-14 11:56
Hi @RealOrangeOne 

In the case, you described the solution is to use global redirection on an entry point as it is described in our [docs](https://doc.traefik.io/traefik/routing/entrypoints/#redirection). By using that approach there is no need to create redirectscheme middleware because all incoming requests on a specific entry point will be redirected to another entry point or port.

**Comment by RealOrangeOne** [comment] 2021-04-14 12:52
That would mostly work, at least for this case, but i'd also like to prevent `http://example.com:443` from working, which the redirection won't do. This is how i'm currently doing it, but it'd be nice to protect against that case.

Even then, it still wouldn't fix the "There's a middleware which doesn't work when applied to entrypoints" problem, which is still a bug.

**Comment by jakubhajek** [comment] 2021-04-14 15:04
Hello @RealOrangeOne 

I've just created a test environment with the following configuration: 

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`w.wrks.demo.traefiklabs.tech`)
      services:
        - kind: Service
          name: whoami-svc
          port: 80
  tls:
    certResolver: le
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-http-websecure
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`w.wrks.demo.traefiklabs.tech`)
      services:
        - kind: Service
          name: whoami-svc
          port: 80
      middlewares:
        - name: redirectscheme
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
```

I have created two routers:
1. the first is listening on `websecure` with TLS termination
2. the second is listening on `web` and `websecure ` with no TLS termination

Having that configuration I can send the HTTP request with port 443 and the request is being redirected to `https://w.wrks.demo.traefiklabs.tech`, 
```
curl http://w.wrks.demo.traefiklabs.tech:443 -L -v
*   Trying 15.236.171.43...
* TCP_NODELAY set
* Connected to w.wrks.demo.traefiklabs.tech (15.236.171.43) port 443 (#0)
> GET / HTTP/1.1
> Host: w.wrks.demo.traefiklabs.tech:443
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: https://w.wrks.demo.traefiklabs.tech/
< Date: Wed, 14 Apr 2021 14:53:23 GMT
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
```

There is no customized configuration added to the entrypoints and everything comes down to routers setup, in my case Ingresroutes.
As it is not a bug and it is rather a configuration-related question I highly recommend continuing conversation on our [community forum](https://community.traefik.io/).

Thank you, 

PS. The test environment will be available for the next few hours, so feel free to perform some tests.

**Closed** 2021-04-14 15:18 UTC
Labels: contributor/waiting-for-feedback, kind/question

**Comment by RealOrangeOne** [comment] 2021-04-14 15:46
Unfortunately that's still not my set up. 

I've tested the middleware works absolutely fine when applied to a router on my infrastructure (which I think is what your config does too). 

My issue is that when it's applied to an **entrypoint**, it doesn't work as expected. Even if the middleware itself isn't modified at all, just moving it from the router to the entrypoint stops it from working. _That's_ the issue i'm reporting here.

**Comment by ldez** [comment] 2021-04-14 16:03
Middleware is not applied to an entry point but defines at the entrypoint configuration level.

A middleware is always applied at the router level even if define through the entrypoint level.

I recommend using the dedicated redirection configuration in the entrypoint configuration:
https://doc.traefik.io/traefik/v2.4/routing/entrypoints/#redirection

**Comment by RealOrangeOne** [comment] 2021-04-15 08:24
Ah I see, thanks for the clarification!

I can see the middleware being applied correctly to the routers, and yet still the redirection isn't happening. Instead it results in a 404, which is also sort of suspect.

I'll try and spin up a minimal broken config so I can isolate it not working.

**Comment by RealOrangeOne** [comment] 2021-04-15 16:46
I think i've found the issue.

I'd missed that enabling TLS on a router prevents it from listening for HTTP traffic. That means that the middleware never had a HTTP router to listen on, and therefore there's nothing listening on `http:80` for the middleware to be applied to, hence it's returning a 404 instead.

I'm probably going to go back to the wildcard matching router which listens on HTTP only, which with the middleware applied, will be caught when needed.
