### ISSUE TITLE
Incorrect routing in ingressroute with the same priority

### ISSUE THREAD

**Issue by tide34** [traefik/traefik#9054] opened 2022-05-31 05:07 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have two ingressroute with different priority. The first one is simple match host header + path and the last one (with higher priority) match host header + path + cookie header. Sometimes requests from ingressroute with higher priority proxied to incorrect backend.  
  
As a rule this bug appears after restart of traefik pod.

### What did you see instead?

Traefik proxied traffic to correct backend

### What version of Traefik are you using?

Kubernetes (traefik v2.4.8), minikube (traefik v2.7.0). Default helm chart was used to install traefik from documentation [here](https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-helm-chart).

### What is your environment & configuration?

<details>

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-22-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) 
    kind: Rule
    priority: 322
    services:
      - name: root-3-22
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-22-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && HeadersRegexp(`Cookie`,`version=3.22`)
    kind: Rule
    priority: 10000
    services:
      - name: root-3-22
        port: 80  
---  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-22-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)
    kind: Rule
    priority: 322
    services:
      - name: profile-3-22
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-22-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)  && HeadersRegexp(`Cookie`,`version=3.22`)
    kind: Rule
    priority: 10000
    services:
      - name: profile-3-22
        port: 80  
---  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-21-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) 
    kind: Rule
    priority: 321
    services:
      - name: root-3-21
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-21-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && HeadersRegexp(`Cookie`,`version=3.21`)
    kind: Rule
    priority: 10000
    services:
      - name: root-3-21
        port: 80  
---  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-21-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)
    kind: Rule
    priority: 321
    services:
      - name: profile-3-21
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-21-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)  && HeadersRegexp(`Cookie`,`version=3.21`)
    kind: Rule
    priority: 10000
    services:
      - name: profile-3-21
        port: 80  
```

</details>

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Cookie\":[\"version=3.22\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:31906\"],\"X-Forwarded-Port\":[\"31906\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-m44wn\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:31906\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:41003\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: begin ServeHttp on request","time":"2022-05-27T07:30:58Z"}
{"ForwardURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.3:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Cookie\":[\"version=3.22\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:31906\"],\"X-Forwarded-Port\":[\"31906\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-m44wn\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:31906\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:41003\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: Forwarding this request to URL","time":"2022-05-27T07:30:58Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Cookie\":[\"version=3.22\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:31906\"],\"X-Forwarded-Port\":[\"31906\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-m44wn\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:31906\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:41003\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: completed ServeHttp on request","time":"2022-05-27T07:30:58Z"}
{"ClientAddr":"172.17.0.1:41003","ClientHost":"172.17.0.1","ClientPort":"41003","ClientUsername":"-","DownstreamContentSize":153,"DownstreamStatus":404,"Duration":4871750,"OriginContentSize":153,"OriginDuration":4478395,"OriginStatus":404,"Overhead":393355,"RequestAddr":"app.abc:31906","RequestContentSize":0,"RequestCount":20,"RequestHost":"app.abc","RequestMethod":"GET","RequestPath":"/profile","RequestPort":"31906","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"app-root-3-22-header-c78c3739d67570ccbd2f@kubernetescrd","ServiceAddr":"172.17.0.3:80","ServiceName":"app-root-3-22-header-c78c3739d67570ccbd2f@kubernetescrd","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.3:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2022-05-27T07:30:58.422826867Z","StartUTC":"2022-05-27T07:30:58.422826867Z","entryPointName":"web","level":"info","msg":"","time":"2022-05-27T07:30:58Z"}
```

**Comment by rtribotte** [comment] 2022-05-31 11:56
Hello @tide34,

Can you narrow down the example configuration to the case you identified as an incorrect behavior (only two ingress routes), with the example requests showing the incorrect routing?
Can you also share the full debug log trace, in order to see the applied configuration as well as the access logs?

**Comment by tide34** [comment] 2022-05-31 12:34
detailed description you can find [here](https://github.com/traefik/traefik/issues/9048)

**Comment by rtribotte** [comment] 2022-05-31 13:19
Hello @tide34,

I took a look at #9048, unfortunately, this issue is not (as well) strictly restricted to the priority issue between the two ingress routes you are mentioning.
Following my previous comment, can you please provide a simple reproduction case restricted to the problem, as well as the full debug log trace?

**Comment by tide34** [comment] 2022-05-31 18:32
I have two ingressroute with THE SAME priority - sorry, i have mistace in issue description.  
  
Step:  
1. apply next [manifest](https://github.com/tide34/traefik-test/blob/main/config.yaml)  
2. send curl request:  
curl http://app.abc/  
curl http://app/abc/profile  
  
result: one of the request failed, due to matching rule not appied.

**Comment by tide34** [comment] 2022-05-31 18:48
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:32257\"],\"X-Forwarded-Port\":[\"32257\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-jm8jh\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:32257\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:10201\",\"RequestURI\":\"/\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: begin ServeHttp on request","time":"2022-05-31T18:47:24Z"}
{"ForwardURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.5:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:32257\"],\"X-Forwarded-Port\":[\"32257\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-jm8jh\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:32257\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:10201\",\"RequestURI\":\"/\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: Forwarding this request to URL","time":"2022-05-31T18:47:24Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:32257\"],\"X-Forwarded-Port\":[\"32257\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-jm8jh\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:32257\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:10201\",\"RequestURI\":\"/\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: completed ServeHttp on request","time":"2022-05-31T18:47:24Z"}
{"ClientAddr":"172.17.0.1:10201","ClientHost":"172.17.0.1","ClientPort":"10201","ClientUsername":"-","DownstreamContentSize":67,"DownstreamStatus":200,"Duration":4177069,"OriginContentSize":67,"OriginDuration":4006054,"OriginStatus":200,"Overhead":171015,"RequestAddr":"app.abc:32257","RequestContentSize":0,"RequestCount":27,"RequestHost":"app.abc","RequestMethod":"GET","RequestPath":"/","RequestPort":"32257","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"test-root-3-22-default-c6d862987f24e8361b67@kubernetescrd","ServiceAddr":"172.17.0.5:80","ServiceName":"test-root-3-22-default-c6d862987f24e8361b67@kubernetescrd","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.5:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2022-05-31T18:47:24.301177633Z","StartUTC":"2022-05-31T18:47:24.301177633Z","entryPointName":"web","level":"info","msg":"","time":"2022-05-31T18:47:24Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:32257\"],\"X-Forwarded-Port\":[\"32257\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-jm8jh\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:32257\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:3995\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: begin ServeHttp on request","time":"2022-05-31T18:47:26Z"}
{"ForwardURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.5:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:32257\"],\"X-Forwarded-Port\":[\"32257\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-jm8jh\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:32257\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:3995\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: Forwarding this request to URL","time":"2022-05-31T18:47:26Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:32257\"],\"X-Forwarded-Port\":[\"32257\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-jm8jh\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:32257\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:3995\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: completed ServeHttp on request","time":"2022-05-31T18:47:26Z"}
{"ClientAddr":"172.17.0.1:3995","ClientHost":"172.17.0.1","ClientPort":"3995","ClientUsername":"-","DownstreamContentSize":153,"DownstreamStatus":404,"Duration":1571118,"OriginContentSize":153,"OriginDuration":1383897,"OriginStatus":404,"Overhead":187221,"RequestAddr":"app.abc:32257","RequestContentSize":0,"RequestCount":28,"RequestHost":"app.abc","RequestMethod":"GET","RequestPath":"/profile","RequestPort":"32257","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"test-root-3-22-default-c6d862987f24e8361b67@kubernetescrd","ServiceAddr":"172.17.0.5:80","ServiceName":"test-root-3-22-default-c6d862987f24e8361b67@kubernetescrd","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.5:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2022-05-31T18:47:26.975910611Z","StartUTC":"2022-05-31T18:47:26.975910611Z","entryPointName":"web","level":"info","msg":"","time":"2022-05-31T18:47:26Z"}

**Comment by rtribotte** [comment] 2022-06-01 07:57
Hello @tide34,

Unfortunately, we are not able to reproduce any bug because you are still not providing a minimal reproduction case and a clear description of the bug. It seems that you are dealing with a configuration issue.

The GitHub issue tracker is dedicated to bug and feature requests.
For help with your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to ask to re-open it if you can provide a minimal reproduction case and a clear description of the bug you are facing.

**Closed by rtribotte** 2022-06-01 07:57 UTC
Labels: status/0-needs-triage, contributor/waiting-for-feedback, area/provider/k8s/crd
