### ISSUE TITLE
Provide more realistic examples

### ISSUE THREAD

**Issue by marcbria** [traefik/traefik#7700] opened 2020-12-22 08:32 UTC
Traefik's documentation is great but sometimes you can find examples like this:

https://github.com/traefik/traefik/blob/3ff83fc1f8281851e56dcc5f18600be8fbb6fe9f/docs/content/reference/dynamic-configuration/file.yaml#L5

It's a great example but the use of "foobar" is excesive and don't let you understand the references or make searches in the example.

To make it easier to follow, I would encourage to modify to something like this:

```yaml
http:
  routers:
    Router0:
      entryPoints:
      - varWebInsecure
      - varWebSecure
...
```

The "var" prefix will let you know that's something to change and the name will make the example more realistic and significative.

Thanks a lot for the great project.

**Comment by ldez** [comment] 2020-12-22 16:41
Hello,

The reference pages provided only the global structure and they are generated.
The reference pages don't provide examples, it's just a global overview, the examples are in the pages related to topics.

It's a kind of duplicate of https://github.com/traefik/traefik/issues/4332

**Closed by ldez** 2020-12-22 16:41 UTC
Labels: area/documentation, resolution/duplicate
