### ISSUE TITLE
rate limit middleware to support long latency requests

### ISSUE THREAD

**Issue by inforly** [traefik/traefik#10737] opened 2024-05-18 02:17 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

rate limit middle ware can't work well with long latency requests, it should be due to the TTL. Since LLM (large language model) usually take long time (several to tens of seconds), it really needs rate limit to support such long latency requests. Please see the details of the issue: #10700

**Comment by jspdown** [comment] 2024-05-23 13:19
Duplicate of https://github.com/traefik/traefik/issues/10700

**Closed by jspdown** 2024-05-23 13:19 UTC
Labels: status/0-needs-triage
