### ISSUE TITLE
subdomain HostRegexp in k8s crd does not create Lets Encrypt certificates

### ISSUE THREAD

**Issue by mstenz** [traefik/traefik#8750] opened 2022-02-01 12:08 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have used the following in an IngressRoute on K8s while using HTTP-Challenge for LE inside traefik configuration. 
This works for "Host" configurations like a charm. But now I have used the subdomain feature like here:

> match: HostRegexp(`{subdomain:[a-z0-9]+}.example.com`)

### What did you see instead?

This results in the Traefik default certificate provided and does not ask LE to get the cert for the specific domain.

### What version of Traefik are you using?

2.6.0

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

no output (nothing in the log for Lets encrypt for this domain)

**Comment by ddtmachado** [comment] 2022-02-01 13:54
Hi @mstenz , `HostRegexp` rules are not considered by the certificate resolver, in this case you must specify the domains directly. 

See [this section](https://doc.traefik.io/traefik/https/acme/#domain-definition) on the docs for examples.

**Comment by mstenz** [comment] 2022-02-01 13:59
@ddtmachado Thank you for your note. It is not possible to specify domains directly because they are dynamic. 
I have also tested "Host()" with wildcard, but then it is required to use also a wildcard dns record. 
Do you think it is either an option to add HostRegexp to be considered by certificate resolver? (I think this is the correct resolution) or/and have a new feature that allowed registering unique domain with lets encrypt even the Host rule specify a wildcard? 
Theoretically both things can be different.

**Comment by ddtmachado** [comment] 2022-02-01 20:06
Indeed wildcard support is only available to the DNS challenge, this is a LE limitation as its the only way it can validate the challenge. As for registering a unique domain, even if the router rule sets a wildcard, this is already possible as seen on the linked examples doc.

> Do you think it is either an option to add HostRegexp to be considered by the certificate resolver? (I think this is the correct resolution) or/and have a new feature that allows registering unique domains with lets encrypt even the Host rule specifies a wildcard?

I don't think that considering the HostRegexp on the cert resolver is an option here because there would be no way to determine the domain at that point.

In a use case were you know the domains you need to serve but must match your routers based on regex I think the best alternative would be to generate the certificates beforehand, you could do it with a CLI tool like [lego](https://go-acme.github.io/lego/usage/cli/) in an automated way and then load the certificates into Traefik. From that point your router would only need to enable tls without specifying anything else:

```yaml
[...]
  tls: {}
```

I hope this helps in some way

**Comment by mstenz** [comment] 2022-02-01 20:22
`I don't think that considering the HostRegexp on the cert resolver is an option here because there would be no way to determine the domain at that point.`

That's interesting. Isn't the domain known because of the Host HTTP Header? 
I think without using HostRegexp by certificate resolver this option is mostly useless (and it is in my case). I do not know the subdomains, this can be potentially thousand different names and I do not want a wildcard DSN, but a separate unique certificate for all domains. Reason here is mainly that I have configured HTTP challenge centrally for all deployments + my DNS provider does not support LE. 
If I would know the names I could have used Host() only.

**Comment by ddtmachado** [comment] 2022-02-01 20:42
> That's interesting. Isn't the domain known because of the Host HTTP Header?
Yes you might get the Host from the request but that's at another stage.

To put it better, we could simplify the cert generation and cert matching (serving) as two phases:

1. You declare your host matching rule and apply the config to Traefik, at this point it will check against its local certificate store and if there is no match to the specified domain + SANS it will request a new cert to LE and present the challenge.
2. A request arrives at Traefik, via an entrypoint, then it matches it against existing routers once matched if the router has TLS enabled it tries to serve a certificate based on the request host, if it cannot find a suitable one it will serve the default certificate.

When applying a `HostRegex` rule we are at step 1, and the proxy would have no clue what domain you want to get a certificate for.

Once you get a request in and it is matched against the regex router, then sure you known the Host it requested but the options at this point would be:

-  to halt the request altogether until you ask a certificate for LE then validate it add it to store then serve the certificate, which would in the best case scenario add a load of latency for every first request of unique domains or in the worst scenario timing out.
-  falling back to serving the default certificate. 
 
Neither option seems really optimal, plus it feels very risky to allow creating certificate requests live, based on the requested Host.

**Comment by mstenz** [comment] 2022-02-01 21:36
`to halt the request altogether until you ask a certificate for LE then validate it add it to store then serve the certificate, which would in the best case scenario add a load of latency for every first request of unique domains or in the worst scenario timing out.`

This is exactly what happens currently based on my experience in the past have used both Traefik v1 + v2 (i am an early adopter). 
In my environments, the certs have only been requested when traefik boots up if I would have been adding them manually to the configuration. 
But when it's dynamically (for example via docker or k8s) the first time a user hits the domain and it matches the certificate is requested. This takes some time (1-2 seconds) and the browser is waiting this time, but then either serves the received certificate (or in case of error provide the default certificate). 
That's at least my experience from my recent uses on ~100 installations. Has this behavior changed?
Because Traefik is mostly used in Dynamic Environments (because this is what it is made for) and the subdomain HostRegexp feature is also mainly for this type of even more dynamic environments my view is that supporting this is crucial for that type of workloads. 
Not sure why this should be risky.

**Comment by ddtmachado** [comment] 2022-02-02 19:01
Hi again @mstenz 

> But when it's dynamically (for example via docker or k8s) the first time a user hits the domain and it matches, the certificate is requested. This takes some time (1-2 seconds) and the browser is waiting this time, but then either serves the received certificate (or in case of error provide the default certificate).

That's interesting but probably a coincidence factor, such as when adding the ingress route definition than immediately hitting the endpoint to check for the certificate. You'll certainly experience what you described but not because it only requested the certificate on the first hit but rather because it was still working on it since the config was applied when the first hit got in.

In any case, at this point I'm still not convinced by a strong use case to justify that, and considering that what we are discussing now is no longer related to the original topic I'm going to close this. 

As always feel free to open a new issue with the proposal template if you would like to push for a more dynamic cert generation mechanism, just be sure to state a clear requirement and use case as that will help out the team and increase the chance it gets more traction.

Thank you again for the time and readiness in responding!

**Closed by ddtmachado** 2022-02-02 19:01 UTC
Labels: status/0-needs-triage

**Comment by mstenz** [comment] 2022-02-15 08:34
Hi, 
in understand about the coincidence, this can theoretically. 
You have marked my issue as "question", but this is no question. This is in fact a feature request to enable more dynamic Host configurations. 
One specific (our) use case is gitlab. Specially gitlab pages. users are able to define their own subdomain to a root domain. This subdomain name is dynamic and can be anything (mostly a username or groupname). It is not possible to specify the names before because they are not known. 
For example username.example.com or groupname.example.com

Now it get more complicated. Also users would be able to register "custom domains", which means ANY domain that exist need to be routed to the k8s service. 
For example mydomain.com or mygitlabpages.io
This would mean a ".*" regexp need to be created and allow then also creation of the certificates for all domains that for a first ar requested (this is in fact a CATCH ALL mechanism of all Hosts that are not used in any other traefic configuration. 
Can you please reopen this issue? Thx.

**Comment by mstenz** [comment] 2022-02-15 08:51
@ddtmachado 
Here an example diagram to make it more clear:
![grafik](https://user-images.githubusercontent.com/7984329/154026223-c777b4a9-86c1-4a8d-9b54-6a6d94d778ab.png)

**Comment by ddtmachado** [comment] 2022-02-15 17:26
Hi @mstenz, 

Just to clarify this was flagged as question because the original report is not considered a bug since this is expected behavior, or lack of behavior since we don't really support what was reported as an issue, and further down on our discussion it looked more of a QA on how it works.

I still feel the use case is not there and doesn't seems suitable for the way Traefik works currently. There is this [nice post](https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/) you can view for how Traefik 2 was designed to handle TLS in multiple scenarios.

Back to the use case, TLS is not dynamic because its all about trusting something you already know, so if your end customer can register a custom domain, there will be this **register** step somewhere and that is probably were you want to also map / register its routing info in the proxy, otherwise if you just use a match all rule on the proxy where is your actual routing decision made? Is the proxy used just to get certificates from LE?

In any case, as I mentioned before, you're free to open a new issue following the [new feature template](https://github.com/traefik/traefik/issues/new?assignees=&labels=&template=feature-request.yml) with as much detail as possible and if its something others would also like to have it will get traction.
