### ISSUE TITLE
Traefik crashes with SIGSEGV when PUTting empty file to TLS-secured minio backend service

### ISSUE THREAD

**Issue by cgoeller** [traefik/traefik#7642] opened 2020-12-09 12:49 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Traefik is configured as load balancer in front of several Minio (S3 compatible storage) instances.
Our java application accesses Minio using the Amazon S3 Java Client (group: 'com.amazonaws', name: 'aws-java-sdk-s3', version: '1.11.913' )

This setup works fine as long as TLS is not activated in Minio itself.

When TLS is activated in Minio and an empty file is uploaded to Minio using the application the request is served by Traefik, but after that it will crash with SIGSEGV.

It is reproducable. See attached docker-compose setup. 

### What did you expect to see?

Traefik is serving the request and not crashing afterwards.

### What did you see instead?

Traefik is serving the request and crashing afterwards.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5c9862]

goroutine 186 [running]:
bufio.(*Writer).Available(...)
	/usr/local/go/src/bufio/bufio.go:624
bufio.(*Writer).WriteString(0x0, 0x34d8845, 0x19, 0xc0007b85a0, 0x8, 0x7ffff)
	/usr/local/go/src/bufio/bufio.go:705 +0x82
net/http.(*expectContinueReader).Read(0xc0007b9800, 0xc000680000, 0x7ffff, 0x80000, 0xc0008aacd8, 0x410670, 0x8)
	/usr/local/go/src/net/http/server.go:904 +0x1ae
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*captureRequestReader).Read(0xc0007b9860, 0xc000680000, 0x7ffff, 0x80000, 0x438dfb, 0x203000, 0x7f23245627d0)
	/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/capture_request_reader.go:13 +0x51
net/http.(*readTrackingBody).Read(0xc0007b9d80, 0xc000680000, 0x7ffff, 0x80000, 0xc000022120, 0x60, 0x58)
	/usr/local/go/src/net/http/transport.go:621 +0x55
golang.org/x/net/http2.(*clientStream).writeRequestBody(0xc0002874a0, 0x3984020, 0xc0007b9d80, 0x7f22fd720a28, 0xc0007b9d80, 0x0, 0x0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:1308 +0x682
golang.org/x/net/http2.(*Transport).getBodyWriterState.func1()
	/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2585 +0xd0
sync.(*Once).doSlow(0xc0002fede0, 0xc0007bbef0)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
golang.org/x/net/http2.(*Transport).getBodyWriterState.func2()
	/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2603 +0x47
created by time.goFunc
	/usr/local/go/src/time/sleep.go:167 +0x45
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.4
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-24T16:16:43Z
OS/Arch:      linux/amd64
```

Same issue on 2.2.11 and 2.1.6

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Ubuntu 20.04
Linux 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Docker-CE 19.03.13

Same issue on RHEL7
Same issue on Docker 19.03.2

```yaml
entryPoints:
  minio:
    address: :9100
providers:
  file:
    filename: /etc/traefik/dynamic_conf.yml
api:
  insecure: true
log:
  level: DEBUG
accessLog: {}
serversTransport:
  insecureSkipVerify: true
```

```yaml
http:
  routers:
    router-minio:
      rule: "HostRegexp(`{any:.*}`)"
      entryPoints:
        - minio
      service: minio

  services:
    minio:
      loadBalancer:
        servers:
          - url: "https://minio1:9000"
          - url: "https://minio2:9000"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-12-09T12:21:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/test/emptyFile.txt\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Amz-Sdk-Invocation-Id\":[\"b29b6301-00cb-0f8a-4b7f-7942c6960995\"],\"Amz-Sdk-Request\":[\"attempt=1;max=4\"],\"Amz-Sdk-Retry\":[\"0/0/500\"],\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=admin/20201209/us-west-2/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=44934cf1d08a3611def481d434fe1c7df0903dbd2e17e91f3f428b289f2e05c2\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"86\"],\"Content-Type\":[\"application/octet-stream\"],\"Expect\":[\"100-continue\"],\"User-Agent\":[\"aws-sdk-java/1.11.913 Linux/5.4.0-54-generic OpenJDK_64-Bit_Server_VM/11.0.9.1+1-Ubuntu-0ubuntu1.20.04 java/11.0.9.1 vendor/Ubuntu\"],\"X-Amz-Content-Sha256\":[\"STREAMING-AWS4-HMAC-SHA256-PAYLOAD\"],\"X-Amz-Date\":[\"20201209T122128Z\"],\"X-Amz-Decoded-Content-Length\":[\"0\"],\"X-Forwarded-Host\":[\"localhost:9100\"],\"X-Forwarded-Port\":[\"9100\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"1820cc6bd079\"],\"X-Real-Ip\":[\"172.23.0.1\"]},\"ContentLength\":86,\"TransferEncoding\":null,\"Host\":\"localhost:9100\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.23.0.1:60690\",\"RequestURI\":\"/test/emptyFile.txt\",\"TLS\":null}"
time="2020-12-09T12:21:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/test/emptyFile.txt\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Amz-Sdk-Invocation-Id\":[\"b29b6301-00cb-0f8a-4b7f-7942c6960995\"],\"Amz-Sdk-Request\":[\"attempt=1;max=4\"],\"Amz-Sdk-Retry\":[\"0/0/500\"],\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=admin/20201209/us-west-2/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=44934cf1d08a3611def481d434fe1c7df0903dbd2e17e91f3f428b289f2e05c2\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"86\"],\"Content-Type\":[\"application/octet-stream\"],\"Expect\":[\"100-continue\"],\"User-Agent\":[\"aws-sdk-java/1.11.913 Linux/5.4.0-54-generic OpenJDK_64-Bit_Server_VM/11.0.9.1+1-Ubuntu-0ubuntu1.20.04 java/11.0.9.1 vendor/Ubuntu\"],\"X-Amz-Content-Sha256\":[\"STREAMING-AWS4-HMAC-SHA256-PAYLOAD\"],\"X-Amz-Date\":[\"20201209T122128Z\"],\"X-Amz-Decoded-Content-Length\":[\"0\"],\"X-Forwarded-Host\":[\"localhost:9100\"],\"X-Forwarded-Port\":[\"9100\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"1820cc6bd079\"],\"X-Real-Ip\":[\"172.23.0.1\"]},\"ContentLength\":86,\"TransferEncoding\":null,\"Host\":\"localhost:9100\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.23.0.1:60690\",\"RequestURI\":\"/test/emptyFile.txt\",\"TLS\":null}" ForwardURL="https://minio2:9000"
time="2020-12-09T12:21:28Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/test/emptyFile.txt\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Amz-Sdk-Invocation-Id\":[\"b29b6301-00cb-0f8a-4b7f-7942c6960995\"],\"Amz-Sdk-Request\":[\"attempt=1;max=4\"],\"Amz-Sdk-Retry\":[\"0/0/500\"],\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=admin/20201209/us-west-2/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=44934cf1d08a3611def481d434fe1c7df0903dbd2e17e91f3f428b289f2e05c2\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"86\"],\"Content-Type\":[\"application/octet-stream\"],\"Expect\":[\"100-continue\"],\"User-Agent\":[\"aws-sdk-java/1.11.913 Linux/5.4.0-54-generic OpenJDK_64-Bit_Server_VM/11.0.9.1+1-Ubuntu-0ubuntu1.20.04 java/11.0.9.1 vendor/Ubuntu\"],\"X-Amz-Content-Sha256\":[\"STREAMING-AWS4-HMAC-SHA256-PAYLOAD\"],\"X-Amz-Date\":[\"20201209T122128Z\"],\"X-Amz-Decoded-Content-Length\":[\"0\"],\"X-Forwarded-Host\":[\"localhost:9100\"],\"X-Forwarded-Port\":[\"9100\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"1820cc6bd079\"],\"X-Real-Ip\":[\"172.23.0.1\"]},\"ContentLength\":86,\"TransferEncoding\":null,\"Host\":\"localhost:9100\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.23.0.1:60690\",\"RequestURI\":\"/test/emptyFile.txt\",\"TLS\":null}"
172.23.0.1 - - [09/Dec/2020:12:21:28 +0000] "PUT /test/emptyFile.txt HTTP/1.1" 200 0 "-" "-" 2 "router-minio@file" "https://minio2:9000" 26ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5c9862]

goroutine 72 [running]:
bufio.(*Writer).Available(...)
	/usr/local/go/src/bufio/bufio.go:624
bufio.(*Writer).WriteString(0x0, 0x34d8845, 0x19, 0x80000, 0x7f39c84bd7d0, 0xc000700000)
	/usr/local/go/src/bufio/bufio.go:705 +0x82
net/http.(*expectContinueReader).Read(0xc0005780e0, 0xc000700000, 0x7ffff, 0x80000, 0xc000700000, 0xc000429c98, 0x1212f0a)
	/usr/local/go/src/net/http/server.go:904 +0x1ae
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*captureRequestReader).Read(0xc0005781c0, 0xc000700000, 0x7ffff, 0x80000, 0x438dfb, 0x6909b9, 0x6948de)
	/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/capture_request_reader.go:13 +0x51
net/http.(*readTrackingBody).Read(0xc000578700, 0xc000700000, 0x7ffff, 0x80000, 0x1000, 0x397f0a0, 0xc000098180)
	/usr/local/go/src/net/http/transport.go:621 +0x55
golang.org/x/net/http2.(*clientStream).writeRequestBody(0xc0001b51e0, 0x3984020, 0xc000578700, 0x7f39a15023
[traefik-error.zip](https://github.com/traefik/traefik/files/5665908/traefik-error.zip)
80, 0xc000578700, 0x0, 0x0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:1308 +0x682
golang.org/x/net/http2.(*Transport).getBodyWriterState.func1()
	/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2585 +0xd0
sync.(*Once).doSlow(0xc0001fcaa0, 0xc0008970b0)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
golang.org/x/net/http2.(*Transport).getBodyWriterState.func2()
	/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2603 +0x47
created by time.goFunc
	/usr/local/go/src/time/sleep.go:167 +0x45
```

**Comment by cgoeller** [comment] 2020-12-09 12:50
[traefik-error.zip](https://github.com/traefik/traefik/files/5665918/traefik-error.zip)

**Comment by jspdown** [comment] 2020-12-09 14:20
Hello @cgoeller :wave Thanks for reporting the issue and big thanks for providing a reproducible test case.
I'm able to reproduce the issue and we are currently investigating it.

**Comment by jspdown** [comment] 2020-12-10 16:46
I ran the race detector while uploading an empty file using your test client:

<details><summary>Race Detector output</summary>
<p>

```
WARNING: DATA RACE
Read at 0x00c0001d60f8 by goroutine 83:
  net/http.(*expectContinueReader).Read()
      /usr/local/go/src/net/http/server.go:904 +0x264
  github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*captureRequestReader).Read()
      /home/jspdown/Containous/traefik/pkg/middlewares/accesslog/capture_request_reader.go:13 +0x78
  net/http.(*readTrackingBody).Read()
      /usr/local/go/src/net/http/transport.go:621 +0x8a
  golang.org/x/net/http2.(*clientStream).writeRequestBody()
      /home/jspdown/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:1308 +0x761
  golang.org/x/net/http2.(*Transport).getBodyWriterState.func1()
      /home/jspdown/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2585 +0x13d
  sync.(*Once).doSlow()
      /usr/local/go/src/sync/once.go:66 +0x109
  sync.(*Once).Do()
      /usr/local/go/src/sync/once.go:57 +0x68
  golang.org/x/net/http2.(*Transport).getBodyWriterState.func2()
      /home/jspdown/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2603 +0x85

Previous write at 0x00c0001d60f8 by goroutine 71:
  net/http.(*conn).finalFlush()
      /usr/local/go/src/net/http/server.go:1690 +0xd2
  net/http.(*conn).close()
      /usr/local/go/src/net/http/server.go:1696 +0x38
  net/http.(*conn).serve.func1()
      /usr/local/go/src/net/http/server.go:1805 +0xba
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1935 +0xb54

Goroutine 83 (running) created at:
  time.goFunc()
      /usr/local/go/src/time/sleep.go:167 +0x51

Goroutine 71 (finished) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:2969 +0x5d3
  github.com/traefik/traefik/v2/pkg/server.createHTTPServer.func1()
      /home/jspdown/Containous/traefik/pkg/server/server_entrypoint_tcp.go:506 +0x52
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6dd0db]

goroutine 100 [running]:
bufio.(*Writer).Available(...)
	/usr/local/go/src/bufio/bufio.go:624
bufio.(*Writer).WriteString(0x0, 0x4d9a147, 0x19, 0x10100000047836a, 0x0, 0x80000)
	/usr/local/go/src/bufio/bufio.go:705 +0x9b
net/http.(*expectContinueReader).Read(0xc000993c40, 0xc000da6000, 0x7ffff, 0x80000, 0x4561820, 0x1ffffff01, 0xc000da6000)
	/usr/local/go/src/net/http/server.go:904 +0x28c
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*captureRequestReader).Read(0xc000993ca0, 0xc000da6000, 0x7ffff, 0x80000, 0x0, 0x0, 0xc000da6000)
	/home/jspdown/Containous/traefik/pkg/middlewares/accesslog/capture_request_reader.go:13 +0x79
net/http.(*readTrackingBody).Read(0xc000d7e1a0, 0xc000da6000, 0x7ffff, 0x80000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:621 +0x8b
golang.org/x/net/http2.(*clientStream).writeRequestBody(0xc0003a29a0, 0x551a8c0, 0xc000d7e1a0, 0x7f9f9e4cc198, 0xc000d7e1a0, 0x0, 0x0)
	/home/jspdown/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:1308 +0x762
golang.org/x/net/http2.(*Transport).getBodyWriterState.func1()
	/home/jspdown/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2585 +0x13e
sync.(*Once).doSlow(0xc000536da0, 0xc000249ad0)
	/usr/local/go/src/sync/once.go:66 +0x10a
sync.(*Once).Do(0xc000536da0, 0xc000249ad0)
	/usr/local/go/src/sync/once.go:57 +0x69
golang.org/x/net/http2.(*Transport).getBodyWriterState.func2()
	/home/jspdown/go/pkg/mod/golang.org/x/net@v0.0.0-20200822124328-c89045814202/http2/transport.go:2603 +0x86
created by time.goFunc
	/usr/local/go/src/time/sleep.go:167 +0x52
exit status 2
```
</p>
</details>


This indicates that we are calling `WriteString` on an already closed connection. It appears that the`io.ReadCloser` `expectContinueReader` (from Golang standard library) does not protect correctly against reading the body from an already closed connection:

https://github.com/golang/go/blob/9b955d2d3fcff6a5bc8bce7bafdc4c634a28e95b/src/net/http/server.go#L895-L920

A commit which addresses exactly this issue as landed recently on their master branch: https://github.com/golang/go/commit/dfee3332e66bd3f3afd76615767d2cd9b1905b26. Once released we will make sure to update Traefik.

**Comment by atomlab** [comment] 2020-12-13 11:41
May be I have similar issue with download files(more then 40Mb) when use traefik+tls. How you think could it connected with this bug? 

Client -> Internet -> Traefik(TLS) -> Caddy file server(without TLS)

Traefik TLS config. Tested with Traefik 2.2.1 and 2.3.5
```
tls:
  certificates:
    - certFile: /etc/traefik/ssl/selfsigned.crt
      keyFile: /etc/traefik/ssl/selfsigned.key
      stores:
        - default
  options:
    default:
      minVersion: VersionTLS12
```

wget and Connection closed 
```
# wget --no-check-certificate --server-response https://URL/file.exe
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Accept-Ranges: bytes
  Content-Length: 55740568
  Content-Type: application/x-msdos-program
  Date: Sun, 13 Dec 2020 11:29:07 GMT
  Etag: "ql71crx6pp4"
  Last-Modified: Fri, 11 Dec 2020 21:07:39 GMT
  Server: Caddy
Length: 55740568 (53M) [application/x-msdos-program]
Saving to: ‘file.exe’

file.exe                                            75%[================================================================================================================================>                                           ]  40,13M  1,47MB/s    in 29s

2020-12-13 14:29:37 (1,37 MB/s) - Connection closed at byte 42077979. Retrying.

```

**But** when TLS on Traefik side disabled (only http) then all works fine, without any disconnect!

**Comment by jspdown** [comment] 2020-12-14 10:28
@atomlab If you get the same stacktrace there is a high chance the problem is similar. You can still try the patch on the v2.3 branch if you want to make sure. 

If you think there's a bug in Traefik and you can't find a similar reported bug please open a new issue. If you need help from the community, please visit the [community forum](https://community.traefik.io/c/traefik/traefik-v2/10)

**Comment by jspdown** [comment] 2021-01-12 10:26
Just for the record, we are expecting this fix to land in go 1.16. It has currently been released in `v1.16beta1`.

**Comment by traefiker** [comment] 2021-03-04 19:08
Closed by #7932.

**Comment by cgoeller** [comment] 2021-03-15 14:16
This error still occurs with version traefik 2.4.7 

```
Version:      2.4.7
Codename:     livarot
Go version:   go1.16
Built:        2021-03-08T17:18:28Z
OS/Arch:      linux/amd64
```

I tested it using the same test setup based on docker compose, this time with Docker for desktop windows 20.10.5

The error message is still the same:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5cbc02]

goroutine 95 [running]:
bufio.(*Writer).Available(...)
        /usr/local/go/src/bufio/bufio.go:624
bufio.(*Writer).WriteString(0x0, 0x3122da3, 0x19, 0x1011a6cb3d91140, 0x7f14b5b4e568, 0x0)
        /usr/local/go/src/bufio/bufio.go:705 +0x82
net/http.(*expectContinueReader).Read(0xc0003221e0, 0xc0008da000, 0x7ffff, 0x80000, 0xc0008da000, 0xc0005c9c50, 0x13641a5)
        /usr/local/go/src/net/http/server.go:906 +0x1ac
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*captureRequestReader).Read(0xc0005ee060, 0xc0008da000, 0x7ffff, 0x80000, 0x43981b, 0xcd789caf12786139, 0x77ac15571539dc9a)
        /go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/capture_request_reader.go:13 +0x51
net/http.(*readTrackingBody).Read(0xc0005ee3d8, 0xc0008da000, 0x7ffff, 0x80000, 0xc96109a73a8d8465, 0x6a4735e1080d1c04, 0x70af7f221f94a428)
        /usr/local/go/src/net/http/transport.go:632 +0x55
golang.org/x/net/http2.(*clientStream).writeRequestBody(0xc0000dc9a0, 0x35b6300, 0xc0005ee3d8, 0x7f14b5b04340, 0xc0005ee3d8, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200904194848-62affa334b73/http2/transport.go:1308 +0x6aa
golang.org/x/net/http2.(*Transport).getBodyWriterState.func1()
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200904194848-62affa334b73/http2/transport.go:2585 +0xd0
sync.(*Once).doSlow(0xc00052cdb0, 0xc00026e720)
        /usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
golang.org/x/net/http2.(*Transport).getBodyWriterState.func2()
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200904194848-62affa334b73/http2/transport.go:2603 +0x47
created by time.goFunc
        /usr/local/go/src/time/sleep.go:180 +0x45
```

**Comment by tomMoulard** [comment] 2021-09-17 09:06
Hello @cgoeller,

I've conducted some tests with the new Traefik version, and it seems that this issue is now fixed.

Can you confirm this in order to close this issue ?

Thanks,
Tom

**Comment by cgoeller** [comment] 2021-09-17 10:30
Hello @tomMoulard,

I can confirm that the testcase now works with Traefik 2.5.2 👍 

Thanks for the good work

**Comment by tomMoulard** [comment] 2021-09-17 12:36
Awesome !

**Closed by tomMoulard** 2021-09-17 12:36 UTC
Labels: kind/bug/confirmed
