### ISSUE TITLE
Support load plugin from the Golang plugin file. (.so)

### ISSUE THREAD

**Issue by longquan0104** [traefik/traefik#9429] opened 2022-10-10 08:16 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

From what I tested and double-checked with other plugins, the plugin written in Yeagi currently does not support to import the library from other modules. Those plugin doesn't support [reflection](https://www.geeksforgeeks.org/reflection-in-golang/) as well. 
So it would be nice if there is support from Traefik that allow us to load the plugin from the Golang plugin file (which has file extension `.so`).
Anyone passes by please leave a sign that this would be a necessary feature for Traefik. 
Thank you for reading. 👯

**Comment by ldez** [comment] 2022-10-10 08:27
Duplicate of #1336

**Closed by ldez** 2022-10-10 08:27 UTC
Labels: resolution/duplicate
