### ISSUE TITLE
Support metrics backend for InfluxDB v2

### ISSUE THREAD

**Issue by DiedB** [traefik/traefik#7606] opened 2020-12-01 13:03 UTC
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
The metrics backend for InfluxDB only supports InfluxDB v1. v2 has been released and is not supported by Traefik.

The go client library for InfluxDB v2:
github.com/influxdata/influxdb-client-go/v2

**Comment by kevinpollet** [comment] 2020-12-07 08:34
Duplicate of #6389

**Closed by kevinpollet** 2020-12-07 08:34 UTC
Labels: area/middleware/metrics, kind/enhancement, priority/P2
