### ISSUE TITLE
Improve the performance of access logs

### ISSUE THREAD

**Issue by immanuelfodor** [traefik/traefik#10433] opened 2024-02-14 14:46 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Traefik v3 has a new logging engine (zerolog by [#9515](https://github.com/traefik/traefik/pull/9515)), which is more performant than the previous replaced one (logrus).

After improving the main logs, it would be beneficial to bring performance improvements to **access logs** as well to gain performance in this area, too. The original PR is worded as "This PR is only about Traefik logs and not access logs, the access logs will be handled in another PR." so the issue is addressing this part.

Note: OpenTelemetry (Otel) [tracing](https://doc.traefik.io/traefik/v3.0/observability/tracing/opentelemetry/) and [metrics](https://doc.traefik.io/traefik/v3.0/observability/metrics/opentelemetry/) are available for v3 as well, and recently, the Otel logs status went from unavailable to "[in development](https://opentelemetry.io/docs/languages/go/)" for Go but there is a separate issue for that in https://github.com/traefik/traefik/issues/10056.

**Comment by ldez** [comment] 2024-02-14 15:01
Kind of duplicate of #9453

**Comment by mmatur** [comment] 2024-02-15 13:54
Duplicated of https://github.com/traefik/traefik/issues/9453 and https://github.com/traefik/traefik/issues/10056

**Closed by mmatur** 2024-02-15 13:54 UTC
Labels: kind/enhancement, priority/P2, area/accesslogs
