### ISSUE TITLE
traefik as TCP loadbalancer for MTA is not working as expected

### ISSUE THREAD

**Issue by marco-giovannini-robotict** [traefik/traefik#7730] opened 2021-01-07 09:46 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

Like #4875

### What did you do?

I have exposed an SMTP server using the TCP ingress

### What did you expect to see?

I expect to see the SMTP Banner when I do the telnet without need to send additional traffic.

telnet mailman.eks-prod.XXXXX.com 25
Trying XX.XX.XX.XX...
Connected to XXXXXXXXXXXXXXXXXXX-XXXXXXXXXXX.XXXXXXXXXX.elb.amazonaws.com.
Escape character is '^]'.
220 lists-uat.XXXXX.com ESMTP

### What did you see instead?

I don't get the SMTP banner without sending some additional traffic after the connection (like just pressing ENTER)

telnet mailman.eks-prod.xxxxxx.com 25
Trying XX.XX.XX.XX...
Connected to XXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXX.XXXXXXXXX.elb.amazonaws.com.
Escape character is '^]'.
-----I PRESS ENTER HERE -----
220 lists-uat.XXXXXXXXX.com ESMTP

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
we run docker traefik 2.3.3.
we tried to update to 2.3.6 in a test environment but no difference.

    Image:         traefik:2.3.3
    Image ID:      docker-pullable://traefik@sha256:47a745f484911477d46947473ea91b10836626a52e3f1235397686cd2616bc26
    Ports:         10025/TCP, 9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --global.checknewversion
      --global.sendanonymoususage
      --entryPoints.smtp.address=:10025/tcp
      --entryPoints.traefik.address=:9000/tcp
      --entryPoints.web.address=:8000/tcp
      --entryPoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --providers.kubernetescrd
      --providers.kubernetescrd.throttleDuration=2s
      --providers.kubernetesingress
      --providers.kubernetesingress.ingressclass=traefik-pub
      --providers.kubernetescrd.ingressclass=traefik-pub

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: v1
items:
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRouteTCP
  metadata:
    annotations:
      kubernetes.io/ingress.class: traefik-pub
      meta.helm.sh/release-name: mailman-backend
      meta.helm.sh/release-namespace: mailman
    creationTimestamp: "2020-12-10T08:50:03Z"
    generation: 3
    labels:
      app.kubernetes.io/managed-by: Helm
    name: mailman-backend-ingress
    namespace: mailman
    resourceVersion: "18741058"
    selfLink: /apis/traefik.containo.us/v1alpha1/namespaces/mailman/ingressroutetcps/mailman-backend-ingress
    uid: 3cfcba7a-1299-4c0b-b334-93102831b5a4
  spec:
    entryPoints:
    - smtp
    routes:
    - match: HostSNI(`*`)
      services:
      - name: mailman-backend
        port: 25
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by SantoDE** [comment] 2021-01-15 15:06
Duplicate of #6786

**Closed by SantoDE** 2021-01-15 15:06 UTC
Labels: status/0-needs-triage
