### ISSUE TITLE
customFrameOptionsValue doesn't override frameDeny

### ISSUE THREAD

**Issue by donihalim** [traefik/traefik#9888] opened 2023-05-09 17:14 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have `frameDeny: true` on secureHeaders middlewares, I want to override that headers using `customFrameOptionsValue: sameorigin` however it doesn't override the X-Frame-Options

### What did you see instead?

I still see 'X-Frame-Options' set to 'deny' on the chrome dev tool

### What version of Traefik are you using?
```
Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64
```
### What is your environment & configuration?
```
http:
  middlewares:
    frameOptionsSameOrigin:
      headers:
        customFrameOptionsValue: "sameorigin"

  routers:
    code:
      service: code
      rule: Host(`code.mydomain.com`)
      entrypoints:
        - websecure
      tls: true
      middlewares:
        - authelia@docker
        - frameOptionsSameOrigin@file

  services:
    code:
      loadbalancer:
        servers:
          - url: "http://10.8.0.10:8080"
```

**Comment by rtribotte** [comment] 2023-05-10 07:44
Hello @donihalim,

Thanks for your interest in Traefik,

I tried to reproduce the problem without success.
I see that there is a ForwardAuth middleware (`authelia@docker`) also attached to the router and executed first, please check that the problem isn't due to the action of this middleware.

It seems that your issue is related to a configuration issue and the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.

**Closed by rtribotte** 2023-05-10 07:44 UTC
Labels: status/0-needs-triage

**Comment by donihalim** [comment] 2023-05-19 16:17
Hi,
I tried to remove the forward auth middlewares, and the problem still persist
