### ISSUE TITLE
Support for tcp-udp health checks besides http

### ISSUE THREAD

**Issue by ricardo-rod** [traefik/traefik#8154] opened 2021-05-25 17:38 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It will be great that the load balancer for TCP or UDP to have health checks.

I have not founded on the documentation for tcp/udp, only for http.

This is because I was trying to test a file load balancer for a UDP, DNS without using containers as it was based on VM services, And found a very slow response when I was doing some test, I stop one of the servers and the answer was very slow from the nslookup.

I try to use another TCP port and got the same result, maybe the slow response it's the timeout that the server has but to improve because when a server is down in the router section does not reflect the actual status on the listed servers that is down, and that's why I am making this feature request.

**Comment by ldez** [comment] 2021-05-25 17:47
Duplicate of #5598

**Closed by ldez** 2021-05-25 17:47 UTC
Labels: resolution/duplicate
