### ISSUE TITLE
Allow Sprig templates in static configuration (v2)

### ISSUE THREAD

**Issue by compiaffe** [traefik/traefik#9713] opened 2023-02-14 12:39 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I am porting an nginx-based docker-compose stack to Traefik. At the core of our stack are an RTSP server and a webRTC server. 
Both of these require a significant number of TCP and UDP ports to be opened (about 2 for every client).

In order for Traefik to be able to route these I require all these ports to be configured as `entryPoints` in the static configuration. The sprig templating available for the dynamic configuration would solve this. However, it is missing from the static configuration.

I'd like to ask for implementing templating in the static configuration.

**Comment by compiaffe** [comment] 2023-02-14 12:39
The discussion at https://github.com/traefik/traefik/issues/1677 seems to have fizzled out in 2018

**Comment by rtribotte** [comment] 2023-02-14 16:04
Hello @compiaffe,

Thanks for your interest in Traefik!

After analyzing your feature request, we think this is a duplicate.
Accordingly, we are closing it, but, please, do not hesitate to interact on #8438.

Duplicate of #8438

**Comment by compiaffe** [comment] 2023-02-15 14:58
Hey @rtribotte,
Thanks for the quick response. The use case is similar. However, the feature request is a different one.
#8438 is asking for port ranges, while I'm asking explicitly for sprig templates to be supported in the static configuration.

Therefore, I kindly ask to reopen this issue.

**Comment by mpl** [comment] 2023-02-16 15:21
Hello @compiaffe ,

Why are port ranges not a satisfactory solution to you?

Can you please give an example of the kind of configuration you're using, and why it is problematic for you?

And can you please explain why you think sprig would solve your problem better than port ranges?

thanks.

**Comment by compiaffe** [comment] 2023-02-17 10:09
Hey, @mpl Port ranges are of course a fine solution. I'd be happy to use them if they were available. 
Not much visible movement on that front though :)

However, for dynamic configs, Traefik suggests using sprig. 
Wouldn't it make sense to align the tools for both types of configs?

**Comment by mpl** [comment] 2023-02-17 15:19
Hello @compiaffe ,

Among other things, using sprig for the static config would not be as simple as it seems, because it would clash with the (Provider) DefaultRule static configuration option, whose value is a Go template in itself.

And given that using templates is not in itself a better solution for your issue (as far as we understand it) than port ranges for your issue, we don't see any reason to explore that avenue for now.

Please let us know if we missed something.

**Closed by mpl** 2023-02-17 15:19 UTC
Labels: kind/proposal, contributor/waiting-for-feedback, area/server

**Comment by compiaffe** [comment] 2023-02-20 08:39
Thanks for the clarification @mpl Looking forward to seeing the port ranges implemented.
