### ISSUE TITLE
Traefik 1.7: Memory usage keeps increasing

### ISSUE THREAD

**Issue by darkl0rd** [traefik/traefik#8467] opened 2021-09-25 18:47 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Running Traefik in multiple regions with about ~500 containers, would expect stable/steady memory usage.

### What did you see instead?

Memory usage shows slow but linear increase over time, ~ 700MB increase in a month.

### What version of Traefik are you using?

1.7.30

### What is your environment & configuration?

docker labels.

**Comment by rtribotte** [comment] 2021-09-27 14:56
duplicate of #7191

**Closed by rtribotte** 2021-09-27 14:56 UTC
Labels: resolution/duplicate
