### ISSUE TITLE
Make documentation responsive

### ISSUE THREAD

**Issue by christianlupus** [traefik/traefik#11221] opened 2024-10-25 06:42 UTC
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The documentation currently is not fully responsive: You can open it on mobile/tablet but there is no obvious option to open the navigation (left side). One can only navigate by forward/backward buttons at the bottom. This is tedious and not very useful as a reference.

**Comment by kevinpollet** [comment] 2024-10-28 13:36
Duplicate of https://github.com/traefik/traefik/issues/9462

**Closed by kevinpollet** 2024-10-28 13:36 UTC
Labels: status/0-needs-triage
