### ISSUE TITLE
Access log by domain or service

### ISSUE THREAD

**Issue by r0und** [traefik/traefik#7627] opened 2020-12-05 15:23 UTC
Hi!

I hosted 2 domains on a k8s cluster. One is for release, the other is for dev. For the tracking purpose, I only need the access logs of the release domain or service. I read over the documents on the traefik website, only found one trigger that turns on or off the access logs. Once it turns on, it pops the logs of all services.
Could we have a setting somewhere to set up the logs individually? For example, in ingressroute setting.
Another similar situation is to disable the logs of internal services (like ping@internal) while the logs of user services are enabled.

Thanks!

**Comment by kevinpollet** [comment] 2020-12-07 11:08
Duplicate of #6369

**Closed by kevinpollet** 2020-12-07 11:08 UTC
Labels: status/0-needs-triage
