### ISSUE TITLE
mtls not working as mentioned in documentation

### ISSUE THREAD

**Issue by fossilscm** [traefik/traefik#9606] opened 2022-12-14 13:59 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

trying configure mTLS with traefic 2.9.6, for particular routes on same host

### What did you see instead?

it either works with all routes on same host or none
with traefic 2.1 it worked but it was not reliable, when request comes from multiple clients it stoped work.

I believe that my setup is in accordance with documentation.

is it possible make it work please ?

### What version of Traefik are you using?

traefik:v2.9.6

### What is your environment & configuration?

```yaml
## MTLS SETTINGS

#https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/
# global mTLS
# this works, but applies mtls to all routes
[tls.options.default.clientAuth]
    caFiles = ["/etc/traefik/certs/testaplikace.cert"]
    clientAuthType = "VerifyClientCertIfGiven"


# for mtls secured routes
#https://smallstep.com/hello-mtls/doc/server/traefik
[tls.options.require-mtls.clientAuth]
    caFiles = ["/etc/traefik/certs/testaplikace.cert"]
    clientAuthType = "VerifyClientCertIfGiven"


# explicit no-mTLS routes
#never worked when added to routes, report error
[tls.options.no-mTLS.clientAuth]
    caFiles = ["/etc/traefik/certs/testaplikace.cert"]
    clientAuthType = "NoClientCert"
    
    
## ROUTERS
  
#router without mtls
[http.routers.r-kz-mobilka-data-test]
    entryPoints = ["web-tls"]
    rule = "Host(`testspital.kzcr.eu`) && PathPrefix(`/tls/nosso/mobilka/data`)"
    service = "wsvc-kz-mobilka-test"
    [http.routers.r-kz-mobilka-data-test.tls]
 
 #routed with mtls
[http.routers.r-kz-mobilka-svc-test]
    entryPoints = ["web-tls"]
    rule = "Host(`testspital.kzcr.eu`) && PathPrefix(`/tls/nosso/mobilka/svc`)"
    service = "wsvc-kz-mobilka-test"
    middlewares = ["mw-mobilky-passtlsclientcert"]
    [http.routers.r-kz-mobilka-svc-test.tls]
        #this is used with require-mtls
        #with global mtls must be disabled !
        options="require-mtls@file"
        
        
## SERVICES
        
#windows backend
[http.services.wsvc-kz-mobilka-test.loadBalancer]
    passhostheader = true
    [[http.services.wsvc-kz-mobilka-test.loadBalancer.servers]]
        url = "http://winserver1.kzcr.eu:8002/"
        
        
## MIDDLEWARES

#upacked mtls cert processing
#https://community.traefik.io/t/authorize-with-x509-client-cert-and-include-cert-info-in-header-of-non-tls-service/784
[http.middlewares.mw-mobilky-passtlsclientcert.passTLSClientCert]
    pem = false
	[http.middlewares.mw-mobilky-passtlsclientcert.passTLSClientCert.info]
	    #notAfter = true
	    #notBefore = true
	    sans = true
    [http.middlewares.mw-mobilky-passtlsclientcert.passTLSClientCert.info.subject]
        country = true
        province = true
        locality = true
        organization = true
        commonName = true
        serialNumber = true
        domainComponent = true
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

with 2.9.6 log is much less informative than 2.1, nothing usefull about mtls in it

**Comment by nmengin** [comment] 2022-12-15 15:11
Hey @fossilscm,

Could you provide your full debug logs, please?

Indeed, we've recently fixed a [CVE](https://community.traefik.io/t/bug-confirmed-improperly-defined-attributes-in-tls-configuration-may-expose-router-with-empty-tls-config/16672) that changes the way to handle routers with a not well-formatted TLSOption.
Maybe it's linked.

**Comment by fossilscm** [comment] 2022-12-16 20:54
with 2.9.6 just this in log:

time="2022-12-16T20:50:53Z" level=debug msg="Serving default certificate for request: \"\""
time="2022-12-16T20:51:15Z" level=warning msg="Tried to extract a certificate on a request without mutual TLS" middlewareName=mw-mobilky-passtlsclientcert@file middlewareType=PassClientTLSCert

**Comment by nmengin** [comment] 2022-12-19 18:07
Hello @fossilscm,

From my understanding, there is an issue with your configuration: the TLSOption `require-mtls` authorizes non mTLS connections, but the middleware `mw-mobilky-passtlsclientcert` needs a client certificate to work correctly.

That's why every time a non mTLS connection reaches your router `r-kz-mobilka-svc-test` Traefik authorizes the connection and logs a warning.

Note that you can force your client to provide a certificate if you set a more restrictive level to the `clientAuthType` such as `RequireAndVerifyClientCert` as described in the [documentation](https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls).

I hope my answer is helpful.

I close this issue, and I mark it as a question because we don't think there is any issue on Traefik for the use case you've described.

If you want more guidance, I encourage you to reach [the community forum](https://community.traefik.io/) and create a dedicated topic.

**Closed by nmengin** 2022-12-19 18:07 UTC
Labels: status/0-needs-triage, contributor/need-more-information
