### ISSUE TITLE
Traefik is not purging old key value pairs or overwriting old config in any KV store for HA

### ISSUE THREAD

**Issue by billykwooten** [traefik/traefik#2093] opened 2017-09-09 01:15 UTC
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

What I have done is enable consul as my KV store for testing HA, and I uploaded the following below config to the KV store, using the `traefik storeconfig` command.

What I did is enabled http -> https forwarding for the endpoints (you can see it's commented out below in the config). When I commented it out and enabled regular http port 80 endpoints again, and reran the 
 `traefik storeconfig`, traefik was still respecting the http -> https forwarding. 

The issue is that I uploaded the consul config to the KV store which created https endpoint KV pairs, when I commented out the https stuff and re-pushed the config to consul, it didn't purge the old keys.

*EDIT:* This has been seen in almost any HA configuration such as etcd as well.

See config below:

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
# debug = true

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
# traefikLogsFile = "log/traefik.log"

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "ERROR"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.http]
  address = ":80"

#[entryPoints]
#  [entryPoints.http]
#  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
#  [entryPoints.https]
#  address = ":443"



# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]

# Web administration port
#
# Required
#
address = ":8080"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
#[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
# domain = "docker.localhost"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedbydefault = true

################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend
#
# Optional
#
[consulCatalog]

# Consul server endpoint
#
# Required
#
endpoint = "127.0.0.1:8500"

# Default domain used.
#
# Optional
#
#domain = "consul.localhost"

# Prefix for Consul catalog tags
#
# Optional
#
prefix = "traefik"

################################################################
# Consul KV configuration backend
################################################################

# Enable Consul KV configuration backend
#[consul]

# Consul server endpoint
#
# Required
#
endpoint = "127.0.0.1:8500"

# Enable watch Consul changes
#
# Optional
#
watch = true

# Prefix used for KV store.
#
# Optional
#
prefix = "traefik"

# Override default configuration template. For advanced users :)
#
# Optional
#
# filename = "consul.tmpl"

# Enable consul TLS connection
#
# Optional
#
# [consul.tls]
# ca = "/etc/ssl/ca.crt"
# cert = "/etc/ssl/consul.crt"
# key = "/etc/ssl/consul.key"
# insecureskipverify = true
```

### What did you expect to see?

I expected traefik to purge keys that were in the KV store (in this case the https endpoint KV pairs), or at least overwrite the entire config, however traefik kept them there and didn't respect my new config.

### What did you see instead?

The https endpoint stuff was still in the KV store, resulting in traefik still doing http -> https, even though the config I just pushed only had 80 as an endpoint.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik v1.3.8 (running the binary)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

CentOS 7
Nomad + Consul + Docker

### My workaround

My workaround was to stop the traefik service (aka binary file), and go delete the entire KV store folder for traefik in consul. Once I deleted it and then ran `traefik storeconfig` again. Everything started working as expected.

### Why do we need this

It'd be nice if we could modify our config files and run the storeconfig command and it completely overwrite the current KV configuration. Instead of me having to go to consul, delete the entire folder and repush my configuration.

This could be accomplished numerous ways, one simple way is to delete the entire KV folder and recreate it when we run storeconfig, and/or go through and purge un-used key values compared to the new configuration deltas.

**Comment by igoratencompass** [comment] 2018-01-22 22:35
@Cryson just a note here, deleting the whole store can not be a solution when you have ssl certificates saved there too.

**Comment by Cryson** [comment] 2018-02-10 01:57
@igoratencompass Agreed. We could do a diff comparison and based on that update only the changed files. That'd stop potential deletion of important files such as ssl/tls certificates.

**Comment by darkl0rd** [comment] 2019-01-05 18:03
Never knew this was the case until I recently spent an hour debugging a configuration which eventually was caused by remnant keys in my KV (Consul).

Any update on this?

**Comment by phroggyy** [comment] 2019-03-06 17:08
Just ran into this is well. Could we bump the priority on this? I feel like `storeconfig` would have to check what keys do and don't exist, remove what's no longer present in the config.

Would it be viable to retrieve a list of keys from the kv store, then filter out the ones that should remain (based on the new config being stored), and delete the rest?

**Comment by phroggyy** [comment] 2019-03-06 22:00
I've opened a PR to staert for this – https://github.com/containous/staert/pull/49

Once we're able to get that (or something similar) in, we can update Traefik to use that instead.

Note that this issue likely is not limited to just Consul, but should be happening for every KV provider (etcd, zookeeper, etc).

**Comment by bradjones1** [comment] 2019-09-13 17:01
I can confirm this applies to etcd as well. Could use a title/summary update accordingly. Thanks!

**Comment by Dids** [comment] 2021-08-20 06:20
Not sure how many are still even using Traefik 1.x, but I'm assuming there hasn't been any progress with this?

**Comment by mmatur** [comment] 2024-07-01 12:58
Hello,

This enhancement is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.

**Closed by mmatur** 2024-07-01 12:58 UTC
Labels: kind/enhancement, area/provider/consul, area/acme, priority/P3, area/cluster, contributor/wanted
