### ISSUE TITLE
Server-sent event in traefik - too many transfer encoding errors

### ISSUE THREAD

**Issue by sandroden** [traefik/traefik#8623] opened 2021-12-10 15:16 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have an issue with Server-Sent events. I cannot state this is a bug report but I really looked everywhere and even [in the community forum](https://community.traefik.io/t/server-side-event-in-traefik-internal-server-error/12625) nor [StackOverflow](https://community.traefik.io/t/server-side-event-in-traefik-internal-server-error/12625) I could not find any help.

I have a simple sse generated from Django that is served correctly by Nginx and is not working under Traefik. I attach a complete setup working under `docker-compose`.

In docker, I use:

```
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.dj.rule=Host(`$SSE_HOST`)"
       - "traefik.http.routers.dj.entrypoints=web"
       - "traefik.http.routers.dj.service=dj"
       - "traefik.http.services.dj.loadbalancer.server.port=8000" 
       #- "traefik.http.routers.dj.middlewares=compress-no-stream"
       #- "traefik.http.middlewares.compress-no-stream.compress=true"
       #- "traefik.http.middlewares.compress-no-stream.compress.excludedcontenttypes=text/event-stream"
```
while in the same docker-compose setup I define nginx with the following conf that is working:

```
server {
  listen 80;
  server_name _ ;
  charset utf-8;
  client_max_body_size 20M;

  location / {
    proxy_pass http://django:8000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }
}
```

### What did you see instead?

When visiting the Server-Sent Event page directly via nginx I see messages sent from the server getting to the page.
When proxying via Traefik (w/ or w/o compression) no event gets to the browser.
If Traefik proxies to a Django run from console, I get a "Temporary failure in name resolution" and I cannot understand what it refers to.

### What version of Traefik are you using?

I'm using Traefik version 2.5.4

### What is your environment & configuration?

```yaml
version: '3.7'
services:
  nginx:
    image: nginx
    networks:
      - django
    ports:
      - "8081:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: "redis:5"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
     - ./redis-data:/var/lib/redis
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      - django

  django:
    image: fiverr-traefik
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - "8080:8000"
    environment:
      ENV: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: "any-key-will-do"
      #ALLOWED_HOSTS: '*'
    volumes:
      - ./logs/uwsgi:/var/log/uwsgi
      - ./logs/django:/var/log/django
      - ./media:/code/media
    networks:
      - web
      - django
      - redis
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.dj.rule=Host(`$DJANGO_HOST`)"
       - "traefik.http.routers.dj.entrypoints=web"
       - "traefik.http.routers.dj.service=dj"
       - "traefik.http.services.dj.loadbalancer.server.port=8000" 
       #- "traefik.http.routers.dj.middlewares=compress-no-stream"
       #- "traefik.http.middlewares.compress-no-stream.compress=true"
       #- "traefik.http.middlewares.compress-no-stream.compress.excludedcontenttypes=text/event-stream"
    #command: uwsgi --ini /etc/uwsgi.ini
    
  traefik:
    image: traefik:v2.5.4
    restart: always
    container_name: traefik
    ports:
      - "9000:80" # <== http
      - "443:443" # <== https
    extra_hosts:
    - "django.sse:192.168.1.100"# your ip; name set in providers.file's static conf
    command:
    #### These are the CLI commands that will configure Traefik and tell it how to work! ####
      - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
      - --api.insecure=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
      - --log.level=INFO # <== Setting the level of the logs from traefik
      - --accessLog.filePath=/logs/access.log
      - --log.filePath=/logs/traefik.log
      - --providers.file.directory=/etc/traefik/traefik.d
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      - --providers.docker=true # <== Enabling docker as the provider for traefik
      - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
      - --providers.docker.network=web # <== Operate on the docker network named web
      - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
    volumes:
      - ./logs/traefik:/logs
      - ./conf/traefik:/etc/traefik # <== Volume for certs (TLS)
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
    networks:
      - web
      - django 
    depends_on:
      - django
    labels:
    #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_HOST}`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access

networks:
  django:
  web:
    external: true
  redis:

```

Attached is a minimal setup to reproduce the problem w/ README
[demo-sse-traefik.zip](https://github.com/traefik/traefik/files/7693468/demo-sse-traefik.zip)

### If applicable, please paste the log output in DEBUG level

The meaningful part of the logs that I believe can give info is this:

```
level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: too many transfer encodings: [\"chunked\" \"chunked\"]"
```

But again I cannot find useful info on what is should depend on. 

Other logs:

```
time="2021-12-10T14:46:04Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/demo/sse/channels/sse-example/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/event-stream\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Referer\":[\"http://demo.sse:9000/sse\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36\"],\"X-Forwarded-Host\":[\"demo.sse:9000\"],\"X-Forwarded-Port\":[\"9000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"3fbd4799b7e7\"],\"X-Real-Ip\":[\"172.21.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"demo.sse:9000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.21.0.1:37094\",\"RequestURI\":\"/demo/sse/channels/sse-example/\",\"TLS\":null}"
time="2021-12-10T14:46:04Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/demo/sse/channels/sse-example/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/event-stream\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Referer\":[\"http://demo.sse:9000/sse\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36\"],\"X-Forwarded-Host\":[\"demo.sse:9000\"],\"X-Forwarded-Port\":[\"9000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"3fbd4799b7e7\"],\"X-Real-Ip\":[\"172.21.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"demo.sse:9000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.21.0.1:37094\",\"RequestURI\":\"/demo/sse/channels/sse-example/\",\"TLS\":null}" ForwardURL="http://172.20.0.2:8000"

```

**Comment by ddtmachado** [comment] 2022-02-18 17:52
Hello @sandroden 

This seems to be a known issue caused by a stricter check on the `Transfer-Encoding` header in [Go v1.15](https://golang.org/doc/go1.15#net/http) which was then brought in Traefik 2.3 in [this commit](https://github.com/traefik/traefik/commit/eecc2f4dd736278f28afa55338aafb0fc2cf71b2).

In previous versions there was no strict checking and the defective response would go through unnoticed, which might still be the case for other tools like curl for example.

Since this is an issue on the backend and not Traefik I'm closing it, but let me know if you disagree.

**Closed by ddtmachado** 2022-02-18 17:52 UTC
Labels: kind/bug/possible
