### ISSUE TITLE
Duplicate routers and services when using both file and docker provider

### ISSUE THREAD

**Issue by schklom** [traefik/traefik#8453] opened 2021-09-15 19:10 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Defined a router and service in dynamic_conf.yml, and picked the network via
```yaml
    labels:
      - "traefik.enable=true"
      - traefik.docker.network=docker_1dupli_web
```

### What did you see instead?

Now, I have the router I configured (works fine) and a useless router automatically created (see attachment) by traefik because of the container label, and similar for the services (one made by me in the file, and one useless created by traefik).
![Capture](https://user-images.githubusercontent.com/23263086/133492424-561a2eaa-fea2-4a0c-81c4-c13a30f9d6fb.JPG)
`.

Since my container is attached to many networks, I need to define which network traefik should use. So I cannot just stop using labels. I feel this is a bug. Since I am trying to move all my labels to the dynamic_conf file, I will end up with a lot of extra routers and services that don't do anything.

### What version of Traefik are you using?

```
Unable to find image 'traefik:latest' locally
latest: Pulling from library/traefik
Digest: sha256:b8802f19de00e344ae5f87d8dde9ff17360a10cf0d5e85949a065de89e69bbe3
Status: Downloaded newer image for traefik:latest
Version:      2.5.2
Codename:     livarot
Go version:   go1.17
Built:        2021-09-02T15:07:43Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration?

dynamic_conf.yml
```yaml
http:
  routers:
    duplicati_rtr:
      entrypoints: websecure
      rule: Host(`duplicati.MYDOMAIN.duckdns.org`)
      service: duplicati_svc

  services:
    duplicati_svc:
      loadBalancer:
        servers:
          - url: http://duplicati:8200
```

traefik.yml
```yaml
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml

entryPoints:
  websecure:
    address: ":60000"
    http:
      tls:
        certResolver: websecure # Not defined here to keep it short
        domains:
          - main: "MYDOMAIN.duckdns.org"
            sans: "*.MYDOMAIN.duckdns.org"
```

docker_compose.yml
```yaml
services:
  duplicati:
    image: "duplicati/duplicati:linux-arm32v7-latest"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFIG}/duplicati:/data
    labels:
      - "traefik.enable=true"
      - traefik.docker.network=docker_1dupli_web
    networks:
      1dupli_web:
      othernetwork:

  traefik:
    image: "traefik:v2.5"
    ports:
      - 60000:60000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFIG}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${DOCKERCONFIG}/traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - ${DOCKERCONFIG}/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DUCKDNS_TOKEN: XXXXXXXXXXXXXXXXXXXX
    networks:
      1dupli_web:

networks:
  othernetwork:
  1dupli_web:
```

### If applicable, please paste the log output in DEBUG level

```
time="2021-09-15T20:37:30+02:00" level=debug msg="Creating middleware" entryPointName=lan middlewareName=pipelining middlewareType=Pipelining routerName=duplicati_rtr@file serviceName=duplicati_svc
time="2021-09-15T20:37:30+02:00" level=debug msg="Creating load-balancer" entryPointName=lan routerName=duplicati_rtr@file serviceName=duplicati_svc
time="2021-09-15T20:37:30+02:00" level=debug msg="Creating server 0 http://duplicati:8200" entryPointName=lan routerName=duplicati_rtr@file serviceName=duplicati_svc serverName=0
time="2021-09-15T20:37:30+02:00" level=debug msg="child http://duplicati:8200 now UP"
time="2021-09-15T20:37:30+02:00" level=debug msg="Propagating new UP status"
time="2021-09-15T20:37:30+02:00" level=debug msg="Added outgoing tracing middleware duplicati_svc" entryPointName=lan routerName=duplicati_rtr@file middlewareName=tracing middlewareType=TracingForwarder
time="2021-09-15T20:37:30+02:00" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=lan
time="2021-09-15T20:37:30+02:00" level=debug msg="Adding route for duplicati.MYDOMAIN.duckdns.org with TLS options default" entryPointName=lan
time="2021-09-15T20:37:30+02:00" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2021-09-15T20:37:30+02:00" level=debug msg="Looking for provided certificate(s) to validate [\"MYDOMAIN.duckdns.org\" \"*.MYDOMAIN.duckdns.org\"]..." providerName=lanresolver.acme
time="2021-09-15T20:37:31+02:00" level=debug msg="Adding certificate for domain(s) MYDOMAIN.duckdns.org,*.MYDOMAIN.duckdns.org"
time="2021-09-15T20:37:31+02:00" level=debug msg="No ACME certificate generation required for domains [\"MYDOMAIN.duckdns.org\" \"*.MYDOMAIN.duckdns.org\"]." providerName=lanresolver.acme
time="2021-09-15T20:37:31+02:00" level=debug msg="Creating middleware" routerName=duplicati_rtr@file serviceName=duplicati_svc entryPointName=lan middlewareName=pipelining middlewareType=Pipelining
time="2021-09-15T20:37:31+02:00" level=debug msg="Creating load-balancer" routerName=duplicati_rtr@file serviceName=duplicati_svc entryPointName=lan
time="2021-09-15T20:37:31+02:00" level=debug msg="Creating server 0 http://duplicati:8200" serviceName=duplicati_svc entryPointName=lan serverName=0 routerName=duplicati_rtr@file
time="2021-09-15T20:37:31+02:00" level=debug msg="child http://duplicati:8200 now UP"
time="2021-09-15T20:37:31+02:00" level=debug msg="Propagating new UP status"
time="2021-09-15T20:37:31+02:00" level=debug msg="Added outgoing tracing middleware duplicati_svc" routerName=duplicati_rtr@file middlewareType=TracingForwarder middlewareName=tracing entryPointName=lan
time="2021-09-15T20:37:31+02:00" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=lan
time="2021-09-15T20:37:31+02:00" level=debug msg="Adding route for duplicati.MYDOMAIN.duckdns.org with TLS options default" entryPointName=lan
time="2021-09-15T20:37:31+02:00" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [lan websecure]" routerName=duplicati-docker
time="2021-09-15T20:37:31+02:00" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2021-09-15T20:37:31+02:00" level=debug msg="Looking for provided certificate(s) to validate [\"MYDOMAIN.duckdns.org\" \"*.MYDOMAIN.duckdns.org\"]..." providerName=lanresolver.acme
time="2021-09-15T20:37:32+02:00" level=debug msg="Adding certificate for domain(s) MYDOMAIN.duckdns.org,*.MYDOMAIN.duckdns.org"
time="2021-09-15T20:37:32+02:00" level=debug msg="No ACME certificate generation required for domains [\"MYDOMAIN.duckdns.org\" \"*.MYDOMAIN.duckdns.org\"]." providerName=lanresolver.acme
time="2021-09-15T20:37:32+02:00" level=debug msg="Creating middleware" serviceName=duplicati-docker routerName=lan-duplicati-docker@docker middlewareName=pipelining middlewareType=Pipelining entryPointName=lan
time="2021-09-15T20:37:32+02:00" level=debug msg="Creating load-balancer" entryPointName=lan serviceName=duplicati-docker routerName=lan-duplicati-docker@docker
time="2021-09-15T20:37:32+02:00" level=debug msg="Creating server 0 http://192.168.28.2:8200" serviceName=duplicati-docker routerName=lan-duplicati-docker@docker entryPointName=lan serverName=0
time="2021-09-15T20:37:32+02:00" level=debug msg="child http://192.168.28.2:8200 now UP"
time="2021-09-15T20:37:32+02:00" level=debug msg="Propagating new UP status"
time="2021-09-15T20:37:32+02:00" level=debug msg="Added outgoing tracing middleware duplicati-docker" entryPointName=lan routerName=lan-duplicati-docker@docker middlewareName=tracing middlewareType=TracingForwarder
```

**Comment by ldez** [comment] 2021-09-15 19:36
Hello,

```
    labels:
      - "traefik.enable=true"
      - traefik.docker.network=docker_1dupli_web
```
This configuration means that the container, with this label, will be on the network `docker_1dupli_web`.
But this configuration doesn't handle the network for all your containers, it's only for one container.

https://doc.traefik.io/traefik/v2.5/routing/providers/docker/#traefikdockernetwork

And the use of `traefik.enable=true` creates the related service and router, because it's the goal of this label.

If you want to set the default network for all the containers you have to use this option:
- https://doc.traefik.io/traefik/v2.5/providers/docker/#network

But your real problem is the fact to use a file to create the routing for your containers: the right way to create routing for containers is to use labels not a file.

We will close this issue because it's a question and not a bug, we can continue discussing on the [community forum](https://community.traefik.io/)

**Closed by ldez** 2021-09-15 19:36 UTC
Labels: status/0-needs-triage

**Comment by schklom** [comment] 2021-09-15 19:40
@ldez I never said I wanted this network to be the default network for all containers.

This example was kept simple, but I have nearly 30 networks and 20 containers. I want to define specific networks for each container. Unfortunately, it seems I MUST use labels to define the network traefik will use. Creating duplicate routers and services is actually a bug.

**Comment by ldez** [comment] 2021-09-15 19:44
As I said your problem is the fact to use a file to create the routing for your containers: the right way to create routing for containers is to use labels not a file.

Traefik doesn't create "duplicate" routers and services, it just creates routers and services because you are using the label `traefik.enable=true` on the containers.
The goal of this label is to automatically create a router and a service by default.

We can continue discussing on the [community forum](https://community.traefik.io/)

**Comment by schklom** [comment] 2021-09-15 20:24
Thanks for the replies! I opened a topic on the forum.

Continued https://community.traefik.io/t/duplicate-routers-and-services-when-using-both-file-and-docker-provider/11770
