### ISSUE TITLE
Multiple wildcard certificates, correct subdomain wildcard no longer selected

### ISSUE THREAD

**Issue by dejaeghered** [traefik/traefik#4081] opened 2018-10-19 08:44 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I upgraded from 1.5.3 to 1.7.3.  Traefik seems to select and use the wrong certificates now.  I have mutiple wildcard certificates in the likes of:
- *.domain.com
- *.int.domain.com
- *.app.domain.com (edited)
Now all sub domain hostnames such as test.int.domain.com are using the *.domain.com certificate

### What did you expect to see?
Similar behavior as 1.5 up to 1.6.6, the wildcard being served matching the proper wildcard subdomain certificate

### What did you see instead?
 all sub domain hostnames such as test.int.domain.com are using the *.domain.com certificate

### Output of `traefik version`: (_What version of Traefik are you using?_)
Traefik 1.7.3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```
arguments
        - -d
        - --kubernetes
        - --consul
        - --consul.endpoint=consul-consul.infra.svc.cluster.local:8500
```
Certificates are configured in Consul KV and confirmed working in earlier versions.  

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
```
time="2018-10-19T09:00:58Z" level=info msg="No tls.defaultCertificate given for https: using the first item in tls.certificates as a fallback."
time="2018-10-19T09:00:58Z" level=info msg="Traefik version v1.7.3 built on 2018-10-15_10:13:00AM"
time="2018-10-19T09:00:58Z" level=debug msg="Global configuration loaded  ... [[ removed because of sensitive data... ]]
time="2018-10-19T09:00:58Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-10-19T09:00:58Z" level=debug msg="Configured Prometheus metrics"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.domain.com,domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.int.domain.com,int.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.app.domain.com,app.domain.com"
time="2018-10-19T09:00:58Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000370b80} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-10-19T09:00:58Z" level=info msg="Preparing server https &{Address::443 TLS:0xc0002a4ab0 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000370bc0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-10-19T09:00:58Z" level=info msg="Starting server on :80"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.domain.com,domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.int.domain.com,int.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.app.domain.com,app.domain.com"
time="2018-10-19T09:00:58Z" level=info msg="Preparing server traefik &{Address::8181 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000370b60} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-10-19T09:00:58Z" level=info msg="Starting server on :443"
time="2018-10-19T09:00:58Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2018-10-19T09:00:58Z" level=info msg="Starting server on :8181"
time="2018-10-19T09:00:58Z" level=debug msg="Node cb3a601c-9579-4b40-aa0c-6c65bde806de running for election"
time="2018-10-19T09:00:58Z" level=info msg="Starting provider *consul.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"consul-consul.infra.svc.cluster.local:8500\",\"Prefix\":\"traefik\",\"TLS\":null,\"Username\":\"\",\"Password\":\"\"}"
time="2018-10-19T09:00:58Z" level=info msg="Starting provider *kubernetes.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"\",\"Token\":\"\",\"CertAuthFilePath\":\"\",\"DisablePassHostHeaders\":false,\"EnablePassTLSCert\":false,\"Namespaces\":null,\"LabelSelector\":\"\",\"IngressClass\":\"\",\"IngressEndpoint\":null}"
time="2018-10-19T09:00:58Z" level=debug msg="Using Ingress label selector: \"\""
time="2018-10-19T09:00:58Z" level=info msg="ingress label selector is: \"\""
time="2018-10-19T09:00:58Z" level=info msg="Creating in-cluster Provider client"
time="2018-10-19T09:00:58Z" level=info msg="Node cb3a601c-9579-4b40-aa0c-6c65bde806de elected worker ♝"
time="2018-10-19T09:00:58Z" level=debug msg="Datastore reload"
time="2018-10-19T09:00:58Z" level=debug msg="Building ACME client..."
time="2018-10-19T09:00:58Z" level=error msg="Cannot unmarshall private key []"
time="2018-10-19T09:00:58Z" level=error msg="Error building ACME client &{Email: Registration:<nil> PrivateKey:[] KeyType: DomainsCertificate:{Certs:[] lock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} ChallengeCerts:map[] HTTPChallenge:map[]}: private key was nil"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot get key traefik/alias Key not found in store, setting default traefik"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot list keys under \"traefik/backends/\": Key not found in store"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot get key traefik/alias Key not found in store, setting default traefik"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot list keys under \"traefik/frontends/\": Key not found in store"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot list keys under \"traefik/tls/\": Key not found in store"
time="2018-10-19T09:00:58Z" level=debug msg="Configuration received from provider consul: {}"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.domain.com,domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot list keys under \"traefik/backends/\": Key not found in store"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.int.domain.com,int.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.app.domain.com,app.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot list keys under \"traefik/frontends/\": Key not found in store"
time="2018-10-19T09:00:58Z" level=info msg="Server configuration reloaded on :8181"
time="2018-10-19T09:00:58Z" level=info msg="Server configuration reloaded on :80"
time="2018-10-19T09:00:58Z" level=info msg="Server configuration reloaded on :443"
time="2018-10-19T09:00:58Z" level=debug msg="Cannot list keys under \"traefik/tls/\": Key not found in store"
time="2018-10-19T09:00:58Z" level=debug msg="Configuration received from provider consul: {}"
time="2018-10-19T09:00:58Z" level=info msg="Skipping same configuration for provider consul"
time="2018-10-19T09:00:58Z" level=debug msg="Received Kubernetes event kind *v1beta1.Ingress"
time="2018-10-19T09:00:58Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"alertmanager.app.domain.com/\":{\"servers\":{\"alertmanager-main-0\":{\"url\":\"http://10.99.85.233:9093\",\"weight\":1},\"alertmanager-main-1\":{\"url\":\"http://10.99.72.137:9093\",\"weight\":1},\"alertmanager-main-2\":{\"url\":\"http://10.99.105.51:9093\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"blackbox.app.domain.com/\":{\"servers\":{\"blackbox-exporter-6cd8cf6875-22gz6\":{\"url\":\"https://10.99.105.37:9115\",\"weight\":1}},   [[ Data removed ]]

time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.domain.com,domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.int.domain.com,int.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Add certificate for domains *.app.domain.com,app.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Wiring frontend alertmanager.app.domain.com/ to entryPoint http"
time="2018-10-19T09:00:58Z" level=debug msg="Creating backend alertmanager.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Adding TLSClientHeaders middleware for frontend alertmanager.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Creating load-balancer wrr"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server alertmanager-main-2 at http://10.99.105.51:9093 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server alertmanager-main-0 at http://10.99.85.233:9093 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server alertmanager-main-1 at http://10.99.72.137:9093 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route alertmanager.app.domain.com Host:alertmanager.app.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-10-19T09:00:58Z" level=debug msg="Wiring frontend alertmanager.app.domain.com/ to entryPoint https"
time="2018-10-19T09:00:58Z" level=debug msg="Creating backend alertmanager.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Adding TLSClientHeaders middleware for frontend alertmanager.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Creating load-balancer wrr"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server alertmanager-main-1 at http://10.99.72.137:9093 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server alertmanager-main-2 at http://10.99.105.51:9093 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server alertmanager-main-0 at http://10.99.85.233:9093 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route alertmanager.app.domain.com Host:alertmanager.app.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-10-19T09:00:58Z" level=debug msg="Wiring frontend blackbox.app.domain.com/ to entryPoint http"
time="2018-10-19T09:00:58Z" level=debug msg="Creating backend blackbox.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Adding TLSClientHeaders middleware for frontend blackbox.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Creating load-balancer wrr"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server blackbox-exporter-6cd8cf6875-22gz6 at https://10.99.105.37:9115 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route blackbox.app.domain.com Host:blackbox.app.domain.com"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-10-19T09:00:58Z" level=debug msg="Wiring frontend blackbox.app.domain.com/ to entryPoint https"
time="2018-10-19T09:00:58Z" level=debug msg="Creating backend blackbox.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Adding TLSClientHeaders middleware for frontend blackbox.app.domain.com/"
time="2018-10-19T09:00:58Z" level=debug msg="Creating load-balancer wrr"
time="2018-10-19T09:00:58Z" level=debug msg="Creating server blackbox-exporter-6cd8cf6875-22gz6 at https://10.99.105.37:9115 with weight 1"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route / PathPrefix:/"
time="2018-10-19T09:00:58Z" level=debug msg="Creating route blackbox.app.domain.com Host:blackbox.app.domain.com"
...
```

**Comment by dtomcej** [comment] 2018-10-22 14:59
Hello @dejaeghered,

I have created a PR with some added tests, and they suggest that the correct certificate should be chosen even when two wildcards overlap.

Could you provide us with the configuration you have stored in consul? It appears that you also have some ACME errors in your logs that may be complicating things.

Thanks!

**Comment by dejaeghered** [comment] 2018-10-22 17:07
We are not using ACME.  The errors are probably caused by an old test
configuration data.  Can I provide the full export of the consul data
somewhere privately? ( I will still have to strip out some domain and cert
data )

Op ma 22 okt. 2018 om 17:00 schreef Daniel Tomcej <notifications@github.com

**Comment by traefiker** [comment] 2018-10-23 16:04
Closed by #4091.

**Comment by maxmeyer** [comment] 2018-10-25 14:34
@dtomcej Having a look at the test and the logs, there seems to be a difference: your certificate uses the DN, but the issue author seems to use Subject Alternative Names in the certificate.

In our infrastructure I've got the same issue, but using static certificates only + docker backend

**Comment by dtomcej** [comment] 2018-10-25 14:55
If you guys could create a reproducible configuration with self signed certs, I would absolutely continue work on this.

There shouldn't be any difference between SANS and CNs, since our code should treat them the same.

Again, If you can provide a repo with a compose file (ideally using self signed certs + just a simple whoami as a backend) that reproduces your issue, I can continue working on it.

Thanks!

**Comment by maxmeyer** [comment] 2018-10-26 14:50
@dtomcej I think I was able to reproduce the problem. See this repo for a non-working example: https://github.com/maxmeyer/verify-problem-with-traefik. It has a README attached, but feel free to ping me if something is unclear.

According to https://security.stackexchange.com/a/150776 and the referenced RFCs using uppercase letters in "Common Names" is allowed. Our internal CA does this. When I switch the generated certificate to have an upper case common name/subject alternative name, traefik does not use the correct certificate anymore.

**Comment by dtomcej** [comment] 2018-10-29 16:31
@maxmeyer I was able to reproduce this issue, and will have a PR and fix shortly.

**Comment by maxmeyer** [comment] 2018-10-30 09:21
@dtomcej Sounds great. Thanks a lot. 

Will this fix be part of 1.7.4? Is there an ETA for 1.7.4? Would love to run the fixed version in production.

**Comment by dtomcej** [comment] 2018-11-01 14:18
@dejaeghered We have had another reported issue that may be similar:

https://github.com/containous/traefik/issues/4144

Can you see if you can provide us a consul config that reproduces your issue? Feel free to use self-signed certs or at least give us the CN/SANS that you used to test with, so we can generate our own.

Re-reading your original logs, its not apparent that your issue is due to case-sensitivity.

@maxmeyer The PR is not going to be in 1.7.4, due to it being released yesterday 😉

**Comment by traefiker** [comment] 2020-09-20 00:00
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Closed by traefiker** 2020-09-20 00:00 UTC
Labels: area/tls, contributor/waiting-for-feedback, kind/bug/confirmed
