### ISSUE TITLE
Middlewares disappear when there is an error in IngressRoute object

### ISSUE THREAD

**Issue by paulyhedral** [traefik/traefik#7651] opened 2020-12-10 22:01 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created an `IngressRoute` object, specifying a Middleware incorrectly.

Middleware spec requires the use of the `name` key, but this particular object was missing the key, and only had the value, i.e.:

Expected:
```yaml
middlewares:
- name: cors-headers
```

Actual:
```yaml
middlewares:
- cors-headers
```
Traefik threw an error in the log, complaining that the `IngressRoute` object could not be parsed (which it should), but then proceeded to ignore _every Middleware_ in the system.

### What did you expect to see?

We have a Middleware object configured to insert CORS headers in HTTP responses. Expected to see the CORS headers.

### What did you see instead?

Traefik stopped recognizing _all_ Middleware objects (web console showed that no Middleware was found at all). CORS headers were no longer present in HTTP responses.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.4
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-24T16:16:43Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
    spec:
      containers:
      - args:
        - --api.insecure
        - --api.dashboard
        - --accesslog
        - --log.level=WARN
        - --ping
        - --metrics.prometheus
        - --entrypoints.web.Address=:8000
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress=true
        image: traefik:v2.3
```

Kubernetes v1.18.9-eks-d1db3c on Amazon EKS

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by paulyhedral** [comment] 2020-12-11 19:06
It was all of the middlewares that I added. I noticed in the web console that the Traefik-provided middlewares (there were 2 of them) were still there, but everything that I had added to the cluster did not show up.

As for reproducing, all you have to do is remove the `name` key from an item in the list of middlewares for an `IngressRoute` and that's when things break. I provided a sparse example in the initial comment. I don't have access to the logs at the moment, but I will try to get those added here soon.

**Comment by jspdown** [comment] 2020-12-14 14:44
Hello @paulyhedral :wave: 
I tried to reproduce what you described but it works as expected with my setup:

<details>
  <summary>test-case.yaml</summary>

  ```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 3
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:latest

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: whoami
      targetPort: 80
      protocol: TCP
  selector:
    app: whoami

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /stripit

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route
spec:
  entryPoints:
    - whoami
  routes:
  - kind: Rule
    match: Host(`test.example.com`)
    middlewares:
      - name: stripprefix
    services:
    - kind: Service
      name: whoami
      namespace: default
      port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-2
spec:
  entryPoints:
    - whoami
  routes:
  - kind: Rule
    match: Host(`test.example.com`)
    middlewares:
      - stripprefix
    services:
    - kind: Service
      name: whoami
      namespace: default
      port: 8080

  ```
</details>

In this test I created a middleware `stripprefix`, declared 2 ingressRoutes, one valid and one invalid with the `name` attribute missing. Once applied, it works as expected, the first ingressRoute is successfully loaded with its middleware and the second is not because the of its invalid format. 

Could you provide us a reproducible test case (complete dynamic and static configuration, logs in debug mode)?

**Comment by paulyhedral** [comment] 2020-12-14 17:36
It's the Middleware that doesn't load, not the IngressRoute. The IngressRoute was loading, but it was not using the middleware, because none of the Middlewares would load after the error in the IngressRoute definition.

**Comment by jspdown** [comment] 2020-12-15 08:24
> Could you provide us a reproducible test case (complete dynamic and static configuration, logs in debug mode)?

@paulyhedral Your configuration would be really helpful.

**Comment by a-nldisr** [comment] 2020-12-21 19:18
Ran into the same issue i think, we are giving Traefik v2 a review before we migrate our workloads from one container cluster to the next. So the misconfigurations are result of inexperience and mistakes made. However did not expect a mistake could break all middlewares, seems some validation before applying the rules is missing.

Traefik version: 2.3.3
Kubernetes version: 1.19.4
helm chart version: 9.11

Empty Traefik

Create a valid middleware:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist-localhost
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
```

Applied the following Middleware with wrong config:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: wrong
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: "true"
    port: 443
```

The error in the logs:
```E1221 17:04:22.126949       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.Middleware: v1alpha1.MiddlewareList.Items: []v1alpha1.Middleware: v1alpha1.Middleware.Spec: v1alpha1.MiddlewareSpec.RedirectScheme: dynamic.RedirectScheme.Permanent: ReadBool: expect t or f, but found ", error found in #10 byte of ...|rmanent":"true","por|..., bigger context ...|aed8081d"},"spec":{"redirectScheme":{"permanent":"true","port":443,"scheme":"https"}}},{"apiVersion"|...```

Errors tab shows nothing:
```
No data available
```

Don't know yet how to trigger the complete failure we saw today, but after this you cannot add new middlewares anymore. 

After a while suddenly all our configured middlewares vanished and poof... Everything was offline. 
Looking into how to reproduce this.

**Comment by avdhoot** [comment] 2020-12-26 11:09
same observed. 
 To reproduce deploy wrong Middleware(like below) & restart traefik.  @jspdown 
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: somethingy-cross
  namespace: something
spec:
  headers:
    accessControlAllowOrigin: '*'
    accessControlAllowHeaders: authorization

**Comment by rtribotte** [comment] 2020-12-29 08:52
Hello @paulyhedral,

I also tried to reproduce your issue with no success.
If an ingressRoute use a bad reference to middleware, the ingressRoute is not loaded, but I cannot see all the middlewares being not recognized (and the ingressRoute with a valid reference to middleware is applied correctly and working).

All the middleware you are talking about were declared via CRDs?

That being said, the scenario you are describing is still not clear, we need a minimal but reproducible example.

Because it's not clear, and because @a-nldisr and @avdhoot stepped in, do you think they are referring to the same issue as the one you are facing (I think not)?

I can reproduce their issue. Using an invalid middleware declaration breaks the load of every CRD resource on Traefik restart.

**Comment by paulyhedral** [comment] 2020-12-29 17:43
> Hello @paulyhedral,
> 
> I also tried to reproduce your issue with no success.
> If an ingressRoute use a bad reference to middleware, the ingressRoute is not loaded, but I cannot see all the middlewares being not recognized (and the ingressRoute with a valid reference to middleware is applied correctly and working).

That is the inverse of the issue I'm seeing. If the IngressRoute has an invalid reference (see first post) to a Middleware, then _all_ the Middlewares fail to load.

> All the middleware you are talking about were declared via CRDs?

Yes.

> That being said, the scenario you are describing is still not clear, we need a minimal but reproducible example.

I provided an example in the initial post.

> Because it's not clear, and because @a-nldisr and @avdhoot stepped in, do you think they are referring to the same issue as the one you are facing (I think not)?
> 
> I can reproduce their issue. Using an invalid middleware declaration breaks the load of every CRD resource on Traefik restart.

Yes, this is the same issue.

**Comment by rtribotte** [comment] 2020-12-30 09:45
Hello @paulyhedral @avdhoot @a-nldisr,

I can confirm the bug. To reproduce it, the Traefik pod creation should occur after the creation of malformed ingressRoute/middleware objects (e.g. a restart of Traefik).

Thus, there is no simple solution to solve that bug, this is due to the lack of validation of the CRDs and we will work on it in a future version.

The current workaround is to produce a reload of your configuration, one of the following steps should work:
- Without restarting Traefik, delete all your resources and apply again (without fixing the malformed resources), this should make Traefik re-handling the valid resources
- Fixing/Deleting the malformed resources 

I'll close this issue in favor of #5473, which is addressing this issue by proposing the support of CRD openAPIV3Schema schema.

Closed in favor of #5473

**Closed by rtribotte** 2020-12-30 09:45 UTC
Labels: area/provider/k8s/crd, contributor/waiting-for-feedback, kind/bug/possible

**Comment by a-nldisr** [comment] 2021-01-04 09:17
@rtribotte In our case Traefik did not restart.

**Comment by rtribotte** [comment] 2021-01-04 11:01
@a-nldisr Thanks for your feedback, if your issue is not related to the validation of the CRDs or will not be solved by the introduction of the validation, please file a new issue that will be the proper place to discuss it.
