### ISSUE TITLE
Traefik Rancher App header not working

### ISSUE THREAD

**Issue by JustNZ** [traefik/traefik#7938] opened 2021-02-28 19:55 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Traefik is running inside my Rancher Cluster as an App.
I have L7 Ingress configured for my two applications with the following annotations:

`ingress.kubernetes.io/custom-request-headers: Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS,DELETE,PUT||Access-Control-Allow-Headers:append,delete,entries,foreach,get,has,keys,set,values,Authorization,Content-Type,Origin,Accept,X-Requested-With||Access-Control-Max-Age:86400||Access-Control-Allow-Credentials:true`

`ingress.kubernetes.io/custom-response-headers: Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS,DELETE,PUT||Access-Control-Allow-Headers:append,delete,entries,foreach,get,has,keys,set,values,Authorization,Content-Type,Origin,Accept,X-Requested-With||Access-Control-Max-Age:86400||Access-Control-Allow-Credentials:true`

Now i want to make Rest API requests from app1 to app2 but get the following error message:

> Access to XMLHttpRequest at 'App2' from origin 'App1' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### What did you expect to see?

Successful API Requests with configured L7 Ingress

### What did you see instead?

> Access to XMLHttpRequest at 'App1' from origin 'App2' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### Output of `traefik version`: (_What version of Traefik are you using?_)

v1.7.14

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- Traefik running as an App inside my Rancher Cluster.

- Two Applications with L7 Ingress.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

> Access to XMLHttpRequest at 'App1' from origin 'App2' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by SantoDE** [comment] 2021-03-01 10:16
Hey,

thanks for your interest in the project.

This is, because you are not using the correct annotations.

For Traefik, the annotations are:

```
traefik.frontend.headers.customRequestHeaders=EXPR
``` 

As you can see here: https://doc.traefik.io/traefik/v1.7/configuration/backends/rancher/#custom-headers

Ill close that issue, as its a question :)

**Comment by rtribotte** [comment] 2021-03-03 09:30
Hello @JustNZ,

Can your share a complete and minimal reproducible case?
`Access-Control-Allow-Headers` is a CORS header applicable only to responses.
Moreover, that's the case for all `Access-Control-Allow-` headers.

**Comment by JustNZ** [comment] 2021-03-03 09:40
Hey @rtribotte,

I have an Vue.js Admin Dashboard which is running as an pod inside Rancher/Kubernetes.
In that application I want to make axios get requests to the rancher api.
Rancher and my Admin Dashboard are both exposed with an L7 Ingress and the provied Header configuration.

And it's not only the Rancher API where I got that problem. Every Service with rest api that is exposed over an Loadbalancer doesn't work.

Does that nearly answer what you asked for?

**Comment by JustNZ** [comment] 2021-03-03 09:45
In the past i used Apache for reverse-proxying and also configured there some headers and that worked totally fine.
And since this procedure isn't anymore the state of the art :D, I switched over to Traefik. 

Retired Apache2 header config:
```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Headers "append,delete,entries,foreach,get,has,keys,set,values,Authorization"
Header set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header set Access-Control-Max-Age "86400"
```

**Comment by rtribotte** [comment] 2021-03-03 09:59
Hey @JustNZ,

Unfortunately, we are not providing configuration troubleshoot support on Github.

Since your answer is only describing your setup and could not be used to reproduce a bug, it looks like a configuration issue.

I strongly encourage you to post on our [community forum](https://community.traefik.io/c/traefik/traefik-v2/10) to get some help troubleshooting your configuration issue.

Question aside, since you said that you are moving from Apache, did you check the v2 of Traefik? For a new setup, it's more appropriate to move on directly to our latest version.

Accordingly, I'll close this issue again.

**Closed by rtribotte** 2021-03-03 09:59 UTC
Labels: contributor/waiting-for-feedback, kind/question
