### ISSUE TITLE
One invalid IngressRouteTCP resource blocks discovery across entire cluster

### ISSUE THREAD

**Issue by 0xVox** [traefik/traefik#7802] opened 2021-01-26 20:07 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

Applied an invalid IngressRouteTCP and restarted my traefik instances (As this involved adding a new entrypoint)

### What did you expect to see?

I expected that a single invalid route resource would not disable discovery for all other resources. This bug caused all ingress in our dev cluster to break once we restarted traefik.

### What did you see instead?

If you post an invalid ingressroutetcp to a namespace traefik is watching, a bit like the problem in this snippet:

```
- match: Host(`redacted.internal.domain`)
      services:
         name: websockets # This line needs a '-' prepended as traefik validates this section as an array, but it's technically valid YAML so k8s lets it through.
         namespace: websockets
         port: 7650
```

this throws one of these in the logs:

```
E0126 18:44:41.164141       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.IngressRouteTCP: v1alpha1.IngressRouteTCPList.Items: []v1alpha1.IngressRouteTCP: v1alpha1.IngressRouteTCP.Spec: v1alpha1.IngressRouteTCPSpec.Routes: []v1alpha1.RouteTCP: v1alpha1.RouteTCP.Services: []v1alpha1.ServiceTCP: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ervices":{"name":"we|..., bigger context ...|redacted.internal.domain`)","services":{"name":"websockets","namespace":"websock|...

```

And then traefik gets real weird and outputs some trace level logs, even though it's in INFO log level mode:

```
I0126 18:44:53.168221       1 trace.go:116] Trace[1157944885]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125 (started: 2021-01-26 18:44:40.97107118 +0000 UTC m=+0.149159378) (total time: 12.197128638s):
Trace[1157944885]: [12.197105041s] [12.197105041s] Objects listed
```

I've tested triggering this bug a few times now, and a few things to note:
- This is catastrophic after a restart of the traefik instances that watch this particular IngressRouteTCP. The instances will completely fail to pick up *all* routing config from Kubernetes if they encounter this route. I've not tested if they still succeed to get file provider config.
- The order of the namespaces in the `providers.kubernetesCRD.namespaces` section makes no difference. (I was curious to see, because the route existed in the first namespace in this instance, whereas usually I _append_ new namespaces)
- If the IngressRouteTCP is added during execution, then all previously registered routes will continue to work, but discovering new routes and of course this new route will not work.
- The debug logs imply that traefik-generated middlewares are still made, so there is still file discovery happening at least.

### Output of `traefik version`: 
```
Version:      2.4.0 (Originally found and tested on 2.3.7)
Codename:     livarot
Go version:   go1.15.6
Built:        2021-01-19T17:26:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]

[ping]

[log]
  level = "DEBUG"

[accessLog]

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
    buckets = [0.1,0.3,1.2,5.0,10.0]

[entryPoints]
  [entryPoints.metrics]
    address = ":9090"

# We have a bunch of other entryPoints and a redirect rule for http->https here i've left out.

[providers]
  [providers.kubernetesCRD]
    namespaces = ["websockets", "plus 15 or so other namespaces that have their routes broken"]
    ingressClass = "traefik-private"
  [providers.file]
    filename = "/config/dyn/traefik-dyn.toml"
```

We are running on Kubernetes 1.19.3
Traefik is running as a DaemonSet

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
<details>
  <summary>Loud debug logs</summary>
  
Logs:
  
```
time="2021-01-26T19:52:37Z" level=info msg="Configuration loaded from file: /config/static/traefik.toml"
time="2021-01-26T19:52:37Z" level=info msg="Traefik version 2.4.0 built on 2021-01-19T17:26:51Z"
time="2021-01-26T19:52:37Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"insecureSkipVerify\":true,\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"argocd-internal\":{\"address\":\":8888\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"elastic-internal\":{\"address\":\":9200\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"elastic-transport-internal\":{\"address\":\":9300\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"redacted\":{\"address\":\":8545\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"filebeat-central\":{\"address\":\":6514\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"kafka-internal\":{\"address\":\":9093\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"logstash\":{\"address\":\":5044\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"metrics\":{\"address\":\":9090\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"mysql-internal\":{\"address\":\":3306\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"thanos-grpc-internal\":{\"address\":\":10901\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"vault\":{\"address\":\":8200\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"web\":{\"address\":\":8000\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\":443\",\"scheme\":\"https\",\"permanent\":true,\"priority\":2147483647}}}},\"web-internal\":{\"address\":\":8001\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\":443\",\"scheme\":\"https\",\"permanent\":true,\"priority\":2147483647}}}},\"websecure\":{\"address\":\":4443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"websecure-internal\":{\"address\":\":4444\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"websockets-internal\":{\"address\":\":2011\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"file\":{\"watch\":true,\"filename\":\"/config/dyn/traefik-dyn.toml\"},\"kubernetesCRD\":{\"namespaces\":[\"tt-websockets\",\"bd-druid-infra\",\"bd-kafka-infra\",\"bd-mariadb-infra\",\"bd-timescale-infra\",\"ingress\",\"vault\",\"logging\",\"acg\",\"prometheus\",\"monitoring\",\"cryptonodes\",\"frontend\",\"cattle-system\",\"cbe-acg\",\"cbe-risk\",\"argocd\"],\"allowCrossNamespace\":true,\"ingressClass\":\"traefik-private\"}},\"api\":{\"dashboard\":true},\"metrics\":{\"prometheus\":{\"buckets\":[0.1,0.3,1.2,5,10],\"addEntryPointsLabels\":true,\"addServicesLabels\":true,\"entryPoint\":\"metrics\"}},\"ping\":{\"entryPoint\":\"traefik\",\"terminatingStatusCode\":503},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}}}"
time="2021-01-26T19:52:37Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2021-01-26T19:52:37Z" level=debug msg="Configured Prometheus metrics" metricsProviderName=prometheus
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=filebeat-central
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=metrics
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=web
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=web-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=redacted
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=elastic-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=logstash
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=mysql-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=elastic-transport-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=argocd-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=kafka-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=websockets-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=vault
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=websecure-internal
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=thanos-grpc-internal
time="2021-01-26T19:52:37Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2021-01-26T19:52:37Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2021-01-26T19:52:37Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/config/dyn/traefik-dyn.toml\"}"
time="2021-01-26T19:52:37Z" level=info msg="Starting provider *acme.ChallengeTLSALPN {\"Timeout\":2000000000}"
time="2021-01-26T19:52:37Z" level=info msg="Starting provider *crd.Provider {\"namespaces\":[\"websockets\",\"redacted-the-rest\"]}"
time="2021-01-26T19:52:37Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2021-01-26T19:52:37Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2021-01-26T19:52:37Z" level=info msg="Starting provider *traefik.Provider {}"
time="2021-01-26T19:52:37Z" level=debug msg="Configuration received from provider file: {\"http\":{},\"tcp\":{},\"udp\":{},\"tls\":{\"stores\":{\"default\":{}}}}" providerName=file
time="2021-01-26T19:52:37Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2021-01-26T19:52:37Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"ping\":{\"entryPoints\":[\"traefik\"],\"service\":\"ping@internal\",\"rule\":\"PathPrefix(`/ping`)\",\"priority\":2147483647},\"prometheus\":{\"entryPoints\":[\"metrics\"],\"service\":\"prometheus@internal\",\"rule\":\"PathPrefix(`/metrics`)\",\"priority\":2147483647},\"web-internal-to-443\":{\"entryPoints\":[\"web-internal\"],\"middlewares\":[\"redirect-web-internal-to-443\"],\"service\":\"noop@internal\",\"rule\":\"HostRegexp(`{host:.+}`)\",\"priority\":2147483647},\"web-to-443\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"redirect-web-to-443\"],\"service\":\"noop@internal\",\"rule\":\"HostRegexp(`{host:.+}`)\",\"priority\":2147483647}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{},\"ping\":{},\"prometheus\":{}},\"middlewares\":{\"redirect-web-internal-to-443\":{\"redirectScheme\":{\"scheme\":\"https\",\"port\":\"443\",\"permanent\":true}},\"redirect-web-to-443\":{\"redirectScheme\":{\"scheme\":\"https\",\"port\":\"443\",\"permanent\":true}}},\"serversTransports\":{\"default\":{\"insecureSkipVerify\":true,\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2021-01-26T19:52:37Z" level=warning msg="Cross-namespace reference between IngressRoutes and resources is enabled, please ensure that this is expected (see AllowCrossNamespace option)" providerName=kubernetescrd
E0126 19:52:38.127518       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1alpha1.IngressRouteTCP: failed to list *v1alpha1.IngressRouteTCP: v1alpha1.IngressRouteTCPList.Items: []v1alpha1.IngressRouteTCP: v1alpha1.IngressRouteTCP.Spec: v1alpha1.IngressRouteTCPSpec.Routes: []v1alpha1.RouteTCP: v1alpha1.RouteTCP.Services: []v1alpha1.ServiceTCP: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ervices":{"name":"tt|..., bigger context ...|g.tt-websockets.int.p1d.kraken.com`)","services":{"name":"tt-websockets-wsg","namespace":"tt-websock|...
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=logstash middlewareType=Metrics middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=mysql-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint entryPointName=web middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=elastic-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=elastic-transport-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=kafka-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=thanos-grpc-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=websecure-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=redacted middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=filebeat-central middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=metrics middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=websockets-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=traefik middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=argocd-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint entryPointName=vault middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=web-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=logstash middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=mysql-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=elastic-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=elastic-transport-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint entryPointName=kafka-internal middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=thanos-grpc-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=websecure-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=redacted middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=filebeat-central middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=metrics middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=websockets-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint middlewareType=Metrics entryPointName=traefik
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=argocd-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" entryPointName=vault middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:38Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=web-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:38Z" level=debug msg="No default certificate, generating one"
time="2021-01-26T19:52:39Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
I0126 19:52:39.129885       1 request.go:645] Throttling request took 1.197665698s, request: GET:https://10.254.0.1:443/api/v1/namespaces/namespace-name/services?limit=500&resourceVersion=0
time="2021-01-26T19:52:39Z" level=debug msg="Serving default certificate for request: \"private1.internal.domain.com\""
time="2021-01-26T19:52:39Z" level=debug msg="Serving default certificate for request: \"private1.internal.domain.com\""
time="2021-01-26T19:52:39Z" level=debug msg="http: TLS handshake error from 100.64.163.128:60178: remote error: tls: bad certificate"
time="2021-01-26T19:52:39Z" level=debug msg="http: TLS handshake error from 100.64.163.128:60172: remote error: tls: bad certificate"
time="2021-01-26T19:52:39Z" level=debug msg="Added outgoing tracing middleware prometheus@internal" entryPointName=metrics routerName=prometheus@internal middlewareName=tracing middlewareType=TracingForwarder
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=metrics
time="2021-01-26T19:52:39Z" level=debug msg="Added outgoing tracing middleware noop@internal" entryPointName=web-internal routerName=web-internal-to-443@internal middlewareName=tracing middlewareType=TracingForwarder
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=web-internal routerName=web-internal-to-443@internal middlewareName=redirect-web-internal-to-443@internal middlewareType=RedirectScheme
time="2021-01-26T19:52:39Z" level=debug msg="Setting up redirection to https 443" entryPointName=web-internal routerName=web-internal-to-443@internal middlewareName=redirect-web-internal-to-443@internal middlewareType=RedirectScheme
time="2021-01-26T19:52:39Z" level=debug msg="Adding tracing to middleware" entryPointName=web-internal routerName=web-internal-to-443@internal middlewareName=redirect-web-internal-to-443@internal
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web-internal
time="2021-01-26T19:52:39Z" level=debug msg="Added outgoing tracing middleware noop@internal" routerName=web-to-443@internal middlewareName=tracing middlewareType=TracingForwarder entryPointName=web
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=web routerName=web-to-443@internal middlewareName=redirect-web-to-443@internal middlewareType=RedirectScheme
time="2021-01-26T19:52:39Z" level=debug msg="Setting up redirection to https 443" middlewareName=redirect-web-to-443@internal middlewareType=RedirectScheme entryPointName=web routerName=web-to-443@internal
time="2021-01-26T19:52:39Z" level=debug msg="Adding tracing to middleware" entryPointName=web routerName=web-to-443@internal middlewareName=redirect-web-to-443@internal
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
time="2021-01-26T19:52:39Z" level=debug msg="Added outgoing tracing middleware ping@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=ping@internal
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=logstash middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=mysql-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint middlewareType=Metrics entryPointName=web
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=elastic-internal middlewareType=Metrics middlewareName=metrics-entrypoint
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint middlewareType=Metrics entryPointName=elastic-transport-internal
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=kafka-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=thanos-grpc-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=websecure-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=filebeat-central middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=metrics middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=websockets-internal middlewareType=Metrics middlewareName=metrics-entrypoint
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=traefik middlewareName=metrics-entrypoint
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareType=Metrics middlewareName=metrics-entrypoint entryPointName=argocd-internal
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint middlewareType=Metrics entryPointName=vault
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint middlewareType=Metrics entryPointName=web-internal
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareType=Metrics middlewareName=metrics-entrypoint entryPointName=logstash
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=mysql-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=websecure middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=elastic-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=elastic-transport-internal middlewareType=Metrics middlewareName=metrics-entrypoint
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=kafka-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=thanos-grpc-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=websecure-internal middlewareName=metrics-entrypoint
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareType=Metrics entryPointName=filebeat-central middlewareName=metrics-entrypoint
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=metrics middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareType=Metrics middlewareName=metrics-entrypoint entryPointName=websockets-internal
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" middlewareName=metrics-entrypoint entryPointName=traefik middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=argocd-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=vault middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="Creating middleware" entryPointName=web-internal middlewareName=metrics-entrypoint middlewareType=Metrics
time="2021-01-26T19:52:39Z" level=debug msg="No default certificate, generating one"
100.64.9.195 - - [26/Jan/2021:19:52:39 +0000] "GET /metrics HTTP/1.1" - - "-" "-" 1 "-" "-" 2ms
time="2021-01-26T19:52:44Z" level=debug msg="Serving default certificate for request: \"private1.internal.domain.com\""
time="2021-01-26T19:52:44Z" level=debug msg="http: TLS handshake error from 10.101.126.12:46220: remote error: tls: bad certificate"
time="2021-01-26T19:52:44Z" level=debug msg="Serving default certificate for request: \"private1.internal.domain.com\""
time="2021-01-26T19:52:44Z" level=debug msg="Serving default certificate for request: \"private1.internal.domain.com\""
time="2021-01-26T19:52:44Z" level=debug msg="http: TLS handshake error from 100.64.78.0:53302: remote error: tls: bad certificate"
time="2021-01-26T19:52:44Z" level=debug msg="http: TLS handshake error from 100.64.25.64:57476: remote error: tls: bad certificate"
100.64.9.195 - - [26/Jan/2021:19:52:44 +0000] "GET /metrics HTTP/1.1" 200 1719 "-" "-" 2 "prometheus@internal" "-" 6ms
100.64.10.251 - - [26/Jan/2021:19:52:46 +0000] "GET /metrics HTTP/1.1" 200 1778 "-" "-" 3 "prometheus@internal" "-" 1ms
time="2021-01-26T19:52:47Z" level=debug msg="Serving default certificate for request: \"private.internal.domain.com\""
time="2021-01-26T19:52:47Z" level=debug msg="Serving default certificate for request: \"private.internal.domain.com\""
time="2021-01-26T19:52:47Z" level=debug msg="http: TLS handshake error from 100.64.78.0:27408: local error: tls: bad record MAC"
time="2021-01-26T19:52:47Z" level=debug msg="http: TLS handshake error from 100.64.112.0:1192: local error: tls: bad record MAC"
I0126 19:52:48.131723       1 trace.go:205] Trace[879648553]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (26-Jan-2021 19:52:37.932) (total time: 10198ms):
Trace[879648553]: ---"Objects listed" 10198ms (19:52:00.131)
Trace[879648553]: [10.198815716s] [10.198815716s] END
I0126 19:52:48.331940       1 trace.go:205] Trace[4088582]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (26-Jan-2021 19:52:37.932) (total time: 10399ms):
Trace[4088582]: ---"Objects listed" 10398ms (19:52:00.331)
Trace[4088582]: [10.399011095s] [10.399011095s] END
I0126 19:52:48.531772       1 trace.go:205] Trace[1966711297]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (26-Jan-2021 19:52:37.932) (total time: 10598ms):
Trace[1966711297]: ---"Objects listed" 10598ms (19:52:00.531)
Trace[1966711297]: [10.598806044s] [10.598806044s] END
```
The tracing logsat the end then continue to be _very_ loud, drowning out almost everything else with that message repeated.
  
</details>

**Comment by kevinpollet** [comment] 2021-01-27 09:01
Duplicate of #5473

**Closed by kevinpollet** 2021-01-27 09:01 UTC
Labels: status/0-needs-triage
