### ISSUE TITLE
Exclude for middlewares

### ISSUE THREAD

**Issue by ScreNN** [traefik/traefik#9862] opened 2023-04-25 00:49 UTC
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hey \0

I would like to be able to exclude global middleware from individual services

Example traefik.yml file:
```
Global Middlewares in traefik.yml file

      middlewares:
        - geoblock@file
        - gzip@file
        - secureHeaders@file
        - log4shell@file
```

Example individual services:
```
Middlewares in dynamic.yml file

http:
  routers:
    test:
      rule: "Host(`exclude.test.com`)"
      middlewares:
        - individual_middlewares and global_middlewares
      exclude_middlewares:
        - log4shell <--------- exclude from this services
      entryPoints:
        - "https"
      service: test
```

**Comment by rtribotte** [comment] 2023-04-25 10:36
Hello @ScreNN,

Thanks for your interest in Traefik!

This issue seems to be a duplicate proposal issue.
We are closing it accordingly, but feel free to ask to re-open it.

Duplicate of #8654

**Closed by rtribotte** 2023-04-25 10:36 UTC
Labels: status/0-needs-triage
