### ISSUE TITLE
Traefik not picking up Docker container

### ISSUE THREAD

**Issue by Philantrop** [traefik/traefik#7377] opened 2020-10-02 14:03 UTC
Bug

### What did you do?

I'm using Docker containers to run Synapse, a homeserver for the Matrix protocol. One container runs the primary process while some others run so-called workers. Everything was working fine until I updated to Traefik 2.3 (curiously a downgrade does not fix my issue, though!).  

Since then, while the primary container is recognised just fine by Traefik via the labels in my compose file, the workers aren't recognised anymore at all. They don't appear in the dashboard nor can they be routed to. The containers themselves are running just fine and are functional, though.  

I'm completely unable to see what might be wrong and I've been experimenting for days now. Since asking for advice in your community (https://community.traefik.io/t/traefik-2-3-0-not-picking-up-docker-container/7936) didn't yield any results and there was one person on Reddit who had the same issue (https://www.reddit.com/r/Traefik/comments/j22034/traefik_230_not_picking_up_docker_container/), I assume they and I are hitting some obscure bug.

Here's the docker-compose yaml configuration for the main process which does get picked up by Traefik:

https://mailstation.de/~krueger/traefik/main_process-working.yaml

Here's the worker configuration that does NOT get picked up by Traefik:

https://mailstation.de/~krueger/traefik/worker_unseen_by_traefik.yaml

Should you need any additional information, please just let me know.

### What did you expect to see?
The worker should be displayed in Traefik's dashboard and - more importantly - routed to.

### What did you see instead?
Neither of my above expectations were fulfilled.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
 
  [entryPoints.web2]
    address = ":81"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.matrix-login]
    address = ":8448"

[log]
  level = "WARN"
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"

[api]
  insecure = false
  dashboard = true

[ping]


[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[certificatesResolvers.le.acme]
  email = "wk@mailstation.de"
  #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.le.acme.httpChallenge]
  # used during the challenge
  entryPoint = "web"

[providers]
  # Enable the file provider to define routers / middlewares / services in file
  [providers.file]
    directory = "/etc/traefik/dynamic"
    watch = true

[pilot]
    token = "removedXXX"
```

**Comment by KeldorDE** [comment] 2020-10-07 11:18
I can also confirm this bug on multiple systems. But the bug seems not to be limited to version 2.3.1. I have downgraded to version 2.2.11 and I have the same behaviour there too.

What I noticed is that normally the Docker Containers appear in Traefik after a few seconds, but at the moment it takes about 5 minutes until they appear in the list and can be accessed via Traefik.

###Output of traefik version:
`Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64`


### What is your environment & configuration (arguments, toml, provider, platform, ...)?
`logLevel = "ERROR"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers]
[providers.file]
  directory = "/etc/traefik/dynamic"
  watch = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  network = "vhosts"
  exposedByDefault = false
  watch = true

[log]
  filePath = "/var/log/traefik/traefik.log"
  level = "WARN"

[api]
insecure = false
dashboard = true`

**Comment by Philantrop** [comment] 2020-10-07 12:04
Just to be clear: My container as specified in the original report doesn't **ever** show up in Traefik.

**Comment by rtribotte** [comment] 2020-10-08 08:04
Hello @Philantrop,

Thanks for your interest in Traefik !

To go further in troubleshooting, can you paste you dynamic config file and the output of the [endpoint](https://doc.traefik.io/traefik/v2.3/operations/api/#endpoints) `/api/rawdata` ? For that I am assuming that you have a router that routes to api@internal in your dynamic file.
Also the full debug logs would be great to trace down the problem.

**Comment by rtribotte** [comment] 2020-10-08 08:21
Also, i just notice that you used regular expressions in your rules for the not picked up container.
Thus it seems that the it is not respecting the expected format, as stated in the documentation:

> In order to use regular expressions with Host and Path expressions, you must declare an arbitrarily named variable followed by the colon-separated regular expression, all enclosed in curly braces. Any pattern supported by Go's regexp package may be used (example: /posts/{id:[0-9]+}).

**Comment by Philantrop** [comment] 2020-10-10 10:51
Thanks for getting back to me, @rtribotte!

I've fixed the regexp issue, I think, (cf. https://mailstation.de/~krueger/traefik/worker_unseen_by_traefik.yaml), restarted the container and after having ensured the container is running, Traefik itself with debug loglevel.

Dynamic config: https://mailstation.de/~krueger/traefik/rules.toml and https://mailstation.de/~krueger/traefik/redirect.toml
Debug log (in which I see Traefik thinks the container is "unhealthy" (which is simply wrong)): https://mailstation.de/~krueger/traefik/traefik.log

/api/rawdata:
`{"routers":{"api@docker":{"entryPoints":["websecure"],"middlewares":["keycloak@file"],"service":"api@internal","rule":"Host(\"auth.mailstation.de\")","tls":{"certResolver":"le"},"status":"enabled","using":["websecure"]},"auth@docker":{"entryPoints":["websecure"],"middlewares":["keycloak@file"],"service":"auth@docker","rule":"Host(\"auth.mailstation.de\")","tls":{"certResolver":"le"},"status":"enabled","using":["websecure"]},"bitwarden@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"service":"bitwarden@docker","rule":"Host(\"bw.mailstation.de\")","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"bw-websockets@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"service":"bw-websockets@docker","rule":"PathPrefix(\"/notifications/hub\")","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"calibre@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","keycloak@file","replacepath-root-calibre@file"],"service":"calibre","rule":"PathPrefix(`/calibre`) || Host(`calibre.mailstation.de`)","priority":200,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"cops@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","keycloak@file"],"service":"apache","rule":"PathPrefix(`/cops`)","priority":150,"tls":{},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"cweb@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","keycloak@file","replacepath-root-cweb@file","cwebscript@file"],"service":"cweb","rule":"PathPrefix(`/cweb`)","priority":150,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"dimension@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"service":"dimension-dimension@docker","rule":"Host(`dimension.mailstation.de`)","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"hawking@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file"],"service":"apache","rule":"Host(`hawking.mailstation.de`)","priority":9,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"heimdall@docker":{"entryPoints":["websecure"],"middlewares":["keycloak@file"],"service":"heimdall@docker","rule":"Host(\"family.mailstation.de\")","tls":{"certResolver":"le"},"status":"enabled","using":["websecure"]},"ipa-ca@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file"],"service":"apache","rule":"Host(`ipa-ca.mailstation.de`)","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"ipa@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file"],"service":"ipa","rule":"Host(`ipa.mailstation.de`)","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"keycloak@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file"],"service":"keycloak","rule":"Host(`keycloak1.mailstation.de`)","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"ma1sd@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"service":"ma1sd-ma1sd@docker","rule":"PathPrefix(`/_matrix/client/r0/login`) || PathPrefix(`/_matrix/identity`) || PathPrefix(`/_matrix/client/r0/user_directory/`)","priority":450,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"mailstation@file":{"entryPoints":["websecure"],"middlewares":["std-headers@file"],"service":"apache","rule":"Host(`mailstation.de`)","priority":1,"tls":{"certResolver":"le"},"status":"enabled","using":["websecure"]},"matrix-monitor-bot@docker":{"entryPoints":["websecure"],"middlewares":["std-headers@file"],"service":"matrix-monitor-bot@docker","rule":"PathPrefix(`/mmb`)","tls":{"certResolver":"le"},"status":"enabled","using":["websecure"]},"maubot@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"service":"maubot@docker","rule":"PathPrefix(\"/_matrix/maubot\")","priority":400,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"mx-puppet-twitter@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"service":"mx-puppet-twitter-mx-puppet-twitter@docker","rule":"PathPrefix(`/_matrix/twitter/webhook`)","priority":500,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"phpmyadmin@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","keycloak@file"],"service":"apache","rule":"PathPrefix(`/phpMyAdmin`)","priority":150,"tls":{},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"ping@internal":{"entryPoints":["traefik"],"service":"ping@internal","rule":"PathPrefix(`/ping`)","priority":2147483647,"status":"enabled","using":["traefik"]},"pwm@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","replacepath-pwm@file"],"service":"pwm","rule":"PathPrefix(`/pwm`) || PathPrefix(`/ssp`)","priority":150,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"redirecttohttps@file":{"entryPoints":["web"],"middlewares":["httpsredirect@file"],"service":"noop","rule":"HostRegexp(`{host:.+}`)","status":"enabled","using":["web"]},"riot-web@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["riot-web@docker","element-web@docker","std-headers@file"],"service":"riot-web-riot-web@docker","rule":"(PathPrefix(`/riot`) || PathPrefix(`/element`)) \u0026\u0026 (Host(`mailstation.de`) || Host(`hawking.mailstation.de`))","priority":150,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"rspamd@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","keycloak@file"],"service":"rspamd","rule":"Host(`rspamd.mailstation.de`)","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"saxophonissima@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file"],"service":"apache","rule":"Host(`saxophonissima.de`) || Host(`www.saxophonissima.de`)","priority":5,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"spotweb@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","keycloak@file"],"service":"apache","rule":"PathPrefix(`/spotweb`)","priority":150,"tls":{},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"synapse@docker":{"entryPoints":["matrix-login","web","web2","websecure"],"service":"synapse","rule":"Host(`mailstation.de`) \u0026\u0026 ( PathPrefix(`/_matrix`) || PathPrefix(`/_synapse`) )","priority":300,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"traefik-dashboard@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","keycloak@file"],"service":"api@internal","rule":"Host(`hawking.mailstation.de`) \u0026\u0026 (PathPrefix(`/dashboard/`) || PathPrefix(`/api`))","tls":{},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"well-known-IPA-LE@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","replacepath-well-known-IPA-LE@file"],"service":"apache","rule":"(Host(`ipa.mailstation.de`) || Host(`188.40.120.189`)) \u0026\u0026 PathPrefix(`/.well-known/acme-challenge`)","priority":150,"status":"enabled","using":["matrix-login","web","web2","websecure"]},"well-known-dav@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file","replacepath-well-known-dav@file"],"service":"apache","rule":"PathPrefix(`/.well-known/carddav`) || PathPrefix(`/.well-known/caldav`)","priority":150,"tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]},"www@file":{"entryPoints":["matrix-login","web","web2","websecure"],"middlewares":["std-headers@file"],"service":"apache","rule":"Host(`www.mailstation.de`)","tls":{"certResolver":"le"},"status":"enabled","using":["matrix-login","web","web2","websecure"]}},"middlewares":{"add-cops@file":{"addPrefix":{"prefix":"/cops"},"status":"enabled"},"cwebscript@file":{"headers":{"customRequestHeaders":{"X-SCHEME":"https","X-SCRIPT-NAME":"/cweb"}},"status":"enabled","usedBy":["cweb@file"]},"element-web@docker":{"replacePathRegex":{"regex":"^/element/(.*)","replacement":"/$1"},"status":"enabled","usedBy":["riot-web@docker"]},"gzip-compress@file":{"compress":{},"status":"enabled"},"httpsredirect@file":{"redirectScheme":{"scheme":"https"},"status":"enabled","usedBy":["redirecttohttps@file"]},"keycloak@file":{"forwardAuth":{"address":"http://traefik-forward-auth:4181","trustForwardHeader":true,"authResponseHeaders":["X-Forwarded-User"]},"status":"enabled","usedBy":["api@docker","auth@docker","calibre@file","cops@file","cweb@file","heimdall@docker","phpmyadmin@file","rspamd@file","spotweb@file","traefik-dashboard@file"]},"matrix-monitor-bot@docker":{"stripPrefix":{"prefixes":["/mmb"],"forceSlash":true},"status":"enabled"},"replacepath-pwm@file":{"replacePathRegex":{"regex":"^/ssp/(.*)","replacement":"/pwm/$1"},"status":"enabled","usedBy":["pwm@file"]},"replacepath-root-calibre@file":{"replacePathRegex":{"regex":"^/calibre/(.*)","replacement":"/$1"},"status":"enabled","usedBy":["calibre@file"]},"replacepath-root-cweb@file":{"replacePathRegex":{"regex":"^/cweb/(.*)","replacement":"/$1"},"status":"enabled","usedBy":["cweb@file"]},"replacepath-well-known-IPA-LE@file":{"replacePathRegex":{"regex":"/.well-known/acme-challenge/(.*)","replacement":"/LE/.well-known/acme-challenge/$1"},"status":"enabled","usedBy":["well-known-IPA-LE@file"]},"replacepath-well-known-dav@file":{"replacePathRegex":{"regex":"/.well-known/(card|cal)dav","replacement":"/owncloud/remote.php/dav/"},"status":"enabled","usedBy":["well-known-dav@file"]},"riot-web@docker":{"replacePathRegex":{"regex":"^/riot/(.*)","replacement":"/$1"},"status":"enabled","usedBy":["riot-web@docker"]},"std-headers@file":{"headers":{"customRequestHeaders":{"Server":"","X-Powered-by":"","X-SSL":"on"}},"status":"enabled","usedBy":["calibre@file","cops@file","cweb@file","hawking@file","ipa-ca@file","ipa@file","keycloak@file","mailstation@file","matrix-monitor-bot@docker","phpmyadmin@file","pwm@file","riot-web@docker","rspamd@file","saxophonissima@file","spotweb@file","traefik-dashboard@file","well-known-IPA-LE@file","well-known-dav@file","www@file"]}},"services":{"apache@file":{"loadBalancer":{"servers":[{"url":"http://172.17.0.1/"}],"passHostHeader":true},"status":"enabled","usedBy":["cops@file","hawking@file","ipa-ca@file","mailstation@file","phpmyadmin@file","saxophonissima@file","spotweb@file","well-known-IPA-LE@file","well-known-dav@file","www@file"],"serverStatus":{"http://172.17.0.1/":"UP"}},"api@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.7:80"}],"healthCheck":{"path":"/ping","followRedirects":true},"passHostHeader":true},"status":"enabled"},"api@internal":{"status":"enabled","usedBy":["api@docker","traefik-dashboard@file"]},"auth@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.2:4181"}],"passHostHeader":true},"status":"enabled","usedBy":["auth@docker"],"serverStatus":{"http://172.19.0.2:4181":"UP"}},"bitwarden@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.8:80"}],"passHostHeader":true},"status":"enabled","usedBy":["bitwarden@docker"],"serverStatus":{"http://172.19.0.8:80":"UP"}},"bw-websockets@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.8:3012"}],"passHostHeader":true},"status":"enabled","usedBy":["bw-websockets@docker"],"serverStatus":{"http://172.19.0.8:3012":"UP"}},"calibre@file":{"loadBalancer":{"servers":[{"url":"http://172.17.0.1:8352/"}],"passHostHeader":true},"status":"enabled","usedBy":["calibre@file"],"serverStatus":{"http://172.17.0.1:8352/":"UP"}},"cweb@file":{"loadBalancer":{"servers":[{"url":"http://172.17.0.1:8083/"}],"passHostHeader":true},"status":"enabled","usedBy":["cweb@file"],"serverStatus":{"http://172.17.0.1:8083/":"UP"}},"dashboard@internal":{"status":"enabled"},"dimension-dimension@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.18:8184"}],"passHostHeader":true},"status":"enabled","usedBy":["dimension@docker"],"serverStatus":{"http://172.19.0.18:8184":"UP"}},"heimdall@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.26:80"}],"passHostHeader":true},"status":"enabled","usedBy":["heimdall@docker"],"serverStatus":{"http://172.19.0.26:80":"UP"}},"ipa@file":{"loadBalancer":{"servers":[{"url":"http://192.168.100.237/"}],"passHostHeader":true},"status":"enabled","usedBy":["ipa@file"],"serverStatus":{"http://192.168.100.237/":"UP"}},"keycloak@file":{"loadBalancer":{"servers":[{"url":"http://188.40.120.189:58080/"}],"passHostHeader":true},"status":"enabled","usedBy":["keycloak@file"],"serverStatus":{"http://188.40.120.189:58080/":"UP"}},"ma1sd-ma1sd@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.6:8090"}],"passHostHeader":true},"status":"enabled","usedBy":["ma1sd@docker"],"serverStatus":{"http://172.19.0.6:8090":"UP"}},"matrix-monitor-bot@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.19:8080"}],"passHostHeader":true},"status":"enabled","usedBy":["matrix-monitor-bot@docker"],"serverStatus":{"http://172.19.0.19:8080":"UP"}},"maubot@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.4:29316"}],"passHostHeader":true},"status":"enabled","usedBy":["maubot@docker"],"serverStatus":{"http://172.19.0.4:29316":"UP"}},"mx-puppet-twitter-mx-puppet-twitter@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.16:8536"}],"passHostHeader":true},"status":"enabled","usedBy":["mx-puppet-twitter@docker"],"serverStatus":{"http://172.19.0.16:8536":"UP"}},"noop@file":{"loadBalancer":{"servers":[{"url":"http://192.168.0.1"}],"passHostHeader":true},"status":"enabled","usedBy":["redirecttohttps@file"],"serverStatus":{"http://192.168.0.1":"UP"}},"noop@internal":{"status":"enabled"},"ping@internal":{"status":"enabled","usedBy":["ping@internal"]},"pwm@file":{"loadBalancer":{"servers":[{"url":"http://172.17.0.1:8080/pwm/"}],"passHostHeader":true},"status":"enabled","usedBy":["pwm@file"],"serverStatus":{"http://172.17.0.1:8080/pwm/":"UP"}},"riot-web-riot-web@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.5:80"}],"passHostHeader":true},"status":"enabled","usedBy":["riot-web@docker"],"serverStatus":{"http://172.19.0.5:80":"UP"}},"rspamd@file":{"loadBalancer":{"servers":[{"url":"http://172.17.0.1:11334/"}],"passHostHeader":true},"status":"enabled","usedBy":["rspamd@file"],"serverStatus":{"http://172.17.0.1:11334/":"UP"}},"synapse@docker":{"loadBalancer":{"servers":[{"url":"http://172.19.0.9:8008"}],"passHostHeader":true},"status":"enabled","usedBy":["synapse@docker"],"serverStatus":{"http://172.19.0.9:8008":"UP"}}}}`

**Comment by Philantrop** [comment] 2020-10-26 21:48
Any news about this? Even a way to (temporarily) work-around the symptom by telling Traefik to ignore the health check result would be immensely helpful as a stop-gap measure.

**Comment by rtribotte** [comment] 2020-10-28 11:25
Hello @Philantrop,

Sorry for the delay, but it's difficult to troubleshoot your issue since it's not minimal reproducible example.
I wonder how did you checked the health of your container, can you produce the output this command ?
`docker inspect --format "{{json .State.Health }}" <container name> | jq`

**Comment by ldez** [comment] 2020-10-28 12:52
Also, could you provide more information about your Docker installation (version, ...)

**Comment by Philantrop** [comment] 2020-10-31 13:11
> I wonder how did you checked the health of your container, can you produce the output this command ?
> `docker inspect --format "{{json .State.Health }}" <container name> | jq`

{
  "Status": "unhealthy",
  "FailingStreak": 0,
  "Log": []
}

So, ok, Docker, too, thinks it's unhealthy. Nevertheless, Traefik should let me be the judge about that and provide an option to ignore (potentially) faulty health checks. 

As for my Docker version: Docker version 19.03.11, build 42e35e6

**Comment by rtribotte** [comment] 2020-11-02 08:02
Hello @Philantrop,

Thanks for your inputs, as already guessed, Traefik rely on this status to state if a container is healthy or not.
I understand that you are proposing a new behavior to be allowed to by-pass this status.
I please you to open a new issue to detail your proposal to be able to discuss about it.
I'll close this issue accordingly as a question.

Thanks for your interest in Traefik !

**Closed by rtribotte** 2020-11-02 08:02 UTC
Labels: area/provider/docker, contributor/need-more-information, kind/bug/possible

**Comment by Philantrop** [comment] 2020-11-02 17:05
Feel free to open such an issue yourself. Seeing this kind of support in this kind of timeframe sadly let me lose all interest in Traefik.

**Comment by notsureifkevin** [comment] 2020-11-03 15:19
> So, ok, Docker, too, thinks it's unhealthy. Nevertheless, Traefik should let me be the judge about that and provide an option to ignore (potentially) faulty health checks.

@Philantrop I'm sorry about the misunderstanding. As this issue was submitted as a bug and instead looks like you're requesting a feature, the team decided to close it. The functionality you're encountering here is by design to allow Traefik to know the service's state before routing. If that's something you'd like to workaround, we can discuss that on our community forums built for end-user support.

**Comment by Philantrop** [comment] 2020-11-03 15:33
@notsureifkevin: Please take a look at my original post at the top (mind the dates as well, if you seriously want to understand) and then follow through this thread and you might understand my frustration about the support experience on several media (including your forums).

Not sure how I'm personally going to proceed here but it likely won't include Traefik in the long run. I think all has been said here so I'm going to stop responding now.
