### ISSUE TITLE
file provider doesn't work after upgrade to 2.3.0

### ISSUE THREAD

**Issue by braham2019** [traefik/traefik#7343] opened 2020-09-24 12:17 UTC
Bug

Upgraded to version 2.3

File provider does not work anymore.

I see this in the log file:
level=error msg="Cannot start the provider *file.Provider: /configuration/dyn-traefik.yml: field not found, node: domains"

Reverting back to 2.2.11 fixed the issue.
Am running docker-compose in Debian

**Comment by jbdoumenjou** [comment] 2020-09-24 13:19
Hello @braham2019 ,

Thanks for your interest in Traefik!

Since the Traefik v2.3.0-rc1, the file parsing is more strict and does not fail silently anymore.
Please double check your [file configuration](https://doc.traefik.io/traefik/v2.3/reference/dynamic-configuration/file/).

Duplicate of #7342

If you need more information on configuration, feel free to join the [community forum](https://community.traefik.io/).

**Closed by jbdoumenjou** 2020-09-24 13:19 UTC
Labels: status/0-needs-triage

**Comment by braham2019** [comment] 2020-09-24 13:45
you were absolutely right. thanks for the help
