### ISSUE TITLE
Traefik collects usage data without permission

### ISSUE THREAD

**Issue by mpeter50** [traefik/traefik#10007] opened 2023-07-03 19:07 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have this in the global section of the static configuration:
```
[global]
    checkNewVersion = false
    sendAnonymousUsage = false
```

### What did you see instead?

I see this in the logs:
```
time="2023-07-03T18:35:08Z" level=info msg="Stats collection is enabled."
time="2023-07-03T18:35:08Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
```

I have also seen #9598, and although it is similar, this is a different problem.
This is NOT a duplicate.

### What version of Traefik are you using?

Version:      2.10.3
Codename:     saintmarcelin
Go version:   go1.20.5
Built:        2023-06-19T16:18:54Z
OS/Arch:      linux/arm

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

I do not use command arguments.
The TOML static confiuration (at `/etc/traefik/traefik.toml`) contains the following:
```
[global]
    checkNewVersion = false
    sendAnonymousUsage = false

[pilot]
    dashboard = false

[log]
    #level = "warn"
    level = "debug"

[api]
    insecure = false
    dashboard = true

# Note: [endpoints] intentionally removed from the snippet I posted here

[providers]
    [providers.docker]
        exposedByDefault = false
        network = "t2-proxy"

    [providers.file]
        directory = "/etc/traefik/dynamicconf/"
        watch = true
```

Platform is Linux on ARM, as can be seen above.

### If applicable, please paste the log output in DEBUG level

```
2023-07-02T23:30:52.020891801+02:00 time="2023-07-02T21:30:52Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
2023-07-02T23:30:52.028534497+02:00 time="2023-07-02T21:30:52Z" level=warning msg="Traefik Pilot has been removed."
2023-07-03T20:35:08.799145662+02:00 time="2023-07-03T18:35:08Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
2023-07-03T20:35:08.800339402+02:00 time="2023-07-03T18:35:08Z" level=info msg="Traefik version 2.10.3 built on 2023-06-19T16:18:54Z"
2023-07-03T20:35:08.805571801+02:00 time="2023-07-03T18:35:08Z" level=debug msg="Static configuration loaded {\"global\":{\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{...},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"t2-proxy\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/etc/traefik/dynamicconf/\",\"watch\":true}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"debug\",\"format\":\"common\"},\"pilot\":{}}"
2023-07-03T20:35:08.805669596+02:00 time="2023-07-03T18:35:08Z" level=info msg="Stats collection is enabled."
2023-07-03T20:35:08.805692077+02:00 time="2023-07-03T18:35:08Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
2023-07-03T20:35:08.805712873+02:00 time="2023-07-03T18:35:08Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
2023-07-03T20:35:08.805736021+02:00 time="2023-07-03T18:35:08Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
2023-07-03T20:35:08.809294964+02:00 time="2023-07-03T18:35:08Z" level=warning msg="Traefik Pilot has been removed."
```

**Comment by ldez** [comment] 2023-07-03 23:40
Hello,

it's because you are using `pilot`.

You have to remove the pilot section.

duplicate of #9895, #9771, #9508

**Closed by ldez** 2023-07-03 23:40 UTC
Labels: kind/question

**Comment by mpeter50** [comment] 2023-07-03 23:45
I am **NOT** using pilot.
Pilot has been removed, or isn't it? And even the configuration tells to **not** use it.

There is zero reason why disabling a nonexistent component should somehow force-enable your data mining.

Please reopen the issue, as it has not been solved.

**Comment by ldez** [comment] 2023-07-03 23:48
Sorry but you are using pilot:
in your configuration:

```toml
[pilot]
    dashboard = false
```
in your logs:

> 2023-07-03T20:35:08.805571801+02:00 time="2023-07-03T18:35:08Z" level=debug msg="Static configuration loaded {\"global\":{\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{...},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"t2-proxy\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/etc/traefik/dynamicconf/\",\"watch\":true}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"debug\",\"format\":\"common\"},\"pilot\":{}}"
> ...
> 2023-07-03T20:35:08.809294964+02:00 time="2023-07-03T18:35:08Z" level=warning msg="Traefik Pilot has been removed."


You have to remove the pilot section of your configuration.
