### ISSUE TITLE
Support prometheus inside plugins

### ISSUE THREAD

**Issue by darkweak** [traefik/traefik#8711] opened 2022-01-19 08:55 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Træfik use the prometheus go client in the codebase https://github.com/traefik/traefik/blob/master/go.mod#L56. But this library depends on the unsafe library which is forbidden inside plugins. It would be great to let plugin creators to use the prometheus go client in their plugins to expose their own metrics.

Thanks in advance.

**Comment by rtribotte** [comment] 2022-01-19 13:53
Hello @darkweak,

Thanks for your interest in Traefik!

As per the description you are giving, it seems that this issue https://github.com/traefik/traefik/issues/8685 addresses the same need, so we will close this issue as a duplicate of https://github.com/traefik/traefik/issues/8685.

As a side note, regarding the usage of the `unsafe` package inside plugins, this has already been discussed in https://github.com/traefik/traefik/issues/7459, and as of now, the situation remains the same.

**Closed by rtribotte** 2022-01-19 13:53 UTC
Labels: status/0-needs-triage

**Comment by darkweak** [comment] 2022-01-19 14:14
That's not the same issue as #8685 because he wants to expose metrics on a specific endpoint for each plugin. My goal is to use prometheus with træfik through a plugin. 
The another issue you linked was about the opening of the unsafe usage and I understood that the Træfik team doesn't want to let users setup plugins using a third-party libraries that use the unsafe package. Here the situation is different because Træfik has this dependency in the codebase so I don't understand why you block developers that want to use the same libs as Træfik does.
