### ISSUE TITLE
Support Docker SwarmMode and Standalone Docker/Docker Compose Simultaneously

### ISSUE THREAD

**Issue by jawabuu** [traefik/traefik#6063] opened 2019-12-18 17:34 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Start traefik v2.0.4 in a single node docker swarm with
`docker stack deploy`
```yaml
version: '3.5'
networks:
  default:
    name: main
  traefik-net:
    name: traefik-net
    driver: overlay
    attachable: true
services:
  traefik:
    deploy:
      placement:
        constraints: [node.role==manager]
      update_config:
        delay: 60s
        monitor: 30s
        order: stop-first
        failure_action: rollback
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    image: "traefik:latest"
    env_file:
      - .env
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--log.level=DEBUG"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
Once running, I would like to deploy another container in the node using;
`docker run..`
or 
`docker-compose up..`
with labels so traefik can route traefik to it.

```yaml
version: "3.5"
networks:
  traefik-net:
    external: true
services:
  whoami:
    image: containous/whoami
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=HostRegexp(`whoami.${HOST}`)"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=HostRegexp(`whoami.${HOST`)"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
```

### What did you expect to see?
1. Dashboard accessible at http://dash.${HOST`)
2. Whoami accessible at http://whoami.${HOST`)

### What did you see instead?
1. Dashboard accessible at http://dash.${HOST`)
2. Whoami is not accessible at http://whoami.${HOST`)
No route is created

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.0.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
arguments
```yaml
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--log.level=DEBUG"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by g13013** [comment] 2019-12-18 17:52
that would be really useful

**Comment by jawabuu** [comment] 2019-12-18 18:13
> that would be really useful

Especially when deploying containers that require PRIVILEGED mode or other capabilities which docker swarm mode does not support.
VPN/Tunnelling containers are an example.

**Comment by mpl** [comment] 2019-12-20 16:54
@jawabuu I'm afraid we still don't fully grasp what you're trying to do. In particular, it seems to us that you're trying to run containers both in docker non-swarm mode and in swarm mode on the same host, which we think is not possible (because the docker daemon would not allow it).
Could you please clarify some more a precise use-case, or even better, give us a fully reproducible example?

**Comment by jawabuu** [comment] 2019-12-20 19:44
Hey @mpl 
It is entirely possible to run standalone containers in a docker swarm node/same host.
However, swarm-mode containers have a limitation when it comes to host capabilities i.e. Running as PRIVILEGED or a capability such as NET_ADMIN

Below is a scenario:
1.  Start traefik in swarm-mode to route traffic  to swarm-mode containers. This works as expected.
2. Start container(s) that require HOST privileges in non swarm-mode. One would still like to use Traefik to route traffic to these containers but this doesn't work.

Ultimately the goal is to have traefik docker provider support any docker container in the host.

You should be able to test with below compose files
https://github.com/containous/traefik/issues/6063#issue-539821452

**Comment by g13013** [comment] 2019-12-20 20:28
@mpl it is possible to run both, but I am not sure if traefik could access `local` networks when deployed in a `swarm` network and vis-ver-sa

**Comment by jawabuu** [comment] 2019-12-20 21:11
@g13013 I am attaching the container to an overlay network  that traefik is also connected to and specifying `traefik.docker.network`
The non swarm-mode containers are reachable from the traefik container

**Comment by g13013** [comment] 2019-12-21 12:03
@jawabuu if it's true, there is no reason to no support both

**Comment by mfisher87** [comment] 2019-12-31 04:02
Just to add another use case that tripped me up -- passing a device through (`--device` option on `docker run`) to a container is not supported by Docker Swarm, and that doesn't seem to be upcoming like the support for `--cap-add`. I think it may be a long time until all the reasons to mix and match swarm services with standalone containers go away.

I migrated a large number of stacks from compose to swarm and only after doing most of the work did I realize that some stacks which relied on those features would have to stay in compose. :( For now, I'm keeping the mix of standalone and swarm stacks and sidestepping Traefik to hit the standalone services directly at their exposed ports and that works fine. I could use a file provider to manually expose this container behind Traefik, I think.

This sounds like a complex problem for Traefik to solve, from a layman's perspective. Can Traefik running on a swarm manager see standalone containers running on worker nodes, or for that matter _any_ node other than its own? Or would that just magically work as long as the standalone container is attached to the correct network?

**Comment by jawabuu** [comment] 2020-01-23 12:25
Hey @juliens @g13013 
A workaround for this is to use the file provider as below
Start traefik with file provider enabled providing the file **dynamic-conf.yml** as a config
`docker stack deploy -c traefik.yml traefik`
**traefik.yml**
``` 
version: '3.5'
networks:
  default:
    name: main
  traefik-net:
    name: traefik-net
    driver: overlay
    attachable: true
 configs:
   traefik_conf_v1:
   file: ./dynamic-conf.yml
services:
  traefik:
    deploy:
      placement:
        constraints: [node.role==manager]
      update_config:
        delay: 60s
        monitor: 30s
        order: stop-first
        failure_action: rollback
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    image: "traefik:latest"
    env_file:
      - .env
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=dynamic-conf.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--log.level=DEBUG"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    configs:
      - source: traefik_conf_v1
        target: /dynamic-conf.yml
        mode: 444
```
**dynamic-conf.yml**
```
http:
  # Add the router
  routers:
    router-whoami:
      entryPoints:
      - web
      service: service-whoami
      rule:  "Host(`whoami.${HOST}`)"

  # Add the service
  services:
    service-whoami:
      loadBalancer:
        servers:
        - url: http://whoami:80
        passHostHeader: true
```
Start whoami container with `docker-compose up` making sure to connect to traefik network.
**docker-compose.yml**
``` 
version: "3.5"
networks:
  traefik-net:
    external: true
services:
  whoami:
    image: containous/whoami
    networks:
      - traefik-net
```
Dashboard is  accessible at http://dash.${HOST`)
Whoami is accessible at http://whoami.${HOST`)

A plus for this method is that container IPs  can be resolved using docker DNS.

**Comment by jawabuu** [comment] 2020-01-23 12:29
Incidentally this approach has me thinking whether it is possible to extend the flexibility of the file provider for other providers like docker.
I believe this has already been done in some form for Kubernetes in Traefik v2.1 with regard to mirroring.

**Comment by yamac-kurtulus** [comment] 2020-03-10 15:15
This could be especially valuable for Windows-native containers (although i assume 5 insane people work on it, one of them is me and i am spiraling down badly) since services using overlay networks cannot currently access services on host network (e.g. SQL server outside docker) because of some obscure reason. In this case it could be possible to allow some containers using host services to run as containers, using compose or `docker run` while also managing services on the swarm

**Comment by bd8392** [comment] 2020-03-31 13:59
I would also need this functionality and don't know how to implement....

**Comment by fireba11** [comment] 2020-06-18 05:34
I'm aware that is not supposed to be a common use case .. but here I am :-)
I think there are quite a few docker installations out there where swarm is enabled but only one node and people are deploying with "normal" compose on there too ;-)
So +1

**Comment by ibnesayeed** [comment] 2021-01-19 11:55
Currently, I am setting up a new single-node web server which will run a bunch of different containerized applications. I am still debating to myself, should I go with the Swarm-mode or local, because Traefik does not support mixed service discovery yet.

**Comment by Floeig** [comment] 2021-01-20 08:02
> Currently, I am setting up a new single-node web server which will run a bunch of different containerized applications. I am still debating to myself, should I go with the Swarm-mode or local, because Traefik does not support mixed service discovery yet.

I would say yes. You can use secrets and configs, and if you don't use theses your system will be ready the day you need another node.
The extra steps for docker-compose to swarm are little one by one but it would be a lot of work if one day you would like to migrate.

**Comment by rahendatri** [comment] 2021-03-26 14:09
Hello,
I encounter the same need for a use case that uses Docker in Swarm Mode and Standalone mode within the same machine(s). As far as I understand this is not yet supported and this is the goal of this issue.
This goes back to December 2019 and I believe that lots of people would be glad to have this supporting feature.
Could anybody explain the current state of this issue, please ?
Feel free if you need any help.
Thanks in advance.

**Comment by jawabuu** [comment] 2021-03-26 14:20
Hey @rahendatri 
You can try using this workaround at the moment
https://github.com/traefik/traefik/issues/6063#issuecomment-577659646

**Comment by rahendatri** [comment] 2021-03-26 16:40
Hello @jawabuu Thank you for this tips. I looked at it but I am afraid that this would not be easily scalable for the following reason :
It seems that the method implies a "static" configuration of services deployed on Standalone mode. For example, if one wants to deploy a new service called `whoami1`, he will also have to modify `dynamic-config.yml ` (to add the new service) then redeploy the traefik stack to "reload" the newly modified `dynamic-config.yml`.
Do you confirm this ?
(I don't know whether Docker Config propagates natively file modifications like in Docker Volume).

Thanks in advance for your response.

**Comment by jahegu** [comment] 2021-08-07 12:34
I'm on the same case. I think that the best workarround would be to support more than a single provider of each type. This allow to keep a first instance with swarmMode 'true' and another without it or, why not, from another different host.

**Comment by jonathantullett** [comment] 2021-08-09 08:42
Another request for this functionality. Deploying with some containers with swarm and others stand-alone is definitely a use case I've seen many times.

**Comment by diogosalazar** [comment] 2022-01-01 20:01
Just to echo what others are saying, Docker Swarm's lack of support for privileged mode and inability to bind devices (`--device`) makes it so that I can't host containers such as `Octoprint` for my 3D printer using Swarm, so I have to resort to deploying it to a Docker Swarm node directly, in a non-Swarm way. It would be great for Traefik to be able to listen for these deployments and process labels/routes/etc automatically.

**Comment by antran22** [comment] 2022-02-18 06:19
Hello, I am currently needing this use case and would very much like to make it happens.
My current setup is a 2-node docker swarm cluster, and sometime I want to create a `docker-compose` application on one node and have Traefik on the other node pick it up.
I was investigating the output of `docker node ps` and I found out that it's not listing standalone container on other nodes, therefore I suspect Traefik might not be able to pick up standalone containers and configure it properly. I might be wrong, because Traefik might be listening on new container on another API.
Can we get the `docker swarm` team to work on this? Is this functionality feasible?

**Comment by an0t8** [comment] 2022-02-23 03:11
Wow.  I just spent a ton of time swapping over about 15 swarms services to traefik from nginx.  The last one to go is my lone standalone service, which needs a --device attribute.   To find that this is in no way supported, or apparently even planed to be supported is a huge letdown.  Either I have to use some insane docker udev workaround to tell my host to add the device every time, or I have to rewrite all my docker provider rules for the file provider and go back to having ansible dump this configuration in my traefik folder, just like I was doing with nginx.  It totally invalidates the reason I was moving to traefik in the first place.  Very dissapointed.  I wish I had started with that container first...

**Comment by jawabuu** [comment] 2022-02-23 04:41
@an0t8  try this for now
https://github.com/traefik/traefik/issues/6063#issuecomment-577659646

**Comment by EdgarSedov** [comment] 2022-06-05 00:18
Sorry for maybe a stupid question, i haven't looked into code throughtly, but can't we just have 2 clients working in parrallel?
https://github.com/traefik/traefik/blob/3bf4a8fbe24a2ee8f9cf9999efad6f042440545e/pkg/provider/docker/docker.go#L216

If someone from core developers could comment on this that would be amazing. Traefik is awesome and i would really like to do that i can to make it better

**Comment by jawabuu** [comment] 2022-06-05 05:40
> Sorry for maybe a stupid question, i haven't looked into code throughtly, but can't we just have 2 clients working in parrallel?
> 
> https://github.com/traefik/traefik/blob/3bf4a8fbe24a2ee8f9cf9999efad6f042440545e/pkg/provider/docker/docker.go#L203-L228
> 
> If someone from core developers could comment on this that would be amazing. Traefik is awesome and i would really like to do that i can to make it better

@ldez Does this make sense?

**Comment by ldez** [comment] 2022-06-05 12:13
If we introduce a way to manage Docker and Docker Swarm at the same time, it will be by adding a multi-providers system.
It cannot be done inside the Docker provider because you can have 2 different configurations between your Docker and Docker Swarm.

**Comment by EdgarSedov** [comment] 2022-06-06 09:15
> If we introduce a way to manage Docker and Docker Swarm at the same time, it will be by adding a multi-providers system. It cannot be done inside the Docker provider because you can have 2 different configurations between your Docker and Docker Swarm.
> 
> The support of multi-providers is niche and Traefik is focused on the "90% of the use-cases" because more possibilities mean less simplicity. In this context, for now, I will recommend using 2 Traefik instances.

@ldez Thank you very much for the feedback. Sorry for taking a piece of your time, but could you please answer another couple of questions?)
1. First of all, thanks for your product. traefik is awesome) Can u please explain a bit further or maybe provide a ref for routing configuration on using 2 traefik instances? If i understood you correctly, only primary will be listening on 80/443, and secondary will be registered throught labels as "catch default when no others matched", is that correct? I'm kinda not sure how this will work with other settings, so example configuraton would be much appreciated (like should they have exact configuration expect providers or..)
2. Is there a possibility of just separating them like different providers: for example as docker.go and docker_swarm.go? Or there're internal implementation issues with that?

**Comment by DeoLeung** [comment] 2022-06-14 06:39
we are running compose on each machine, currently we use one traefik on each machine, and have an entry traefik loadbalance to the per machine traefiks.

the problem is the machine traefik knows the scale of the service, but the entry one don't. we are now manually set it for the entry traefik, however it will be great if we could have some "multiple provider" solution to auto discover it.

**Comment by ddtmachado** [comment] 2022-06-14 18:09
Hey everyone, we're unifying similar requests into a new [proposal for multiple providers](https://github.com/traefik/traefik/issues/9101), which as stated in [this comment](https://github.com/traefik/traefik/issues/6063#issuecomment-1146793755) would also solve this use case. 
Feel free to track that one from now on and don't hesitate to add your input and feedback there.

**Closed by ddtmachado** 2022-06-14 18:09 UTC
Labels: kind/enhancement, area/provider/docker, priority/P3, area/provider/docker/swarm
