### ISSUE TITLE
Traefik 2.11 file provider fails with ReadDirectoryChanges error

### ISSUE THREAD

**Issue by michaellwest** [traefik/traefik#11059] opened 2024-08-30 15:43 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgraded from traefik v2.9 to v2.11

I have two yml files in a dynamic configuration directory.

### What did you see instead?

Traefik reports an error exactly as that documented in #10562 .

I'm able to overcome the issue by switching the file provider from `"--providers.file.directory=C:/etc/traefik/config/dynamic/"` to `"--providers.file.filename=C:/etc/traefik/config/dynamic/combined.yaml"`.

Alternately, I was able to set the file watch to false.

**Note:** I would have reopened the former issue but it closed a few days ago.

### What version of Traefik are you using?

traefik:v2.11-windowsservercore-1809

### What is your environment & configuration?

traefik\config\dynamic\certs_config.yaml
```yaml
tls:
  certificates:
    - certFile: C:\etc\traefik\certs\devcert.cer
      keyFile: C:\etc\traefik\certs\devcert.key
```

traefik\config\dynamic\global_config.yaml
```yaml
http:
  middlewares:
    security-headers:
      headers: 
        forceSTSHeader: true
        stsSeconds: 31536000
```

```yaml
services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    hostname: traefik
    command:
      - "--ping"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=npipe:////./pipe/docker_engine"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=C:/etc/traefik/config/dynamic/"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "443:443"
      - "8079:8080"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
    volumes:
      - source: \\.\pipe\docker_engine\
        target: \\.\pipe\docker_engine\
        type: npipe
      - ./docker/traefik:C:/etc/traefik
```

### If applicable, please paste the log output in DEBUG level

```
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="Configuration loaded from flags."
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="Traefik version 2.11.8 built on 2024-08-06T13:14:05Z"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\"websecure\",\"scheme\":\"https\",\"permanent\":true,\"priority\":9223372036854775806}}},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"npipe:////./pipe/docker_engine\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"C:/etc/traefik/config/dynamic/\",\"watch\":true}},\"api\":{\"insecure\":true,\"dashboard\":true},\"ping\":{\"entryPoint\":\"traefik\",\"terminatingStatusCode\":503},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="Starting TCP Server" entryPointName=websecure
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="Starting TCP Server" entryPointName=web
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="Starting TCP Server" entryPointName=traefik
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="Starting provider *file.Provider"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="*file.Provider provider configuration: {\"directory\":\"C:/etc/traefik/config/dynamic/\",\"watch\":true}"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="add watcher on: C:/etc/traefik/config/dynamic/"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="add watcher on: C:/etc/traefik/config/dynamic/certs_config.yaml"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="add watcher on: C:/etc/traefik/config/dynamic/global_config.yaml"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=error msg="Cannot start the provider *file.Provider: error adding file watcher: ReadDirectoryChanges: The I/O operation has been aborted because of either a thread exit or an application request."
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="Starting provider *traefik.Provider"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="*traefik.Provider provider configuration: {}"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":9223372036854775806},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":9223372036854775805},\"ping\":{\"entryPoints\":[\"traefik\"],\"service\":\"ping@internal\",\"rule\":\"PathPrefix(`/ping`)\",\"priority\":9223372036854775807},\"web-to-websecure\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"redirect-web-to-websecure\"],\"service\":\"noop@internal\",\"rule\":\"HostRegexp(`{host:.+}`)\",\"priority\":9223372036854775806}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{},\"ping\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}},\"redirect-web-to-websecure\":{\"redirectScheme\":{\"scheme\":\"https\",\"port\":\"443\",\"permanent\":true}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=internal
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="Starting provider *docker.Provider"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"npipe:////./pipe/docker_engine\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {}"
2024-08-30 10:47:16 time="2024-08-30T10:47:16-05:00" level=debug msg="Provider connection established with docker 27.1.1 (API 1.46)" providerName=docker
```

**Comment by michaellwest** [comment] 2024-08-30 16:43
Problem seems to resolve when you disable the watcher:

`- "--providers.file.watch=false"`

```
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=info msg="Configuration loaded from flags."
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=info msg="Traefik version 2.11.8 built on 2024-08-06T13:14:05Z"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\"websecure\",\"scheme\":\"https\",\"permanent\":true,\"priority\":9223372036854775806}}},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"npipe:////./pipe/docker_engine\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"C:/etc/traefik/config/dynamic/\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"ping\":{\"entryPoint\":\"traefik\",\"terminatingStatusCode\":503},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=debug msg="Starting TCP Server" entryPointName=websecure
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=debug msg="Starting TCP Server" entryPointName=web
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=debug msg="Starting TCP Server" entryPointName=traefik
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=info msg="Starting provider *file.Provider"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=debug msg="*file.Provider provider configuration: {\"directory\":\"C:/etc/traefik/config/dynamic/\"}"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=info msg="Starting provider *traefik.Provider"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=debug msg="*traefik.Provider provider configuration: {}"
2024-08-30 11:40:58 time="2024-08-30T11:40:58-05:00" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":9223372036854775806},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":9223372036854775805},\"ping\":{\"entryPoints\":[\"traefik\"],\"service\":\"ping@internal\",\"rule\":\"PathPrefix(`/ping`)\",\"priority\":9223372036854775807},\"web-to-websecure\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"redirect-web-to-websecure\"],\"service\":\"noop@internal\",\"rule\":\"HostRegexp(`{host:.+}`)\",\"priority\":9223372036854775806}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{},\"ping\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}},\"redirect-web-to-websecure\":{\"redirectScheme\":{\"scheme\":\"https\",\"port\":\"443\",\"permanent\":true}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=internal
```

**Comment by nmengin** [comment] 2024-09-02 12:44
Hey @michaellwest,

Thanks for reaching out.

If any community member can help us find verified steps to reproduce and fix the issue if possible, we would love the help.

**Comment by arp-mbender** [comment] 2024-09-13 11:42
@nmengin 
While an unrelated issue, I've had the same problem when creating a sample docker project used to showcase and reproduce the issue described here: https://github.com/traefik/traefik/issues/11037

This is the sample project:
https://github.com/arp-mbender/win-auth-traefik

If you remove the `- "--providers.file.watch=false"` flag from the configuration then the error is reproduced.

**Comment by anantsaraswat** [comment] 2024-10-24 10:23
@nmengin - If you mount a directory with a **symlink** that is not present on the Traefik container, it will fail with "--providers.file.watch=true", It used to work fine until Traefik2.10.

### Example: 

[providers]
  [providers.file]
    watch = true
    directory = "/certs"
    debugLogGeneratedTemplate = true

and if you mount "/etc/pki/tls/certs" from the host to the traefik container, it will fail, As `/etc/pki/tls/certs` have two symlinks of ca-bundle.crt and ca-bundle.trust.crt, which points to some other directory, which is not present in traefik container.

**Comment by emilevauge** [comment] 2024-10-24 13:00
Duplicate of https://github.com/traefik/traefik/issues/10573

**Closed by emilevauge** 2024-10-24 13:00 UTC
Labels: kind/bug/possible, area/provider/file, contributor/wanted

**Comment by michaellwest** [comment] 2024-10-24 13:14
Do you intend to reopen this issue?

**Comment by michaellwest** [comment] 2024-10-24 13:15
Do you intend to reopen this issue?

**Comment by emilevauge** [comment] 2024-10-24 13:18
As it's a duplicate of #10573, we will close this one.
