### ISSUE TITLE
IngressRoute subset not found for kube-system/kubernetes-dashboard

### ISSUE THREAD

**Issue by jwausle** [traefik/traefik#6821] opened 2020-05-18 15:25 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

* installed traefik2 with helm from here [traefik-helm-chart](https://github.com/containous/traefik-helm-chart) (namespace:kube-system)
* check: IngressRoute successful installed
* check: IngressRoute traefik-dashboard is routable 
* try to install kubernetes dashboard with helm from here 
 [kubernetes-dashboard chart](https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard) (namespace:kube-system)
* apply this ingressRoute 

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name:  kubernetes-dashboard
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/ui`)
    kind: Rule
    middlewares:
    - name: strip-ui
    services:
    - name:  kubernetes-dashboard
      port: 443

----
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-ui
spec:
  stripPrefix:
    prefixes:
      - "/ui"
      - "/ui/"
``` 

> Try browsing of 'MY_IP/ui' 

```
# kubectl logs traefik-pod -f
level=error msg="subset not found for kube-system/kubernetes-dashboard" providerName=kubernetescrd ingress=kubernetes-dashboard namespace=kube-system
```

### What did you expect to see?

Dashboard UI in browser

### What did you see instead?

* `Internal Server Error` in browser

### Output of `traefik version`: version:2

```
# traefik pod log
level=error msg="subset not found for kube-system/kubernetes-dashboard" providerName=kubernetescrd ingress=kubernetes-dashboard namespace=kube-system` in the traefik pod log
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# No toml 
# - thats my helm command `helm upgrade --install kubernetes-dashboard stable/kubernetes-dashboard -n kube-system --set enableInsecureLogin=true`
# - check Vagrant sample below for details
```

* [k3s](https://rancher.com/docs/k3s/latest/en/installation/install-options/) as single host kubernetes without default traefik1
* [helm3](https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3) installed
* host system:  debian10 

<details>
<summary>
Vagrant sample
</summary>

<pre>
# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/bionic64"

  config.vm.box = "debian/buster64"
  config.vm.box_version = "10.3.0"

  config.vm.network "private_network", ip: "172.28.129.23"
  #config.vm.network "private_network", type: "dhcp"
  #config.vm.network "public_network", bridge: "en0: WLAN (AirPort)"

  config.vm.synced_folder ".", "/usr/share/whoami-charts"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 1
   end

  config.vm.provision "shell", inline: <<SHELL
  # To prevent `k3s check-config`
  # /usr/sbin iptables v1.8.2 (nf_tables): should be older than v1.8.0 or in legacy mode (fail)
  update-alternatives --set iptables /usr/sbin/iptables-legacy

  apt-get update

  # install curl - if not exist
  # - https://www.cyberciti.biz/faq/howto-install-curl-command-on-debian-linux-using-apt-get/
  if ! curl --version > /dev/null ; then
    apt --yes install curl
  else
    echo ">> Command 'curl' already installed."
  fi

  # install k3s - if not exist (without default  traefik v1)
  # - https://rancher.com/docs/k3s/latest/en/installation/install-options/
  # - without default traefik - https://github.com/rancher/k3s/issues/1160
  if ! k3s -v > /dev/null ; then
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --no-deploy traefik" sh -
  else
    echo ">> Command 'k3s' already installed."
  fi

  # install helm - if not exist
  if ! helm version > /dev/null ; then
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /home/vagrant/.bashrc
    echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /root/.bashrc
  else
    echo ">> Command 'helm' already installed."
  fi

  # Ensure that traefik(v2) is deployed
  # - https://github.com/containous/traefik-helm-chart/tree/master
  # - https://docs.traefik.io/user-guides/crd-acme/ (traefik-doc: +1)
  helm repo add traefik https://containous.github.io/traefik-helm-chart
  helm repo update
  helm upgrade --install traefik traefik/traefik --namespace kube-system --set additionalArguments={--log.level=DEBUG}

  # Bind traefik /dashboard and /api on entryPoint:web
  cat << 'EOF' >> /tmp/traefik-dashboard.yaml
   # traefik-dashboard.yaml
   apiVersion: traefik.containo.us/v1alpha1
   kind: IngressRoute
   metadata:
    name: traefik-dashboard
   spec:
    entryPoints:
      - web
    routes:
      - match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
        kind: Rule
        services:
          - name: api@internal
            kind: TraefikService
EOF

  kubectl delete IngressRoute -n kube-system traefik-dashboard
  kubectl apply -f /tmp/traefik-dashboard.yaml

  helm repo add stable https://kubernetes-charts.storage.googleapis.com
  helm repo update
  helm upgrade --install kubernetes-dashboard stable/kubernetes-dashboard -n kube-system --set enableInsecureLogin=true
  
  cat << 'EOF' >> /tmp/kubernetes-dashboard-ingressroute.yaml
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name:  kubernetes-dashboard
    spec:
      entryPoints:
        - web
      routes:
      - match: PathPrefix(`/ui`)
        kind: Rule
        middlewares:
        - name: strip-ui
        services:
        - name:  kubernetes-dashboard
          port: 443
EOF

  kubectl apply -f /tmp/kubernetes-dashboard-ingressroute.yaml -n kube-system

  cat << 'EOF' >> /tmp/kubernetes-dashboard-middleware.yaml
    apiVersion: traefik.containo.us/v1alpha1
    kind: Middleware
    metadata:
      name: strip-ui
    spec:
      stripPrefix:
        prefixes:
          - "/ui"
          - "/ui/"
EOF

  kubectl apply -f /tmp/kubernetes-dashboard-middleware.yaml -n kube-system
SHELL
end
</pre>
</details>

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-05-19T09:46:44Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
time="2020-05-19T09:46:44Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Connection\":[\"keep-alive\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36\"],\"X-Forwarded-Host\":[\"172.28.129.23\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Prefix\":[\"/ui\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-7697b4bb9c-qxfv8\"],\"X-Real-Ip\":[\"10.42.0.14\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"172.28.129.23\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.42.0.14:56382\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-05-19T09:46:44Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Connection\":[\"keep-alive\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36\"],\"X-Forwarded-Host\":[\"172.28.129.23\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Prefix\":[\"/ui\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-7697b4bb9c-qxfv8\"],\"X-Real-Ip\":[\"10.42.0.14\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"172.28.129.23\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.42.0.14:56382\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="https://10.42.0.18:9090"
time="2020-05-19T09:46:44Z" level=debug msg="'500 Internal Server Error' caused by: tls: first record does not look like a TLS handshake"
time="2020-05-19T09:46:44Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Connection\":[\"keep-alive\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36\"],\"X-Forwarded-Host\":[\"172.28.129.23\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Prefix\":[\"/ui\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-7697b4bb9c-qxfv8\"],\"X-Real-Ip\":[\"10.42.0.14\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"172.28.129.23\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.42.0.14:56382\",\"RequestURI\":\"/\",\"TLS\":null}"
```

**Comment by Overbryd** [comment] 2020-08-20 14:32
I have the same problem.
Logs filling up with:

```
time="2020-08-20T14:17:09Z" level=error msg="endpoints not found for default/<redacted>-staging" providerName=kubernetescrd ingress=<redacted>-api namespace=default
```

However:

* Traefik Dashboard shows the service with the correct Pod IP
* The service is alive and well
* The IngressRoute is properly configured

I have added yet another IngressRoute, for the same service on another Domain. That one worked.
We have about 50+ HTTP Routers, and we expect to add more. Hopefully this does not manifest itself as a serious bug.

**Comment by Overbryd** [comment] 2020-08-24 07:25
@ddtmachado thanks for jumping in on this.

We are running Kubernetes`v.1.14.10-gke.42` here.
The service + endpoint is present (outputs are pasted below).
To give some context to the outputs below, the ingressroute in question is `nis-ng-staging`, pointing to service `nis-ng-staging`.

* The YAML-output of the ingressroute itself is also pasted below.
* It is redacted, but I left the necessary labels in place.
* A `curl` request inside the cluster to `http://nis-ng-staging.default.svc.cluster.local/` works just fine.

<details>
  <summary>kubectl get svc</summary>
<pre>
NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                       AGE
redacted                    ClusterIP      10.210.248.205   <none>           80/TCP                        11d
redacted                    ClusterIP      10.210.245.221   <none>           80/TCP                        12d
redacted                    ClusterIP      10.210.250.97    <none>           80/TCP                        11d
redacted                    ClusterIP      10.210.246.49    <none>           80/TCP                        12d
redacted                    ClusterIP      10.210.252.167   <none>           9402/TCP                      39d
redacted                    ClusterIP      10.210.240.187   <none>           443/TCP                       39d
redacted                    ClusterIP      10.210.255.74    <none>           80/TCP                        16d
redacted                    ClusterIP      10.210.255.76    <none>           80/TCP                        17d
redacted                    ClusterIP      10.210.240.1     <none>           443/TCP                       2y220d
redacted                    ClusterIP      10.210.254.161   <none>           80/TCP                        11d
redacted                    ClusterIP      10.210.247.122   <none>           80/TCP                        11d
redacted                    ClusterIP      10.210.246.182   <none>           80/TCP                        9d
redacted                    ClusterIP      10.210.248.155   <none>           80/TCP                        9d
nis-ng-production           ClusterIP      10.210.253.193   <none>           80/TCP                        3d16h
nis-ng-staging              ClusterIP      10.210.246.224   <none>           80/TCP                        3d16h
redacted                    ClusterIP      10.210.241.189   <none>           15672/TCP,5672/TCP,4369/TCP   18d
redacted                    ClusterIP      None             <none>           15672/TCP,5672/TCP,4369/TCP   18d
redacted                    LoadBalancer   10.210.243.40    redacted         80:32080/TCP,443:32443/TCP    66d
redacted                    ClusterIP      10.210.254.109   <none>           80/TCP                        11d
redacted                    ClusterIP      10.210.240.164   <none>           80/TCP                        11d
redacted                    ClusterIP      10.210.240.164   <none>           80/TCP                        11d
</pre>
</details>

<details>
  <summary>kubectl get endpoints -n default</summary>
<pre>
NAME                        ENDPOINTS                                                           AGE
redacted                    10.210.3.20:4030,10.210.4.227:4030                                  11d
redacted                    10.210.1.141:4030,10.210.5.142:4030                                 12d
redacted                    10.210.5.136:4000                                                   11d
redacted                    10.210.5.143:4000                                                   12d
redacted                    10.210.2.240:9402                                                   39d
redacted                    10.210.3.181:10250                                                  39d
redacted                    10.210.2.79:9000,10.210.4.225:9000                                  16d
redacted                    10.210.4.233:9000                                                   17d
redacted                    redacted:443                                                        2y220d
redacted                    10.210.1.137:80,10.210.5.139:80                                     11d
redacted                    10.210.5.140:80                                                     11d
redacted                    10.210.1.140:80,10.210.2.81:80                                      9d
redacted                    10.210.4.232:80                                                     9d
nis-ng-production                                                                               3d16h
nis-ng-staging              10.210.2.78:6025                                                    3d16h
redacted                    10.210.1.35:4369,10.210.2.19:4369,10.210.4.8:4369 + 6 more...       18d
redacted                    10.210.1.35:4369,10.210.2.19:4369,10.210.4.8:4369 + 6 more...       18d
redacted                    10.210.1.127:8000,10.210.5.133:8000,10.210.1.127:8443 + 1 more...   66d
redacted                    10.210.1.100:9000,10.210.5.52:9000                                  11d
redacted                    10.210.1.116:9000                                                   11d
</pre>
</details>

<details>
  <summary>kubectl get ingressroute</summary>
<pre>
NAME                       AGE
redacted                   39d
redacted-api               3d16h
redacted-staging           39d
redacted-staging-api       39d
default                    39d
</pre>
</details>

<details>
  <summary>kubectl get ingressroute redacted-api</summary>
<pre>
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  creationTimestamp: "2020-08-20T14:51:46Z"
  generation: 4
  name: redacted-api
  namespace: default
  resourceVersion: "289972436"
  selfLink: /apis/traefik.containo.us/v1alpha1/namespaces/default/ingressroutes/redacted-api
  uid: ab7db77d-e2f4-11ea-b8da-42010a800062
spec:
  routes:
  - kind: Rule
    match: Host(`redacted.host.com`)
    middlewares:
    - name: cors
    priority: 1
    services:
    - kind: Service
      name: redacted
      namespace: default
      port: 80
  - kind: Rule
    match: |
      Host(`redacted.host.com`) && PathPrefix(`/redacted/path`)
    middlewares:
    - name: cors
    - name: strip-prefix-level1
    services:
    - kind: Service
      name: redacted
      namespace: default
      port: 80
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-prefix-level1
    services:
    - kind: Service
      name: redacted
      namespace: default
      port: 80
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 6020
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 6020
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5030
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5030
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5070
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5070
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5060
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5060
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5060
  - kind: Rule
    match: Host(`redacted.host.com`) && (PathPrefix(`/redacted/path`) || PathPrefix(`/redacted/path`))
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: redacted
      namespace: microservices
      port: 5060
  - kind: Rule
    match: Host(`redacted.host.com`) && PathPrefix(`/nis-ng`)
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: nis-ng-production
      namespace: default
      port: 80
  - kind: Rule
    match: Host(`redacted.host.com`) && PathPrefix(`/dev/nis-ng`)
    middlewares:
    - name: cors
    - name: strip-api-prefixes
    services:
    - kind: Service
      name: nis-ng-staging
      namespace: default
      port: 80
  tls:
    secretName: redacted-wildcard
</pre>
</summary>

**Comment by ddtmachado** [comment] 2020-09-01 00:01
@Overbryd After some more testing it looks to me that the issue comes from an old [caching bug](https://github.com/kubernetes/kubernetes/issues/47711) in Kubernetes that was recently [fixed and merged](https://github.com/kubernetes/kubernetes/pull/93030) 

It was really hard to reproduce so far, very inconsistent for me, but I plan to give a go at k8s v1.19, which contains this fix, and see if it would still appear eventually or if its completely gone. 

Please give it a go as well if you can and let us know.

**Comment by Overbryd** [comment] 2020-09-03 11:42
@ddtmachado thanks for looking into it.

Can you update me on how to debugged this? I am myself developing against the Kubernetes API and was not aware of this bug. Some hints on this matter are highly appreciated.

I am sorry to not be able to give more for a reproducible case for that bug.
Do you think there is a workaround in the meantime?

Otherwise I think we can plan an upgrade of the Kubernetes version, but that will definitely take some more time on our side. But I keep track of this, and will let you know if it got resolved when updating the K8s version.

If you have the time to do some more tests on your side, I appreciate an update as well.

Thanks!

**Comment by Overbryd** [comment] 2020-09-03 11:55
@ddtmachado futhermore, what is still puzzling me about this issue, is that fact that the service works for one route, but not the other.

Does not work:

```
  - kind: Rule
    match: Host(`redacted`) && PathPrefix(`/dev/nis-ng`)
    middlewares:
    - name: cors-all
    - name: strip-api-prefixes
    services:
    - {kind: Service, port: 80, namespace: default, name: nis-ng-staging}
```

Works:

```
  - kind: Rule
    match: Host(`redacted`) && PathPrefix(`/nis-ng`)
    middlewares:
    - name: cors-all
    - name: strip-prefix-level1
    services:
    - {kind: Service, port: 80, namespace: default, name: nis-ng-staging}
```

**Comment by AndrewSav** [comment] 2020-09-03 21:05
> Do you think there is a workaround in the meantime?

It was mentioned in several places in the linked thread that deleting and re-creating the kuberntes service clears up the caching issue. If that does not work for you, then perhaps your issue caused by a still unidentified reason.

**Comment by Overbryd** [comment] 2020-09-03 21:19
@AndrewSav right. Thanks for pointing that out. I forgot to tell that afroimentioned workarounds did not work for the case I was working on here.

But good news (at least for this bug ticket). After going through all the routes that were present in the system, and mapping them all out, I found the culprit, and hereby can confirm that the issue is no longer reproducible in our traefik installation.
It was a routing priority issue. *facepalm

**Comment by tinyzimmer** [comment] 2020-09-06 11:21
For whatever it's worth, I'm running into this exact error on EKS 1.17 right now.

Priorities all checkout, endpoints are all there, tried deleting and re-creating the services, no dice.

**Comment by tardich** [comment] 2020-09-16 12:45
Got the same issue on my side. Kubernetes 1.18.8, Calico CNI, Traefik 2.2.8 installed with Helm (from official repo). Everything looks good other than...  it doesn't work. The dashboard reports my services correctly but the ingresses (kubernetes ingress) do not seem to route correctly. Everything appear as `404 page not found`. No mather if I try to reach a real service, or anything that would point to the traefik IP (even services not yet installed)

**Comment by tardich** [comment] 2020-09-17 00:34
Got my answer.....  in the docs. To make my ingress correctly "translated" for Traefik v2.2+, I need to add these into the ingress annotations section:

```
traefik.ingress.kubernetes.io/router.entrypoints: websecure
traefik.ingress.kubernetes.io/router.tls: "true"
```

**Comment by AndrewSav** [comment] 2020-09-17 21:19
@tardich if you do not have "subset not found" in the logs, your issues is not related. 404 simply means that no router matched incoming url, as you discovered - a configuration error. Consider posting on the [community forums](https://community.containo.us/) next time you need help configuring traefik.

**Comment by rdxmb** [comment] 2020-10-20 09:28
I also have this issue on

- `k3s version v1.18.9+k3s1 (630bebf9)`
- traefik 2.2.0 (first traefik 2.2.11, then downgraded to see if it helps - did not help)

Deleteing and recreating the ingressroutes and services did not help.

I have to tell that I have the same project deployed on kubernetes initiated with kubeadm

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

and it is working there.

**Comment by AndrewSav** [comment] 2020-10-20 23:00
@rdxmb the most common cause for this error (which has nothing to do with this issue) is not having endpoints on your services. You should check this first.

**Comment by rdxmb** [comment] 2020-10-22 10:38
@AndrewSav Seems this was not an endpoint-problem,  but a roblem with too little memory - although the pods and services were present. Increasing the memory solved my problem, sorry for spaming this issue...

**Comment by nustiueudinastea** [comment] 2020-11-03 20:52
I have the same issue:
```
time="2020-11-03T20:34:49Z" level=error msg="Cannot create service: subset not found" namespace=test providerName=kubernetes serviceName=test1 ingress=test1 servicePort=80
```

I am running traefik 2.3.1 installed via the latest helm chart I could find. This is on K8s 1.19.2. For the record, the ingresses work as expected, I just see that error printed for all the ingresses in the namespace every time a new ingress is created.

**Comment by ddtmachado** [comment] 2020-11-03 21:16
@nustiueudinastea it is normal to see this message upon creation of a new ingress, as Traefik is watching for the endpoints and they may not be ready or created yet by Kubernetes

**Comment by nustiueudinastea** [comment] 2020-11-03 21:21
@ddtmachado got it, thanks! Is there a way to get traefik to not log those lines? Since it is expected that traefik will not see the service ready for a while, maybe the error should suppressed for the first couple of times or X seconds.

**Comment by ddtmachado** [comment] 2020-11-04 16:40
@nustiueudinastea unfortunately not, at the moment this particular log is considered an error as it may be related to a real issue if something is wrong in the environment. But feel free to submit your suggestions into a new feature / improvement request issue.

**Comment by SantoDE** [comment] 2020-11-06 14:44
Hey all, 

as @ddtmachado pointed out, this is not a direct traefik bug and thus, Ill close that issue.

As he also pointed out, if you have further suggestions feel free to raise a new issue :)

**Closed by SantoDE** 2020-11-06 14:44 UTC
Labels: area/provider/k8s/crd, kind/bug/possible

**Comment by pvcnt** [comment] 2020-11-30 22:21
Hello, what is the tl;dr around this bug? Was it caused because of the Kubernetes caching issue? I have exactly the same problem, it happens quite often actually, and prevents me from accessing my service (that is other healthy, and has endpoints).

**Comment by ivorscott** [comment] 2020-12-30 16:12
@pvcnt I fixed this by cleaning up disk usage on my machine. I'm using Docker Desktop. [https://docs.docker.com/docker-for-mac/space/](https://docs.docker.com/docker-for-mac/space/)

**Comment by kagodarog** [comment] 2021-01-18 20:41
> Got my answer..... in the docs. To make my ingress correctly "translated" for Traefik v2.2+, I need to add these into the ingress annotations section:
> 
> ```
> traefik.ingress.kubernetes.io/router.entrypoints: websecure
> traefik.ingress.kubernetes.io/router.tls: "true"
> ```
This resolves my issue  "Cannot create service: subset not found"
