### ISSUE TITLE
Lost file on POST with multipart/form-data request through RedirectScheme middleware

### ISSUE THREAD

**Issue by e7d** [traefik/traefik#8125] opened 2021-05-06 15:37 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Issuing a POST request with multipart/form-data content type, containing to an image file, to an HTTP endpoint, then forwarded to another HTTPS endpoint through the RedirectScheme middleware, using a catch all rule.

### What did you expect to see?

The original request to arrive as-is (with the file untouched) on the final HTTPS endpoint.

### What did you see instead?

The original request arrived on the final HTTPS endpoint, but without the file if it exceeds a minimum size. The exact minimum size is not clear at this time. We're still experiencing on this aspect and will add information on that later.
The smallest lost file we experienced was a 275KB one.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
# traefik version
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[accessLog]

[api]
  insecure = true
  dashboard = true

[certificatesResolvers.le.acme]
  email = "***@***.***"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.le.acme.dnsChallenge]
    provider = "***"
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[http.middlewares]
  [http.middlewares.allow-cors.headers]
    [http.middlewares.allow-cors.headers.customRequestHeaders]
      accessControlAllowOrigin = "*"
  [http.middlewares.force-https.redirectScheme]
    permanent = true
    scheme = "https"

[log]
  level = "DEBUG"

[providers]
  [providers.docker]
    exposedByDefault = false
    network = "traefik"
  [providers.file]
    directory = "/etc/traefik"
    watch = true
```

Our docker-compose config file:
```yaml
version: "3.3"

services:
    traefik:
        container_name: traefik
        image: traefik:2.4
        restart: unless-stopped
        environment:
            - ***_API_KEY_FILE=/run/secrets/***_api_key
        labels:
            - traefik.docker.network=traefik
            - traefik.enable=true
            - traefik.http.routers.https-redirect.entrypoints=web
            - traefik.http.routers.https-redirect.middlewares=allow-cors@file,force-https@file
            - traefik.http.routers.https-redirect.rule=hostregexp(`{host:.+}`)
            - traefik.http.routers.traefik_dashboard.entrypoints=websecure
            - traefik.http.routers.traefik_dashboard.rule=Host(`traefik.***.***`)
            - traefik.http.routers.traefik_dashboard.service=api@internal
            - traefik.http.routers.traefik_dashboard.tls.certresolver=le
        ports:
            - "80:80"
            - "443:443"
        secrets:
            - ***_api_key
        networks:
            - traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./config/traefik.toml:/etc/traefik/traefik.toml
            - traefik_letsencrypt:/letsencrypt
```

Our catch-alll HTTP to HTTPS rule is made effective through this labels:
```yaml
            - traefik.http.routers.https-redirect.entrypoints=web
            - traefik.http.routers.https-redirect.middlewares=allow-cors@file,force-https@file
            - traefik.http.routers.https-redirect.rule=hostregexp(`{host:.+}`)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik    | 192.168.37.253 - - [06/May/2021:15:30:37 +0000] "POST /media/upload HTTP/1.1" 308 18 "-" "-" 286 "https-redirect@docker" "-" 0ms
traefik    | time="2021-05-06T15:30:37Z" level=debug msg="vulcand/oxy/buffer: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/media/upload\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Authorization\":[\"Bearer ***************************************************************************************************************************************************************************\"],\"Connection\":[\"keep-alive\"],\"Content-Length\":[\"275167\"],\"Content-Type\":[\"multipart/form-data; boundary=--------------------------660248662409705234316975\"],\"Postman-Token\":[\"83d54576-732e-49df-a587-c52e1a0611ad\"],\"Referer\":[\"http://***.**.****.**/media/upload\"],\"User-Agent\":[\"PostmanRuntime/7.26.8\"],\"X-Api-Key\":[\"789\"],\"X-Forwarded-Host\":[\"***.***\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"fb84bbc6159f\"],\"X-Real-Ip\":[\"192.168.37.253\"],\"X-Tenant-Id\":[\"recette-2-v2\"]},\"ContentLength\":275167,\"TransferEncoding\":null,\"Host\":\"***.***\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.37.253:58690\",\"RequestURI\":\"/media/upload\",\"TLS\":null}"
traefik    | time="2021-05-06T15:30:37Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/media/upload\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Authorization\":[\"Bearer ***************************************************************************************************************************************************************************\"],\"\"],\"Connection\":[\"keep-alive\"],\"Content-Length\":[\"275167\"],\"Content-Type\":[\"multipart/form-data; boundary=--------------------------660248662409705234316975\"],\"Postman-Token\":[\"83d54576-732e-49df-a587-c52e1a0611ad\"],\"Referer\":[\"http://***.**.****.**/media/upload\"],\"User-Agent\":[\"PostmanRuntime/7.26.8\"],\"X-Api-Key\":[\"789\"],\"X-Forwarded-Host\":[\"***.***\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"fb84bbc6159f\"],\"X-Real-Ip\":[\"192.168.37.253\"],\"X-Tenant-Id\":[\"recette-2-v2\"]},\"ContentLength\":275167,\"TransferEncoding\":null,\"Host\":\"***.***\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.37.253:58690\",\"RequestURI\":\"/media/upload\",\"TLS\":null}"
traefik    | time="2021-05-06T15:30:37Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/media/upload\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Authorization\":[\"Bearer ***************************************************************************************************************************************************************************\"],\"\"],\"Connection\":[\"keep-alive\"],\"Content-Length\":[\"275167\"],\"Content-Type\":[\"multipart/form-data; boundary=--------------------------660248662409705234316975\"],\"Postman-Token\":[\"83d54576-732e-49df-a587-c52e1a0611ad\"],\"Referer\":[\"http://***.**.****.**/media/upload\"],\"User-Agent\":[\"PostmanRuntime/7.26.8\"],\"X-Api-Key\":[\"789\"],\"X-Forwarded-Host\":[\"***.***\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"fb84bbc6159f\"],\"X-Real-Ip\":[\"192.168.37.253\"],\"X-Tenant-Id\":[\"recette-2-v2\"]},\"ContentLength\":275167,\"TransferEncoding\":null,\"Host\":\"***.***\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.37.253:58690\",\"RequestURI\":\"/media/upload\",\"TLS\":null}" ForwardURL="http://192.168.112.16:3000"
traefik    | time="2021-05-06T15:30:37Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/media/upload\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Authorization\":[\"Bearer ***************************************************************************************************************************************************************************\"],\"\"],\"Connection\":[\"keep-alive\"],\"Content-Length\":[\"275167\"],\"Content-Type\":[\"multipart/form-data; boundary=--------------------------660248662409705234316975\"],\"Postman-Token\":[\"83d54576-732e-49df-a587-c52e1a0611ad\"],\"Referer\":[\"http://***.**.****.**/media/upload\"],\"User-Agent\":[\"PostmanRuntime/7.26.8\"],\"X-Api-Key\":[\"789\"],\"X-Forwarded-Host\":[\"***.***\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"fb84bbc6159f\"],\"X-Real-Ip\":[\"192.168.37.253\"],\"X-Tenant-Id\":[\"recette-2-v2\"]},\"ContentLength\":275167,\"TransferEncoding\":null,\"Host\":\"***.***\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.37.253:58690\",\"RequestURI\":\"/media/upload\",\"TLS\":null}"
traefik    | time="2021-05-06T15:30:37Z" level=debug msg="vulcand/oxy/buffer: completed ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/media/upload\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Authorization\":[\"Bearer ***************************************************************************************************************************************************************************\"],\"\"],\"Connection\":[\"keep-alive\"],\"Content-Length\":[\"275167\"],\"Content-Type\":[\"multipart/form-data; boundary=--------------------------660248662409705234316975\"],\"Postman-Token\":[\"83d54576-732e-49df-a587-c52e1a0611ad\"],\"Referer\":[\"http://***.**.****.**/media/upload\"],\"User-Agent\":[\"PostmanRuntime/7.26.8\"],\"X-Api-Key\":[\"789\"],\"X-Forwarded-Host\":[\"***.***\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"fb84bbc6159f\"],\"X-Real-Ip\":[\"192.168.37.253\"],\"X-Tenant-Id\":[\"recette-2-v2\"]},\"ContentLength\":275167,\"TransferEncoding\":null,\"Host\":\"***.***\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.37.253:58690\",\"RequestURI\":\"/media/upload\",\"TLS\":null}"
traefik    | 192.168.37.253 - - [06/May/2021:15:30:37 +0000] "POST /media/upload HTTP/1.1" 400 66 "-" "-" 287 "api-v0_2_0@docker" "http://192.168.112.16:3000" 142ms
```

**Comment by JonFreer** [comment] 2022-05-22 09:25
I was able to solve this problem in my case by adding a buffering middleware: https://doc.traefik.io/traefik/middlewares/http/buffering/#memrequestbodybytes, increasing the value to force the request to be stored in memory. Like so:

```- "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=8000000"```

Hope this helps

**Comment by julian-eckhardt** [comment] 2022-12-28 17:52
I had a similar problem with Traefik up to v2.9. In my case, the file was not completely missing, but only a large part at the beginning of it. This led to my Spring Boot backend throwing the following error message:

```
DefaultHandlerExceptionResolver : Resolved [org.springframework.web.multipart.support.MissingServletRequestPartException: Required request part 'file' is not present]
```

### Traefik in my docker-compose file:

```docker-compose.yml
version: "3.7"

services:
    traefik:
        image: "traefik:v2.9"
        command:
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
          - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
          - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
          - "--certificatesresolvers.defaultresolver.acme.caserver=${TRAEFIK_CA_SERVER}"
          - "--certificatesresolvers.defaultresolver.acme.email=${TRAEFIK_ACME_EMAIL_ADDRESS}"
          - "--certificatesresolvers.defaultresolver.acme.storage=/acme.json"
          - "--certificatesresolvers.defaultresolver.acme.tlschallenge=true"
          - "--log.level=debug"
        ports:
          - "80:80"
          - "443:443"
        labels:
          - "traefik.enable=true"
        volumes:
          - "./volumes/traefik_data/acme.json:/acme.json"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        restart: unless-stopped
```

Adding a buffering middleware unfortunately didn't help for me. The solution was explicitly adding `https://` to the request URL in order to stay clear of the HTTP to HTTPS redirect.

Easy fix, but took me days to figure out as the problem was very hard to locate.

**Comment by rtribotte** [comment] 2023-01-04 10:08
Hello @e7d @julian-eckhardt,

We tried to reproduce this issue, using curl, but without success.
The permanent redirect `308` contract should imply no changes for the method and the body (https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#permanent_redirections), thus it seems that some clients may have different behavior on this.

Since this issue seems to be caused by a wrong behavior from the client, we are closing this issue.

**Closed by rtribotte** 2023-01-04 10:08 UTC
Labels: kind/bug/possible
