### ISSUE TITLE
Enable httpchallenge.delaybeforecheck and tlschallenge.delaybeforecheck

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9709] opened 2023-02-11 21:35 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

There is a `delayBeforeCheck` function for the Traefik LetsEncrypt `dnsChallenge`:
```
certificatesResolvers:
  CertificateResolver0:
    acme:
      dnsChallenge:
        delayBeforeCheck: 42s
```
It would be great to have this for `httpChallenge` and `tlsChallenge` as well. This would hopefully enable the usage of multiple Traefik instances with `acme.json` stored in a distributed file system, for example in Docker Swarm.

From a really quick&dirty scan in the code the required change seems minimal:
```
./pkg/provider/acme/provider.go:  if p.DNSChallenge.DelayBeforeCheck > 0 {
./pkg/provider/acme/provider.go:    logger.Debug().Msgf("Delaying %d rather than validating DNS propagation now.", p.DNSChallenge.DelayBeforeCheck)
./pkg/provider/acme/provider.go:    time.Sleep(time.Duration(p.DNSChallenge.DelayBeforeCheck))
./pkg/provider/acme/provider.go:  }
```

**Comment by ldez** [comment] 2023-02-11 22:01
duplicate of #9439

**Closed by ldez** 2023-02-11 22:01 UTC
Labels: resolution/duplicate
