### ISSUE TITLE
CORS OriginList not shown in Dashboard

### ISSUE THREAD

**Issue by wopl** [traefik/traefik#6890] opened 2020-06-05 10:16 UTC
Running Traefik 2.2.0. Need to define some CORS Header:

> apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: longhorn-cors
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
   accessControlAllowOriginList:
     - "http://localhost"
    accessControlMaxAge: 100
    addVaryHeader: "true"

Dashboard does not show OriginList. Is this an UI-issue only? Or was OriginList not accepted for any reason?

**Comment by jspdown** [comment] 2020-11-27 15:23
Hello @wopl and thanks for your interest in Traefik.

CORS headers are returned only if:
- The request method is `OPTIONS`
- The `Access-Control-Request-Method` header is given in the request
- The `Origin` header is given in the request

The `Access-Control-Allow-Origin` header will be returned only if the given `Origin` matches with one defined in the `accessControlAllowOriginList`.

We are going to close this issue as this is not a bug. However, if you need some help, don't hesitate to visit the [community forum](https://community.traefik.io/)

**Closed** 2020-11-27 15:26 UTC
Labels: kind/question
