### ISSUE TITLE
RateLimit middleware only created if period is provided

### ISSUE THREAD

**Issue by tkronawitter** [traefik/traefik#8724] opened 2022-01-22 14:07 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I tried to create a http ratelimit middleware using trafic_dynamic.yml using the example from the [documentation](https://doc.traefik.io/traefik/v2.0/middlewares/ratelimit/)

    http:
      middlewares:
        rate-limit:
          rateLimit:
            average: 100
            burst: 50

### What did you see instead?

The middleware was not created. No error message was displayed in the logs.

If I add a period value (found from examples on other sites) it works.

    http:
      middlewares:
        rate-limit:
          rateLimit:
            average: 100
            burst: 50
            period: 10

The v2 documentation does not mention the period at all.

### What version of Traefik are you using?

Version:      2.5.7
Codename:     brie
Go version:   go1.17.6
Built:        2022-01-20T16:16:23Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
http:
  middlewares:

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 10
```

Add more configuration information here.

**Comment by rtribotte** [comment] 2022-01-24 08:21
Hello @tkronawitter,

Thanks for your interest in Traefik,

Unfortunately, we are not able to reproduce the issue you are describing, and it is probably due to a configuration issue.

The GitHub issue tracker is dedicated to bug and feature requests.
For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.

**Closed by rtribotte** 2022-01-24 08:21 UTC
Labels: status/0-needs-triage
