### ISSUE TITLE
Support Service URLs via Docker Provider

### ISSUE THREAD

**Issue by ZaxLofful** [traefik/traefik#9015] opened 2022-05-16 06:46 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Make the URL value of services deployed via the Docker Compose Provider, so far this is the only configuration I can find which isn't 100% compatible across the different configuration types/providers.

It was mentioned awhile back on the community forums...
https://community.traefik.io/t/traefik-v2-with-docker-compose-external-services-possible/5792/2

This would enhance compatibility and it is certainly doable.

**Comment by kevinpollet** [comment] 2022-05-16 06:59
Duplicate of https://github.com/traefik/traefik/issues/8753

**Closed by kevinpollet** 2022-05-16 06:59 UTC
Labels: status/0-needs-triage
