### ISSUE TITLE
Nested traefik instances with "remote error: tls: unrecognized name"

### ISSUE THREAD

**Issue by JamborJan** [traefik/traefik#10880] opened 2024-07-04 18:41 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have on main traefik instances which is passing through tcp traffic to 3 secondary instances. One of the configured routes and service is looking like this:

```yaml
tcp:
  routers:
    services-secure:
      entryPoints:
        - "websecure"
      rule: "(HostSNIRegexp(`{subdomain:[a-zA-Z0-9-]+}.services.mydomain.com`))"
      service: "services-secure"
      tls:
        passthrough: true
  services:
    services-secure:
      loadBalancer:
        servers:
          - address: "services:443"
        proxyProtocol:
          version: 2
```

The secondary traefik instances are configured with "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true" and running in different Docker environments.

Up until version v2.10.7 the setup was working flawless.

### What did you see instead?

After having updated to v2.11.6 or v3.0.4 the setup is not working anymore. Routing is still working, but TLS challenges are not working anymore. The error is `remote error: tls: unrecognized name`.

### What version of Traefik are you using?

Not working: v2.11.6 or v3.0.4

Working: v2.10.7

### What is your environment & configuration?

Main configuration:

```toml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG #  DEBUG, INFO, WARN, ERROR, FATAL, PANIC

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  mytlschallenge:
    acme:
      tlsChallenge: {}
      email: "my@email.org"
      storage: "/etc/traefik/acme.json"

serversTransport:
  insecureSkipVerify: true
```

The routes are configured as mentioned in the example above.

One of the secondary configuration looks like this

```yaml
version: "3.8"

services:

  traefik:
    image: traefik:v3.0.3
    restart: always
    command:
      - "--accesslog"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=${LB_IPS}"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--serverstransport.insecureskipverify=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=my@email.org"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443" 
    volumes:
      - "${CT_DATA_BASEPATH}/traefik_data:/etc/traefik/"
      - "${CT_DATA_BASEPATH}/letsencrypt_data:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${INSTANCE}.mydomain.org`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
      - "traefik.http.services.traefik-traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.MyIP.ipallowlist.sourcerange=127.0.0.1/32, 172.29.72.0/24, 192.168.3.0/24, 192.168.11.0/24, 10.8.0.0/24"
      - "traefik.http.routers.traefik.middlewares=MyIP@docker"
      ## middleware security-headers
      # Source: https://dev.to/paulknulst/harden-your-website-with-traefik-and-security-headers-5dpd
      - "traefik.http.middlewares.security-headers.headers.accesscontrolallowmethods=GET, OPTIONS, PUT"
      - "traefik.http.middlewares.security-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.security-headers.headers.addvaryheader=true"
      - "traefik.http.middlewares.security-headers.headers.hostsproxyheaders=X-Forwarded-Host"
      - "traefik.http.middlewares.security-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.security-headers.headers.stsseconds=63072000"
      - "traefik.http.middlewares.security-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stspreload=true"
      - "traefik.http.middlewares.security-headers.headers.forcestsheader=true"
      - "traefik.http.middlewares.security-headers.headers.framedeny=true"
      - "traefik.http.middlewares.security-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserxssfilter=true"
      - "traefik.http.middlewares.security-headers.headers.referrerpolicy=same-origin"
      - "traefik.http.middlewares.security-headers.headers.permissionspolicy=camera=(), geolocation=(), microphone=(), payment=(), usb=(), vr=()"
      - "traefik.http.middlewares.security-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex"
      # Content Security Policy
      - "traefik.http.middlewares.strict-csp.headers.contentsecuritypolicy=default-src 'none' data:; img-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

  whoami:
    image: traefik/whoami
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${INSTANCE}.mydomain.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"
      - "traefik.http.services.traefik-whoami.loadbalancer.server.port=80"
      # IP Allowlist
      - "traefik.http.routers.whoami.middlewares=MyIP@docker"
      # Security headers
      - "traefik.http.routers.whoami.middlewares=security-headers"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - prd-docker

networks:
  prd-docker:
    external: true
```

### If applicable, please paste the log output in DEBUG level

As I needed to role back my instance, I lost the debug log and I don't have a development instance yet where I can purposly brick the setup for testing. So unfortunately I cannot provide the log. I am very sorry.

**Comment by kristoficko** [comment] 2024-07-04 19:48
I can help with testing as I observe the same issue.  I'm running my primary traefik instance on Mikrotik and I'm able to easily switch between versions if needed. Home environment so no strict availability objectives 😉

**Comment by vojtad** [comment] 2024-07-08 14:54
I am seeing similar issue where I want Traefik to passthrough TLS challenge to Teleport container which should handle the challenge on its own. This container is configured with `traefik.tcp.routers.teleport.tls.passthrough=true`.

I've verified with tcpdump and Wireshark that Client Hello with ALPN Next Protocol set to `acme-tls/1` is not passsed through to the Teleport container and is instead rejected by Traefik with `Unrecognized Name` error.

I believe this was introduced in #10536 merged in v2.11.1 (and 3.0.0-rc3). Also, this issue is probably duplicate of #10684.

**Comment by kevinpollet** [comment] 2024-07-09 07:27
Hello @vojtad and thanks for the analysis,

You are right this issue is a duplicate, I am closing it accordingly.

Duplicate of https://github.com/traefik/traefik/issues/10684

**Closed by kevinpollet** 2024-07-09 07:27 UTC
Labels: area/acme, kind/bug/possible

**Comment by CybotTM** [comment] 2024-08-02 06:41
But #10684 is only speaking of 3.0 - maybe the issue topic should be adapted.

**Comment by emilevauge** [comment] 2024-08-05 12:42
https://github.com/traefik/traefik/issues/10684 also affects 2.x, we edited the title accordingly.
