### ISSUE TITLE
X-Forwarded-For unset when forwarding websocket handshake

### ISSUE THREAD

**Issue by eigengrau** [traefik/traefik#6076] opened 2019-12-20 16:13 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I established a websocket connection to a capable backend.

### What did you expect to see?
I expected the `X-Forwarded-For` header to be set.

### What did you see instead?
The `X-Forwarded-For` header was unset. Other `X-Forwarded-Foo` headers were set, as was `X-Real-IP`. Notably, `X-Forwarded-For` *is* set when passing any other HTTP request to the backend.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.20
Codename:     maroilles
Go version:   go1.12.14
Built:        2019-12-10_05:02:10PM
OS/Arch:      linux/amd64
```

**Comment by eigengrau** [comment] 2019-12-20 17:18
I have noticed that when I set `X-Forwarded-For` on the client request, Traefik does pass this value through to the application unmodified (i.e., the IP of the Traefik instance is not appended).

**Comment by jainbhavya65** [comment] 2019-12-20 21:09
check this link by using this you can allow traefik to trust all the forwarded headers.
https://docs.traefik.io/routing/entrypoints/#forwarded-header

**Comment by eigengrau** [comment] 2019-12-21 11:43
> check this link by using this you can allow traefik to trust all the forwarded headers.

Thanks. Can you elaborate how this is a matter of setting trust in forwarded headers? The issue is that Traefik does not *set* one of the `X-Forwarded`-headers when making a websocket handshake, whereas the header *is set* when making any other HTTP request.

**Comment by jainbhavya65** [comment] 2019-12-21 12:22
@eigengrau Traefik block all the x-forwarded header by default to pass all the header we need to that setting in Traefik

**Comment by eigengrau** [comment] 2019-12-21 13:09
> Traefik block all the x-forwarded header by default to pass all the header we need to that setting in Traefik

We are not attempting to pass through a client-set header. Our issue is that Traefik (correctly) inserts the header into non-websocket requests, whereas the header is missing in websocket handshakes.

**Comment by jainbhavya65** [comment] 2019-12-21 15:37
@eigengrau can you give any proto type for your use case

**Comment by bradjones1** [comment] 2020-01-22 00:59
I can verify this is causing us trouble as well; rubber-ducking a little bit here, this looks like potentially related to https://github.com/containous/traefik/blob/a20a6636b4582e4e7b562fc01f64567775fc8a9a/pkg/middlewares/forwardedheaders/forwarded_header.go#L90

**Comment by bradjones1** [comment] 2020-01-22 20:08
I've tried to verify this but have been unsuccessful; in my case the situation was with a specific application, namely Rancher: see https://github.com/containous/traefik/issues/5533#issuecomment-553823512 for a good summary.

**Comment by saez0pub** [comment] 2020-06-22 09:18
Hello,

X-forwarded-for is something important.
Is it a regression we can fix with a downgrade ?

Thanks.

**Comment by john-dev** [comment] 2020-11-25 07:31
I would love to have that feature as well but according to the Websocket protocol, it's not allowed to send X-Forward-* Headers.

**Comment by eigengrau** [comment] 2020-11-25 07:57
> I would love to have that feature as well but according to the Websocket protocol, it's not allowed to send X-Forward-* Headers.

That’s curious. Do you take this from the RFC? Would you mind sharing a reference? I find this surprising, since I have not so far encountered the case where the use of non-standardized headers is forbidden or mandated as part of an HTTP request.

**Comment by frbayart** [comment] 2020-12-01 13:34
I have the same issue on Traefik `1.7.26`,

**X-Forwarded-For** is added by Traefik on HTTPS:// but not on WSS://.

**Comment by sdelicata** [comment] 2024-07-04 09:30
Hello!
I close this issue as it targets an unsupported version of Traefik.
Feel free to re-open it or join our [Community Forum](https://community.traefik.io/).

**Closed by sdelicata** 2024-07-04 09:30 UTC
Labels: area/websocket, kind/bug/possible
