### ISSUE TITLE
Compression Breaks BasicAuth on iOS Safari

### ISSUE THREAD

**Issue by ellisonpatterson** [traefik/traefik#11054] opened 2024-08-29 13:53 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If you enable a BasicAuth middleware and a compression middleware for a container, BasicAuth works on a non-iOS web browser. You enter your credentials and it lets you through.

### What did you see instead?

On iOS, if you have a BasicAuth middleware and a compression middleware enabled for a container, BasicAuth will not let you through and infinitely prompts you to enter your credentials.

### What version of Traefik are you using?

Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

traefik.toml
```
[global]
  checkNewVersion = true

[log]
  level = "DEBUG"

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
  [entryPoints.webinsecure]
    address = "xxx.xxx.xxx.xxx:80"
    [entryPoints.webinsecure.http]
      middlewares = ["secure-headers@file", "compression@file"]
  [entryPoints.websecure]
    address = "xxx.xxx.xxx.xxx:443"
    [entryPoints.websecure.http]
      middlewares = ["secure-headers@file", "compression@file"]
    [entryPoints.websecure.http3]
      advertisedPort = 443
    [entryPoints.websecure.http.tls]
      certResolver = "default"
      [[entryPoints.websecure.http.tls.domains]]
        main = "website.website"
        sans = ["*.website.website"]

[providers]
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    defaultRule = "Host(`{{ index .Labels \"traefik_url\"}}`)"
    constraints = "LabelRegex(`traefik_url`, `\\S+`)"
    exposedByDefault = false
  [providers.file]
    watch = true
    directory = "/etc/traefik/providers"

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "xxx@xxx"
      storage = "/etc/traefik/acme/acme.json"
      [certificatesResolvers.default.acme.dnsChallenge]
        provider = "cloudflare"
        delayBeforeCheck = "30s"
```

/etc/traefik/providers/rules.toml
```
[http]
  [http.middlewares]
    [http.middlewares.auth]
      [http.middlewares.auth.basicAuth]
        users = [
          "xxx:xxx",
        ]
    [http.middlewares.websecure-only]
      [http.middlewares.websecure-only.redirectScheme]
        scheme = "https"
        permanent = true
    [http.middlewares.secure-headers]
      [http.middlewares.secure-headers.headers]
        hostsProxyHeaders = ["X-Forwarded-Host", "X-Forwarded-For", "X-Forwarded-Proto", "X-Real-IP"]
        contentTypeNosniff = true
        browserXssFilter = true
        referrerPolicy = "same-origin"
        [http.middlewares.secure-headers.headers.customResponseHeaders]
          X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex,"
          server = ""
    [http.middlewares.rate-limit]
      [http.middlewares.rate-limit.rateLimit]
        average = 100
        burst = 50
    [http.middlewares.compression.compress]
```

### If applicable, please paste the log output in DEBUG level

```
2024-08-29T13:42:23Z DBG github.com/traefik/traefik/v3/pkg/middlewares/compress/compress.go:109 > Unable to parse MIME type error="mime: no media type" middlewareName=compression@file middlewareType=Compress
2024-08-29T13:42:23Z DBG github.com/traefik/traefik/v3/pkg/middlewares/auth/basic_auth.go:79 > Authentication failed middlewareName=auth@file middlewareType=BasicAuth
2024-08-29T13:42:40Z DBG github.com/traefik/traefik/v3/pkg/middlewares/compress/compress.go:109 > Unable to parse MIME type error="mime: no media type" middlewareName=compression@file middlewareType=Compress
2024-08-29T13:42:40Z DBG github.com/traefik/traefik/v3/pkg/middlewares/auth/basic_auth.go:86 > Authentication succeeded middlewareName=auth@file middlewareType=BasicAuth
2024-08-29T13:42:41Z DBG github.com/traefik/traefik/v3/pkg/middlewares/compress/compress.go:109 > Unable to parse MIME type error="mime: no media type" middlewareName=compression@file middlewareType=Compress
2024-08-29T13:42:41Z DBG github.com/traefik/traefik/v3/pkg/middlewares/auth/basic_auth.go:79 > Authentication failed middlewareName=auth@file middlewareType=BasicAuth
```

**Comment by ellisonpatterson** [comment] 2024-08-29 13:58
Ughhh actually for some services, it's still not working on iOS after disabling compression...

```
2024-08-29T13:57:42Z DBG github.com/traefik/traefik/v3/pkg/middlewares/auth/basic_auth.go:79 > Authentication failed middlewareName=auth@file middlewareType=BasicAuth
2024-08-29T13:57:58Z DBG github.com/traefik/traefik/v3/pkg/middlewares/auth/basic_auth.go:86 > Authentication succeeded middlewareName=auth@file middlewareType=BasicAuth
2024-08-29T13:57:59Z DBG github.com/traefik/traefik/v3/pkg/middlewares/auth/basic_auth.go:79 > Authentication failed middlewareName=auth@file middlewareType=BasicAuth
```

**Comment by nmengin** [comment] 2024-09-02 12:36
Hey @ellisonpatterson,

Thanks for reaching out!

From what we understand, it's not a bug on our side. For this reason, I close the issue.
To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly. 

If you still think that an issue we should address, please provide a complete reproducible use case.

**Closed by nmengin** 2024-09-02 12:36 UTC
Labels: status/0-needs-triage
