### ISSUE TITLE
Allow for watching of multiple paths in Consul KV 

### ISSUE THREAD

**Issue by benvanstaveren** [traefik/traefik#9501] opened 2022-11-09 15:32 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently we store Traefik's dynamic configuration in Consul KV - this is fine when all Traefik instances share a configuration, but gets progressively more complicated when they don't. It leads to duplicating an entire configuration into a separate path, and making 1 or 2 changes. 

It would be nice if we can specify the root path as an array/list of paths, from lowest to highest priority. For instance by setting:

```
providers:
  consulCatalog:
    prefix: 
    - traefik/common
    - traefik/specificinstance
```

Where the configuration is first retrieved from "traefik/common/*" and then from "traefik/specificinstance/*" with the latter's data overwriting the former. This allows for a bit more flexibility, in my opinion.

**Comment by ldez** [comment] 2022-11-09 16:37
Duplicate of #7419

**Closed by ldez** 2022-11-09 16:37 UTC
Labels: resolution/duplicate

**Comment by benvanstaveren** [comment] 2022-11-09 17:09
Not a duplicate - the alias functionality allows for switching to a new configuration for one traefik instance transparently, this would allow for multiple configurations to be loaded with some form of inheritance of configuration values.

**Comment by tfny** [comment] 2022-11-10 17:30
Sorry about that, you are right, this is not a duplicate.  During our sync today we decided that this is something we don't think we wish to include in Traefik Proxy right now, but we do think it is a candidate for a [provider plug-in](https://plugins.traefik.io/create) if you are interested in creating one. 

Thanks!
