### ISSUE TITLE
Rolling deployment with different Consul Catalog Tags

### ISSUE THREAD

**Issue by GabeL7r** [traefik/traefik#7817] opened 2021-01-28 21:47 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We deployed Traefik with services not using the health check feature for their load balancers. We discovered we needed the health check to prevent Traefik from sending to requests to services that stopped running in between the polling interval of Traefik. Next we deployed changes to our service to include the tags for the health check, and this is where we ran into the problem.

We are using a rolling deployment strategy which first doubles the number of tasks running, verifies they are healthy, and then stops the old tasks. During the time period where the old (no health check tags) and new (contains health check tags) services were running Traefik produced an error:

```
level=error msg="Service defined multiple times with different configurations
```

The error did not go away until all of the old services had stopped running.

I have read all of the documentation and I have been unable to find any information related to rolling deployments and how to change Traefik configurations for your service if two versions of the service cannot be running simultaneously with the different tags.

### What did you expect to see?
I would expect the service to continue operating in Traefik during the rolling deployment transition period.

### What did you see instead?
Traefik responded to all requests to the service with 404.

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.3

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by rtribotte** [comment] 2021-01-29 17:13
Hello @GabeL7r,

Thanks for your interest in Traefik!

It's a bit difficult to properly know what can go wrong without a concrete example.
Can you share some configuration, a minimal reproducible case?

As for now, from what you are describing, if you are naming your services, this is the expected behavior.
Traefik is not able to merge configurations with different services with the same name and will drop them from the resultant configuration.

Could you share your logs too?

**Comment by parkedwards** [comment] 2021-01-29 17:37
hey @rtribotte -- I'm working with @GabeL7r on this particular project, so I can elaborate a bit more

We currently register all of our services (each with multiple instances/tasks) with a Consul registry, and then we use Traefik to discover + build routing through the ConsulCatalog provider.  We're using Consul tags on these services to inform Traefik that they are routable destinations.  We now have it in a live environment with network traffic being routed through Traefik.

These services dynamically scale in/out based on demand, so there are times when Traefik attempts to send traffic to a service instance that is draining, resulting in a 503.  We recently discovered that [Traefik services can be configured to specify a per-instance health check](https://doc.traefik.io/traefik/routing/services/#health-check), which seems like the right solution.  We updated a service's configuration by adding these extra Consul tags during registration:

```
- "traefik.http.services.service01.loadbalancer.healthcheck.followredirects=true"
- "traefik.http.services.service01.loadbalancer.healthcheck.headers.name0=foobar"
- "traefik.http.services.service01.loadbalancer.healthcheck.headers.name1=foobar"
- "traefik.http.services.service01.loadbalancer.healthcheck.hostname=foobar"
- "traefik.http.services.service01.loadbalancer.healthcheck.interval=foobar"
- "traefik.http.services.service01.loadbalancer.healthcheck.path=foobar"
- "traefik.http.services.service01.loadbalancer.healthcheck.port=42"
- "traefik.http.services.service01.loadbalancer.healthcheck.scheme=foobar"
- "traefik.http.services.service01.loadbalancer.healthcheck.timeout=foobar"
- "traefik.http.services.service01.loadbalancer.healthcheck.followredirects=true"
```

When we deploy these changes, our orchestrator performs a rolling deploy; it adds new instances, confirms they are healthy, and then drains the old instances.  But during that period when both sets exist, Traefik is throwing error logs like these (this is from a locally reproduced container, but the logs are exactly the same as what we're seeing in production):

``` 
...
time="2021-01-29T17:31:54Z" level=error msg="Service defined multiple times with different configurations in [consul-dev-api-microservice-auth-docker-desktop-hs-gateway-api-microservice-auth-1-10000 consul-dev-api-microservice-auth-docker-desktop-hs-gateway-api-microservice-auth-2-1-10000]" serviceName=api-microservice-auth

time="2021-01-29T17:31:59Z" level=error msg="Service defined multiple times with different configurations in [consul-dev-api-microservice-auth-docker-desktop-hs-gateway-api-microservice-auth-1-10000 consul-dev-api-microservice-auth-docker-desktop-hs-gateway-api-microservice-auth-2-1-10000]" serviceName=api-microservice-auth
...
```

We can see this state change in the Traefik admin UI -- having this service page opened, and then initiating the deploy, we'll see the service become undefined:

![image](https://user-images.githubusercontent.com/19556538/106308301-5a139480-6215-11eb-8870-15e602309a98.png)


Right now, it seems like we're unable to push Traefik configuration changes to a live service (using Consul tags) without the service blipping out of existence, since there are differing sets of configurations for different instances for the same service.  

We guessed that we're not the only ones performing rolling service
deploys like this...so wanted to see if we were missing anything in terms of approach to avoid this

**Comment by rtribotte** [comment] 2021-02-01 11:39
Hello @GabeL7r @parkedwards,

Thanks for your feedback.

As I said before, the problem you are facing is expected. Two different load balancer configurations for the same service cannot be merged and the service is dropped.

Using a different name for services would work but will create multiple routers with the same routing rule, and without specific priorities, you may reach one router or another.

For further control over the rolling deployment (canary deployment), this would be achieved with a Weigthed Round Robin load balancer that overlays your services.

Thus, it's currently not possible to achieve this with a label provider and there's a proposal already opened (#5673) for this.

In the meantime, as a workaround, you can define a router and a WRR load balancer service referring to your Consul services with the file provider.
But this cross providers setup breaks a bit the dynamicity.

WDYT?

**Comment by parkedwards** [comment] 2021-02-01 19:41
hey @rtribotte -- that's unfortunate. we test drove your suggestion, but it's as you said - we lose the dynamic element of pulling from a provider if we need to statically configure Weighted Round Robin "routing" services as well as manual routing rules.  The WRR route also requires the "v2" version to already exist, which it often does not during new releases.

Anyway, we'll investigate our own workaround for this, but appreciate the time.  definitely look forward to Traefik fleshing out some of these Canary capabilities!

**Comment by rtribotte** [comment] 2021-02-02 11:29
Hello @parkedwards,

Thanks for your feedback,

I'll close this issue as a duplicate accordingly, as I understand that you are requesting support for WRR for label providers.
Feel free to interact on this issue to discuss about the proposal, or just add a thumb up :-)

duplicate of #5673

**Closed by rtribotte** 2021-02-02 11:29 UTC
Labels: contributor/need-more-information
