### ISSUE TITLE
Namespace isolation is not guaranteed to serve TLS certificates on k8s

### ISSUE THREAD

**Issue by a-bouts** [traefik/traefik#9746] opened 2023-02-24 14:16 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

using two k8s namespaces `test`and `test2`, I create a valid TLS certificate resolving two URLs : `test.example.org` and `test2.example.org` (with cert-manager) stored in `test-tls` secret, in `test` namespace

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-tls
  namespace: test
spec:
  dnsNames:
  - test.example.org
  - test2.example.org
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: test-tls
  usages:
  - digital signature
  - key encipherment
```

I deploy ingress, service and deployment in these both namespaces, resolving `test.example.org` for the first one, using the tls secret and `test2.example.org` for the second one

In the `test` namespace, I create an ingress resolving `test.example.org` using the previous certificate

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: test
spec:
  ingressClassName: traefik
  rules:
  - host: test.example.org
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test.example.org
    secretName: test-tls
```

In the `test2` namespace, I create an ingress resolving `test2.example.org` without providing certificate

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: test2
spec:
  ingressClassName: traefik
  rules:
  - host: test2.example.org
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test2.example.org
```

I was expecting having the TRAEFIK internal certificate when reaching `test2.example.org`

### What did you see instead?

For both URLs, the certificate provided is the one stored in `test` namespace

### What version of Traefik are you using?

v2.9.7

### What is your environment & configuration?

Traefik is deployed using the helm chart with fluxcd

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: ingress-system
spec:
  interval: 30m
  url: https://traefik.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress-system
spec:
  interval: 30m
  targetNamespace: ingress-system
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ingress-system
      interval: 30m
  values:
    service:
      spec:
        loadBalancerIP: x.x.x.x
        externalTrafficPolicy: Local
```

**Comment by rtribotte** [comment] 2023-02-27 15:39
Hello @a-bouts,

Thanks for your interest in Traefik!

Any certificate provided to Traefik could be used for any route.
This is because there is only one TLS certificate store in Traefik, that is used to do the TLS handshake, which happens before the actual routing.

This is a known limitation and we are closing this issue in favor of https://github.com/traefik/traefik/issues/4756, which is the related feature request.

Duplicate of #4756

**Closed by rtribotte** 2023-02-27 15:39 UTC
Labels: status/0-needs-triage
