### ISSUE TITLE
TCP Router with TLS sends incorrect ALPN

### ISSUE THREAD

**Issue by ericlathrop** [traefik/traefik#7776] opened 2021-01-19 02:45 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I was trying to work around #7771 so I put my app behind a TCP router with these docker labels:

```
      traefik.docker.network: web
      traefik.enable: "true"
      traefik.tcp.routers.awslambdaproxy.rule: HostSNI(`aws-lambda-proxy.ericlathrop.dev`)
      traefik.tcp.routers.awslambdaproxy.tls: "true"
      traefik.tcp.routers.awslambdaproxy.tls.certresolver: leresolver
```

My app only supports HTTP 1.1, but traefik negotiates an ALPN of `h2` which causes connections to fail. 

```
$ curl -v https://my-app.example/
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to my-app.example (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=my-app.example
*  start date: Jan 17 03:55:14 2021 GMT
*  expire date: Apr 17 03:55:14 2021 GMT
*  subjectAltName: host "my-app.example" matched cert's "my-app.example"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x557c11fd35c0)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: my-app.example
> User-Agent: curl/7.58.0
> Accept: */*
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* SSL_write() returned SYSCALL, errno = 104
* Failed sending HTTP2 data
* Connection #0 to host my-app.example left intact
curl: (55) SSL_write() returned SYSCALL, errno = 104
```

If I force HTTP 1.1 mode with `curl -v --http1.1 https://my-app.example`, it works successfully.

Perhaps traefik should do one or more of the following:
1. only send a ALPN of `http/1.1` when it is configured to terminate TLS connections
2. inspect the service to see which protocol it supports
3. allow for configuring which ALPN is sent

### What did you expect to see?

I expected `curl -v https://my-app.exmaple` to return successfully.

### What did you see instead?

A `curl` error like `* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.`. See above for the full output.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[accessLog]
[api]
  dashboard = true

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.leresolver.acme]
  email = "..."
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.leresolver.acme.dnsChallenge]
    provider = "namecheap"

[providers.docker]
  exposedByDefault = false
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by rtribotte** [comment] 2021-01-19 08:52
Hello @ericlathrop,

Thanks for your interest in Traefik!

By using a TCP router, the negotiation between Traefik and the backend only happens at layer 4. That means Traefik is not taking part in/influencing the HTTP negotiation.
Have you tried to connect directly to your service, does the ALPN negotiation also failing?

As for now, I think that the issue is not involving Traefik, and I'll close this issue as a question.

For future configuration questions please consider posting on our [community forum](https://community.traefik.io/c/traefik/traefik-v2/).

**Comment by ericlathrop** [comment] 2021-01-19 16:56
@rtribotte [ALPN negotiation happens in TLS](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation), which traefik manages. My app does not do TLS, so there's no ALPN to negotiate inside my app. A curl command to my app without traefik works correctly. The issue definitely involves traefik, please reopen this issue.

**Comment by rtribotte** [comment] 2021-01-20 14:02
Hello @ericlathrop,

Sorry for that, I can reproduce your issue.

For more insights, the TLS config used for the TLS termination is by default defined with "h2" in the list of application level protocols, as well as other protocols.
This makes Traefik negotiating HTTP/2 and forwarding HTTP/2 frames to the HTTP/1.1 backend, which leads to the error you encountered.

**Comment by abrichr** [comment] 2021-08-04 21:54
@rtribotte can you please suggest how we can prevent this from happening? @ericlathrop were you able to identify a workaround?

**Comment by ericlathrop** [comment] 2021-08-05 17:44
I was not able to identify a workaround.

**Comment by traefiker** [comment] 2021-08-20 16:24
Closed by #8383.

**Closed by traefiker** 2021-08-20 16:24 UTC
Labels: kind/bug/confirmed, area/tls, area/tcp

**Comment by rtribotte** [comment] 2021-08-20 16:37
Hello @ericlathrop @abrichr,

PR #8383 should help to work around the issue you are facing.
It introduces a new `ALPNProtocols` option which allows specifying the list of "negotiable" application protocols.
Could you try configuring a TLS Options with only "http/1.1" configured?
You'll find the documentation [here](https://doc.traefik.io/traefik/v2.5/https/tls/#alpn-protocols).

**Comment by rtribotte** [comment] 2021-08-20 16:38
The feature will be released with the new v2.5.1.

**Comment by ericlathrop** [comment] 2021-09-06 20:45
@rtribotte Per the docs, I added this to the bottom of my `traefik.toml`:

```
[tls.options]
  [tls.options.default]
    alpnProtocols = ["http/1.1"]
```

then restarted traefik. Nothing appears to have changed. I still get the `* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.` error as described above.

**Comment by ldez** [comment] 2021-09-07 06:22
`[tls.options]` is a part of the dynamic configuration.

With the v2, the [dynamic configuration](https://docs.traefik.io/v2.5/getting-started/configuration-overview/#the-dynamic-configuration) and the [static configuration](https://docs.traefik.io/v2.5/getting-started/configuration-overview/#the-static-configuration) must be defined in separated files

**Comment by ericlathrop** [comment] 2021-09-07 16:39
I tried setting the configuration in my docker labels, but was blocked by #5507. I'll see if I can setup a dynamic config file next.

**Comment by ericlathrop** [comment] 2021-09-07 18:28
I got it working with the dynamic configuration file. Is there a way to only make it apply to a single service?

**Comment by rtribotte** [comment] 2021-09-08 07:13
@ericlathrop The TLS option is configurable on a router, maybe you are looking for this label:
`"traefik.http.routers.myrouter.tls.options=foobar"`
With this label, you'll be able to specify a TLS Option for each router.
See https://doc.traefik.io/traefik/v2.5/routing/providers/docker/#routers

If you have defined the `default` TLSOption, it is by default used for all your routers.
