### ISSUE TITLE
Bug: Traefik pilot not responsive and sluggish

### ISSUE THREAD

**Issue by daniel-wtd** [traefik/traefik#8188] opened 2021-06-15 14:25 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to access metrics or register a new instance to pilot.traefik.io. The website is quite unresponsiv and registering new instances takes ages. Sometimes the page does not load at all, but provides error messages:

`Error fetching Traefik proxies. Please try again later or contact the support team.`

i can also see different console errors like:

```
XHR 502 Bad Gateway
```
for links to:

- https://pilot.traefik.io/api/services/tokens/?
- https://pilot.traefik.io/api/services/subscriptions/
- https://pilot.traefik.io/api/services/instances/?token=SOMETOKEN

This happens on different pages like:

- instances
- metrics
- alerts
- plugins

This issue is present for ~2 weeks now. I can reproduce it from different locations.

Would be awesome, if you can have a look or advise what's going on. Please feel free to reach out to me for more information, if needed.

### What did you expect to see?

That it works again like 2 weeks ago ;)

### What did you see instead?

Error messages like "Error fetching Instances. Please try again later or contact the support team."

### Output of `traefik version`: (_What version of Traefik are you using?_)

different versions for testing

```
2.3.7
through
2.4.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

not applicable

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

not applicable

**Comment by SantoDE** [comment] 2021-06-15 14:44
Thanks for the report. We are investigating

**Comment by ldez** [comment] 2021-06-15 15:17
Hello,

The problem is fixed now. Thank you for the report :+1:

**Closed by ldez** 2021-06-15 15:17 UTC
Labels: area/pilot, kind/bug/confirmed

**Comment by daniel-wtd** [comment] 2021-06-15 15:52
Awesome, that was a quick fix. Thanks a lot!
