### ISSUE TITLE
Add middleware ratelimit for TCP

### ISSUE THREAD

**Issue by xzycn** [traefik/traefik#9610] opened 2022-12-16 04:17 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We have the ratelimit middleware for HTTP currently, can we have one for TCP?
We need to do traffic controll for TCP with match-rules like port、client IP、CIDR、etc.
Thanks.

**Comment by ldez** [comment] 2022-12-16 09:14
Duplicate of #5999

**Closed by ldez** 2022-12-16 09:14 UTC
Labels: resolution/duplicate
