### ISSUE TITLE
Move traefik images from docker hub to a different repository

### ISSUE THREAD

**Issue by r0bj** [traefik/traefik#9234] opened 2022-08-07 02:46 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Move traefik images to a different repository (quay.io, ghcr.io, etc.) due to docker hub rate limiting. Alternatively store images on those alternative registries as an additional option.

It seems that traefik image are not exempt from rate limiting (due to being open source project):
```
$ TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/traefik:pull" | jq -r .token)
$ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/library/traefik/manifests/2.8.1
HTTP/1.1 200 OK
content-length: 7569
content-type: application/vnd.docker.distribution.manifest.v1+prettyjws
docker-content-digest: sha256:90cb87c1df9f9f358e2ec0dd78602fe25a6ed32135ae6f8c215be002409c79be
docker-distribution-api-version: registry/2.0
etag: "sha256:90cb87c1df9f9f358e2ec0dd78602fe25a6ed32135ae6f8c215be002409c79be"
date: Sun, 07 Aug 2022 02:40:38 GMT
strict-transport-security: max-age=31536000
ratelimit-limit: 100;w=21600
ratelimit-remaining: 100;w=21600
docker-ratelimit-source: 74.120.190.3
```

Docker hub rate limiting is a pain for k8s and requires additional logic (e.g. mirror or clone images) to handle images just to avoid unpleasant consequences.

**Comment by ldez** [comment] 2022-08-07 02:56
duplicate of #8149

**Closed by ldez** 2022-08-07 02:56 UTC
Labels: status/0-needs-triage
