### ISSUE TITLE
request interrupt

### ISSUE THREAD

**Issue by wwdz** [traefik/traefik#8909] opened 2022-04-02 09:40 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

To create an ingressroutetcp, for example: redis, you need to create an entrypoint correspondingly, and then you need to restart traefik, but the restart will cause the request to be interrupted. Does this support hot update?

**Comment by ldez** [comment] 2022-04-02 10:14
Duplicate of #6551

**Closed by ldez** 2022-04-02 10:14 UTC
Labels: resolution/duplicate
