### ISSUE TITLE
Kubernetes Ingress: multiple hosts with wildcard not working

### ISSUE THREAD

**Issue by tillepille** [traefik/traefik#7745] opened 2021-01-12 11:13 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured a Ingress like below, background is that `staging.example.org` is my staging env, `*.staging.example.org` is used for sandboxes like `feature-abc.staging.example.org`. This service should be receive requests for both use cases.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  managedFields:
  name: image-ingress
spec:
  rules:
  - host: staging.example.org
    http:
      paths:
      - backend:
          serviceName: image-service
          servicePort: 80
        path: /uploads/image/
  - host: '*.staging.example.org'
    http:
      paths:
      - backend:
          serviceName: image-service
          servicePort: 80
        path: /uploads/image/
```

### What did you expect to see?

- Requests routed to `image-service` for both `staging.example.org/uploads/image/some-image.jpg` as well as `new-feature.staging.example.org/uploads/image/some-image.jpg`
- A router in the dashboard which reflects the defined rules

### What did you see instead?

Only requests for `new-feature.staging.example.org/...` are routed to the correct service.

Requests to `staging.example.org/...` are **not** routed to this service and seem to be handled by another ingress 

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  managedFields:
  name: main-ingress
spec:
  rules:
  - host: staging.example.org
    http:
      paths:
      - backend:
          serviceName: main-service
          servicePort: 80
        path: /
```

When using two seperate ingress documents, it works fine. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.3.3
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-19T17:43:21Z
OS/Arch:      linux/amd64
/ # 
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

only file based configuration used: 

```yaml
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: '/certs/default.crt' 
            keyFile: '/certs/default.key'
```

AKS (Kubernetes by Azure) 1.19.3

**Comment by kevinpollet** [comment] 2021-01-12 11:50
Duplicate of #7691

**Closed by kevinpollet** 2021-01-12 11:50 UTC
Labels: status/0-needs-triage
