### ISSUE TITLE
1.7.26 memory usage grows even under decreasing load

### ISSUE THREAD

**Issue by emalihin** [traefik/traefik#7481] opened 2020-10-28 09:12 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Updated Traefik from 1.7.14 to 1.7.26 on EKS

### What did you expect to see?
Normal memory usage, as before

### What did you see instead?
Memory usage spins out of control, reaching ~30GB on some nodes, Traefik being OOM killed

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.26
Codename:     maroilles
Go version:   go1.14.6
Built:        2020-07-28_03:45:27PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
        - --debug
        - --ping
        - --ping.entrypoint=http
        - --kubernetes
        - --api=true
        - --api.dashboard=true
        - --retry.attempts=3
        - --respondingtimeouts.idletimeout=360s
        - --logLevel=ERROR
        - --traefikLog.format=json
        - --accessLog.format=json
        - --accessLog.filters.statusCodes=200-600
        - --accessLog.filters.retryAttempts=true
        - --accessLog.fields.defaultMode=keep
        - --accessLog.fields.names="Username=drop"
        - --accessLog.fields.headers.defaultMode=keep
        - --accessLog.fields.headers.names="User-Agent=redact Authorization=drop Content-Type=keep"
        - --tracing.backend=datadog
        - --tracing.spanNameLimit=100
        - --tracing.datadog.globalTag=env:production
        - --tracing.datadog.prioritySampling=true
        - --tracing.datadog.localAgentHostPort=datadog-svc:8126
        - --insecureSkipVerify=true
```
EKS (k8s v1.16.13)
574 Frontends, 577 Backends
Traefik is behind ALB
SSL is terminated before Traefik

Before (1.7.14) and after (1.7.26) upgrade:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/6379998/97414692-f96e7600-190c-11eb-9f66-f168887aa608.png">

Example of a single fresh pod memory usage alongside with the traffic pattern:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/6379998/97415232-a1843f00-190d-11eb-8d74-4817cfdb3e66.png">

Same pod as above, memory usage alongside CPU usage:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/6379998/97420615-32f6af80-1914-11eb-8fec-d45c4a547699.png">

```
(pprof) inuse_space
(pprof) top
Showing nodes accounting for 2.86GB, 87.44% of 3.27GB total
Dropped 255 nodes (cum <= 0.02GB)
Showing top 10 nodes out of 73
      flat  flat%   sum%        cum   cum%
    1.72GB 52.47% 52.47%     1.72GB 52.47%  github.com/containous/traefik/vendor/github.com/codahale/hdrhistogram.New
    0.34GB 10.35% 62.82%     0.34GB 10.35%  bytes.(*Buffer).String
    0.22GB  6.72% 69.55%     0.22GB  6.72%  regexp/syntax.(*compiler).inst
    0.21GB  6.33% 75.88%     0.21GB  6.33%  regexp.onePassCopy
    0.11GB  3.45% 79.33%     0.11GB  3.45%  github.com/containous/traefik/vendor/github.com/vulcand/oxy/utils.CopyURL
    0.07GB  2.17% 81.50%     0.08GB  2.51%  regexp.makeOnePass.func1
    0.07GB  2.09% 83.59%     0.07GB  2.09%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).replaceEscapes
    0.06GB  1.78% 85.37%     0.06GB  1.78%  github.com/containous/traefik/vendor/github.com/containous/mux.(*Router).NewRoute
    0.04GB  1.28% 86.65%     0.04GB  1.28%  github.com/containous/traefik/vendor/github.com/vulcand/oxy/forward.New
    0.03GB  0.79% 87.44%     0.03GB  0.79%  fmt.Sprintf
```

```
(pprof) alloc_space
(pprof) top
Showing nodes accounting for 776.33GB, 61.31% of 1266.28GB total
Dropped 1083 nodes (cum <= 6.33GB)
Showing top 10 nodes out of 120
      flat  flat%   sum%        cum   cum%
  143.52GB 11.33% 11.33%   143.52GB 11.33%  github.com/containous/traefik/provider/kubernetes.getAnnotationName (inline)
  120.55GB  9.52% 20.85%   120.55GB  9.52%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).replaceEscapes
   86.69GB  6.85% 27.70%   339.33GB 26.80%  github.com/containous/traefik/provider/kubernetes.(*Provider).loadIngresses
   81.83GB  6.46% 34.16%    81.83GB  6.46%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).setValue
   64.91GB  5.13% 39.29%    64.91GB  5.13%  github.com/containous/traefik/vendor/github.com/codahale/hdrhistogram.New
   63.52GB  5.02% 44.30%    90.97GB  7.18%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).setType
   61.75GB  4.88% 49.18%    61.75GB  4.88%  bytes.makeSlice
   58.14GB  4.59% 53.77%    58.14GB  4.59%  strings.(*Builder).grow (inline)
   50.20GB  3.96% 57.74%    50.20GB  3.96%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.lexSkip
   45.21GB  3.57% 61.31%   390.03GB 30.80%  github.com/containous/traefik/vendor/github.com/BurntSushi/toml.(*parser).topLevel```

**Comment by rtribotte** [comment] 2020-10-28 16:20
Hello @emalihin,

Thanks for your contribution, but your issue seems to be a duplicate of #7191, as you mentioned it, so i will close it accordingly.

**Closed by rtribotte** 2020-10-28 16:20 UTC
Labels: status/0-needs-triage
