### ISSUE TITLE
Middlewares: IpAllowList doesn't work with localhost

### ISSUE THREAD

**Issue by PaulMarisOUMary** [traefik/traefik#10653] opened 2024-04-22 16:43 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

After configuring the `localnetwork` middleware with the following settings:
```
sourceRange:
  - "127.0.0.1/32"
  - "192.168.1.0/24"
```
(Complete minimal configuration below)

1. Attempt to access the service from the browser using http://127.0.0.1:8080.
    -> `Forbidden`
2. Still from localhost:
    ```bash
    $ curl -k http://127.0.0.1:8080/dashboard/#/
    Forbidden
    ```
3. From another machine:
    ```bash
    $ curl -k http://192.168.1.5:8080/dashboard/#/ 
    <!DOCTYPE html><html>[...]</html>
    ```

*This issue mirrors a similar scenario discussed in a [Traefik community forum post](https://community.traefik.io/t/traefik-in-docker-gets-docker-network-ip-instead-of-real-one-randomly/21540)*

### What did you see instead?

Access is denied (Forbidden 403) when the request originates **only** from localhost (127.0.0.1).

Requests from localhost should be permitted by the middleware to access the service without encountering a 403 Forbidden error.

### What version of Traefik are you using?

Version:      2.11.2
Codename:     mimolette
Go version:   go1.22.2
Built:        2024-04-11T15:38:45Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

`traefik.yml`
```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  format: common
  filePath: /etc/traefik/logs/traefik.log

accessLog:
  format: common
  filePath: /etc/traefik/logs/access.log
  bufferingSize: 4096

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

  traefik:
    address: ":8080"
    http:
      middlewares:
        - "localnetwork@file"

api:
  dashboard: true
  insecure: true
  debug: true

http:
  middlewares:
    localnetwork:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.0/24"
        ipStrategy:
          depth: 0

providers:
  docker:
    exposedByDefault: false
    network: traefik-bridge
    watch: true
  file:
    directory: /etc/traefik
    filename: traefik.yml
    watch: true
```

`compose.yml`
```yml
services:
  reverse-proxy:
    image: traefik:v2.11.2
    container_name: traefik-orchestrator
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik

networks:
  traefik-bridge:
    external: true
```

```
$ tree /etc/traefik
.
├── compose.yml
├── logs
│   ├── access.log
│   └── traefik.log
└── traefik.yml
```

### If applicable, please paste the log output in DEBUG level

`logs\access.log`
```
172.24.0.1 - - [22/Apr/2024:16:21:30 +0000] "GET /v1/health HTTP/1.1" 403 9 "-" "-" 1 "dashboard@internal" "-" 0ms
172.24.0.1 - - [22/Apr/2024:16:21:35 +0000] "GET /dashboard/ HTTP/1.1" 403 9 "-" "-" 2 "dashboard@internal" "-" 0ms
172.24.0.1 - - [22/Apr/2024:16:21:35 +0000] "GET /favicon.ico HTTP/1.1" 403 9 "-" "-" 3 "dashboard@internal" "-" 0ms
```
`logs\traefik.log`
```
time="2024-04-22T16:21:28Z" level=info msg="Traefik version 2.11.2 built on 2024-04-11T15:38:45Z"
time="2024-04-22T16:21:28Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"middlewares\":[\"localnetwork@file\"]},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"readTimeout\":\"1m0s\",\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"traefik-bridge\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/etc/traefik\",\"watch\":true,\"filename\":\"traefik.yml\"}},\"api\":{\"insecure\":true,\"dashboard\":true,\"debug\":true},\"log\":{\"level\":\"DEBUG\",\"filePath\":\"/etc/traefik/logs/traefik.log\",\"format\":\"common\"},\"accessLog\":{\"filePath\":\"/etc/traefik/logs/access.log\",\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}},\"bufferingSize\":4096}}"
time="2024-04-22T16:21:28Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2024-04-22T16:21:28Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2024-04-22T16:21:28Z" level=debug msg="Starting TCP Server" entryPointName=websecure
time="2024-04-22T16:21:28Z" level=info msg="Starting provider *file.Provider"
time="2024-04-22T16:21:28Z" level=debug msg="*file.Provider provider configuration: {\"directory\":\"/etc/traefik\",\"watch\":true,\"filename\":\"traefik.yml\"}"
time="2024-04-22T16:21:28Z" level=debug msg="Starting TCP Server" entryPointName=traefik
time="2024-04-22T16:21:28Z" level=debug msg="Starting TCP Server" entryPointName=web
time="2024-04-22T16:21:28Z" level=debug msg="add watcher on: /etc/traefik"
time="2024-04-22T16:21:28Z" level=debug msg="add watcher on: /etc/traefik/cloudflare.env"
time="2024-04-22T16:21:28Z" level=debug msg="add watcher on: /etc/traefik/compose.yml"
time="2024-04-22T16:21:28Z" level=debug msg="add watcher on: /etc/traefik/traefik.yml"
time="2024-04-22T16:21:29Z" level=info msg="Starting provider *traefik.Provider"
time="2024-04-22T16:21:29Z" level=debug msg="*traefik.Provider provider configuration: {}"
time="2024-04-22T16:21:29Z" level=info msg="Starting provider *docker.Provider"
time="2024-04-22T16:21:29Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"traefik-bridge\",\"swarmModeRefreshSeconds\":\"15s\"}"
time="2024-04-22T16:21:29Z" level=debug msg="Configuration received: {\"http\":{\"middlewares\":{\"localnetwork\":{\"ipAllowList\":{\"sourceRange\":[\"127.0.0.1/32\",\"192.168.1.0/24\"],\"ipStrategy\":{}}}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=file
time="2024-04-22T16:21:29Z" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":9223372036854775806},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":9223372036854775805},\"debug\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/debug`)\",\"priority\":9223372036854775806}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}},\"models\":{\"traefik\":{\"middlewares\":[\"localnetwork@file\"]}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=internal
time="2024-04-22T16:21:29Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2024-04-22T16:21:29Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {}"
time="2024-04-22T16:21:29Z" level=debug msg="Provider connection established with docker 26.0.0 (API 1.45)" providerName=docker
time="2024-04-22T16:21:29Z" level=debug msg="Filtering disabled container" providerName=docker container=reverse-proxy-traefik-orchestrator-4dcd93f4f249f81e4ee849727ca81117f3e61221ae807cbae2fa09270d8b24d3
time="2024-04-22T16:21:29Z" level=debug msg="Could not find network named \"traefik-bridge\" for container \"/portainer-orchestrator\". Maybe you're missing the project's prefix in the label?" serviceName=portainer-portainer container=portainer-portainer-f0239f86cd59cb23ffd4b9b044b0f076058f649ed5dd381b6b3515b096fb3d42 providerName=docker
time="2024-04-22T16:21:29Z" level=warning msg="Defaulting to first available network (&{\"portainer_default\" \"172.18.0.2\" '\\x00' \"\" \"0898d0b46f9352db153029e9f7e84eb5f794c56c91fc2122662c71caba263808\"}) for container \"/portainer-orchestrator\"." providerName=docker serviceName=portainer-portainer container=portainer-portainer-f0239f86cd59cb23ffd4b9b044b0f076058f649ed5dd381b6b3515b096fb3d42
time="2024-04-22T16:21:29Z" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"server\":{\"entryPoints\":[\"web\",\"websecure\"],\"service\":\"portainer-portainer\",\"rule\":\"Host(`port.localhost`)\"}},\"services\":{\"portainer-portainer\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.18.0.2:8000\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=docker
time="2024-04-22T16:21:29Z" level=debug msg="No default certificate, fallback to the internal generated certificate" tlsStoreName=default
time="2024-04-22T16:21:29Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing entryPointName=traefik routerName=debug@internal middlewareType=TracingForwarder
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" entryPointName=traefik routerName=debug@internal middlewareName=localnetwork@file middlewareType=IPAllowLister
time="2024-04-22T16:21:29Z" level=debug msg="Setting up IPAllowLister with sourceRange: [127.0.0.1/32 192.168.1.0/24]" middlewareType=IPAllowLister entryPointName=traefik routerName=debug@internal middlewareName=localnetwork@file
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik middlewareName=localnetwork@file routerName=debug@internal
time="2024-04-22T16:21:29Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareType=TracingForwarder entryPointName=traefik routerName=api@internal middlewareName=tracing
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" entryPointName=traefik routerName=api@internal middlewareName=localnetwork@file middlewareType=IPAllowLister
time="2024-04-22T16:21:29Z" level=debug msg="Setting up IPAllowLister with sourceRange: [127.0.0.1/32 192.168.1.0/24]" entryPointName=traefik routerName=api@internal middlewareName=localnetwork@file middlewareType=IPAllowLister
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" middlewareName=localnetwork@file entryPointName=traefik routerName=api@internal
time="2024-04-22T16:21:29Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" entryPointName=traefik routerName=dashboard@internal middlewareName=tracing middlewareType=TracingForwarder
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal middlewareType=StripPrefix
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2024-04-22T16:21:29Z" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik middlewareName=dashboard_redirect@internal routerName=dashboard@internal
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" routerName=dashboard@internal middlewareName=localnetwork@file middlewareType=IPAllowLister entryPointName=traefik
time="2024-04-22T16:21:29Z" level=debug msg="Setting up IPAllowLister with sourceRange: [127.0.0.1/32 192.168.1.0/24]" middlewareType=IPAllowLister entryPointName=traefik routerName=dashboard@internal middlewareName=localnetwork@file
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" middlewareName=localnetwork@file entryPointName=traefik routerName=dashboard@internal
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=traefik
time="2024-04-22T16:21:29Z" level=debug msg="No default certificate, fallback to the internal generated certificate" tlsStoreName=default
time="2024-04-22T16:21:29Z" level=debug msg="Added outgoing tracing middleware api@internal" routerName=api@internal middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" routerName=api@internal entryPointName=traefik middlewareName=localnetwork@file middlewareType=IPAllowLister
time="2024-04-22T16:21:29Z" level=debug msg="Setting up IPAllowLister with sourceRange: [127.0.0.1/32 192.168.1.0/24]" middlewareType=IPAllowLister routerName=api@internal entryPointName=traefik middlewareName=localnetwork@file
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=api@internal middlewareName=localnetwork@file
time="2024-04-22T16:21:29Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=dashboard@internal
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" middlewareType=StripPrefix entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal entryPointName=traefik
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2024-04-22T16:21:29Z" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_redirect@internal entryPointName=traefik
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=localnetwork@file middlewareType=IPAllowLister
time="2024-04-22T16:21:29Z" level=debug msg="Setting up IPAllowLister with sourceRange: [127.0.0.1/32 192.168.1.0/24]" entryPointName=traefik routerName=dashboard@internal middlewareName=localnetwork@file middlewareType=IPAllowLister
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" middlewareName=localnetwork@file entryPointName=traefik routerName=dashboard@internal
time="2024-04-22T16:21:29Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=debug@internal
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" routerName=debug@internal middlewareType=IPAllowLister middlewareName=localnetwork@file entryPointName=traefik
time="2024-04-22T16:21:29Z" level=debug msg="Setting up IPAllowLister with sourceRange: [127.0.0.1/32 192.168.1.0/24]" entryPointName=traefik routerName=debug@internal middlewareType=IPAllowLister middlewareName=localnetwork@file
time="2024-04-22T16:21:29Z" level=debug msg="Adding tracing to middleware" middlewareName=localnetwork@file routerName=debug@internal entryPointName=traefik
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" middlewareType=Pipelining entryPointName=web routerName=server@docker serviceName=portainer-portainer middlewareName=pipelining
time="2024-04-22T16:21:29Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=server@docker serviceName=portainer-portainer
time="2024-04-22T16:21:29Z" level=debug msg="Creating server 0 http://172.18.0.2:8000" entryPointName=web routerName=server@docker serviceName=portainer-portainer serverName=0
time="2024-04-22T16:21:29Z" level=debug msg="child http://172.18.0.2:8000 now UP"
time="2024-04-22T16:21:29Z" level=debug msg="Propagating new UP status"
time="2024-04-22T16:21:29Z" level=debug msg="Added outgoing tracing middleware portainer-portainer" middlewareName=tracing middlewareType=TracingForwarder routerName=server@docker entryPointName=web
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
time="2024-04-22T16:21:29Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=websecure
time="2024-04-22T16:21:30Z" level=debug msg="Rejecting IP 172.24.0.1: \"172.24.0.1\" matched none of the trusted IPs" middlewareType=IPAllowLister middlewareName=localnetwork@file
time="2024-04-22T16:21:35Z" level=debug msg="Rejecting IP 172.24.0.1: \"172.24.0.1\" matched none of the trusted IPs" middlewareName=localnetwork@file middlewareType=IPAllowLister
time="2024-04-22T16:21:35Z" level=debug msg="Rejecting IP 172.24.0.1: \"172.24.0.1\" matched none of the trusted IPs" middlewareType=IPAllowLister middlewareName=localnetwork@file
time="2024-04-22T16:21:38Z" level=info msg="I have to go..."
time="2024-04-22T16:21:38Z" level=info msg="Stopping server gracefully"
time="2024-04-22T16:21:38Z" level=debug msg="Waiting 10s seconds before killing connections." entryPointName=web
time="2024-04-22T16:21:38Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2024-04-22T16:21:38Z" level=debug msg="Waiting 10s seconds before killing connections." entryPointName=websecure
time="2024-04-22T16:21:38Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2024-04-22T16:21:38Z" level=debug msg="Entry point web closed" entryPointName=web
time="2024-04-22T16:21:38Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2024-04-22T16:21:38Z" level=debug msg="Waiting 10s seconds before killing connections." entryPointName=traefik
time="2024-04-22T16:21:38Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2024-04-22T16:21:38Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2024-04-22T16:21:38Z" level=debug msg="Entry point websecure closed" entryPointName=websecure
time="2024-04-22T16:21:38Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2024-04-22T16:21:39Z" level=debug msg="Entry point traefik closed" entryPointName=traefik
time="2024-04-22T16:21:39Z" level=info msg="Server stopped"
time="2024-04-22T16:21:39Z" level=info msg="Shutting down"
```

**Comment by lbenguigui** [comment] 2024-04-25 13:58
Hello @PaulMarisOUMary ,

Thanks for your interest in Traefik.

After reviewing your logs, it seems that the issue is related to your Docker configuration, as the IP address used when calling from localhost belongs to the Docker network (172.24.0.1), resulting in a forbidden response from the middleware.

I suggest seeking assistance on the [community forum](https://community.traefik.io/) which is highly active. There's a good chance your question has already been addressed there. If not, you can quickly get help from other community members by posting your query.

I am closing this issue as a question, feel free to add comment if needed.

**Closed** 2024-04-25 13:58 UTC
Labels: kind/question, area/middleware
