### ISSUE TITLE
Certificate expiration date in dashboard

### ISSUE THREAD

**Issue by OneCreek** [traefik/traefik#11341] opened 2024-12-13 13:59 UTC
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be great to have an overview of the issued certificates stored in the acme.json in the dashboard with some values like domain, storage, resolver name, challenge method, as well as issue and expiration date. 

Also just the last two info's would be helpful, but the more details the better of course. 

Explanation: helps to get an overview of current issues certificates and expiration the date when needed - especially when Debugging. 

Best regards, Michael

**Comment by nmengin** [comment] 2024-12-16 13:32
Duplicate of #6156

**Closed by nmengin** 2024-12-16 13:32 UTC
Labels: status/0-needs-triage
