### ISSUE TITLE
Pork bun API update

### ISSUE THREAD

**Issue by twillist** [traefik/traefik#11255] opened 2024-11-06 04:57 UTC
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm using an http challenge to generate certificates with Porkbun got a notice they are changing their API. 

### What did you see instead?

Here's the notice:

CRITICAL UPDATE DETAILS

Type: API Hostname Change

Old Value: porkbun.com

New Value: api.porkbun.com

Deadline: 2024-12-01 00:00:00 UTC

### What version of Traefik are you using?

Version:      3.2.0
Codename:     munster
Go version:   go1.23.2
Built:        2024-10-28T14:49:00Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by rtribotte** [comment] 2024-11-06 08:44
Hello @twillist,

Thanks for reporting this!

The required change needs to be made directly in https://github.com/go-acme/lego, so this issue should be open directly in the Lego repository.

We will close this issue accordingly.

**Closed by rtribotte** 2024-11-06 08:44 UTC
Labels: status/0-needs-triage

**Comment by ldez** [comment] 2024-11-06 10:19
Duplicate of #11194
