### ISSUE TITLE
traefik modify response headers

### ISSUE THREAD

**Issue by 993639542** [traefik/traefik#10988] opened 2024-08-09 07:40 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I hava a backend service. It provides a custom response header name 'encryptKey', the response message obtained through traefik access has become 'Encryptkey'.

### What did you see instead?

# The direct access pod message is as follows
<img width="876" alt="企业微信截图_552cd1d0-6ac0-479d-b008-722bcd595fa1" src="https://github.com/user-attachments/assets/b738fc0c-9467-4672-ad6f-27a413a8e06c">
# The traefik message is as follows
<img width="850" alt="企业微信截图_1564c0d8-1fe5-4939-8ce6-7b4fa1bf54ce" src="https://github.com/user-attachments/assets/26444010-8db0-4402-b3ad-ad724af3b21f">

### What version of Traefik are you using?

v2.9.5

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by juliens** [comment] 2024-08-12 12:39
Hello,

I think this is a duplicate of #466

You have a complete answer on this one.

**Closed by juliens** 2024-08-12 12:39 UTC
Labels: resolution/duplicate

**Comment by 993639542** [comment] 2024-08-15 06:02
> Hello,
> 
> I think this is a duplicate of #466
> 
> You have a complete answer on this one.

thanks
