### ISSUE TITLE
Traefik v3: postgres Cancel Request not handled

### ISSUE THREAD

**Issue by sjmiller609** [traefik/traefik#10280] opened 2023-12-04 19:36 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If you start a connection to Postgres, for example with psql, through a Traefik proxy, then you start a transaction, then press control + C to send interrupt to psql, psql will send a Cancel request to the server, and this cancel request is not handled in Traefik

example query:
```
create table users(name text);

DO $$
DECLARE
    -- You can declare any necessary variables here
BEGIN
    LOOP
        -- Insert command goes here
        INSERT INTO users (name) VALUES ('brian');

        -- Pause for 1 second
        PERFORM pg_sleep(1);
    END LOOP;
END$$;
```

### What did you see instead?

The cancel request is initiated, TCP handshake works. Then PGSQL Cancel request is sent. The server ACK, then FIN / ACK. TCP connection closes. I'm not sure how this ought to work in the case of required encrypted connections, routing with SNI.

Here is a filtered down pcap that shows this interaction

[cancel-request-rejected.pcapng.zip](https://github.com/traefik/traefik/files/13550544/cancel-request-rejected.pcapng.zip)

This is what a Cancel request looks like
![image](https://github.com/traefik/traefik/assets/7516283/9c9d71e8-c3a0-49a1-9ce0-af10eafa5db9)

### What version of Traefik are you using?

```
Version:      3.0.0-beta2
Codename:     beaufort
Go version:   go1.19.4
Built:        2022-12-07T16:32:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
.... omitted
spec:
  entryPoints:
  - postgresql
  routes:
  - match: HostSNI(`org-tembo-test-inst-steven.data-1.use1.tembo-development.com`)
    services:
    - name: org-tembo-test-inst-steven-rw
      port: 5432
  tls:
    passthrough: true
```

**Comment by ArpitKRS** [comment] 2023-12-14 18:06
Please /assign this issue to me and let's discuss over it.

**Comment by sjmiller609** [comment] 2024-01-08 18:51
@rtribotte We are interested to fix this issue, please let me know and the Tembo team is here to help in any way to move it forward.

**Comment by rtribotte** [comment] 2024-01-30 14:48
Hello @sjmiller609,

Thanks for reporting this and sorry for the late answer!
I was able to reproduce the issue, I'm marking this issue as `bug/confirmed`.

> @rtribotte We are interested to fix this issue, please let me know and the Tembo team is here to help in any way to move it forward.

Sure, any contribution to this would be gladly welcome!
Nonetheless, can you please explain the approach that you think should be taken?
Would recognizing the CancelRequest bytes be enough if it is only a clear text connection, Traefik will not be able to route to the correct Postgres instance. Also, because it is a new connection, even if the connection could be routed to the correct Traefik service thanks to the TLS SNI, if the service is a load-balancer of multiple servers, it seems not possible to target the right possible Postgres instance.

**Comment by sjmiller609** [comment] 2024-02-21 17:12
I have the same initial conclusions about the wire protocol seems not possible to handle the cancel request, so I will need to find more information on the postgres side to know what can be done.

**Closed** 2024-12-04 16:16 UTC
Labels: kind/bug/confirmed, priority/P3, area/server, contributor/wanted
