### ISSUE TITLE
Are you plan to develop a dashboard which can configurate routers config, middlewares  config and  services config etc？

### ISSUE THREAD

**Issue by wangfeng22** [traefik/traefik#9144] opened 2022-06-30 06:08 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I want to configurate routers, middlewares, services by traefik dashboard.

**Comment by ldez** [comment] 2022-06-30 06:10
duplicate of #2481

**Closed by ldez** 2022-06-30 06:10 UTC
Labels: status/0-needs-triage

**Comment by wangfeng22** [comment] 2022-06-30 09:23
> duplicate of #2481

Thanks for your reply. Could you tell me why are you don't develop this feature all the time?

**Comment by wangfeng22** [comment] 2022-06-30 09:24
> > duplicate of #2481
> 
> Thanks for your reply. Could you tell me why are you don't develop this feature all the time?

@ldez
