### ISSUE TITLE
Continuously request based on HTTP status until the requested URL returns 200

### ISSUE THREAD

**Issue by lysilver** [traefik/traefik#9941] opened 2023-06-09 01:54 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Assuming the first URL does not return 200, continue the request. If all URL requests are completed, regardless of the response status, the result will be returned

The middleware retry cannot meet the requirements, and the Failover service is based on health checks and cannot meet the requirements

**Comment by rtribotte** [comment] 2023-06-09 12:46
Hello @lysilver,

Thanks for your contribution!

We think that your issue is a duplicate of https://github.com/traefik/traefik/issues/4578.
We are closing it accordingly.

Duplicate of #4578

**Closed by rtribotte** 2023-06-09 12:46 UTC
Labels: status/0-needs-triage
