### ISSUE TITLE
Traefik Let's encrypt TLS Challenge failing when behind a Traefik v2.11.2+ TCP Router

### ISSUE THREAD

**Issue by CybotTM** [traefik/traefik#10964] opened 2024-08-02 06:39 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Exactly the same as in #10684 just for Traefik v2.11.2+

Running a Traefik behind a Traefik v2.11.2+

### What did you see instead?

TSL challenge failing

### What version of Traefik are you using?

v2.11.2+

### What is your environment & configuration?

Exactly the same as in #10684 just for Traefik v2.11.2+

Running a Traefik behind a Traefik v2.11.2+

**Comment by rtribotte** [comment] 2024-08-05 13:48
Hello @CybotTM,

Thanks for your interest in Traefik!

As you noticed, this issue is a duplicate of #10684.
#10684 will stand for both v2 and v3.
We are closing this issue accordingly.

**Closed by rtribotte** 2024-08-05 13:48 UTC
Labels: status/0-needs-triage
