### ISSUE TITLE
File provider doesn't detect changes in subfolders

### ISSUE THREAD

**Issue by raulgbcr** [traefik/traefik#8771] opened 2022-02-12 18:09 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Using standalone Traefik binary, create a config file, define a file provider on a folder with multiple config files in the folder and multiple subfolders with more config files. 

### What did you see instead?

Any file located in a subfolder of the folder defined in the file provider don't get detected if modified, files in the defined folder get detected and the config changes accordingly. Traefik should detect changes in all the subfolders on the watching folder, or allow a way to define multiple watched folders.

### What version of Traefik are you using?

Version:      2.6.0-rc1
Codename:     rocamadour
Go version:   go1.17.5
Built:        2021-12-20T16:10:10Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

[providers]
  [providers.file]
    directory = "**redacted**"
    watch = true

**Comment by rtribotte** [comment] 2022-02-14 08:16
Duplicate of #3986

**Closed by rtribotte** 2022-02-14 08:16 UTC
Labels: status/0-needs-triage
