### ISSUE TITLE
ForwardAuth middleware support load balancing

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [traefik/traefik#7694] opened 2020-12-19 08:16 UTC
I want middleware ForwardAuth  to support load balancing.

Currently, ForwardAuth only supports a fixed address. And does not support traefik routing and forwarding.

**Comment by AP0rPi7uQ9** [comment] 2020-12-19 08:42
ForwardAuth Unable to use load balancing by traefik

When I want to use traefik for load balancing and ForwardAuth fills in the traefik address, X-Forwarded-Uri will be overwritten and the source address cannot be found.

**Comment by SantoDE** [comment] 2020-12-22 09:35
Duplicate of #4288

**Closed by SantoDE** 2020-12-22 09:35 UTC
