### ISSUE TITLE
v2.11.2 does not accept valid configs from v2.11.1

### ISSUE THREAD

**Issue by thinkl33t** [traefik/traefik#10607] opened 2024-04-12 07:30 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Allowed traefik to automatically update after putting in a fix for yesterday's breaking change.

Our watchtower config is set up to automatically pull in patch versions, as is recommended for semver.

### What did you see instead?

All our traefik containers looping, all our services sitting behind traefik unreachable, unhappy colleagues.

Because of the lingeringTimeout breakage in `v2.11.1`, we had updated our configs to fix our infrastructure.

This release completely breaks semver agreements, `v2.11.2` should **accept** valid config from `v2.11.1`, even if it does nothing with it.

### What version of Traefik are you using?

`v2.11.2`

### What is your environment & configuration?

```yaml
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.transport.respondingTimeouts.tcp]
      lingeringTimeout = 30
```

Traefik in docker, pinned to `v2.11`.  Automatic updates via watchtower.

**Comment by ldez** [comment] 2024-04-12 07:50
duplicate of #10598

**Closed** 2024-04-12 07:50 UTC
Labels: resolution/duplicate
