### ISSUE TITLE
Extend Ingress Controller without CRD's Functionaliy

### ISSUE THREAD

**Issue by leier69** [traefik/traefik#8014] opened 2021-03-28 01:59 UTC
I Really love traffic, and one of the big reasons I do is simplicity. I would really love to see more of the traffic features im used to in the kubernetes ingress controller. With custom resources you can do about everything you can with traefik but not with the non CRD route. https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/

For a start, I would love to be able to do basic auth on my ingresses using annotations instead of having to add a file/CRD configuration source.
```
traefik.ingress.kubernetes.io/router.middlewares: auth@kubernetesingress
traefik.ingress.kubernetes.io/router.middleware.auth.basicauth.removeheader: true
traefik.ingress.kubernetes.io/router.middleware.auth.basicauth.users: "myusername:$apr1$/Lg.Otvv$JIqnwDv54rqSLapBqcOGs.", "myusername:$apr1$/Lg.Otvv$JIqnwDv54rqSLapBqcOGs."
```

I aint no Go developer, but I assume that it would not be that hard implementing, as it is already pretty much in the docker provider now. What do you guys think about implementing this?

**Comment by leier69** [comment] 2021-03-28 02:02
@ ing some people I know is very involved in problems.
@SantoDE @ldez @jbdoumenjou @rtribotte

**Comment by ldez** [comment] 2021-03-28 09:16
duplicate of #6565

**Closed** 2021-03-28 10:30 UTC
Labels: resolution/duplicate
