### ISSUE TITLE
Feature Request: Plugins without Pilot

### ISSUE THREAD

**Issue by samip5** [traefik/traefik#7895] opened 2021-02-14 21:19 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Plugin system which is not dependent on Pilot, as not everyone can and/or want to have a phone-home functionality in applications enabled, which Pilot technically is.

**Comment by ldez** [comment] 2021-02-14 23:16
duplicate of #7088

**Closed by ldez** 2021-02-14 23:16 UTC
Labels: resolution/duplicate
