### ISSUE TITLE
Docker image tag 2.9 is set, but 2.9 is still RC

### ISSUE THREAD

**Issue by etlam** [traefik/traefik#9406] opened 2022-10-01 08:56 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are using Renovate Bot to keep our dependencies up2date and we are using the traefik docker image from docker hub.

### What did you see instead?

When the 2.9 rc versions of traefik get released, a 2.9 tag gets created for docker hub.  
So dependency checkers like dependabot or renovate propose to update to 2.9 tag, but v2.9 is still in rc. 

Because of that I would propose to create a base 2.9 tag only if the released version is not alpha, beta or release candidate version.

### What version of Traefik are you using?

v2.8 from docker hub

### What is your environment & configuration?

-

**Comment by ldez** [comment] 2022-10-01 08:58
duplicate of #9353

**Closed by ldez** 2022-10-01 08:58 UTC
Labels: status/0-needs-triage
