### ISSUE TITLE
Adds tracing option for not accept upstream tracing

### ISSUE THREAD

**Issue by jcchavezs** [traefik/traefik#5925] opened 2019-12-02 15:26 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently traefik supports tracing context propagation, i.e. accepting tracing context propagation via HTTP headers:

- `X-B3-Traceid=7f46165474d11ee5836777d85df2cdab`
- `X-B3-Spanid=6164d11836d85da1`
- `X-B3-Sampled=1`

This is good if traefik is not the edge service because it can continue an existing trace but if traefik is the edge service (i.e. first point of contact with the external world), we should be defensive because accepting trace headers can force sampling decision which users can't be in control of. This is, if someone sends `X-B3-Sampled=1` as header then that trace is going to end up in tracing server storage **no matter what sampling strategy the user defined in configuration** and that is a potential attack (DDoS tracing service and/or tracing storage) and more important, the user can incur in big costs (disk, io) depending on its pricing deal.

An easy and good solution is to add a flag to all tracing backends for the user to define if they want to start a new trace every time (respecting their own sampling decision) or continue the incoming trace (for those who have traefik behind another service dealing with trace and sampling e.g. nginx). The name could be `accept_incoming_trace: bool` and globally defined for all traces.

I am up for contributing.

cc @basvanbeek @ldez

**Comment by jcchavezs** [comment] 2019-12-04 12:13
@dduportal if you agree with the naming of the option I could give it a try to the PR.

**Comment by ldez** [comment] 2019-12-04 13:18
The naming is not a real problem because it can be changed during the PR review, but the implementation is a bit more complex: I think that the behavior could be the same as [forwarded-header](https://docs.traefik.io/v2.1/routing/entrypoints/#forwarded-header).

There are a lot of questions about the implementation, but for now I have not yet thought precisely on the subject.

**Comment by jcchavezs** [comment] 2019-12-05 10:38
I see. That makes more sense actually. Then I would think of something like:

```toml
[tracing]
   [tracing.propagation]
       propagationHeaders = ["x-b3-*", "b3"]
       insecure = false
       trustedIPs = ["127.0.0.2"]
```

This will tell the tracer that if the request comes from trusted IPs (`req. RemoteAddr`) then the context should be extracted otherwise we start a new trace.

Does that make sense?

cc @worldtiki

**Comment by jcchavezs** [comment] 2020-01-09 22:15
@ldez any input on this one?

**Comment by jcchavezs** [comment] 2020-02-04 13:37
Friendly ping @ldez

**Comment by james-callahan** [comment] 2024-06-06 06:54
I'm having the opposite issue today with traefik v3: I *want* to accept a B3 header from the client, but traefik seems to insist on generating its own.
Is there some variable to select this behaviour?

**Comment by rtribotte** [comment] 2024-06-06 12:10
Hello @james-callahan,

Are you using Traefik v3? Because, in v3, OTel tracing should support propagation, and the enabled propagators can be controlled with the `OTEL_PROPAGATORS` env variable, see the [propagation](https://doc.traefik.io/traefik/v3.0/observability/tracing/opentelemetry/) section in the documentation.

**Comment by james-callahan** [comment] 2024-06-06 12:29
> Are you using Traefik v3?

yes



> OTel tracing should support propagation, and the enabled propagators can be controlled with the `OTEL_PROPAGATORS` env variable, see the [propagation](https://doc.traefik.io/traefik/v3.0/observability/tracing/opentelemetry/) section in the documentation.

Yes it does. However from my tests, traefik doesn't seem to respect existing traces, and always seems to want to start a new trace.
i.e. with `OTEL_PROPAGATORS=b3`, traefik creates a new header `B3: 0123456789abcdef-12345678-1` with random ids, ignoring any B3 headers on incoming requests

**Comment by rtribotte** [comment] 2024-06-06 13:13
@james-callahan Can you please open a specific issue for this issue with all the details that are necessary for reproduction?

@jcchavezs After discussing this feature with other maintainers, we decided to close this issue.
Since the revamp of the tracing feature with OpenTelemetry in Traefik v3, we do not think it should be the responsibility of Traefik to filter out the traces but the responsibility of the collector.

If you or anyone in the community thinks we've got something wrong here, please don't hesitate to let us know.

**Closed by rtribotte** 2024-06-06 13:13 UTC
Labels: kind/enhancement, priority/P2, area/middleware/tracing
