### ISSUE TITLE
Traefik Configuration Checks

### ISSUE THREAD

**Issue by alberk8** [traefik/traefik#10804] opened 2024-06-12 03:39 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Would be at time save if there is a built in configuration checker for traefik.  It would speed up troubleshooting.

**Comment by ldez** [comment] 2024-06-12 03:48
Hello,

You can use the JSON schema to validate your configurations.

- https://json.schemastore.org/traefik-v2.json
- https://json.schemastore.org/traefik-v2-file-provider.json

```bash
# static configuration
jv -output detailed https://json.schemastore.org/traefik-v2.json ./traefik.yml
```

```bash
# file provider configuration
jv -output detailed https://json.schemastore.org/traefik-v2-file-provider.json ./traefik.yml
```

https://github.com/santhosh-tekuri/jsonschema?tab=readme-ov-file#cli

Duplicate of #6451

**Closed** 2024-06-13 12:58 UTC
