### ISSUE TITLE
(Sub)Domains as whitelist entries

### ISSUE THREAD

**Issue by arunoruto** [traefik/traefik#9988] opened 2023-06-25 00:20 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently we can only use singles IPs or ranges with CIDR notation. It would be nice, if we could also provide domains. Those would be resolved and the resolved IP would be whitelisted.
This would help people with dynamic IPs at home or while traveling with a portable router, to provide a domain which is constantly updated with their IP (like duckdns).

**Comment by ldez** [comment] 2023-06-25 02:20
duplicate of #4145

**Closed by ldez** 2023-06-25 02:20 UTC
Labels: kind/question
