### ISSUE TITLE
Support for multiple sets of environment variables (credentials) with multiple DNS provider

### ISSUE THREAD

**Issue by SamLowryMOI** [traefik/traefik#7365] opened 2020-09-28 15:33 UTC
I have two providers who both use [RFC2136]. So I need different sets of environment variables, one for each provider. In this case these variables:
```
    RFC2136_NAMESERVER
    RFC2136_TSIG_ALGORITHM
    RFC2136_TSIG_KEY
    RFC2136_TSIG_SECRET
```
It would be very nice if I could set the variables in the corresponding certificatesResolver. I think they actually belong there. In this way you could use different DNS providers of the same type (rfc2136, route53, digitalocean, azure, etc.) in one traefic instance.

Is there any chance of this feature? I think lego has to implement this, too. Maybe pass the parameters when lego is called instead of environment variables? Or in traefik changing the environment variables before calling lego? 

Hope I'm not the only one who want this feature! Thanks a lot!

**Comment by ldez** [comment] 2020-09-28 16:19
duplicate of  #5472

**Closed by ldez** 2020-09-28 16:19 UTC
Labels: status/0-needs-triage
