### ISSUE TITLE
Traefik v3.0 breaks existing `cert-manager` integrations

### ISSUE THREAD

**Issue by sebadob** [traefik/traefik#10702] opened 2024-05-07 19:25 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was using Traefik v2 for a long time together with `cert-manager` inside Kubernetes.

For my usual routes, I am using the `IngressRoute` CRD which works perfectly fine again after I followed the migration guide.  
However, all my existing `cert-manager` integrations and automatic certificate renewals in the whole cluster stopped working silently. The `acme-solver`s created by the `cert-manager` are default Kubernetes Ingress and they have not changed at all. I just noticed this today after a certificate could not be renewed for a very long time and gut stuck.

The Ingress they create is nothing special and as mentioned this has not changed, I have not done any other updates to the cluster than Traefik v3.0 since this problem came up.

### What did you see instead?

It seems that the Ingress route is simply ignored. I tried by removing all existing `IngressRoutes` in the same namespace and only leaving the auto-created Ingress for a testing certificate. I tried to manually debug the whole flow and see where it gets stuck and it was for sure Traefik v3.0.  
I am using the Helm Chart to deploy Traefik and `providers.kubernetesIngress.enabled` is set to true and is the default value in there.

The auto-created spec looks like this:

```yaml
spec:
  rules:
  - host: host.example.com
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-qrg6m
            port:
              number: 8089
        path: /.well-known/acme-challenge/als2om6EN1LVdx548XZESnj9DkuHh3idOaexEcaFkmI
        pathType: ImplementationSpecific
```

I usually have https-redirects for each host name and as soon as I added the IngressRoute again, I got back the HTTP 301 from it, even though I should have gotten the acme challenge. But as mentioned even without this redirect route I alway received a `404 page not found`.

I am using a very nasty workaround everywhere now so I can at least get my certificates renewed. This is simply ignoring the auto-created Ingres resources and I manually added the following IngressRoute definitions to at least make it working again:

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-redirect
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`host.example.com`) && !PathPrefix(`/.well-known/acme-challenge/`)
      kind: Rule
      middlewares:
        - name: https-only
          namespace: traefik
      services:
        - name: some-service
          port: 3000
    - match: Host(`host.example.com`) && PathPrefix(`/.well-known/acme-challenge/`)
      kind: Rule
      services:
        - name: acme-svc-workaround
          port: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: acme-svc-workaround
spec:
  selector:
    acme.cert-manager.io/http01-solver: "true"
  ports:
    - name: http
      port: 8089
      targetPort: 8089
```

This solution is very brittle and tedious though.  
I was very lucky that the failed certificate over night was on some staging environment instead of production.

### What version of Traefik are you using?

Helm Chart version:  
traefik-28.0.0

App-Version:  
3.0.0

### What is your environment & configuration?

Custom `values.yaml`:

```yaml
globalArguments:
  - --global.checknewversion
  - --accesslog.fields.names.StartUTC=drop

deployment:
  kind: DaemonSet
  minReadySeconds: 3

podDisruptionBudget:
  enabled: true
  maxUnavailable: 2

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true

env:
  - name: TZ
    value: Europe/Berlin

logs:
  general:
    level: INFO
  access:
    enabled: true
    bufferingSize: 100
    filters:
      statuscodes: "300-599"
      minduration: 1ms
    fields:
      headers:
        defaultmode: drop
        names:
          User-Agent: keep

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

service:
  enabled: true
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local

ports:
  websecure:
    asDefault: true
    http3:
      enabled: true

podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - traefik
      topologyKey: failure-domain.beta.kubernetes.io/zone
```

**Comment by stellirin** [comment] 2024-05-26 12:37
I have the same setup with Cert Manager and I also see this behaviour in the newly released 3.0.1, I saw it since at least `3.0.0-rc3`. I see 404 in the Traefik logs on requests to `/.well-known/acme-challenge/.*` paths. My workaround is similar, I copy the generated rule to my `IngressRoute`. Fortunately I have only a handful of certificates to manage.

**Comment by sebadob** [comment] 2024-05-26 13:35
I don't think it's related to cert-manager at all, just to the default ingress class for kubernetes.  
I just have this problem with cert-manager, because it creates the default ingress instead of the `IngressRoute` CRD.

**Comment by jeansebastienh** [comment] 2024-05-27 11:39
Yes that's an issue with IngressRoute.

As Traefik v3 changes the API from  `traefik.containo.us/v1alpha1` to `traefik.io/v1alpha1`. Previous IngressRoutes are ignored.

I wrote a little migration script (note: I'm considering here that the IR and the namespace name are equal)

```
# Create a new IR with the proper API
for irname in $(kubectl get ingressroutes.traefik.containo.us --all-namespaces -o json | jq '.items | .[] | .metadata.name' -r); do kubectl -n ${irname} get ingressroute ${irname} -oyaml  | grep -v -e "uid:" -e "resourceVersion:" -e "generation:" -e "creationTimestamp" | sed 's/.containo.us/.io/' | kubectl -n ${irname} apply -f -; done
# Delete the previous one
for irname in $(kubectl get ingressroutes.traefik.containo.us --all-namespaces -o json | jq '.items | .[] | .metadata.name' -r); do kubectl -n ${irname} delete ingressroutes.traefik.containo.us ${irname}; done
```

**Comment by sebadob** [comment] 2024-05-28 07:13
> Yes that's an issue with IngressRoute.

No it's not, all the `IngressRoute`s work fine after the migration. It's the default `Ingress` class not being taken into account for the routing.

**Comment by rtribotte** [comment] 2024-07-15 08:56
> I have the same setup with Cert Manager and I also see this behaviour in the newly released 3.0.1, I saw it since at least 3.0.0-rc3. I see 404 in the Traefik logs on requests to /.well-known/acme-challenge/.* paths. My workaround is similar, I copy the generated rule to my IngressRoute. Fortunately I have only a handful of certificates to manage.

@stellirin I think the problem you are describing is related to #10672.

**Comment by kevinpollet** [comment] 2024-07-15 09:39
Hello @sebadob,

Are you still facing this issue?

On v3 we changed the supported `IngressClass` API Group as detailed in the migration [guide](https://doc.traefik.io/traefik/migration/v2-to-v3-details/#kubernetes-ingress-api-group-networkingk8siov1beta1).
Is your k8s cluster supporting v1 `IngressClass`? which k8s version are you using?

If your cluster is not supporting v1 you should see some ERROR logs. 
Could you provide your logs in debug mode?

**Comment by sebadob** [comment] 2024-07-15 10:09
> Are you still facing this issue?

Yes, I do. I just updates to Helm Chart `29.0.1` / `Traefik 3.0.4`.

I left one of the certificates in place which I don't need anymore just to keep track of the issue.  

The example cluster is currently running K3s `v1.28.7+k3s1`.

The `Ingress` which is automatically created by `cert-manager` is of version `networking.k8s.io/v1`.  
I just replaced the URL and token with an example one in the output below.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
  creationTimestamp: "2024-07-01T19:02:14Z"
  generateName: cm-acme-http-solver-
  generation: 1
  labels:
    acme.cert-manager.io/http-domain: "1538328624"
    acme.cert-manager.io/http-token: "1378291422"
    acme.cert-manager.io/http01-solver: "true"
  name: cm-acme-http-solver-wbpnw
  namespace: nats
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: my.dns.name-tls-staging-2-1854993671-323736840
    uid: e3bed558-def9-4212-8257-c6b6b3e5f454
  resourceVersion: "49310579"
  uid: ed165167-dd6d-494c-9a62-42e3c6802021
spec:
  rules:
  - host: my.dns.name
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-xh2wg
            port:
              number: 8089
        path: /.well-known/acme-challenge/hyyjzsa2grDXN2U3DK42XY89gwp5NhWWQW5tS9MkcWk
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```

For this certificate I did not add my above workaround to the `IngressRoute`, which solves the issue for all other certificates.

I can see the `GET` to the path in the `Ingress` coming in where `cert-manager` is checking availability all the time, but Traefik simply returns a `404`:

```
10.42.0.213 - - [15/Jul/2024:11:52:45 +0200] "GET /.well-known/acme-challenge/hyyjzsa2grDXN2U3DK42XY89gwp5NhWWQW5tS9MkcWk HTTP/1.1" 404 19 "-" "cert-manager-challenges/v1.14.4 (linux/amd64) cert-manager/f5ddc412723722518f401f9ce6ec6fc950e72c04" 10 "-" "-" 0ms
```

I do not really like publishing debug logs here because they would contain sensitive information, but I took a look at them.
If seems that Traefik is automatically adding certificates for all domains I am using in my `IngressRoute`s automatically while at the same time complaining about no configured store, which makes sense because I am using `cert-manager` for this purpose.  
Could this be intercepting the routes to `/.well-known/acme-challenge/` ?

If debug logs would really help you here, I could strip all domains and change them to example ones, but I am not really sure if I might leak something else with them.

**Comment by kevinpollet** [comment] 2024-07-16 07:47
> It seems that Traefik is automatical ly adding certificates for all domains I am using in my IngressRoutes while at the same time complaining about no configured store, which makes sense because I am using cert-manager for this purpose.
Could this be intercepting the routes to /.well-known/acme-challenge/ ?

Could you elaborate on this point? are you using a [certresolver](https://doc.traefik.io/traefik/v2.11/https/acme/#certificate-resolvers)?

**Comment by sebadob** [comment] 2024-07-16 08:42
> Could you elaborate on this point? are you using a [certresolver](https://doc.traefik.io/traefik/v2.11/https/acme/#certificate-resolvers)?

No I am not using any certresolver, which is why these logs confused me. I am managing all my K8s internal certificates with [cert-manager](https://cert-manager.io/) which is probably the de facto standard. All of this was working super nicely with Traefik v1 and v2, but v3 is either intercepting and not forwarding the requests, or is ignoring the default kubernetes `Ingress` route that is added automatically. I see that Traefik picks them up when I take a look at the access logs, but instead of forawrding the request to the `cert-manager` pods like the `Ingress` above defines it, it returns a `404`.

As soon as I add a manual route definition to my `IngressRoute` which does the exact same thing as the auto-created `Ingress` from `cert-manager`, everythings works fine again. But I have to manually define this in each namespace while it was working perfectly fine with the older versions.

**Comment by kevinpollet** [comment] 2024-07-18 14:34
Hello @sebadob,

After multiple tests we reproduced the issue and found that it is a configuration issue. In your `values.yaml` the `websecure` entrypoint is marked as default with the `asDefault: true` option.

As explained in the [documentation](https://doc.traefik.io/traefik/routing/entrypoints/#asdefault) when an entrypoint is marked as default and a router (in this case the certmanager `Ingress`) does not specify an entrypoint, it will be only attached to the default entrypoints (in your case the `websecure` one).

Thus, the certmanager `Ingress` is only attached to the `websecure` entrypoint, but to successfully resolve the challenge it has to be attached to the `web` entrypoint.

To fix the issue you should remove the `asDefault` configuration or add the annotation `traefik.ingress.kubernetes.io/router.entrypoints: web` to the [ingressTemplate](https://cert-manager.io/docs/configuration/acme/http01/#ingresstemplate) configured in certmanager.

According to that I am closing this issue as a question.

**Closed by kevinpollet** 2024-07-18 14:34 UTC
Labels: area/acme, kind/bug/possible, area/rules

**Comment by mohamaddayoub** [comment] 2024-07-18 15:25
No it does not work. I have added this annotation to the cluster issuer under ingressTemplate but still the same i can access this URL  ('http://nginx1.example.com/.well-known/acme-challenge/jeRU8h02AJe_RNTh-GU6nX8mfDd0RxS9Xpf_f_-kl2c) from the cluster node and publicly also. but still challenge is pending.

How it is working for traefik dashboard?? (all the services withing the same IngressRoute)

**Comment by sebadob** [comment] 2024-07-18 15:26
> After multiple tests we reproduced the issue and found that it is a configuration issue. In your values.yaml the websecure entrypoint is marked as default with the asDefault: true option.

@kevinpollet oh man, thank you a lot. I totally missed that, my bad!

After removing the option, everything started working fine again.

Thanks a lot!

**Comment by mohamaddayoub** [comment] 2024-07-18 15:29
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    solvers:
    - http01:
        ingress:
          class: traefik
          ingressTemplate:
            metadata:
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: web
          
    privateKeySecretRef:
      name: letsencrypt-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: dev
spec:
  commonName: traefik.example.com
  dnsNames:
    - traefik.example.com
    - nginx1.example.com
    - nginx2.example.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-cert
  
  ---
  
  ---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`nginx1.example.com`) 
      kind: Rule
      services:
        - name: nginx-svc
          port: 80

    - match: Host(`nginx2.example.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: second-nginx
          port: 80
          
    - match: Host(`traefik.example.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: auth-dashboard
  tls: 
    secretName: tls-cert

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-dashboard
  namespace: dev
spec:
  basicAuth:
    secret: traefik-auth-dashboard
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-auth-dashboard
  namespace: dev
data:
  users: 111111

**Comment by sebadob** [comment] 2024-07-18 17:15
> commonName: traefik.example.com
> dnsNames:
> - traefik.example.com
> - nginx1.example.com
> - nginx2.example.com

@mohamaddayoub It is impossible that this could ever work, because you (most probably) don't own `example.com` and this domain does not have a valid route into your cluster. So this is probably your problem, because Let's Encrypt will never be able to reach your endpoints via `traefik.example.com`.

**Comment by mohamaddayoub** [comment] 2024-07-18 17:22
Actually i am using a proper DNS but i changed it here only.
the error in challenge logs: Waiting for HTTP-01 challenge propagation: failed to perform self check GET request 'http://nginx1.example.com/.well-known/acme-challenge/jeRU8h02AJe_RNTh-GU6nX8mfDd0RxS9Xpf_f_-kl2c': Get "http://nginx1.example.com//.well-known/acme-challenge/jeRU8h02AJe_RNTh-GU6nX8mfDd0RxS9Xpf_f_-kl2c": dial tcp {NODE_IP}:80: connect: connection refused

**Comment by mohamaddayoub** [comment] 2024-07-19 11:29
My issue is resolved, it was DNS issue inside cert-manager deployment
