### ISSUE TITLE
IP blacklist middleware

### ISSUE THREAD

**Issue by paezba** [traefik/traefik#7310] opened 2020-09-18 14:48 UTC
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I think the IP whitelist is a great feature if you want to restrict the access just to a third party, but sometimes you need to do it the other way around. Nowadays it's pretty common to start receiving traffic from bots trying to do brute force over a particular endpoint or just scraping information from internal resources like catalogs.
I believe it would be great to have an IP blacklist middleware working in the same way that the whitelist does, but checking for not allowed addresses.
Alternatively also could be a superset middleware addressing both functionalities, like "IP filtering" or something like that, but this might be disruptive for the existing users if the whitelisting is deprecated afterwards.

I would love to collaborate if you consider this a viable addition to the project.

**Comment by SantoDE** [comment] 2020-09-18 14:59
Duplicate of #4026

**Closed by SantoDE** 2020-09-18 14:59 UTC
Labels: resolution/duplicate
