### ISSUE TITLE
Hot Reload Consul Catalog Certificates

### ISSUE THREAD

**Issue by monwolf** [traefik/traefik#9010] opened 2022-05-12 14:20 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm using traefik v2.x and consul as service catalog, we are implementing tls rotation with vault every 24h. We have deployed with nomad traefik and tried to use template stanzas to reload traefik every time the certificate is expired, this implies killing traefik and starting it again.

This causes 2 seconds of traffic losses in our infrastructure for this reason I'm finding a way to minimize the downtime.  I saw traefik can reload some parts of the configuration when detects a change in some files.

Taking a look at the code seems traefik could do that in some way

```
func (c *connectCert) serversTransport(item itemData) *dynamic.ServersTransport {
	spiffeIDService := connect.SpiffeIDService{
		Namespace:  item.Namespace,
		Datacenter: item.Datacenter,
		Service:    item.Name,
	}

	return &dynamic.ServersTransport{
		// This ensures that the config changes whenever the verifier function changes
		ServerName: fmt.Sprintf("%s-%s-%s", item.Namespace, item.Datacenter, item.Name),
		// InsecureSkipVerify is needed because Go wants to verify a hostname otherwise
		InsecureSkipVerify: true,
		RootCAs:            c.getRoot(),
		Certificates: traefiktls.Certificates{
			c.getLeaf(),
		},
		PeerCertURI: spiffeIDService.URI().String(),
	}
}

```
but I haven't been able to reload the certificates when they change.

In our golang projects we implemented a simple watcher to reload certificates:

```go

func watch(filename string, fn callback) {
	var err error
	watcher, err = fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	err = watcher.Add(filename)
	if err != nil {
		log.Fatal(err)
	}

	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("hashicorp enableWatcher: Modified file", event.Name)
					//done := make(chan bool)
					time.Sleep(1 * time.Second)
					err := fn()
					if err != nil {
						log.Fatal(err)
					}
					//<-done
				}

			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

}
-------------

watch(cli_cert, newClient)

```

Or a sighup listener to force a reload when it's triggered as consul-agent does. 

But I didn't found an easy way to reload certificates without loosing service. 

### What did you see instead?

This causes 2 seconds of traffic losses

### What version of Traefik are you using?

Version 2.5.4

### What is your environment & configuration?

```hcl
job "ingress-traefik-system" {
  region      = "gine"
  datacenters = ["ingress"]
  type        = "system"
  priority    = 90

  group "ingress-traefik-system" {
    count = 1

    network {
      port "http" {
        static = 8880
      }
      port "dns" {
        static = 5333
      }

      port "api" {
        static = 8881
      }
    }

    service {
      name = "ingress-traefik-system"

      check {
        name     = "alive"
        type     = "tcp"
        port     = "http"
        interval = "10s"
        timeout  = "2s"
      }
    }

    task "ingress-traefik-system" {
      driver = "docker"
      vault{
        policies = ["policy-ro-sec", "policy-ro-commons"]
      }

      config {
        image        = "myrepo.com/traefik/traefik:2.5.4-RELEASE"
        ports = ["http", "api", "dns"]
        
        volumes = [
          "local/traefik.toml:/etc/traefik/traefik.toml",
          "/opt/traefik/config:/opt/traefik/config",
          "/opt/consul/ssl:/opt/consul/ssl:ro"
        ]
        logging {
            type = "gelf"
            config {
              gelf-address = "udp://10.153.0.47:12201"
              tag = "traefik"
            }
        }
      }

      template {
        data = <<EOF
[entryPoints]
    [entryPoints.http]
    address = ":8880"
        [entryPoints.http.forwardedHeaders]
            trustedIPs = ["10.153.0.42/32"]
    [entryPoints.traefik]
    address = ":8881"
    [entryPoints.dns]
    address = ":5333/udp"


[api]
    dashboard = true
    insecure  = true

[log]
  level = "DEBUG"

[accessLog]
    format = "json"

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addServicesLabels = true
[tracing]
  serviceName = "ingress-traefik-system"
  [tracing.elastic]
    serverURL = "http://aeaelkpre01.globalia.com:8200"
    serviceEnvironment = "DES"

[providers]

[providers.file]
   directory = "/opt/traefik/config"
   watch = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
      address = "{{ env "node.unique.name" }}:8500"
      scheme  = "https"
      {{ with secret "/secret/commons/gine/consul/tokens" }}
      token = "{{ .Data.acl_token }}"
      {{ end }}
    [providers.consulCatalog.endpoint.tls]
      ca = "/secrets/ssl/consul-ca.pem"
      cert = "/secrets/ssl/cli.pem"
      key = "/secrets/ssl/cli-key.pem"
      insecureSkipVerify = true

EOF

        destination = "local/traefik.toml"
      }

      template {
        data = <<EORC
<< with secret "/secret/tls/gine/consul" >>
<< index .Data "consul-ca.pem" >>
<< end >>
EORC
        left_delimiter  = "<<"
        right_delimiter =  ">>"
        destination   = "/secrets/ssl/consul-ca.pem"
        env = true
      }
      template {
        data = <<EORC
<< with secret "/secret/tls/gine/consul" >>
<< index .Data "cli-key.pem" >>
<< end >>
EORC
        left_delimiter  = "<<"
        right_delimiter =  ">>"
        destination   = "/secrets/ssl/cli-key.pem"
        env = true
      }
            template {
        data = <<EORC
<< with secret "/secret/tls/gine/consul" >>
<< index .Data "cli.pem" >>
<< end >>
EORC
        left_delimiter  = "<<"
        right_delimiter =  ">>"
        destination   = "/secrets/ssl/cli.pem"
        env = true
      }


      resources {
        memory = 384
      }

      logs {
        max_files     = 2
        max_file_size = 2
      }
    }
  }
}```


### If applicable, please paste the log output in DEBUG level

_No response_

**Comment by kevinpollet** [comment] 2022-05-13 12:57
Hello @monwolf,

Thanks for your interest in Traefik,

Which certificates are you trying to refresh? 

If you are trying to refresh the certificates used to connect to the [consul server](https://doc.traefik.io/traefik/providers/consul-catalog/#tls), then these are [static configuration](https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-static-configuration) options, and reloading them will require to restart Traefik (which can cause downtime).

**Comment by monwolf** [comment] 2022-05-13 14:21
Yes, I'm trying to refresh the certificates used to connect with the consul server. 

Could we use this issue as a feature request?

**Comment by kevinpollet** [comment] 2022-05-13 15:47
> Could we use this issue as a feature request?

This issue is a duplicate of https://github.com/traefik/traefik/issues/1188, as this is about reloading the static configuration.

**Closed by kevinpollet** 2022-05-13 15:47 UTC
Labels: contributor/waiting-for-feedback
