### ISSUE TITLE
Expose Path based metrics 

### ISSUE THREAD

**Issue by hoi-wtag** [traefik/traefik#8446] opened 2021-09-15 07:22 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

What do I need?
Actually, I need path-based metrics from any endpoint and also need the DNS name for any endpoint in the metrics result.

Right now from service or router metrics, we have the following output.

```
traefik_service_requests_total{code="200",method="GET",protocol="http",service="test-47b9e3841ae588c814fb@kubernetescrd"} 18

traefik_router_requests_total{code="200", instance="traefik.traefik.svc.cluster.local:9100", job="traefik", method="GET", protocol="http", router="test-47b9e3841ae588c814fb@kubernetescrd", service="test-47b9e3841ae588c814fb"} 10
```

 My ingress route  example

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`test.com`) && PathPrefix(`/tmp-help`)
      kind: Rule
      services:
        - name: test-api
          port: 80
    - match: Host(`test.com`) && PathPrefix(`/public/v1`)
      kind: Rule
      services:
        - name: test1-api
          port: 80
```
   
What I expect now from metrics:
```
traefik_service_requests_total{code="200",method="GET",protocol="http",service="test-47b9e3841ae588c814fb@kubernetescrd",**path="/tmp-help",host="test.com"**} 10

traefik_service_requests_total{code="200",method="GET",protocol="http",service="test-47b9e3841ae588c814fb@kubernetescrd",**path="/public/v1",host="test.com"**} 8

traefik_router_requests_total{code="200", instance="traefik.traefik.svc.cluster.local:9100", job="traefik", method="GET", protocol="http", router="test-47b9e3841ae588c814fb@kubernetescrd", service="test-47b9e3841ae588c814fb",**path="/tmp-help",host="test.com"**} 6

traefik_router_requests_total{code="200", instance="traefik.traefik.svc.cluster.local:9100", job="traefik", method="GET", protocol="http", router="test-47b9e3841ae588c814fb@kubernetescrd", service="test-47b9e3841ae588c814fb",**path="/public/v1",host="test.com"**} 4
```

Log output in DEBUG level
```
textPayload: "time="2021-09-15T03:42:47Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"public/v1/users/me/agreements\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json, text/plain, */*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-GB,en-US;q=0.9,en;q=0.8\"],\"Authorization\":[\"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzE2NzYzNzAsIm5iZiI6MTYzMTY3NjM3MCwianRpIjoiZmRiZGQ3MWYtN2Y0Ny00ZmUwLTgwNTTUtYjYyNDUyZjQ2MzE1IiwiZXhwIjoxNjMyMTA4MzcwLCJpZGVudGl0eSI6ImI5NTZjNTY0LThhZWEtNDcwOC05OWI2LTYZTg0MjJiZTZjNyIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.s2pI3nepOuzQpEkGsuX4QIGXNkaViW0hK0LMpNSMVV8\"],\"Origin\":[\"https://test.com\"],\"Referer\":[\"https://test.com/\"],\"Sec-Ch-Ua\":[\"\\\"Google Chrome\\\";v=\\\"93\\\", \\\" Not;A Brand\\\";v=\\\"99\\\", \\\"Chromium\\\";v=\\\"93\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Ch-Ua-Platform\":[\"\\\"macOS\\\"\"],\"Sec-Fetch-Dest\":[\"empty\"],\"Sec-Fetch-Mode\":[\"cors\"],\"Sec-Fetch-Site\":[\"same-site\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36\"],\"X-Forwarded-Host\":[\"test.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik-fffcb97cd-s5hqj\"],\"X-Real-Ip\":[\"10.172.0.66\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"test.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.172.0.66:32295\",\"RequestURI\":\"public/v1/users/me/agreements\",\"TLS\":null}""
```
  
Log output of Accesslog
  
```
textPayload: "10.60.8.1 - - [15/Sep/2021:06:09:38 +0000] "GET /public/v1?EIO=3&transport=polling&t=Nle4pHd&sid=b3dca4348fe242ed9397c699a5d329c3 HTTP/2.0" 499 21 "-" "-" 1211 "test-47b9e3841ae588c814fb@kubernetescrd" "http://10.66.1.118:80" 35674ms"
```
  
In Debug logs we have both host and path, So it will be nice to integrate the **host and path** field in metrics output.

**Comment by ldez** [comment] 2021-09-15 07:27
duplicate of  #7007

**Closed by ldez** 2021-09-15 07:27 UTC
Labels: status/0-needs-triage

**Comment by hoi-wtag** [comment] 2021-09-15 07:36
> duplicate of #7007

Hi @ldez this one #7007 was about only router-based metrics, not my requested feature.
I need both **path and host** field in metrics output.
