### ISSUE TITLE
 First log entry after startup is always text format 

### ISSUE THREAD

**Issue by talger** [traefik/traefik#9900] opened 2023-05-20 06:43 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to set logs to json format, but the first log entry always formatted as a text. This behavior is disrupt the log processing.

```
$ traefik --log.format=json
INFO[0001] Configuration loaded from flags.
{"entryPointName":"http","level":"error","msg":"accept tcp [::]:80: use of closed network connection","time":"2023-05-20T08:42:23+02:00"}
```

### What did you see instead?

Run traefik with default log format:
```
$ traefik --log.level=debug
INFO[0000] Configuration loaded from flags.
INFO[2023-05-20T08:32:39+02:00] Traefik version 2.10.1 built on I don't remember exactly
DEBU[2023-05-20T08:32:39+02:00] Static configuration loaded {"global":{"checkNewVersion":true},"serversTransport":{"maxIdleConnsPerHost":200},"entryPoints":{"http":{"address":":80","transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s"}},"forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"udp":{"timeout":"3s"}}},"providers":{"providersThrottleDuration":"2s"},"log":{"level":"debug","format":"common"}}
INFO[2023-05-20T08:32:39+02:00]
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/
INFO[2023-05-20T08:32:39+02:00] Starting provider aggregator aggregator.ProviderAggregator
DEBU[2023-05-20T08:32:39+02:00] Starting TCP Server                           entryPointName=http
INFO[2023-05-20T08:32:39+02:00] Starting provider *traefik.Provider
DEBU[2023-05-20T08:32:39+02:00] *traefik.Provider provider configuration: {}
INFO[2023-05-20T08:32:39+02:00] Starting provider *acme.ChallengeTLSALPN
DEBU[2023-05-20T08:32:39+02:00] *acme.ChallengeTLSALPN provider configuration: {}
DEBU[2023-05-20T08:32:39+02:00] Configuration received: {"http":{"services":{"noop":{}},"serversTransports":{"default":{"maxIdleConnsPerHost":200}}},"tcp":{},"udp":{},"tls":{}}  providerName=internal
DEBU[2023-05-20T08:32:39+02:00] No default certificate, fallback to the internal generated certificate  tlsStoreName=default
INFO[2023-05-20T08:32:41+02:00] I have to go...
INFO[2023-05-20T08:32:41+02:00] Stopping server gracefully
DEBU[2023-05-20T08:32:41+02:00] Waiting 10s seconds before killing connections.  entryPointName=http
ERRO[2023-05-20T08:32:41+02:00] accept tcp [::]:80: use of closed network connection  entryPointName=http
ERRO[2023-05-20T08:32:41+02:00] close tcp [::]:80: use of closed network connection  entryPointName=http
DEBU[2023-05-20T08:32:41+02:00] Entry point http closed                       entryPointName=http
INFO[2023-05-20T08:32:41+02:00] Server stopped
INFO[2023-05-20T08:32:41+02:00] Shutting down
```

Run traefik with json formatted log:
(The first line is not json)
```
$ traefik --log.level=debug --log.format=json
INFO[0000] Configuration loaded from flags.
{"level":"info","msg":"Traefik version 2.10.1 built on I don't remember exactly","time":"2023-05-20T08:34:54+02:00"}
{"level":"debug","msg":"Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\"},\"log\":{\"level\":\"debug\",\"format\":\"json\"}}","time":"2023-05-20T08:34:54+02:00"}
{"level":"info","msg":"\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n","time":"2023-05-20T08:34:54+02:00"}
{"level":"info","msg":"Starting provider aggregator aggregator.ProviderAggregator","time":"2023-05-20T08:34:54+02:00"}
{"entryPointName":"http","level":"debug","msg":"Starting TCP Server","time":"2023-05-20T08:34:54+02:00"}
{"level":"info","msg":"Starting provider *traefik.Provider","time":"2023-05-20T08:34:54+02:00"}
{"level":"debug","msg":"*traefik.Provider provider configuration: {}","time":"2023-05-20T08:34:54+02:00"}
{"level":"info","msg":"Starting provider *acme.ChallengeTLSALPN","time":"2023-05-20T08:34:54+02:00"}
{"level":"debug","msg":"*acme.ChallengeTLSALPN provider configuration: {}","time":"2023-05-20T08:34:54+02:00"}
{"level":"debug","msg":"Configuration received: {\"http\":{\"services\":{\"noop\":{}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"udp\":{},\"tls\":{}}","providerName":"internal","time":"2023-05-20T08:34:54+02:00"}
{"level":"debug","msg":"No default certificate, fallback to the internal generated certificate","time":"2023-05-20T08:34:54+02:00","tlsStoreName":"default"}
{"level":"info","msg":"I have to go...","time":"2023-05-20T08:34:55+02:00"}
{"level":"info","msg":"Stopping server gracefully","time":"2023-05-20T08:34:55+02:00"}
{"entryPointName":"http","level":"debug","msg":"Waiting 10s seconds before killing connections.","time":"2023-05-20T08:34:55+02:00"}
{"entryPointName":"http","level":"error","msg":"accept tcp [::]:80: use of closed network connection","time":"2023-05-20T08:34:55+02:00"}
{"entryPointName":"http","level":"error","msg":"close tcp [::]:80: use of closed network connection","time":"2023-05-20T08:34:55+02:00"}
{"entryPointName":"http","level":"debug","msg":"Entry point http closed","time":"2023-05-20T08:34:55+02:00"}
{"level":"info","msg":"Server stopped","time":"2023-05-20T08:34:55+02:00"}
{"level":"info","msg":"Shutting down","time":"2023-05-20T08:34:55+02:00"}
```

### What version of Traefik are you using?

```
$ docker run --rm traefik version
Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64
```
```
$ traefik version
Version:      2.10.1
Codename:     cheddar
Go version:   go1.20.3
Built:        I don't remember exactly
OS/Arch:      darwin/amd64
```

### What is your environment & configuration?

Default configuration, only cli arguments, which are saws in the outputs

**Comment by ldez** [comment] 2023-05-20 07:19
Duplicate of #7723

**Closed by ldez** 2023-05-20 07:20 UTC
Labels: resolution/duplicate
