### ISSUE TITLE
[Windows] Middleware ipWhiteList: failed to parse IP on same system

### ISSUE THREAD

**Issue by ydder007** [traefik/traefik#8584] opened 2021-11-18 09:24 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

- Configured permeable ipWhiteList
- Tried to access configured route in browser on same system
- Traefik rejects connection with "403 Forbidden"

### What did you see instead?

"403 Forbidden" error

### What version of Traefik are you using?

Version:      2.5.4
Codename:     livarot
Go version:   go1.17.3
Built:        2021-11-08T17:41:41Z
OS/Arch:      windows/amd64

### What is your environment & configuration?

```yaml
[http.services.nginx]
      [http.services.nginx.loadBalancer]
        [[http.services.NGINX.loadBalancer.servers]]
          url = "http://example.com:8080"

[http.routers.nginx]
      entryPoints = ["web", "web-secure"]
      priority = 10
      service = "nginx"
      rule = "PathPrefix(`/test`)"
      middlewares = ["whitelist"]

[http.middlewares.whitelist.ipWhiteList]
      sourceRange = ["0.0.0.0/0", "::/0"]
```

### If applicable, please paste the log output in DEBUG level

```RemoteAddr:[fe80::xxxx:yyy:zzz:0123%vEthernet (Default Switch)]:58904 RequestURI:/test/ TLS:0xc0003da210 Cancel:<nil> Response:<nil> ctx:0xc0008ef530}: unable to parse address: fe80::xxxx:yyyy:zzzz:0123%vEthernet (Default Switch): can't parse IP from address fe80::xxxx:yyyy:zzzz:0123%vEthernet (Default Switch)"```

**Comment by ydder007** [comment] 2021-11-18 09:26
ipWhitelist Middleware fails to validate the request IP if a zone id is attached

**Comment by ldez** [comment] 2021-11-18 09:29
duplicate of #7270

**Closed by ldez** 2021-11-18 09:29 UTC
Labels: resolution/duplicate
