### ISSUE TITLE
Podman (rootfull) servicediscovery not updating health status

### ISSUE THREAD

**Issue by floriplum** [traefik/traefik#8833] opened 2022-03-11 11:14 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Trying to get traefik to discover services running in podman as root.

### What did you see instead?

Traefik discovering the service sometimes when i restart the containers or the podman service.
In the Log the container is discovered, but only as unhealthy. That status never changes even when the container is healthy accorging to podman ps.

### What version of Traefik are you using?

Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

docker-compose.yml
```yaml
version: "3.9"

services:
  reverse:
    image: docker.io/traefik
    ports:
      - 80:80
      - 8080:8080
    command: "--api.insecure=true --providers.docker --entrypoints.web.address=:80 --providers.docker.exposedbydefault=false --log.level=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  uptimekuma:
    image: docker.io/louislam/uptime-kuma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`localhost`)"
      - "traefik.http.services.test.loadbalancer.server.port=3001"
```

Add more configuration information here.

podman version: 4.0.1
podman-compose version: 1.03
OS: Arch Linux

### If applicable, please paste the log output in DEBUG level

time="2022-03-11T11:10:41Z" level=info msg="Configuration loaded from flags."
time="2022-03-11T11:10:41Z" level=info msg="Traefik version 2.6.1 built on 2022-02-14T16:50:25Z"
time="2022-03-11T11:10:41Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"pilot\":{\"dashboard\":true}}"
time="2022-03-11T11:10:41Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-03-11T11:10:41Z" level=info msg="Starting provider aggregator.ProviderAggregator"
time="2022-03-11T11:10:41Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2022-03-11T11:10:41Z" level=debug msg="Start TCP Server" entryPointName=web
time="2022-03-11T11:10:41Z" level=info msg="Starting provider *traefik.Provider"
time="2022-03-11T11:10:41Z" level=debug msg="*traefik.Provider provider configuration: {}"
time="2022-03-11T11:10:41Z" level=info msg="Starting provider *docker.Provider"
time="2022-03-11T11:10:41Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
time="2022-03-11T11:10:41Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-03-11T11:10:41Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {\"Timeout\":4000000000}"
time="2022-03-11T11:10:41Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2022-03-11T11:10:41Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-03-11T11:10:41Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareType=TracingForwarder entryPointName=traefik routerName=api@internal middlewareName=tracing
time="2022-03-11T11:10:41Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=dashboard@internal
time="2022-03-11T11:10:41Z" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal middlewareType=StripPrefix
time="2022-03-11T11:10:41Z" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal entryPointName=traefik middlewareName=dashboard_stripprefix@internal
time="2022-03-11T11:10:41Z" level=debug msg="Creating middleware" middlewareType=RedirectRegex middlewareName=dashboard_redirect@internal entryPointName=traefik routerName=dashboard@internal
time="2022-03-11T11:10:41Z" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" middlewareName=dashboard_redirect@internal entryPointName=traefik routerName=dashboard@internal middlewareType=RedirectRegex
time="2022-03-11T11:10:41Z" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal entryPointName=traefik middlewareName=dashboard_redirect@internal
time="2022-03-11T11:10:41Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=traefik middlewareName=traefik-internal-recovery
time="2022-03-11T11:10:41Z" level=debug msg="Provider connection established with docker 4.0.1 (API 1.40)" providerName=docker
time="2022-03-11T11:10:41Z" level=debug msg="Filtering disabled container" providerName=docker container=reverse-tmpappuzbpcda-1ada249e45dbb3b9a4a77d904dc0cadf884b52168b9ae2fc95fd84c53e8c4195
time="2022-03-11T11:10:41Z" level=debug msg="Configuration received from provider docker: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=docker
time="2022-03-11T11:10:41Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-03-11T11:10:41Z" level=debug msg="Added outgoing tracing middleware api@internal" routerName=api@internal middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik
time="2022-03-11T11:10:41Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=dashboard@internal
time="2022-03-11T11:10:41Z" level=debug msg="Creating middleware" middlewareType=StripPrefix entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal
time="2022-03-11T11:10:41Z" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal entryPointName=traefik
time="2022-03-11T11:10:41Z" level=debug msg="Creating middleware" middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal
time="2022-03-11T11:10:41Z" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal
time="2022-03-11T11:10:41Z" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_redirect@internal entryPointName=traefik
time="2022-03-11T11:10:41Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2022-03-11T11:10:42Z" level=debug msg="Provider event received {Status:start ID:46ec4929c48d061dce4cf7b0e3d3da274e9038fd2e2932c11181df65fdb2915b From:docker.io/louislam/uptime-kuma:latest Type:container Action:start Actor:{ID:46ec4929c48d061dce4cf7b0e3d3da274e9038fd2e2932c11181df65fdb2915b Attributes:map[com.docker.compose.container-number:1 com.docker.compose.project:tmpappuzbpcda com.docker.compose.project.config_files:docker-compose.yml com.docker.compose.project.working_dir:/tmp/tmp.ApPUzbpCDA com.docker.compose.service:uptimekuma containerExitCode:0 image:docker.io/louislam/uptime-kuma:latest io.podman.compose.config-hash:123 io.podman.compose.project:tmpappuzbpcda io.podman.compose.version:0.0.1 name:tmpappuzbpcda_uptimekuma_1 traefik.enable:true traefik.http.routers.uptimekuma.rule:Host(`localhost`) traefik.http.services.test.loadbalancer.server.port:3001]} Scope:local Time:1646997042 TimeNano:1646997042149435635}" providerName=docker
time="2022-03-11T11:10:42Z" level=debug msg="Filtering disabled container" providerName=docker container=reverse-tmpappuzbpcda-1ada249e45dbb3b9a4a77d904dc0cadf884b52168b9ae2fc95fd84c53e8c4195
time="2022-03-11T11:10:42Z" level=debug msg="Filtering unhealthy or starting container" providerName=docker container=uptimekuma-tmpappuzbpcda-46ec4929c48d061dce4cf7b0e3d3da274e9038fd2e2932c11181df65fdb2915b
time="2022-03-11T11:10:42Z" level=debug msg="Configuration received from provider docker: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=docker
time="2022-03-11T11:10:42Z" level=debug msg="Skipping same configuration" providerName=docker

**Comment by floriplum** [comment] 2022-03-11 11:15
Running docker-compose with podman under the hood also won't help.

**Comment by kevinpollet** [comment] 2022-03-11 13:34
Duplicate of https://github.com/traefik/traefik/issues/5730

**Closed by kevinpollet** 2022-03-11 13:34 UTC
Labels: status/0-needs-triage

**Comment by floriplum** [comment] 2022-03-11 13:39
I already read through that thread before posting this one.
Since there is no one having problems with the health detection and it is more about rootless podman i don't think it is a duplicate.

But i understand if this is nothing you would work on since podman isn't officially supported yet.

**Comment by floriplum** [comment] 2022-03-11 13:47
After playing a bit with it i found a pattern.
For everybody with the same problem, when you restart the podman.service it looks like traefik is detecting it always.
And when you create multiple containers within a single compose file, it is always the latest container with the status healthy that isn't visible.
