### ISSUE TITLE
Duplicate requests in Access logs

### ISSUE THREAD

**Issue by johnnyplaydrums** [traefik/traefik#8871] opened 2022-03-23 18:09 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

We are seeing duplicate requests to one of our services. We usually get 2x requests per minute (basically a cron job), but every hour or so we get a flood of 100-200 requests. These requests are duplicates of requests from that past 30-60 minutes. In the request headers we see a duplicate `X-Amzn-Trace-Id`, which is uniquely generated by AWS ALB for each request. This indicates something between the ALB and the service is somehow storing/caching requests and then replaying them every hour or so. Although it seems unlikely, we think Traefik might be doing that. One thing that points us to Traefik is that every few minutes in our Traefik access logs we see a duplicate request logged - every attribute in the access log is exactly the same between the two requests, including `request_total` and `duration`. I would expect `request_total` should be unique, is that right? If it should be unique, the duplicate `request_total` access log indicates to use that traefik is duplicating requests that it's receiving. 

### What did you see instead?

Duplicate requests with the same `request_total` in the access logs, even though we expect that value to be unique. In the service that is receiving extra requests, we see duplicate `X-Amzn-Trace-Id` header, which is uniquely generated on every request. Our guess is something is storing/caching requests and then replaying them. Traefik seems to be a possible culprit.

### What version of Traefik are you using?

`2.6.1`

### What is your environment & configuration?

`/etc/traefik/traefik.yml`:
```
accessLog: {}
api:
  dashboard: true
  insecure: true
log:
  level: DEBUG
entryPoints:
  http:
    address: ":80"
  traefik:
    address: ":8080"
metrics:
  datadog:
    address: <redacted>:8125
providers:
  consulCatalog:
    exposedByDefault: false
    refreshInterval: 500ms
  file:
    directory: "/etc/traefik/middlewares/
```

`/etc/traefik/middlewares/ip_allow_list.yml`:
```
http:
  middlewares:
    ip-allow-list:
      ipWhiteList:
        ipStrategy:
          depth: 1
        sourceRange:
          - <redacted> # list of IPs
```

### If applicable, please paste the log output in DEBUG level

Here's some examples of the duplicate requests, you'll see the pairs each of the same request total and duration

```
<redacted> - - [23/Mar/2022:16:44:51 +0000] "POST /retrieval HTTP/1.1" 200 724 "-" "-" 323137 "<redacted>@consulcatalog" "http://<redacted>:23610" 234ms
<redacted> - - [23/Mar/2022:16:44:51 +0000] "POST /retrieval HTTP/1.1" 200 724 "-" "-" 323137 "<redacted>@consulcatalog" "http://<redacted>:23610" 234ms
<redacted> - - [23/Mar/2022:13:04:51 +0000] "POST /retrieval HTTP/1.1" 200 1208 "-" "-" 249632 "<redacted>@consulcatalog" "http://<redacted>:20013" 328ms
<redacted> - - [23/Mar/2022:13:04:51 +0000] "POST /retrieval HTTP/1.1" 200 1208 "-" "-" 249632 "<redacted>@consulcatalog" "http://<redacted>:20013" 328ms
<redacted> - - [23/Mar/2022:09:45:52 +0000] "POST /retrieval HTTP/1.1" 200 15651 "-" "-" 205151 "<redacted>@consulcatalog" "http://<redacted>:21659" 768ms
<redacted> - - [23/Mar/2022:09:45:52 +0000] "POST /retrieval HTTP/1.1" 200 15651 "-" "-" 205151 "<redacted>@consulcatalog" "http://<redacted>:21659" 768ms
<redacted> - - [23/Mar/2022:09:46:51 +0000] "POST /retrieval HTTP/1.1" 200 15651 "-" "-" 205158 "<redacted>@consulcatalog" "http://<redacted>:20013" 1261ms
<redacted> - - [23/Mar/2022:09:46:51 +0000] "POST /retrieval HTTP/1.1" 200 15651 "-" "-" 205158 "<redacted>@consulcatalog" "http://<redacted>:20013" 1261ms
```

**Comment by svenso** [comment] 2022-03-30 05:56
We are facing the same issue since upgrading from 2.5.6 to 2.6.1.
Here it is running on a Windows System using NSSM, the logs are grabbed via NXLOG. 
Our NXLOG config includes the "RenameCheck True" directive, which worked before and now, we get all the events again, as soon as the log is renamed (every 30MB):

D:\xnglog\traefik\\access.log
D:\xnglog\traefik\\access-20220326T190845.751.log

I compared the logfiles from before and now and couldn't detect anything unusual.. And because we are using NSSM which splits the log files, I cannot imagine, how it is possible, that the behavior changed with upgrading traefik.. But it's obvious (about 50Mio duplicated entries).

**Comment by tfny** [comment] 2022-07-20 14:08
This is still in our queue to review.  If you would like to help us with the verification, comment here and one of our triage team will talk to you about what we need for verification.

**Comment by johnnyplaydrums** [comment] 2022-07-20 14:30
> This is still in our queue to review. If you would like to help us with the verification, comment here and one of our triage team will talk to you about what we need for verification.

Hi @tfny, I'll volunteer to help with verification.

**Comment by r0goyal** [comment] 2022-08-23 11:32
Hi Team,

We are also facing a similar issue where duplicate requests are reaching our backend. 

Traefik Version - 2.3.2

We are using `marathon` provider to dynamically discover our routers and services

**Comment by tfny** [comment] 2022-09-12 15:08
Hey @johnnyplaydrums , Did you happen to manage to verify?

**Comment by johnnyplaydrums** [comment] 2022-09-12 16:42
@tfny it seems this issue has stopped occurring, at least for us. I don't believe we've made any relevant changes to fix it but the evidence I had of the issue is no longer present. Not sure if anyone else on this thread can chime in with the validation you need. If not, I think we can close this issue.

**Comment by ddtmachado** [comment] 2022-09-14 00:08
@johnnyplaydrums Thanks for the feedback and all the time spent on trying to reproduce!
According to your last statement I'm closing the issue, but as always don't hesitate to reopen or open a new one if it appears again.

**Closed by ddtmachado** 2022-09-14 00:08 UTC
Labels: kind/bug/possible, area/logs
