### ISSUE TITLE
IPWhiteList middleware not working as expected when traefik behind another reverse proxy

### ISSUE THREAD

**Issue by akunzai** [traefik/traefik#7735] opened 2021-01-08 15:17 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Configure Traefik to trust the forwarded headers from another reverse proxy.
- Configure IPWhiteList middleware to accept connections from specific set of trusted IPs.
- Send an HTTP request via external reverse-proxy from untrusted IPs.
- Send an HTTP request directly from trusted IPs.

### What did you expect to see?

- HTTP request via external reverse-proxy from untrusted IPs should be rejected.
- HTTP request directly from trusted IPs should be accepted.

### What did you see instead?

Before configure `ipwhitelist.ipstrategy.excludedips` on IPWhiteList middleware, HTTP request via external reverse-proxy from untrusted IPs was accepted.

```sh
$ docker-compose run curl -H 'Host: whoami.example.test' http://proxy
Hostname: 7fed11d814b3
IP: 127.0.0.1
IP: 172.20.2.2
RemoteAddr: 172.20.2.4:46530
GET / HTTP/1.1
Host: whoami.example.test
User-Agent: curl/7.74.0-DEV
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.20.1.2, 172.20.2.3
X-Forwarded-Host: whoami.example.test
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 121f8b51ac99
X-Real-Ip: 172.20.2.3
```

After configure `ipwhitelist.ipstrategy.excludedips` on IPWhiteList middleware, HTTP request directly from trusted IPs was rejected.

```sh
$ curl -H 'Host: whoami.example.test' http://localhost
Forbidden
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.6
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-17T16:34:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml:docker-compose.yml
version: '3'

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: "172.20.1.0/24"
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.20.2.0/24"

services:
  curl:
    image: curlimages/curl
    networks:
      - frontend
  proxy:
    image: caddy
    networks:
      - frontend
      - backend
    command: caddy reverse-proxy --from http://whoami.example.test --to traefik:80
  whoami:
    image: containous/whoami
    networks:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.example.test`)
      - traefik.http.routers.whoami.middlewares=test-ipwhitelist
      - traefik.http.middlewares.test-ipwhitelist.ipwhitelist.sourcerange=172.20.2.0/16
      # - traefik.http.middlewares.test-ipwhitelist.ipwhitelist.ipstrategy.excludedips=172.20.1.0/16
  traefik:
    image: traefik:2.3.6
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.trustedIPs=172.20.1.0/16
    ports:
      - '127.0.0.1:80:80'
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Before configure `ipwhitelist.ipstrategy.excludedips` on IPWhiteList middleware, HTTP request via external reverse-proxy from untrusted IPs was accepted.

<details>
 <summary>$ docker-compose run curl -H 'Host: whoami.example.test' http://proxy</summary>

level=debug msg="Accept 172.20.2.4: &{Method:GET URL:/ Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] Accept-Encoding:[gzip] User-Agent:[curl/7.74.0-DEV] X-Forwarded-For:[172.20.1.2] X-Forwarded-Host:[whoami.example.test] X-Forwarded-Port:[80] X-Forwarded-Proto:[http] X-Forwarded-Server:[121f8b51ac99] X-Real-Ip:[172.20.2.4]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:whoami.example.test Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:172.20.2.4:46572 RequestURI:/ TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000423e30}" middlewareName=test-ipwhitelist@docker middlewareType=IPWhiteLister

</details>

After configure `ipwhitelist.ipstrategy.excludedips` on IPWhiteList middleware, HTTP request directly from trusted IPs was rejected.

<details>
 <summary>$ curl -H 'Host: whoami.example.test' http://localhost</summary>

level=debug msg="rejecting request &{Method:GET URL:/ Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] User-Agent:[curl/7.64.1] X-Forwarded-Host:[whoami.example.test] X-Forwarded-Port:[80] X-Forwarded-Proto:[http] X-Forwarded-Server:[121f8b51ac99] X-Real-Ip:[172.20.2.1]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:whoami.example.test Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:172.20.2.1:61654 RequestURI:/ TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000a0bdd0}: empty IP address" middlewareName=test-ipwhitelist@docker middlewareType=IPWhiteLister

</details>

**Comment by jspdown** [comment] 2021-01-12 10:01
Hello @akunzai and thanks for your interest in Traefik.

The problem comes from your docker configuration. For the first test when sending the request to the proxy, Traefik's ipWhitelist middleware is configured with the default ip strategy, which relies on the remote address and not the forwarded headers. Since caddy is in both `frontend` and `backend` networks when caddy forwards the request to Traefik it uses the `backend` network and its IP is a 172.20.2.x which matches the source range provided.

Then, when `excludedIps` is configured, the ip strategy will rely on the `X-Forwarded-For`, which is empty since you are making the call directly to Traefik.

This is working as expected so I'm going to close the issue. If you need help from the community on your configuration please visit the [community forum](https://community.traefik.io/c/traefik/traefik-v2/10)

**Closed by jspdown** 2021-01-12 10:01 UTC
Labels: area/middleware, kind/bug/possible

**Comment by akunzai** [comment] 2021-01-12 10:50
Hello @jspdown and thanks for your response.

In real world, my docker environment hosting in DMZ, and I want to reject internet connections from reverse proxy (with `X-Forwarded-For` header) and accept intranet connections (without `X-Forwarded-For` header).

So, I want to point out is that the `ipWhitelist` middleware strategy cannot satisfy connections with or without `X-Forwarded-For` header at same time.

Maybe when `excludedIps` is configured, the IP strategy should fallback to check the real IP instead of empty?

**Comment by jspdown** [comment] 2021-01-12 16:05
@akunzai Yes that right, there's no ip strategy on the `ipwhitelist` middleware that will both use the`RemoteAddr` and the `X-Forwarded-For` header. A solution however would be to have 2 distinct routers with one using the rule ```HeadersRegexp(`X-Forwarded-For`, `.+`)``` and have 2 different `ipwhitelist` middlewares.

**Comment by jspdown** [comment] 2021-01-12 16:13
> Maybe when excludedIps is configured, the IP strategy should fallback to check the real IP instead of empty?

:thinking: That could be an improvement. I might be wrong, but right now I don't see why not falling back on using the `RemoteAddr` if `X-Forwarded-For` is empty. 

Could you open a proposal for that?

**Comment by akunzai** [comment] 2021-01-13 02:18
Thanks @jspdown,

Problem solved by using different `ipWhitelist` middlewares.

**Comment by zeph** [comment] 2021-02-10 12:10
@jspdown cause it is like that by design... https://github.com/traefik/traefik/issues/7884

I'm probably going down the road of the solution with ```HeadersRegexp(`X-Forwarded-For`, `.+`)```
