### ISSUE TITLE
Toggle controls for routers/middleware via Web UI

### ISSUE THREAD

**Issue by ptruman** [traefik/traefik#9033] opened 2022-05-20 10:16 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be handy if the Traefik web UI allowed for routers (and possibly middleware chains) to be enabled/disabled from the UI.

One use case: Containers which periodically (but not always) require access from external/other networks, and use middleware to restrict IP ranges for access.  There is no way to amend access other than by amending the docker label config to amend the middleware, then restart the container.

If a middleware rule, or chain, contained an "allow network A" and "allow network B" middleware, they could be toggled at the traefik level, without restarting traefik or the container.

Other use case: Temporarily stop traefik access to a whole container (i.e. DNS/TLS routing) but not stopping the whole container, i.e. for on-line maintenance - container may be accessed via IP or other route (known to admin) but not to general users.  Stopping a router would stop any DNS->TLS based access, but allow the container to remain up, without having to amend DNS or firewall rules.

Just a thought, feel free to flame to death :)

**Comment by kevinpollet** [comment] 2022-05-20 14:59
Duplicate of https://github.com/traefik/traefik/issues/2481

**Closed by kevinpollet** 2022-05-20 14:59 UTC
Labels: status/0-needs-triage
