### ISSUE TITLE
Enable service switching in Circuit Breaker middleware

### ISSUE THREAD

**Issue by esteveavi** [traefik/traefik#10152] opened 2023-10-05 12:36 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,

In the Circuit Breaker middlewares the fallback behavior in Open State is to return a fixed 503 page.  

It should be fine if you could defne another serivce as the destination in Open State instead of a fixed response.

Best regards,

**Comment by ldez** [comment] 2023-10-05 12:39
duplicate of #7113

**Closed by ldez** 2023-10-05 12:39 UTC
Labels: resolution/duplicate
