### ISSUE TITLE
Authelia auth provider fails in file but not in docker labels

### ISSUE THREAD

**Issue by Archef2000** [traefik/traefik#9257] opened 2022-08-12 12:44 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If I configure authelia File forwardAuth provider and use it in the same rules.yaml file traefik crashes.
**rules.yaml**
```
http:
  routers:
    router-cockpit:
      entryPoints:
        - websecure
      rule: Host(`test.example.com`)
      service: service-cockpit
      middlewares: authelia@file
      tls:
        certResolver: duckdns

  services:
    service-cockpit:
      loadBalancer:
        servers:
        - url: "http://192.16.5.155:80"

  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.example.com%2F"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
```

### What did you see instead?

**The error message is the following:**
```
time="2022-08-12T12:30:42Z" level=info msg="Configuration loaded from flags."
time="2022-08-12T12:30:42Z" level=error msg="Error in Go routine: runtime error: slice bounds out of range [2:1]"
time="2022-08-12T12:30:42Z" level=error msg="Stack: goroutine 71 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x2fa9260?, 0x40005e67f8})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xac\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x3c\npanic({0x2fa9260, 0x40005e67f8})\n\truntime/panic.go:884 +0x20c\ngithub.com/traefik/paerser/parser.filler.setSlice({{0xb?, {0x328b8b0?, 0x0?}}}, {0x28f6900?, 0x40006fb818?, 0x2c5187f?}, 0x4000048ea0)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0x89c\ngithub.com/traefik/paerser/parser.filler.fill({{0x80?, {0x328b8b0?, 0x40004b8948?}}}, {0x28f6900?, 0x40006fb818?, 0x7c48c?}, 0x40004b8958?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x4d4\ngithub.com/traefik/paerser/parser.filler.setStruct({{0xad?, {0x328b8b0?, 0x40004b8a68?}}}, {0x2fd1980?, 0x40006fb800?, 0x1504244?}, 0x2c08300?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x10c\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x328b8b0?, 0x2c08300?}}}, {0x2fd1980?, 0x40006fb800?, 0x4000389540?}, 0x40004b8b18?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x518\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x48?, {0x328b8b0?, 0x40004b8b78?}}}, {0x2bcb120?, 0x40006f7518?, 0x1504244?}, 0x2c08300?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0x80?, {0x328b8b0?, 0x2c08300?}}}, {0x2bcb120?, 0x40006f7518?, 0x4000773258?}, 0x40004b8cb8?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setPtr({{0xd8?, {0x328b8b0?, 0x40004b8c88?}}}, {0x400041b080?, 0x40006f7510?, 0x40?}, 0x100000000000001?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0xc0?, {0x328b8b0?, 0x2d9d980?}}}, {0x400041b080?, 0x40006f7510?, 0x400041b080?}, 0x40004b8d38?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x68?, {0x328b8b0?, 0x8?}}}, {0x400041b0c0?, 0x40006f7510?, 0x0?}, 0x40004b8d98?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0x98?, {0x328b8b0?, 0x2f812e0?}}}, {0x400041b0c0?, 0x40006f7510?, 0x40004f8790?}, 0x2bcaba0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setMap({{0x7?, {0x328b8b0?, 0x0?}}}, {0x2b325a0?, 0x40004bf230?, 0x2b97d36?}, 0x4000048cf0)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x334\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x328b8b0?, 0x0?}}}, {0x2b325a0?, 0x40004bf230?, 0x2ad01eb?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:103 +0x4b4\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x4f?, {0x328b8b0?, 0x40004b9058?}}}, {0x2f812e0?, 0x40004bf230?, 0xbc880?}, 0x40004b9168?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x10c\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x328b8b0?, 0x199?}}}, {0x2f812e0?, 0x40004bf230?, 0x4000119d80?}, 0x2ad01e6?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x518\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x4?, {0x328b8b0?, 0x0?}}}, {0x2bca920?, 0x4000119d80?, 0x2ad01eb?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x328b8b0?, 0x40004b9368?}}}, {0x2bca920?, 0x4000119d80?, 0x328c755?}, 0x40004b91d8?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x0?, {0x328b8b0?, 0x40004b92d8?}}}, {0x2ee4de0?, 0x4000119d80?, 0x150bc30?}, 0x328c755?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x10c\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x328b8b0?, 0x40006f74b8?}}}, {0x2ee4de0?, 0x4000119d80?, 0x16152d8?}, 0x328c755?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x518\ngithub.com/traefik/paerser/parser.filler.Fill({{0x20?, {0x328b8b0?, 0x2bca520?}}}, {0x2bca520?, 0x4000119d80?}, 0x4000048870)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:58 +0x150\ngithub.com/traefik/paerser/parser.Fill({0x2bca520?, 0x4000119d80?}, 0x4?, {0x20?, {0x328b8b0?, 0x4000048870?}})\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:28 +0x5c\ngithub.com/traefik/paerser/file.DecodeContent({0x400016cd00, 0x808}, {0x7fdf53cf21, 0x4}, {0x2bca520, 0x4000119d80})\n\tgithub.com/traefik/paerser@v0.1.6/file/file.go:83 +0x1e8\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).decodeConfiguration(0x400041ad40?, {0x7fdf53cf0f, 0x16}, {0x400016cd00, 0x808})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:522 +0x2d0\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).CreateConfiguration(0x40004302d0, {0x3d58490, 0x40004bee40}, {0x7fdf53cf0f, 0x16}, 0x2fe1b1f?, {0x2923ec0, 0x5aac880})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:486 +0x638\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfig(0x3d58420?, {0x3d58490, 0x40004bee40}, {0x7fdf53cf0f, 0x16}, 0x18?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:160 +0x9c\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).BuildConfiguration(0x40004302d0)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:85 +0xbc\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).Provide(0x40004302d0, 0x4000119d40?, 0x40004302d0?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:49 +0x28\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.maybeThrottledProvide.func1(0x40006fb320, 0x40004302d0?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:57 +0xc8\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.launchProvider({{0x3d3d600, 0x4000215800}, {0x3d3cdb8, 0x40004302d0}, {0x40005dfe40, 0x3, 0x4}, 0x77359400}, 0x0?, 0x0?, ...)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:208 +0x2e8\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.Provide({{0x3d3d600, 0x4000215800}, {0x3d3cdb8, 0x40004302d0}, {0x40005dfe40, 0x3, 0x4}, 0x77359400}, 0x40006fb320, 0x4000268ae0)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:180 +0x64\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).startProviderAggregator.func1()\n\tgithub.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:76 +0x48\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x58\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x78\n"
```

### What version of Traefik are you using?

Version:      2.8.2
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-11T14:55:50Z
OS/Arch:      linux/arm64

Have tried 2.8 and latest.

### What is your environment & configuration?

Add more configuration information here.
Docker, no Traefik.yaml, rules.yaml on top, 

### If applicable, please paste the log output in DEBUG level

time="2022-08-12T12:39:54Z" level=info msg="Configuration loaded from flags."
time="2022-08-12T12:39:54Z" level=info msg="Traefik version 2.8.2 built on 2022-08-11T14:55:50Z"
time="2022-08-12T12:39:54Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"insecureSkipVerify\":true,\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"tls\":{\"certResolver\":\"duckdns\",\"domains\":[{\"main\":\"example.com\",\"sans\":[\"*.example.com\"]}]}},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"watch\":true,\"filename\":\"/etc/traefik/rules.yml\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"metrics\":{\"prometheus\":{\"buckets\":[0.1,0.3,1.2,5],\"addEntryPointsLabels\":true,\"addServicesLabels\":true,\"entryPoint\":\"traefik\"}},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"duckdns\":{\"acme\":{\"email\":\"test@example.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"dnsChallenge\":{\"provider\":\"duckdns\"}}}},\"pilot\":{\"dashboard\":true}}"
time="2022-08-12T12:39:54Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-08-12T12:39:54Z" level=warning msg="Traefik Pilot is deprecated and will be removed soon. Please check our Blog for migration instructions later this year."
time="2022-08-12T12:39:54Z" level=debug msg="Configured Prometheus metrics" metricsProviderName=prometheus
time="2022-08-12T12:39:54Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2022-08-12T12:39:54Z" level=debug msg="Starting TCP Server" entryPointName=traefik
time="2022-08-12T12:39:54Z" level=debug msg="Starting TCP Server" entryPointName=web
time="2022-08-12T12:39:54Z" level=info msg="Starting provider *file.Provider"
time="2022-08-12T12:39:54Z" level=debug msg="Starting TCP Server" entryPointName=websecure
time="2022-08-12T12:39:54Z" level=debug msg="*file.Provider provider configuration: {\"watch\":true,\"filename\":\"/etc/traefik/rules.yml\"}"
time="2022-08-12T12:39:54Z" level=error msg="Error in Go routine: runtime error: slice bounds out of range [2:1]"
time="2022-08-12T12:39:54Z" level=error msg="Stack: goroutine 72 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x2fa9260?, 0x40000c3440})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xac\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x3c\npanic({0x2fa9260, 0x40000c3440})\n\truntime/panic.go:884 +0x20c\ngithub.com/traefik/paerser/parser.filler.setSlice({{0xb?, {0x328b8b0?, 0x0?}}}, {0x28f6900?, 0x4000201518?, 0x2c5187f?}, 0x40005bc7e0)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0x89c\ngithub.com/traefik/paerser/parser.filler.fill({{0x80?, {0x328b8b0?, 0x4000566948?}}}, {0x28f6900?, 0x4000201518?, 0x7c48c?}, 0x4000566958?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x4d4\ngithub.com/traefik/paerser/parser.filler.setStruct({{0xad?, {0x328b8b0?, 0x4000566a68?}}}, {0x2fd1980?, 0x4000201500?, 0x1504244?}, 0x2c08300?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x10c\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x328b8b0?, 0x2c08300?}}}, {0x2fd1980?, 0x4000201500?, 0x4000331460?}, 0x4000566b18?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x518\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x48?, {0x328b8b0?, 0x4000566b78?}}}, {0x2bcb120?, 0x4000208348?, 0x1504244?}, 0x2c08300?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0xc0?, {0x328b8b0?, 0x2c08300?}}}, {0x2bcb120?, 0x4000208348?, 0x400066b498?}, 0x4000566cb8?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setPtr({{0xd8?, {0x328b8b0?, 0x4000566c88?}}}, {0x40000a9ac0?, 0x4000208340?, 0x40?}, 0x100000000000001?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0x0?, {0x328b8b0?, 0x2d9d980?}}}, {0x40000a9ac0?, 0x4000208340?, 0x40000a9ac0?}, 0x4000566d38?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x68?, {0x328b8b0?, 0x8?}}}, {0x40000a9b00?, 0x4000208340?, 0x0?}, 0x4000566d98?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0x98?, {0x328b8b0?, 0x2f812e0?}}}, {0x40000a9b00?, 0x4000208340?, 0x40005b85f0?}, 0x2bcaba0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setMap({{0x7?, {0x328b8b0?, 0x0?}}}, {0x2b325a0?, 0x400069ecf0?, 0x2b97d36?}, 0x40005bc630)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x334\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x328b8b0?, 0x0?}}}, {0x2b325a0?, 0x400069ecf0?, 0x2ad01eb?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:103 +0x4b4\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x4f?, {0x328b8b0?, 0x4000567058?}}}, {0x2f812e0?, 0x400069ecf0?, 0xbc880?}, 0x4000567168?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x10c\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x328b8b0?, 0x199?}}}, {0x2f812e0?, 0x400069ecf0?, 0x400020d060?}, 0x2ad01e6?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x518\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x4?, {0x328b8b0?, 0x0?}}}, {0x2bca920?, 0x400020d060?, 0x2ad01eb?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x224\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x328b8b0?, 0x4000567368?}}}, {0x2bca920?, 0x400020d060?, 0x328c755?}, 0x40005671d8?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x4c4\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x60?, {0x328b8b0?, 0x40005672d8?}}}, {0x2ee4de0?, 0x400020d060?, 0x150bc30?}, 0x328c755?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x10c\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x328b8b0?, 0x40002082b8?}}}, {0x2ee4de0?, 0x400020d060?, 0x16152d8?}, 0x328c755?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x518\ngithub.com/traefik/paerser/parser.filler.Fill({{0x20?, {0x328b8b0?, 0x2bca520?}}}, {0x2bca520?, 0x400020d060?}, 0x40005bc1b0)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:58 +0x150\ngithub.com/traefik/paerser/parser.Fill({0x2bca520?, 0x400020d060?}, 0x4?, {0x20?, {0x328b8b0?, 0x40005bc1b0?}})\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:28 +0x5c\ngithub.com/traefik/paerser/file.DecodeContent({0x40005ce400, 0x808}, {0x7ffbad5f21, 0x4}, {0x2bca520, 0x400020d060})\n\tgithub.com/traefik/paerser@v0.1.6/file/file.go:83 +0x1e8\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).decodeConfiguration(0x40000a9700?, {0x7ffbad5f0f, 0x16}, {0x40005ce400, 0x808})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:522 +0x2d0\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).CreateConfiguration(0x4000b1bec0, {0x3d58490, 0x400069e900}, {0x7ffbad5f0f, 0x16}, 0x0?, {0x2923ec0, 0x5aac880})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:486 +0x638\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfig(0x3d58420?, {0x3d58490, 0x400069e900}, {0x7ffbad5f0f, 0x16}, 0x18?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:160 +0x9c\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).BuildConfiguration(0x4000b1bec0)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:85 +0xbc\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).Provide(0x4000b1bec0, 0x400020d040?, 0x4000b1bec0?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:49 +0x28\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.maybeThrottledProvide.func1(0x40007970e0, 0x4000b1bec0?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:57 +0xc8\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.launchProvider({{0x3d3d600, 0x4000212180}, {0x3d3cdb8, 0x4000b1bec0}, {0x4000137b40, 0x3, 0x4}, 0x77359400}, 0x0?, 0x0?, ...)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:208 +0x2e8\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.Provide({{0x3d3d600, 0x4000212180}, {0x3d3cdb8, 0x4000b1bec0}, {0x4000137b40, 0x3, 0x4}, 0x77359400}, 0x40007970e0, 0x4000253c50)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:180 +0x64\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).startProviderAggregator.func1()\n\tgithub.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:76 +0x48\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x58\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x78\n"

**Comment by ldez** [comment] 2022-08-12 12:56
Duplicate of #9249

**Closed by ldez** 2022-08-12 12:56 UTC
Labels: status/0-needs-triage
